### ISSUE TITLE
conditionally disable response buffering

### ISSUE THREAD

**Issue by jrobeson** [caddyserver/caddy#1460]
## 1. What version of Caddy are you running (`caddy -version`)?
0.9.4  (and master)

### 2. What are you trying to do?
Stream responses over a FastCGI + PHP Server

### 3. What is your entire Caddyfile?
```text
localhost:8088

log stdout
errors stderr
root /path/to/app/web

fastcgi / /run/php-fpm.sock php
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy -conf /path/to/Caddyfile`

`curl http://localhost:8088/index.php`
### 5. What did you expect to see?
I expected to see the response stream data instead of being buffered forever.

### 6. What did you see instead (give full error messages and/or log)?
In the log I see:
`19/Feb/2017:07:21:45 -0500 [ERROR 502 /index.php] invalid byte in chunk length`

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
```php
<?php
    while(true) {
        sleep(1);
        @ob_flush();
        flush();
        print("FOO\r\n");
    }
```
Nginx has `X-Accel-Buffering: yes/no` to control such behavior.

**Comment by jrobeson** [comment]
I realize I have no idea how apache handles this sort of thing :(

**Comment by jrobeson** [comment]
I see this is tagged as a bug, but I was considering it a feature request.

**Comment by astei** [comment]
Upon further examination, this appears to actually be a bug in the FastCGI client.

I did some work on fixing this, but it's proving a bit more complex than I imagined. After removing the `Transfer-Encoding: chunked` special-case from the FastCGI client, Caddy is now returning an HTTP header response, but no content. This requires further examination.

**Comment by jrobeson** [comment]
I saw https://github.com/mholt/caddy/issues/1736 and made me wonder if this feature did work in the past and perhaps was broken later?

NOTE: I don't think (or have any clue) that #1736 is related, but it did inspire the question.

**Comment by mholt** [comment]
@jrobeson We've merged the revert into master, if you want to build and try again!

**Comment by mholt** [comment]
@jrobeson How does it work for you now? (I don't have a php installation handy to test it right now.) If I don't hear anything back, I'll assume it's working and close the issue.

**Comment by EtienneBruines** [comment]
It seems like `caddy` stillw aits for the entire body to be received, before passing it along. 

The `io.Copy` statement in `fastcgi.go:174` might be why. I'm not sure how we would go about rewriting this?

**Comment by mikelnrd** [comment]
Hi. Just so you're aware, this issue is also important for streaming event data to a browser via the SSE **Server Sent Events API** (also known as **EventSource**, as that's the name of the api in javascript).

Basically you need to turn buffering off in nginx/caddy (not completely, just for the SSE responses).  nginx has the response header "**X-Accel-Buffering: no**" for this. Caddy needs the same I think!

### More info:

I'm currently building a go server for sending Server-Sent-Events to the browser. I'm not using caddy for this particular server (yet anyway)... I just happened upon this issue while searching for "X-Accel-Buffering" and thought I'd mention server-sent-events to you!

Several places online recommend sending the response header "X-Accel-Buffering" with the value "no" to tell Nginx not to do any buffering when sending server-sent-events. (I'm not sure if this is because nginx would buffer the data forever, or would get the chunk boundaries wrong and split an event over two chunks... but either way I figure caddy needs a feature to disable chunking for this use case).

Several SSE blogposts/talks out there tell you to send X-Accel-Buffering: no to disable buffering in nginx.

The [HTML living standard SSE spec](https://html.spec.whatwg.org/multipage/server-sent-events.html#authoring-notes) (see Authoring Notes 3rd paragraph) explains the underlying issue albeit briefly:

> Authors are also cautioned that HTTP chunking can have unexpected negative effects on the reliability of this protocol, in particular if the chunking is done **by a different layer unaware of the timing requirements**. If this is a problem, chunking can be disabled for serving event streams.

The best explanation of this I've found is here (a must read - explains it better than I can):
https://serverfault.com/questions/801628/for-server-sent-events-sse-what-nginx-proxy-configuration-is-appropriate

Anyway, hope that's helpful. Keep up the amazing work with caddy :)

**Comment by mholt** [comment]
I'm pretty sure we can avoid buffering at least in specific circumstances in the proxy for Caddy 2. @dannav can probably spearhead this! Not sure when that will happen quite yet -- would anyone like to take it on? The v2 proxy still needs a lot of work.

**Comment by mholt** [comment]
Can someone try this with the proxy on the v2 branch now? It's looking pretty good, and if it doesn't support this yet, it certainly is capable of it.

Caddyfile documentation: https://github.com/caddyserver/caddy/wiki/v2:-Documentation#reverse_proxy

Or native JSON docs: https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httphandlersreverse_proxy

**Comment by mholt** [comment]
@jrobeson @mikelnrd @EtienneBruines Would any of you be willing to give this a try on Caddy 2? I'm ready and willing to help work on this while we're still in beta.

**Comment by sirthias** [comment]
I'm on V2 (currently beta 10) in "light" production right now and hit this issues today.
My setup is a simple reverse proxy:

```
client <--- HTTP/2.0 ---> caddy <--- HTTP/1.1 ---> origin
```

The origin server sends a chunked (`Transfer-Encoding: chunked`) response over the course of several seconds whereby each chunks only contains a few bytes.
Unfortunately, Caddy buffers things so that the client doesn't receive anything until the origin completes its response and Caddy flushes its buffers.

IMHO it doesn't make sense for Caddy to *ever* buffer the individual chunks of neither requests or responses when the message has `Transfer-Encoding: chunked`. Received chunks should be forwarded immediately.

For normal responses (w/o `Transfer-Encoding: chunked`) the buffering logic might be a bit more aggressive/configurable, as we are faced with a classic latency vs. throughput trade-off. Ideally there'd be a configuration option that users can turn to to tweak things according to their needs.

I'm happy to try out test builds in my setup and provide feedback.

**Comment by sirthias** [comment]
To maybe put a bit more structure to this issue:
I think we really have two tickets here:

1. The current behavior of buffering `Transfer-Encoding: chunked` messages (requests and responses!) is a bug! The fix shouldn't be classified as a feature request!

2. Enabling configuration of buffer behavior for *unchunked* messages should likely be treated as a feature request.

Should I open a "bug" ticket for (1) as (2) appears to be already captured by this ticket?

**Comment by mholt** [comment]
@sirthias Thanks for the report! Glad that this is finally being tested :+1:

I think I agree with you (I am trying to strain my memory if there is any reason that it should be buffered otherwise -- maybe something to do with HTTP/2 trailers or some network edge cases?? Maybe the standard lib had a good reason for it that is not as generally applicable to us?) -- first, can you set `flush_interval` to `-1` and see if that helps? It _should_ disable any buffering and immediately flush writes to the client.

> Should I open a "bug" ticket for (1) as (2) appears to be already captured by this ticket?

I think we're deep enough into both that we should probably just keep it together at this point...

By the way, @mikelnrd:

I just checked, and Caddy (and by extension, the Go standard lib reverse proxy) should not be buffering response bodies for `text/event-stream` responses:

```go
	// For Server-Sent Events responses, flush immediately.
	// The MIME type is defined in https://www.w3.org/TR/eventsource/#text-event-stream
	if resCT == "text/event-stream" {
		return -1 // negative means immediately
	}
```

**Comment by sirthias** [comment]
Thank you for the quick reply, @mholt!

> can you set flush_interval to -1 and see if that helps? 

Sure. However, I have trouble w/ finding any info about a `flush_interval` setting.
I guess it's not documented yet. 
How do I configure the `flush_interval`?
What part of the codebase would I have to look at to see the _complete_ JSON config structure?

I also wanted to try to pin caddy down to HTTP/1.1, i.e. disable HTTP/2, on the frontside in order to see how the `Transfer-Encoding: chunked` from the backside connection is carrying over.
But there too I was stopped in my tracks due to missing docs (I think).

> I am trying to strain my memory if there is any reason that it should be buffered otherwise...

It should be ok to buffer _inside_ of chunks or _outside_ of chunks but not across a chunk boundary. Essentially, receiving a packet containing the last byte of an HTTP/1.1 chunk should trigger a buffer flush. In either direction (request or response).

Maybe the translation between HTTP/1.1 chunk framing and HTTP/2.0 data framing plays a role here, which I was hoping to find out via a "clamp down to HTTP/1.1" trial...

**Comment by mholt** [comment]
@sirthias 

> Sure. However, I have trouble w/ finding any info about a flush_interval setting.

Oops, I missed it before. Just added it: https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httphandlersreverse_proxy (look for "flush_interval")

> What part of the codebase would I have to look at to see the complete JSON config structure?

Since Caddy 2 is modular (pluggable, extensible), there's no single place where you can see the _complete_ structure documentation.

Yet.

I've been working on that for the past week and will be working on it for the better portion of the remainder of this year. The Caddy 2 docs will be automatically generated directly from the code and its godoc comments, making them strongly-typed and strongly-versioned, module-aware, and even interactive, allowing you to explore the entire config structure with rich information and context, including all registered plugins.

> I also wanted to try to pin caddy down to HTTP/1.1, i.e. disable HTTP/2, on the frontside in order to see how the Transfer-Encoding: chunked from the backside connection is carrying over.
But there too I was stopped in my tracks due to missing docs (I think).

This one is documented, but it's a bit obscure right now. HTTP version is negotiated during the TLS handshake, so you want to make a connection policy that disables HTTP/2, i.e. an ALPN value of `http/1.1` only: https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httpserverstls_connection_policies

-------------------

Anyway, I've updated the docs -- thank you very much for helping us figure this out! Let me know what you discover!

**Comment by sirthias** [comment]
Ok, thank you, @mholt!
With `flush_interval` set to `-1` Caddy does indeed forward all incoming HTTP/1.1 chunks from the backside connection to the frontside immediately. No need to downgrade to HTTP/1.1 on the front (I haven't actually tried that).

So while this is a good work-around and won't really result in any perf issues in my use case I'd say no buffering at all might not be the best strategy for all applications.
Letting Caddy apply its own heuristics for whether and how to aggregate data packets coming in from one side before sending out a frame on the other side sounds like a better overall approach.
But: A HTTP/1.1 chunk boundary should trigger an immediate flush.
Then all should be well... :)

Thank you again for your quick support!

> The Caddy 2 docs will be automatically generated directly from the code and its godoc comments...

This sounds awesome! Looking forward to seeing the results of your work here!

**Comment by sirthias** [comment]
Ah, and one more thing:
Currently it doesn't appear to be possible to set the `flush_interval` via the caddyfile adapter.
It'd be awesome if that were possible... :)

**Comment by mholt** [comment]
@sirthias

> With flush_interval set to -1 Caddy does indeed forward all incoming HTTP/1.1 chunks from the backside connection to the frontside immediately. No need to downgrade to HTTP/1.1 on the front 

Aha, excellent news.

Perhaps we should make this the default?

> So while this is a good work-around and won't really result in any perf issues in my use case I'd say no buffering at all might not be the best strategy for all applications.

Agreed -- if immediate flushing was default, users could still configure buffering by setting an interval `>` (or `>=` ?) `0`.

> Letting Caddy apply its own heuristics for whether and how to aggregate data packets coming in from one side before sending out a frame on the other side sounds like a better overall approach.
> But: A HTTP/1.1 chunk boundary should trigger an immediate flush.
> Then all should be well... :)

I would happily review a pull request for this!

**Comment by sirthias** [comment]
> Perhaps we should make this the default?

I'm not sure about the implications of such a default on average throughput and latency numbers.
A diverse benchmark suite could provide some evidence here, but I'm not sure whether such a thing exists. Does it?

Also, I have no idea what the `flush_interval` setting actually _means_, i.e. what exactly it configures and what the _unit_ of this setting actually is.
More in-depth documentation is important here, I think.

>> Letting Caddy apply its own heuristics for whether and how to aggregate data packets
>> coming in from one side before sending out a frame on the other side sounds like a
>> better overall approach. But: A HTTP/1.1 chunk boundary should trigger an immediate flush.
>> Then all should be well... :)
>
> I would happily review a pull request for this!

Unfortunately I'm not qualified enough to make any actual code contributions as I haven't yet written a single line of Go in my life...

**Comment by mholt** [comment]
@sirthias I have just pushed a commit to make `flush_interval` configurable via the Caddyfile.

You can learn more about what it controls in the code for now, we'll write more docs later: 

- https://sourcegraph.com/github.com/caddyserver/caddy@512b004332ebf6dfa3fd14269de3cb0031233e34/-/blob/modules/caddyhttp/reverseproxy/streaming.go#L76

- https://sourcegraph.com/github.com/caddyserver/caddy@512b004332ebf6dfa3fd14269de3cb0031233e34/-/blob/modules/caddyhttp/reverseproxy/streaming.go#L89-99

**Comment by sirthias** [comment]
Awesome!
Thank you for being so response wrt proposals from random users like me!
