### ISSUE TITLE
Proxy upstream headers: Set or Add?

### ISSUE THREAD

**Issue by dhaavi** [caddyserver/caddy#1896]
Currently the proxy plugin adds all headers to upstream requests, _not_ replacing them.
I think we should discuss when using `Set` would be more appropiate than `Add`.

The headers I am thinking about in particular are [the ones added by the `transparent` preset](https://github.com/mholt/caddy/blob/baf6db5b570e36ea2fee30d50f879255a5895370/caddyhttp/proxy/upstream.go#L387). If, for example, the `X-Forwarded-For` Header is simply added and not set (i.e. replaced), an attacker could simply send an initial `X-Forwarded-For` header to spoof his address, as most applications use the first entry as the client IP address. The application running behind Caddy cannot determine what is real and what is not, it must fully trust what Caddy sends upstream. [This blogpost](http://esd.io/blog/flask-apps-heroku-real-ip-spoofing.html) is related to python frameworks, but explains the general problem in detail.

A great option would be to `Set` all headers by default and use a syntax similar to the header plugin (https://caddyserver.com/docs/header) to `Add` them.

Whatever other change may come through this discussion, I propose that the `transparent` proxy preset should be changed to `Set` instead of `Add` to keep Caddy secure by default.

**Comment by tobya** [comment]
The issue here as I discovered in https://github.com/mholt/caddy/issues/1829 is that if we do set them the code as it currently is will overwrite these headers.  A workaround for the moment is to add the headers.  

The case to uses `set` instead of `add` in the case of https://github.com/mholt/caddy/issues/1829 is compelling, but there is currently a technical issue preventing this.     The same technical issue _may_ be an issue in other cases.  

We should still however discuss the merits of making this change.

**Comment by mholt** [comment]
The reverse proxy in Caddy 2 (currently on the v2 branch) gives you very fine-grained control over headers in either direction. Please try it out! https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httphandlersreverse_proxy
