### ISSUE TITLE
Add reserved TLDs to autoTLS exclusion

### ISSUE THREAD

**Issue by My1** [caddyserver/caddy#2006]
The Docs say that TLS only gets shutdown if you use an empty host, localhost, an IP, a wildcard (probably until LE gets Wilds working) (and other conditions that are not related to the hostname)

shouldnt reserved TLDs, like .local also be added into the mix, as these cannot possibly get an HTTPS cert by LE.

according to wiki we have so far

.localhost
.local
.test
.invalid
.example
.onion (could actually get a TLS Cert, but only EV according to Guidelines, so no LE happening)

regarding onion as EV only, the statements became a little more complicated to read in later versions of the Requirements.
in 1.2.4 it was explicitly stated that onions have to be revoked unless they have been made in accordance with Appendix F of EV Guidelines., that part is missing now, and onion are apparently considered "Internal names" for the cabforum (which are, obviously forbidden to be made), as Appendix F number 6 states explicitly that an onion cert made according to it, that the onion shall not be considered an internal name.

https://cabforum.org/wp-content/uploads/EV-V1_6_7-redlined.pdf (PDF Page 54)
https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.5.4.pdf (PDF Pages 49/50)

**Comment by mholt** [comment]
Great points, thank for bringing this up. [RFC 6761](https://tools.ietf.org/html/rfc6761) section 5 prompts application developers to ponder whether the special-use domains require special treatment, which is what we need to do here.

It's important to note that the reserved TLDs according to [RFC 2606](https://tools.ietf.org/html/rfc2606) are `.localhost`, `.test`, `.invalid`, and `.example`, but that does not necessarily preclude them from obtaining certificates from locally-trusted CAs (even an ACME CA like a local instance of boulder). I guess the same could literally be said of the `localhost` name itself, except nobody in practice that I've _ever_ heard of uses a local instance of an ACME CA for that name. But I could see how people might use such infrastructure for other "internal-only" names.

`localhost` is special in that it (almost?) always links to the loopback interface, so there is no network to traverse, thus enabling automatic HTTPS for that name by default seems pointless. The `.localhost` TLD is different because the RFC uses "SHOULD" in telling DNS resolvers to point the TLD to the IP loopback address. Looks like there is more flexibility for `.invalid` and `.test` and `.example` TLDs; I imagine that an interested intranet operator would set those to resolve within his/her own network. `.local` is an odd case, since a Mac on a network will use a ".local" name as its hostname by default. The RFC says this TLD is to be "link-local". There could still be a local, internal ACME CA configured to verify these names.

`.onion` is a special case... there is a possibility in a future ballot that DV certs could be allowed for them. But perhaps we could disable automatic HTTPS for those names for now and re-enable it later if it becomes useful.

So for now, I see good reason to make `.localhost` and `.onion` turn off automatic HTTPS. But for the rest, I am not quite sure.

**Comment by My1** [comment]
well at least for the automatic TLS without a custom acme server (aka using the default, letsencrypt) none of those willbe getting an HTTPS soon.

regarding onion, yeah temp disable wouldnt be bad, basically similar as what we will have to do with wilds, as they will get allowed by LE in feb.

.local is a funny thing, yeah but if .local and the others would get a pass, then IPs (and wilds even now) should also get one because a locally trusted ACME server, so the only option to disable HTTPS in that case would be explicitly turning it off. btw I also saw .local being used in some routers after their pseudo domains got a serious problems when those not existing TLDs actually got registered. e.g. the vodafone easybox had easy.box, which obviously isnt a good Idea by now and now it's easybox.local or whatever, which makes a whole lot more sense, as it's unroutable by definition.

I didnt even consider a custom acme server, I didnt even know that caddy could do that, but well I would consider for the total default with LE and stuff to ax basically anything that wont help, which means IPs, wilds until the end of february, and the domains which may not get a cert according to CAB forum guidelines, unless already done that would probably also include single label names without a TLD.

**Comment by mholt** [comment]
I went ahead and added .localhost and .local TLDs to the list of "internal-only" -- the rest can be worked around in config if needed, I think.

**Comment by ibrahima** [comment]
For posterity, the way to work around this in config is to add [`local_certs`](https://caddyserver.com/docs/caddyfile/options#local-certs) to your configuration, e.g. at the top-level.

```
{
	local_certs
}
```

**Comment by mholt** [comment]
@ibrahima True, but that is only needed if your domains do not end in `.localhost` (or `.local`, though depending on discussion in #5512 we may only do this for `.localhost` in the near-future. :man_shrugging:
