### ISSUE TITLE
Add APM Tracing

### ISSUE THREAD

**Issue by theodesp** [caddyserver/caddy#2548]
## 1. What would you like to have changed?
I would like to have a Caddy plugin that integrates with [Elastic APM server](https://www.elastic.co/solutions/apm) so we can trace and observe the Server Performance in Kibana. I think an official integration module with the [go agent](https://github.com/elastic/apm-agent-go) would be useful.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?
There are lots of reasons:
* Better observability of the Caddy Instances
* Integration with Kibana+ Elastic Stack
* Production level Monitoring

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
I could only find this topic
https://caddy.community/t/health-check-endpoint-to-monitor-caddy-itself/1517

## 4. Please link to any relevant issues, pull requests, or other discussions.
I could give it a `Go`  and implement this if its approved or at least get some recommendations on how to approach this as a external plugin to see how it goes

**Comment by theodesp** [comment]
https://github.com/mholt/caddy/issues/2557

**Comment by mholt** [comment]
(2 years later, sorry) Thanks for the feature request -- this can certainly be done, but might be best as a separate plugin for Caddy 2 (and Caddy 2 didn't exist when this issue was opened).

We also have Prometheus metrics that we support more natively.

Since this will likely be best as a separate plugin, I'll close the issue here, but anyone of course is welcome to build it.
