### ISSUE TITLE
Question: Does caddy support Http2 over cleartext reverse proxy?

### ISSUE THREAD

**Issue by kxmp** [caddyserver/caddy#2668]
I did a simple search but found nothing.
I don't know does caddy H2C reverse proxy.
If not. Will you plan to support it in the future?

**Comment by mholt** [comment]
Nope. And we have no plans to implement H2C at this time.

Encrypt 👍

**Comment by kxmp** [comment]
Thanks for replying.

**Comment by cjjdaq** [comment]
hope

**Comment by ReillyProcentive** [comment]
Can we reopen this as a feature request? 

Our use case is that we use Caddy as a static file server behind another load balancer (Traefik doing dynamic kubernetes things). The underlying network is over an encrypted ipsec mesh which means that using http2-over-tls would double the encryption overhead for requests between the loadbalancer and Caddy. 

There does appear to be a h2c package here:
https://godoc.org/golang.org/x/net/http2/h2c

**Comment by mholt** [comment]
@ReillyProcentive What do you need http/2 for in that scenario?

**Comment by ReillyProcentive** [comment]
@mholt We don't need it per se but it would make our existing setup slightly more efficient. As far as I know http/2 is a straight upgrade over http/1.1 in nearly every way including smaller requests sizes, faster processing and more efficient reuse of connections

**Comment by mholt** [comment]
Have you profiled the performance of H2 vs. H1 in your case? In my experience it seldom makes much of a difference behind load balancers. Also, are you sure the encryption overhead is as much as you think? Most CPUs have specialized hardware instructions that make it mostly negligible, and Go's assembly implementation of the most common ciphers takes advantage of that usually.

**Comment by hehongbo** [comment]
> Nope. And we have no plans to implement H2C at this time.
> 
> Encrypt 👍

Yes, encryption is great, but should only happen between server and browsers (or client-side applications). For reverse proxy between Caddy and upstream servers, that could happen within localhost or Docker containers, and encryption is not necessary.

Imagine an http1.1 scenario, you might have a Python or Node application that serves on a random port, and use Caddy/Nginx/HAProxy/Apache to process requests, as well as to perform TLS encryption. The upstream application is not necessary to encrypt the connection.

For H2, "proxy to h2c" is something equivalent. Even though I can proxy to H2 (a.k.a h2-over-TLS), proxy to h2c is much cleaner, because you don't have to configure certificates on application servers, neither with certificates from a valid CA (which probably unsafe) or with a self-signed certificate.

HAProxy can configure http2 frontends and serving contents from http1.1 backends, but that is different because you don't have http2 features.

**Comment by mholt** [comment]
@hehongbo @ReillyProcentive @cjjdaq @k79e In the interest of interoperability, I'm implementing h2c (as a transport/client, not server) into the v2 reverse proxy over in https://github.com/caddyserver/caddy/issues/3218 -- the [h2c](https://github.com/caddyserver/caddy/tree/h2c) branch. If you could try it out and join the discussion there, that'd be helpful!

**Comment by ReillyProcentive** [comment]
@mholt Unfortunately I don't have a use-case for testing h2c upstream of Caddy itself. For what it's worth though, a few months ago when I was working on this I was able to get h2c working as a server protocol almost trivially in a test branch. I unfortunately never got the time to load-test it though to see what difference it would make.
