### ISSUE TITLE
[question] how to redirct to another domain only with matched string in regex parentheses

### ISSUE THREAD

**Issue by CoolRice** [caddyserver/caddy#2744]
I want redirct http://localhost/somePath/xxxxxxx => http://www.example.com/xxxxxxx.

tried 
```
redir {
    if {path} match ^/somePath/(.*)
    / http://www.example.com{uri}
}

```

and 

```
localhost:80/somePath/ {
	redir / https://www.example.com/{uri}
}
```

They all take the page to https://www.example.com/somePath/xxxxxxx

expected: http://www.example.com/xxxxxxx
platform: windows 10
caddy version: 1.0.3

Anyone can help?

**Comment by mholt** [comment]
Thanks for your question, and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for specific, development-focused discussions, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
