### ISSUE TITLE
V2 - Incorrect output from `adapt` for Caddyfile with rewrite for regexp

### ISSUE THREAD

**Issue by DeanMarkTaylor** [caddyserver/caddy#2791]
When using Caddy v2 beta (built from source) I'm currently getting unexpected output for a regular expression rewrite.

### Input
```
    example.com {
        rewrite {
            r /[^/]+(/wp-content/themes/sample/.*)
            to {1}
        }
    }
    
```

### Output
Note `uri` listed as "`}`" and expression is not seen in output.
```
{
	"apps": {
		"http": {
			"servers": {
				"srv0": {
					"listen": [
						":443"
					],
					"routes": [
						{
							"match": [
								{
									"host": [
										"example.com"
									]
								}
							],
							"handle": [
								{
									"handler": "subroute",
									"routes": [
										{
											"handle": [
												{
													"handler": "rewrite",
													"rehandle": true,
													"uri": "}"
												}
											]
										}
									]
								}
							]
						}
					]
				}
			}
		}
	}
}
```

**Comment by mholt** [comment]
Ah, we should throw an error here because the input has wrong syntax. Thanks for the report.

The syntax for v2's rewrite is documented here: https://github.com/caddyserver/caddy/wiki/v2:-Documentation#rewrite

It's much simpler in v2 because it no longer does request matching: you simply give it the URI to rewrite to.

So, use something like this:

```
matcher themes {
    path_regexp theme_regex /[^/]+(/wp-content/themes/sample/.*)
}
rewrite match:themes {http.matchers.path_regexp.themes.1}
```

It's an advanced use case that is a bit under-documented.

Note how request matching is done outside of directives now.
