### ISSUE TITLE
v2 reverse_proxy without prefix

### ISSUE THREAD

**Issue by jimjimovich** [caddyserver/caddy#2813]
Caddy v1's proxy directive had an option called "without" which allowed you to not include a prefix path when sending a request to the proxied server.  Is this possible in v2? If not, would it be possible to add this feature?

**Comment by mholt** [comment]
`without` was introduced in Caddy 1 because the only middleware powerful enough to match requests on more than just the request path was the `rewrite` middleware. Thus, you would have to `rewrite` the request URL to a special path and then the proxy would pick it up and strip the part of the path you artificially added. Essentially in Caddy 1, you had to send "signals" to other middleware to activate if you wanted to do so based on more than just the path.

In Caddy 2, request matching is _really_ powerful and there's no need for what we call "rewrite hacks."

What is your use case for `without`?

(I want to know the answer to that question, but the reality is that you can accomplish this yourself by adding a `rewrite` route before the proxy to remove the part of the path you don't want. But as far as I can think, this is kind of a _config smell_ and something tells me there is a better way to do what you are looking for...)

**Comment by jimjimovich** [comment]
The use case is to be able to proxy different paths to different backends without sending the entire path to the backend. For example:
```reverse_proxy /test/ localhost:2015```  
sends the /test/ path to the backend. So something like example.com/test/index.html gets sent to the backend as localhost:2015/test/index.html.  I'd like to be able to not send the /test part to the backend.

Perhaps this is possible to do another way, but I don't know how.

**Comment by mholt** [comment]
Hmm, so what you actually want is a way to map properties of the request (in your case, a component of the path) to a particular backend.

You can do this today with a route that matches paths starting with `/test`, having a rewrite handler that strips `/test`, then the proxy.

We could potentially add a load balancing policy that maps an arbitrary value (such as a placeholder value, like from a matcher's regex capture group) to a particular backend -- this would assume that only the backend differs and that the reverse proxy module is configured the same for all the backends.

Another option is to have a path_regexp matcher with a capture group around the part of the path that you want to switch on, then have a handler that switches the value of another placeholder based on that (like nginx's map module).  Then you just specify the proxy and its backend once, since the backend would be dynamically set from the map.

These are just a few ways that come to mind. Can you get even more specific about what you want to do?

**Comment by jimjimovich** [comment]
> You can do this today with a route that matches paths starting with `/test`, having a rewrite handler that strips `/test`, then the proxy.

Could you show how this is done? The new configuration format is really hard to wrap your head around without examples. I still don't really "get it", I guess.

**Comment by mholt** [comment]
Yeah, Caddy 2 is very powerful and expressive, so it takes some reading and time to get used to: https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httpserversroutes and https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httpservershandle are the most relevant sections.

It's after midnight so I just whipped this route up real quick (untested):

```
{
	"match": [
		{"path_regexp": {"name": "test", "pattern": "^/test/(.*)$"}}
	],
	"handle": [
		{
			"handler": "rewrite",
			"uri": "{http.matchers.path_regexp.test.1}"
		},
		{
			"handler": "reverse_proxy"
		}
	]
}
```

**Comment by francislavoie** [comment]
@mholt if you reuse the same matcher for 2 different handlers in the Caddyfile, does it add the 2nd handler to `handle` array or does it make a new route? I assume the former but just wanted to clarify. If so, then this should be equivalent, right?

```
matcher testpath {
    path_regexp ^/test/(.*)$
}
rewrite match:testpath {http.matchers.path_regexp.test.1}
reverse_proxy match:testpath localhost:2015
```

**Comment by jimjimovich** [comment]
> Yeah, Caddy 2 is very powerful and expressive, so it takes some reading and time to get used to: https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httpserversroutes and https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httpservershandle are the most relevant sections.
> 
> It's after midnight so I just whipped this route up real quick (untested):
> 
> ```
> {
> 	"match": [
> 		{"path_regexp": {"name": "test", "pattern": "^/test/(.*)$"}}
> 	],
> 	"handle": [
> 		{
> 			"handler": "rewrite",
> 			"uri": "{http.matchers.path_regexp.test.1}"
> 		},
> 		{
> 			"handler": "reverse_proxy"
> 		}
> 	]
> }
> ```
This works! I see that this new system is extremely powerful. I just hope that people aren't turned off by the initial complexity. Seems like my request wasn't needed after all. Thanks!

**Comment by mholt** [comment]
@francislavoie Basically, although the way it currently works you have to specify the regex name as something different from the matcher name (a matcher can technically have multiple regexes):

```
matcher testpath {
    path_regexp test ^/test/(.*)$
}
rewrite match:testpath {http.matchers.path_regexp.test.1}
reverse_proxy match:testpath localhost:2015
```

But yes that should work:

```
$ caddy adapt --config Caddyfile --adapter caddyfile --pretty

{
	"apps": {
		"http": {
			"servers": {
				"srv0": {
					"listen": [
						":2015"
					],
					"routes": [
						{
							"match": [
								{
									"host": [
										"localhost"
									]
								}
							],
							"handle": [
								{
									"handler": "subroute",
									"routes": [
										{
											"handle": [
												{
													"handler": "rewrite",
													"rehandle": true,
													"uri": "/{http.matchers.path_regexp.test.1}"
												},
												{
													"handler": "reverse_proxy",
													"upstreams": [
														{
															"dial": "localhost:2015"
														}
													]
												}
											],
											"match": [
												{
													"path_regexp": {
														"name": "test",
														"pattern": "^/test/(.*)$"
													}
												}
											]
										}
									]
								}
							]
						}
					]
				}
			}
		}
	}
}
```

@jimjimovich If this is a common request/need, we can look into more efficient and easier ways to do path prefix trimming. I just want to avoid unnecessary special cases if they aren't super common.

Thanks for the question, it was a good one!

**Comment by mholt** [comment]
I've made this easier in the `rewrite` directive, it can now strip prefixes and suffixes: https://github.com/caddyserver/caddy/commit/208f2ff93c1bd2c009e4b96f664c1808ede79f3a

**Comment by WoLfulus** [comment]
I'm struggling with this too, can't seem to find a way to configure that since the examples here aren't working.

In my case caddy is in front of many different servers, for example

domain/ -> serves frontend from frontend:80
domain/api -> serves backend api from api:80
domain/admin -> serves frontend from admin:80

I have the same problem as op, `domain/api/route` is requesting `api:80/api/route` instead of `api:80/route`, same for admin

upstream could receibe the target path too, for example

`reverse_proxy x admin:80` -> proxies `/admin/route` to `admin:80/admin/route`
`reverse_proxy x admin:80/` -> proxies `/admin/route` to `admin:80/`
`reverse_proxy x admin:80/hello` -> proxies `/admin/route` to `admin:80/hello/route`

or some additional parameter on reverse_proxy

**Comment by mholt** [comment]
@WoLfulus Did you try the `rewrite` handler? (see comment above)

```
{
     "handler": "rewrite",
     "strip_path_prefix": "/api"
}
```

Plop that before your proxy handler and tell me how it goes!

**Comment by WoLfulus** [comment]
I don't know what I did wrong, but the rewrite made it serve the contents from the file_server in / so I thought it would conflict somehow because it was running before the reverse_proxy (?). But since I had to get this done ASAP and I spent quite some time trying to figure it out, I had to switch to traefik for now.

I'll give it a try later with another project. I thought it would work just fine since we had `without` in v1.

**Comment by mholt** [comment]
@WoLfulus 

> I don't know what I did wrong

Can you post your full config please? It's a little hard to help without it :)

We're still in beta, so some things need polishing. Was the switch to Traefik really faster than just continuing to use Caddy 1?

**Comment by WoLfulus** [comment]
I was using `jwilder/nginx` and I had to switch to something with proper support for path routing, and as Caddy 2 beta is out, I wanted to give it a try :)

About Caddy 1, a friend is using it and he mentioned the `without` works in my case

**Comment by mholt** [comment]
Yeah, Caddy 1 handles this nicely in the Caddyfile, and Caddy 2 will soon -- what was the config you used?

**Comment by WoLfulus** [comment]
I'm was trying to find it but I couldn't. It wasn't much though.

Most of it was the above examples, plus the "default" file server.

It was pretty much like this one:

```
:8080

root * ./data/www
encode gzip
file_server

matcher admin {
    path_regexp test ^/admin/(.*)$
}
rewrite match:admin {http.matchers.path_regexp.test.1}
reverse_proxy match:admin admin:80
```

I just dont remember if the block with root and file_server was before or after matcher/reverse_proxy. But I probably tried both.

**Comment by mholt** [comment]
Okay... thanks... it's not much to go on but we'll keep an eye out if it comes up again.

If you would, please file a new issue and fill out the issue template that is provided, as soon as you get a chance. It will help us greatly, as we'd like to fix this up while we're still in beta.

**Comment by akkuman** [comment]
I have the same problem

**Comment by alaslums** [comment]
So in Caddy v1, the "without" directive is exceptionally helpful with reverse_proxy.

Take the example of PHPMyAdmin and Docker. You want to pass /phpmyadmin through to the PHPMyAdmin container. With reverse_proxy, this gets you a 404 as phpmyadmin is located at /, not /phpmyadmin. With the "without /phpmyadmin" directive, problem solved.

I've tried the 5 line kludge from above but I get "unrecognized directive: matcher". This is making my brain hurt.

**Comment by mholt** [comment]
@alaslums In v2, the proxy handler is not in the business of rewriting requests. Instead, simply use the `uri` directive, it can strip path prefixes: https://caddyserver.com/docs/caddyfile/directives/uri

```
uri strip_prefix /phpmyadmin
```

**Comment by alaslums** [comment]
@mholt Thanks for the speedy reply, but is there an evaluation order issue here? This now just passes /phpmyadmin through to the main website, not to the phpmyadmin container.

```
foo.domain.tld {
  reverse_proxy website:80 {
    header_up X-Forwarded-Proto HTTPS
  }

  uri strip_prefix /phpmyadmin
  reverse_proxy /phpmyadmin phpmyadmin:80
}
```

**Comment by francislavoie** [comment]
Yeah, good instincts. By default, Caddyfile directives are sorted in a specific order: https://caddyserver.com/docs/caddyfile/directives#directive-order

Instead, you can use `route` to wrap your sites to get around this:

```
foo.domain.tld {
  route /phpmyadmin* {
    uri strip_prefix /phpmyadmin
    reverse_proxy phpmyadmin:80
  }

  route {
    reverse_proxy website:80
  }
}
```

For any further usage questions, it's preferred if you ask on https://caddy.community, as we prefer github issues to be for tracking bugs and feature requests, plus we're sending notifications to anyone else who was in this thread!

**Comment by mholt** [comment]
@francislavoie I am not even sure that the second reverse_proxy needs to be in a route. It's allowed but I don't think it's necessary.

**Comment by francislavoie** [comment]
I know! Just prefer a symmetric config :stuck_out_tongue:

**Comment by zakcutner** [comment]
I really like the idea of separating rewriting and proxying in Caddy 2, and `strip_path_prefix` certainly makes this a lot nicer than previous regex options. However, I think something like the following will become quite a common pattern...

```
example.com {
  route /api {
    route /v1 {
      uri strip_prefix /api/v1
      reverse_proxy oldapi:80
    }

    route /v2 {
      uri strip_prefix /api/v1
      reverse_proxy newapi:80
    }
  }

  route /docs {
    uri strip_prefix /docs
    reverse_proxy docs:80
  }

  reverse_proxy website:80
}
```

My issue is that there is a lot of duplication of paths which I would like to avoid writing and this could very easily lead to errors being accidentally introduced. For instance, if I change `/docs` to be `/documentation` I may forget to update `uri strip_prefix /docs` to ` uri strip_prefix /documents`. In a more complex config like this one you can see how there may be more subtle errors with the `api/` path as there is nesting too.

Seeing as what I really want to be doing is simply stripping the entire path for every reverse proxy, would it make sense to add something like `uri strip_path` (which would strip the entire path) to make this simpler? You could also perhaps even specify an optional number of path segments to strip.

I also briefly tried `uri strip_prefix {http.request.orig_uri.path}` as an alternative, but I couldn't get that to work (maybe I'm just being stupid 😕). However, even so, I'm not sure it expresses in a very readable way what I'm trying to achieve.

Another idea would be to strip the path by default and then simply add it back on if needed, i.e. with `reverse_proxy docs:80/docs`. From my personal experience stripping the path is much more common than leaving it on when reverse proxying, but perhaps there are some examples I haven't thought of?

I'd be really interested to hear others' use cases with `reverse_proxy` and whether any of these ideas would be desirable/feasible? 😄

**Comment by francislavoie** [comment]
Generally, if running multiple reverse proxies, we recommend putting them each under subdomains. When running in a subpath, some sites don't behave well if all their links, redirect URLs and asset paths are not relative - any absolute paths (unless configured to add the prefix) would break the site.

Your suggestion of stripping the entire path wouldn't work - every request would end up routing to the root of the proxied site!

I would say the general user expectation if adding a path to the proxy address is that that path would be prefixed on every request, not stripped. That's how it behaved in v1 when doing that. For implementation reasons, this aspect of the proxy directive was skipped for now because it had some tricky implications. It's also not hard to manually add the rewrite if adding the prefix is what the user needs.

We could look into adding a shortcut for this, but I'm not convinced of any ergonomic way to deal with it yet. It would have to happen in a later version (v2.1 or later) as we're in a feature freeze until then.

This feature request probably belongs in its own issue, we shouldn't keep discussing this in a closed issue. Feel free to open one up for further discussion!

**Comment by zakcutner** [comment]
> Your suggestion of stripping the entire path wouldn't work - every request would end up routing to the root of the proxied site!

Yes, that's a good spot I hadn't thought of that!

> I would say the general user expectation if adding a path to the proxy address is that that path would be prefixed on every request, not stripped. That's how it behaved in v1 when doing that.

That's a fair point particularly particularly as I appreciate it would be confusing to change from how it worked in v1. I'll create a new issue as you suggested... it would be interesting to see what other kinds of use cases exist too.

**Comment by zakcutner** [comment]
Created a new issue #3266 to continue the discussion!

**Comment by ziddey** [comment]
> Generally, if running multiple reverse proxies, we recommend putting them each under subdomains. When running in a subpath, some sites don't behave well if all their links, redirect URLs and asset paths are not relative - any absolute paths (unless configured to add the prefix) would break the site.

This is definitely through for many services I have reverse-proxied. However, some have provisions for specifying a prefix. And better, while non-standard, some services support the [x-forwarded-prefix](https://werkzeug.palletsprojects.com/en/1.0.x/middleware/proxy_fix/) header (e.g. /api) where it will then automatically apply the prefix to any urls.
