### ISSUE TITLE
Open  appleid.com face 502 Bad Gateway when using V2ray WS+TLS+caddy 

### ISSUE THREAD

**Issue by mariokart1992** [caddyserver/caddy#2822]
1. Which version of Caddy are you using (`caddy -version`)?
1.03

2. What are you trying to do?
Visiting www.appleid.com via V2ray (WS+TLS+Caddy) network environment

3. What is your Caddyfile?
mario.top
{
  proxy /win localhost:26808 {
    websocket
    header_upstream -Origin
  }
}
4. How did you run Caddy (give the full command and describe the execution environment)?
Using V2ray ws+tls+caddy mode

5. Please paste any relevant HTTP request(s) here.

This is the error information in Chrome developermode    
Request URL: https://appleid.apple.com/favicon.ico
Request Method: GET
Status Code: 502 Bad Gateway
Remote Address: 127.0.0.1:16809
Referrer Policy: no-referrer-when-downgrade
Connection: keep-alive
Content-Length: 568
Content-Type: text/html
Date: Sat, 19 Oct 2019 00:49:00 GMT
Server: Apple
Provisional headers are shown
Referer: https://appleid.apple.com/
Sec-Fetch-Mode: no-cors
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

6. What did you expect to see?
Normally open the website

**Comment by mholt** [comment]
Thanks for your question, and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for specific, development-focused discussions, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
