### ISSUE TITLE
Health check before retrying Letsencrypt cert request

### ISSUE THREAD

**Issue by ptman** [caddyserver/caddy#2823]
## 1. What would you like to have changed?

Currently it's quite easy to run into letsencrypt rate limits via retries if there are errors, like typos in the domain name. Before requesting a certificate, caddy could make sure that the domain resolves. Or maybe try resolving it if ACME responds with 400 "No valid IP addresses found for" and avoid retrying if there is a problem.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

It would make dealing with letsencrypt certificates easier.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

Read logs, wait for rate-limit to be fixed.

## 4. Please link to any relevant issues, pull requests, or other discussions.

https://letsencrypt.org/docs/rate-limits/

**Comment by francislavoie** [comment]
Some better handling of LE rate limits is being worked on for Caddy v2! See https://github.com/caddyserver/caddy/tree/v2 if you want to try it out.

**Comment by mholt** [comment]
Also, there's a best practices document being published soon that advises against pre-flight checks because they are often complex and unreliable (DNS is ultimately a matter of perspective and past experience has shown that local DNS lookups can't be relied upon as a telling indicator as to whether a challenge will succeed, there are many other factors).
