### ISSUE TITLE
Server logs are incomplete for some failed SSL handshake scenarios

### ISSUE THREAD

**Issue by jkantr** [caddyserver/caddy#2837]
## 1. Which version of Caddy are you using (`caddy -version`)?
v1.0.3-3-g8cc2f770

## 2. What are you trying to do?

Debug SSL handshake issue involving client cert requests with a third party. 

## 3. What is your Caddyfile?

```
services.jkantr.com:443 {
        tls /etc/ssl/certs/services_jkantr_com_bundle.crt /etc/ssl/certs/services.jkantr.com.pem {
                clients request /etc/ssl/certs/DigiCertGlobalRootCA.pem
        }
        proxy / localhost:3444
        log / stdout "[{when}] {remote} \"{method} {uri} {proto}\" {status} {size} - req: {request} body: {request_body}"
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp

## 6. What did you expect to see?

In the logs to stdout, I would expect to see requests that *attempted* to access the resource but failed during handshake. I do sometimes, but only when the issue is related to certain error types. 
## 7. What did you see instead (give full error messages and/or log)?

As examples of the above, if I make a request to the server without supplying SNI, it would log:
```
caddy[14443]: 2019/10/28 19:11:38 http: TLS handshake error from 24.168.59.34:64810: no certificate available for ''
```
 if I remove the `request` from `clients request` in the caddyfile, then attempting to connect without this client cert will log as:
```
2019/10/28 19:11:27 http: TLS handshake error from 24.168.59.34:64797: tls: client didn't provide a certificate
```
But there are other cases when the handshake fails or is aborted when caddy logs nothing. If I run the following:
```
openssl s_client -connect services.jkantr.com:443 -servername services.jkantr.com
```

openssl will 'pause' while waiting for a stream of the client request to be sent... if i simply hit return, then the handshake will fail *but i will receive an http response from caddy*:
```
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad Requestclosed
```

However - this is *not logged whatsoever* on the server. It would appear there are other types of requests / handshake failures that are not necessarily logged, but it's hard to know exactly what requests cause this behavior.

## 8. Why is this a bug, and how do you think this should be fixed?

The docs state that log logs all "access", but frequently also log attempted access that fails for one reason or another - I would expect failed or aborted ssl handshakes to be considered attempted 'access' and logged all the same.

## 9. What are you doing to work around the problem in the meantime?

Trial and error.

**Comment by mholt** [comment]
Interesting. Does this happen with Caddy 2 as well? (on beta in the v2 branch) (also I'm not sure if the v2 Caddyfile supports TLS client auth quite yet, so you might have to use the JSON to configure it, or at least adapt a Caddyfile to JSON using the `adapt` command and then fill out the client auth part yourself)

It seems that this can happen with any TLS config, not just ones with client auth.

What does hitting Enter do when s_client is running?

**Comment by mholt** [comment]
Oh, you know what I think is happening: the Go standard library completes the handshake, but pressing "Enter" while s_client is waiting sends a `\n` character to the server, which the server isn't expecting: it expects an HTTP request. Since it's not a valid HTTP request, the server responds with a 400 "Bad Request" error and closes the connection.

The thing is, that this happens within the Go standard library, before Caddy's entry ServeHTTP handler is invoked. Hence, it doesn't get logged.

We can at least add some logging for the TLS handshake in Caddy 2, though. Can't do much between the handshake completing and a successful HTTP request header being read, though, as that part is right in the standard lib. In other words, I don't think there's a way to add that 400 HTTP response to the Caddy access logs, but we can probably at least nab the TLS handshake and put that in some log.

To expose the bad request, you'd probably have to advocate for a change in the Go standard library... (or if there is a way to do it already, I do not know what it is, I'd be happy to be wrong!)
