### ISSUE TITLE
Question : why this is not working ?

### ISSUE THREAD

**Issue by x4080** [caddyserver/caddy#2857]
@mholt Now I'm progressing to using .json
And when I use this :
```
{
			"apps": {
				"http": {
					"servers": {
						"example": {
							"listen": ["127.0.0.1:2015"],
							"routes": [
								{
									"handle": [{
										"browse": {},
										"handler": "file_server",
										"root":"./static_files"										
									}]
								}
							]
						}
					}
				}
			}
}	

```

It works perfectly when I open http://localhost:2015/ (File browser appears)

And I want to open the file browser at http://localhost:2015/static, I figured that I must change it to 

```
{
			"apps": {
				"http": {
					"servers": {
						"example": {
							"listen": ["127.0.0.1:2015"],
							"routes": [
								{
									"handle": [{
										"browse": {},
										"handler": "file_server",
										"root":"./static_files"										
									}],
									"match":[
                                    {
                                       "path":[
                                          "/static"
                                       ]
                                    }
                                 ]
								}
							]
						}
					}
				}
			}
}	
```

Adding match with path /static, but its not working, do I make mistake ?

Thanks

**Comment by mholt** [comment]
Thanks for trying v2 while we're still in beta!

Can you explain what "not working" means?

**Comment by x4080** [comment]
The address is not opening, just empty

**Comment by mholt** [comment]
Okay, I'm guessing this is because you don't have any files at `./static_files/static`. Remember that the request path is appended to the root path you provide in the config. (This is the same as in Caddy 1 and with other web servers.)

Here're more info on that: https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httphandlersfile_server

If you want to keep that path prefix, you can strip it using the `rewrite` handler (described on the same docs page, for now).

If you have any further questions, please ask on our forums: https://caddy.community - thanks!

**Comment by x4080** [comment]
@mholt Thanks
