### ISSUE TITLE
v1 -> v2 rewrites

### ISSUE THREAD

**Issue by pkpowell** [caddyserver/caddy#2888]
In v1 I import  a bunch of conditional rewrites for https://github.com/wdas/reposado
Basically the path is rewritten based on the value of "User-agent"
```
rewrite {
	r ^/index(.*)\.sucatalog$
	if {>User-agent} has Darwin/18
	to /content/catalogs/others/index-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1{1}.sucatalog
}
```
This works fine in v1 but I have no clue how to do this in v2. 
The basic v2 server block looks like this:
```
srv1.local:7000 {
	file_server {
		root /Users/phil2/Sites/reposado/html
		browse
	}
	tls off
}
```
My guess is I need a bunch of matchers and a rewrite.
Any tips on how to do this would be greatly appreciated

Cheers
Phil

**Comment by mholt** [comment]
Thank you for trying Caddy 2 while it is in beta!

Right now, something like this, I think (_untested_):

```
matcher ua {
	path_regexp mygroup ^/index(.*)\.sucatalog$
	header_regexp User-Agent Darwin/18
}
rewrite match:ua /content/catalogs/others/index-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1{http.matchers.path_regexp.mygroup.1}.sucatalog
```

A couple of things I want to add to the Caddyfile in the future that might be relevant here (not sure if it'll get in before the initial 2.0 release, but we'll see):

- A way to do "contains" matches on headers without using regular expressions (for performance reasons) -- in other words, if the `header` matcher was used instead of `header_regexp`, you could specify something like `header User-Agent *Darwin/18*` and it would do a very fast `strings.Contains()` match because it has wildcards on both sides; similarly could do prefix/suffix matching if the wildcard was just on one side.

- A rough equivalent of nginx's `map` feature, that allows you to more conveniently describe associations and then use them in your routing logic.

- A way to include/embed another matcher into a new one. By "nesting" matchers you could maybe specify the regexp only once and then just make new ones for each User-Agent value.

**Comment by pkpowell** [comment]
Brilliant, thanks Matt!

Btw, how do I get caddy to accept tls.1.1 (we have some older systems that don't support newer tls...)? 
This works
```
tls cert key {
    protocols tls1.2 tls1.3
}
```
but `protocols tls1.1 tls1.3` results in `protocol not supported`. 

Looking forward to the changes you mention.

**Comment by mholt** [comment]
@pkpowell To clarify, did the above snippet work for you?

**Comment by pkpowell** [comment]
Yes, for macOS 10.15 machines.A 10.12 machine is throwing a "tls handshake error” which is why I tried to set a lower pls version."protocol tls1.0 tls1.3" also errors.On 19 Nov 2019, at 23:41, Matt Holt <notifications@github.com> wrote:@pkpowell To clarify, did the above snippet work for you?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by pkpowell** [comment]
Weirdly it’s all working now…
I had one or two spurious tls errors on a 10.15 machine. Is it possible there’s a delay before certs are served?

**Comment by mholt** [comment]
@pkpowell I was referring to the rewrites, not the TLS config. Are the rewrites working for you?

**Comment by pkpowell** [comment]
yes, the rewrites are working.

**Comment by mholt** [comment]
FYI, I have just implemented this:

> A way to do "contains" matches on headers without using regular expressions (for performance reasons) -- in other words, if the header matcher was used instead of header_regexp, you could specify something like header User-Agent *Darwin/18* and it would do a very fast strings.Contains() match because it has wildcards on both sides; similarly could do prefix/suffix matching if the wildcard was just on one side.
