### ISSUE TITLE
net::ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by lscgzwd** [caddyserver/caddy#2897]
## 1. Which version of Caddy are you using (`caddy -version`)?

1.0 custom

## 2. What are you trying to do?

view my sites

## 3. What is your Caddyfile?
```text
domain1, domain2,  domain2,  domain2 {
    proxy / 172.17.17.49:10080 {
        transparent
    }
    tls i@shuncheng.lu
    log requests.log {
        rotate_size 50
        rotate_age 90
        rotate_keep 20
    }
    errors /workspace/proginn2/log/caddy-error.log
    timeouts 30m
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

supervisor
```
[program:proginn]
directory=/workspace/projects/proginn-gogs-proxy/
command=caddy -agree
#user=root
autorestart=yes
startsecs=5
startretries=400
redirect_stderr=true
environment=DNSPOD_API_KEY="xxx,xxxx"
```

## 5. Please paste any relevant HTTP request(s) here.

![image](https://user-images.githubusercontent.com/7054255/69605169-62dd6900-105a-11ea-9289-0297bb11d3c0.png)
![image](https://user-images.githubusercontent.com/7054255/69605214-7f79a100-105a-11ea-8d65-63f3dfb993bc.png)

## 6. What did you expect to see?

200 ok

## 7. What did you see instead (give full error messages and/or log)?

![image](https://user-images.githubusercontent.com/7054255/69605243-99b37f00-105a-11ea-8fb0-b25b9465650e.png)

## Bonus: What do you use Caddy for? Why did you choose Caddy?

auto ssl, replace nginx

**Comment by mholt** [comment]
Thanks for your question, and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for specific, development-focused discussions, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

**Comment by rffensick** [comment]
I'm sorry @lscgzwd , did you manage to solve the problem? If so, could you share your experience?
