### ISSUE TITLE
How to make http and websocket work in the same path?

### ISSUE THREAD

**Issue by Antecer** [caddyserver/caddy#2933]
I want make http and websocket work in the same path.

For example this is a test path: `test.com/test/`

if caddy get http(s) link, i want caddy return `index.html`.
if caddy get websocket link, i want caddy proxy to 127.0.0.1:10000.

How do I need to configure Caddyfile to achieve this?

**Comment by Antecer** [comment]
now i use this config to proxy to 127.0.0.1:10000
it work normal, but webpage can't work, i don't know how to make webpage work.
```
localhost {
	root /home/www
	gzip
	tls xxxx@outlook.com
	proxy /test 127.0.0.1:10086 {
		without /test
		websocket
	}
}
```

**Comment by francislavoie** [comment]
Next time, please ask your usage questions on https://caddy.community as this is the issue board for bugs and feature requests.

In Caddy v1, you're missing one piece to make it work. You need to set up a rewrite that will translate any path that is intended to upgrade a request from HTTP to websockets to some dummy path that will be used for routing it to the proxy internally. Here, I used `/websocket-proxy`, because it's probably unlikely you'll be using that path for anything useful in your app. You can choose whatever you want here, users will never see that path anyways.

```
localhost {
    root /home/www
    gzip
    tls xxxx@outlook.com

    rewrite / {
        if {>Connection} has Upgrade
        if {>Upgrade} is websocket
        to /websocket-proxy/{path}?{query}
    }

    proxy /websocket-proxy 127.0.0.1:10000 {
        without /websocket-proxy
        transparent
        websocket
    }
}
```
