### ISSUE TITLE
Is there a way to refer to Caddyfile in the relative directory of the `main.go` program for caddy v1

### ISSUE THREAD

**Issue by CMCDragonkai** [caddyserver/caddy#2942]
I have a project with `main.go` on the project root, and also a `Caddyfile` in the project root.

I'd like to embed the `Caddyfile` directly into `main.go`. So that way the resulting compiled program always launches with the Caddyfile that I supplied.

This example: https://github.com/caddyserver/caddy/wiki/Embedding-Caddy-in-your-Go-program

doesn't seem to show how to refer to a relative Caddyfile to the `main.go` file.

**Comment by CMCDragonkai** [comment]
For reference I have:

```
package main

import (
	"github.com/caddyserver/caddy/caddy/caddymain"
	_ "github.com/techknowlogick/caddy-s3browser"
)

func main() {
	caddymain.EnableTelemetry = false
	caddymain.Run()
}
```

Are we meant to import `caddy` and set that up?

**Comment by mholt** [comment]
So you want to embed the Caddyfile directly into the compiled binary, so that it does not need to use an external Caddyfile at all?

If so, then yes, there are instructions at the very top of the godoc for doing this: https://godoc.org/github.com/caddyserver/caddy - when you call [Start](https://godoc.org/github.com/caddyserver/caddy#Start) you give it a Caddyfile as input.

If you want to refer to the Caddyfile relative to main.go, then no, because once you compile the program, notion of the source files goes away. You only have relative to the current working directory as described by the system environment then.

Hope that helps!

**Comment by CMCDragonkai** [comment]
Is there a way to read in the Caddyfile prior to compilation so the Caddyfile is embedded? Or alternatively and better, specify the Caddyfile in golang in main.go code?

Actually I know that my executable will be relative to the Caddyfile always.

On 20 December 2019 18:23:37 GMT+11:00, Matt Holt <notifications@github.com> wrote:
>So you want to embed the Caddyfile directly into the compiled binary,
>so that it does not need to use an external Caddyfile at all?
>
>If so, then yes, there are instructions at the very top of the godoc
>for doing this: https://godoc.org/github.com/caddyserver/caddy - when
>you call [Start](https://godoc.org/github.com/caddyserver/caddy#Start)
>you give it a Caddyfile as input.
>
>If you want to refer to the Caddyfile relative to main.go, then no,
>because once you compile the program, notion of the source files goes
>away. You only have relative to the current working directory as
>described by the system environment then.
>
>Hope that helps!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/caddyserver/caddy/issues/2942#issuecomment-567821414

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
