### ISSUE TITLE
start caddy failed  -- caddy.service: main process exited, code=exited, status=217/USER

### ISSUE THREAD

**Issue by ariesfans** [caddyserver/caddy#2953]
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/etc/systemd/system/caddy.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2019-12-29 18:37:56 CST; 3min 54s ago
     Docs: https://caddyserver.com/docs
  Process: 1493 ExecStart=/usr/local/bin/caddy -log stdout -log-timestamps=false -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp (code=exited, status=217/USER)
 Main PID: 1493 (code=exited, status=217/USER)

someone can help me plz?

**Comment by mholt** [comment]
Thanks for your question, and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
