### ISSUE TITLE
is forwardproxy plugin enabled in Caddy 2 ?

### ISSUE THREAD

**Issue by changchichung** [caddyserver/caddy#2991]
I want to use hashed password for basicauth , 
but I can not find any forwardproxy documents in Caddy 2 .
is this plugin still work in Caddy 2 ?

**Comment by francislavoie** [comment]
Since Caddy v2 is quite new and still in beta, there are hardly any modules written yet (plugins were renamed to modules in v2).

The documentation for writing modules is here: https://caddyserver.com/docs/extending-caddy

The forwardproxy plugin (v1) is found here: https://github.com/caddyserver/forwardproxy

You could try to port the plugin yourself to v2 modules if you absolutely need it.
