### ISSUE TITLE
How to disable automatic TLS certificate management in Caddy 2?

### ISSUE THREAD

**Issue by aeroxy** [caddyserver/caddy#3013]
I did my Caddyfile as such:

```
caddy.com:443 {
  tls /etc/certs/caddy.crt /etc/certs/caddy.key
  reverse_proxy /caddy 127.0.0.1:8443 {
    transport http {
      tls
    }
  }
}
```

This did not disable automatic TLS certificate management it seems, the log reads:

```
INFO	http	enabling automatic TLS certificate management	{"domains": []}
```

But it seems that no domain is in the automatic TLS certificate management bucket, but how do I disable it completely in Caddy 2?

**Comment by mholt** [comment]
Thanks for your question, and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

To answer quickly though, you can have fine-grained control over automatic HTTPS with JSON, for now: https://caddyserver.com/docs/json/apps/http/servers/automatic_https/

**Comment by ghostsquad** [comment]
So there's no way to disable automatic HTTPS is using the Caddyfile format?

**Comment by ghostsquad** [comment]
thanks @mholt. You are the best.

**Comment by yonixw** [comment]
For quick reference:

```
"automatic_https": {
			"disable": true / false,
```

https://caddyserver.com/docs/json/apps/http/servers/automatic_https/
https://caddyserver.com/docs/json/apps/http/servers/

**Comment by jak3ster** [comment]
@yonixw is there a format on how to implement in CaddyFile instead of JSON ?

I found the entry for "[disable_certificates]": false, in the provided link, but would like to use in CaddyFile config.

**Comment by jak3ster** [comment]
@yonixw I found the answer! thanks!
https://caddyserver.com/docs/caddyfile/options
