### ISSUE TITLE
How to disable automatic HTTP->HTTPS redirects in Caddy 2?

### ISSUE THREAD

**Issue by aeroxy** [caddyserver/caddy#3014]
I have another service listening at port 80 and wish to keep Caddy 2 away from port 80 completely.

I did my Caddyfile as such:

```
caddy.com:443 {
  tls /etc/certs/caddy.crt /etc/certs/caddy.key
  reverse_proxy /caddy 127.0.0.1:8443 {
    transport http {
      tls
    }
  }
}
```

This did not disable automatic HTTP->HTTPS redirects it seems, the log reads:

```
INFO	http	enabling automatic HTTP->HTTPS redirects	{"server_name": "srv0"}
```

How can I keep Caddy 2 away from port 80 completely?

**Comment by mholt** [comment]
Currently you can customize the automatic HTTPS using JSON: https://caddyserver.com/docs/json/apps/http/servers/automatic_https/ -- set the `disable_redirects` property to `true`.

Hope that helps!

**Comment by psidex** [comment]
Will it be possible to do this in a normal Caddyfile in the future?

**Comment by francislavoie** [comment]
Yes: https://github.com/caddyserver/caddy/pull/3284

**Comment by averri** [comment]
I don't think this is a good feature: redirect from port 80 to port 443 by default. This is very intrusive, even when the user specifies that that port 80 is not in use, Caddy tries to bind to port 80 by default.

> Currently you can customize the automatic HTTPS using JSON:
Is it possible to mix JSON and non JSON in the same Caddyfile? If it's not possible, it's even worst, we have to drop the simple syntax in order to use JSON.

**Comment by mholt** [comment]
@philpraxis Which link doesn't work? They all load here.
