### ISSUE TITLE
How do I achieve "transparent" reverse_proxy with Caddy 2 (with tls and http2)?

### ISSUE THREAD

**Issue by aeroxy** [caddyserver/caddy#3015]
I've noticed in Caddy 2, there is no "transparent" in reverse_proxy <https://caddyserver.com/docs/caddyfile/directives/reverse_proxy>.

I did my Caddyfile as such:

```
caddy.com:443 {
  tls /etc/certs/caddy.crt /etc/certs/caddy.key
  reverse_proxy /caddy 127.0.0.1:8443 {
    transport http {
      tls
    }
  }
}
```

How can I forward 443 to 8443 transparently?

I have a http2 service running at 127.0.0.1:8443 with the same cert: `/etc/certs/caddy.crt` & `/etc/certs/caddy.key`. But I received `ERROR	http.log.error	x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs` in the log.

Does this mean I cannot transparently forward http2?

**Comment by mholt** [comment]
There's no "transparent preset" in v2 like there was with v1 (yet?) but it's simple:

```
header_up Host {host}
```

**Comment by mholt** [comment]
Actually, to clarify: in v2, the `Host` header going to the upstream is passed through (unmodified) by default. In other words, the way it currently works, "transparent" mode is the default (minus any extra headers you want added). So, unless you need extra headers like X-Real-Ip (most apps don't), you don't have to do anything. So disregard my comment above.

If you want the upstream's address in the Host header that goes to the upstream, then you can do:

```
header_up Host {http.reverse_proxy.upstream.hostport}
```

Otherwise, you won't have to add/change anything.
