### ISSUE TITLE
v2: Add `caddy fmt` command to restructure/tab Caddyfiles

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#3020]
As someone who's been frequenting the https://caddy.community forums recently, I see a lot of people who don't bother to tab their Caddyfiles, and it makes it a bit annoying to read when helping them out.

I think it would be pretty cool if we had a  `caddy fmt /path/to/Caddyfile` command that just rewrote the Caddyfile while cleaning up whitespace.

**Comment by mholt** [comment]
I would love to see this.

**Comment by vrongmeal** [comment]
Hey, I'd like to work on this. Can I take this up?

**Comment by mholt** [comment]
@vrongmeal Yes, please do! You've got it. :+1:

Try to avoid adding any dependencies if possible; feel free to submit a draft PR any time -- since this is potentially a larger feature, having iterative reviews might be best. Also, this should be something that is fun and easy to test, so please add tests! 🕺

**Comment by vrongmeal** [comment]
Sure! It does seem fun to start with. I'll keep posting updates on this regularly 😃

**Comment by mholt** [comment]
Merged the initial implementation, so, closing this. Thanks again @vrongmeal !
