### ISSUE TITLE
v2: PHP-FPM using socket but "missing port in address?"

### ISSUE THREAD

**Issue by dogpatchmedia** [caddyserver/caddy#3034]
VERSION: 

```v2.0.0-beta.13 h1:QL0JAepFvLVtOatABqniuDRQ4HmtvWuuSWZW24qVVtk=```

CONFIG:
```
domain.com, www.domain.com {
	root * /home/caddy
	encode gzip
	php_fastcgi / unix//var/run/php/php7.3-fpm.sock php 
	#php_fastcgi / 127.0.0.1:9000 php	
	file_server
}
```
PROBLEM:

```
php_fastcgi / unix//var/run/php/php7.3-fpm.sock php = error: missing port in address
```

```
php_fastcgi / 127.0.0.1:9000 php = error: dialing backend: dial tcp 127.0.0.1:9000: connect: connection refused
```

I can't get PHP-FPM to work. I get errors either way I try and configure it. Port 9000 is open in UFW so I dont know what is causing the connection refused on that. The first error cause a 500 and the second causes a 502. 

I'd like to use the socket not the port since its on the same machine. 

Ive read pretty much every post about PHP-FPM and Caddy2 and none of it is working for me.

**Comment by mholt** [comment]
Whatever `php` is, it needs a port -- the server doesn't know what port to dial if it only has a hostname.

**Comment by dogpatchmedia** [comment]
so php_fastcgi / unix//var/run/php/php7.3-fpm.sock php should be php_fastcgi / unix//var/run/php/php7.3-fpm.sock php:9000 (or whatever) ?

**Comment by whitestrake** [comment]
Why is `php` on the end there? Are you emulating the [old v1 `fastcgi` PHP preset](https://caddyserver.com/v1/docs/fastcgi#presets)?

I note that there is no such preset in v2, the syntax only calls for two parameters - a matcher and the upstream server: https://caddyserver.com/docs/caddyfile/directives/php_fastcgi

Therefore, `php` here is being interpreted as a second upstream. If you have a second upstream located at `php:9000`, then yes, it should be `php:9000`. If you're just carrying over the preset from v1, drop it entirely; just use `php_fastcgi / unix//var/run/php/php7.3-fpm.sock`.

**Comment by whitestrake** [comment]
P.S. re: connection refused - it _could_ occur for an open port that no program is currently listening on, the operating system is the one issuing a refusal in this case. If you've got PHP-FPM listening on the socket, did you disable the port 9000 listener maybe? Just something to double check, although hopefully unnecessary if you get the socket working.

**Comment by dogpatchmedia** [comment]
> Why is `php` on the end there? Are you emulating the [old v1 `fastcgi` PHP preset](https://caddyserver.com/v1/docs/fastcgi#presets)?
> 
> I note that there is no such preset in v2, the syntax only calls for two parameters - a matcher and the upstream server: https://caddyserver.com/docs/caddyfile/directives/php_fastcgi
> 
> Therefore, `php` here is being interpreted as a second upstream. If you have a second upstream located at `php:9000`, then yes, it should be `php:9000`. If you're just carrying over the preset from v1, drop it entirely; just use `php_fastcgi / unix//var/run/php/php7.3-fpm.sock`.

im getting conflicting info about how to get php to work in caddy. i want to use caddy2 but i cant tell whats caddy1 and whats caddy2 in the documentation since the actual docs suck pretty bad are are just the most basic of basic. 

so i got the web server working, but php doesnt "work" the php parts of the page dont update when the page is reloaded.

**Comment by whitestrake** [comment]
Huge amounts of threads on the community forums relate to v1 because v2 is relatively very new. Assume that any thread that doesn't explicitly mention v2 is not applicable at all.

Here's the official home of Caddy v2 documentation: https://caddyserver.com/docs/

I have also linked the `php_fastcgi` documentation in the comment you quoted.

Try that one with just the unix socket and no `php` on the end and let us know if it works. Hopefully you should be up and running with just that.

**Comment by mholt** [comment]
@dogpatchmedia 

> im getting conflicting info about how to get php to work in caddy. i want to use caddy2 but i cant tell whats caddy1 and whats caddy2 in the documentation

By default, the docs are for Caddy 2 now. Just look at the big banners at the top of each page:

<img width="1173" alt="Screen Shot 2020-02-10 at 10 55 06 PM" src="https://user-images.githubusercontent.com/1128849/74253475-5c9b7800-4cac-11ea-94cb-e22c370c6e92.png">

<img width="978" alt="Screen Shot 2020-02-10 at 10 55 19 PM" src="https://user-images.githubusercontent.com/1128849/74253484-5efdd200-4cac-11ea-8fcb-ca78a018703f.png">

I don't think that's very difficult...

> since the actual docs suck pretty bad are are just the most basic of basic.

You can help improve them instead of complaining that they "suck pretty bad", you know. The docs are open source: https://github.com/caddyserver/website
