### ISSUE TITLE
Read redirects from file

### ISSUE THREAD

**Issue by jlelse** [caddyserver/caddy#3037]
Netlify allows configuration for [redirects and rewrites with files](https://docs.netlify.com/routing/redirects/), e.g. redirects are read from the `_redirects` file in the root folder. Is something similar possible with Caddy 1 / 2 too?

A use case for this is having a site generated by a static site generator like Hugo, which allows the use of aliases. Alias redirects are generated by default using HTML redirects. But it's possible to generate a file containing all redirects, so that Netlify for example can already do 301 / 302 HTTP redirects.

**Comment by mholt** [comment]
> Is something similar possible with Caddy 1 / 2?

Yes, simply generate a generate a Caddy config (JSON, Caddyfile, NGINX, whatever other format you want) that includes the redirects. You can use files with the command line, or you can skip the file thing and go straight to its API.

Keep in mind that one design goal of Caddy 2 is to centralize the config to a single place rather than scattering it in different places. It makes for lower maintenance, fewer mistakes, and easier troubleshooting.
