### ISSUE TITLE
v2: Error chains override the default error handling behavior

### ISSUE THREAD

**Issue by roblabla** [caddyserver/caddy#3053]
If a config has an error handling route, it will [bypass the default codepath that sets the status code](https://github.com/caddyserver/caddy/blob/v2/modules/caddyhttp/server.go#L224) (it will go in the if branch instead of the else).

This is problematic, because it's possible for the error handler to never actually handle an error. What if our error handling route handles only some paths, but not others? For instance in the config at the bottom of the post, we actually don't handle anything at all! What happens in this case is, we accidentally return a 200 OK response instead of the promised 500 we should receive (as set by the `error` Handler).

Ideally, I think we should automatically append a suffix middleware that sets the error code. I think we could do this by [replacing this line](https://github.com/caddyserver/caddy/blob/v2/modules/caddyhttp/caddyhttp.go#L188) with something along the lines of

```go
srv.errorHandlerChain = srv.Errors.Routes.Compile(HandlerFunc(func(w http.ResponseWriter, r *http.Request) error {
    repl := r.Context().Value(caddy.ReplacerCtxKey).(*caddy.Replacer)
    status_code := repl.Get("http.error.status_code")
    if status_code_int, err := strconv.Atoi(status_code); err != nil {
        w.WriteHeader(status_code_int)
    } else {
        w.WriteHeader(500)
    }
}))
```

---

The problematic json. You can run it with `caddy run -config test.json -adapter json5`

```json5
{
  // Boilerplate to make it easy to run config
  "admin": { "disabled": true },
  "apps": {
    "http": {
      "http_port": 4444,
      "servers": {
        "srv0": {
          "listen": [":4444"],
          "routes": [{
            "handle": [{"handler": "error"}]
          }],
          // Imagine we have routes in there that match based on status_code for instance, and don't handle all cases
          "errors": {
            "routes": [
              {} // Noop route. I'm... surprised this works at all X)
            ]
          }
        }
      }
    }
  }
}
```

**Comment by mholt** [comment]
Thanks for the issue.

There's probably a few ways to solve this -- appending a catch-all handler as you suggested is one of them. However, maybe a better way of doing that is to pass in your proposed handler [instead of the emptyHandler like is currently used here](https://github.com/caddyserver/caddy/blob/57c6f22684e74191814a30f9de83a05c11ac4b78/modules/caddyhttp/caddyhttp.go#L188).

Also, instead of using replacers to access the error information, I would access the error information directly on the request context using `ErrorCtxKey`.

**Comment by Henrocker** [comment]
My domain hnrk.io has a wildcard DNS entry at A and AAAA:

- *.hnrk.io A "167.86.123.102"
- *.hnrk.io AAAA "2a02:c207:3004:1207:be:a:bad:babe"

and my certificate for hnrk.io is a wildcard cert. So effectively I let Caddy v2 choose the right vhost (if specified in Caddyfile) via SNI.

If I now use the following config and try to reach e.g. abc.hnrk.io (no entry in Caddyfile) I get displayed a blank white page and HTTP status code 200:

```
hnrk.io, www.hnrk.io {
        root * /etc/caddy/html
        tls /etc/caddy/hnrk.io.crt /etc/caddy/hnrk.io.key
        encode brotli zstd gzip
        php_fastcgi unix//run/php/php7.3-fpm.sock
        try_files {path} /index.php?{query}
        file_server /md* browse
        file_server
}
draw.hnrk.io {
        root * /etc/caddy/html/draw
        tls /etc/caddy/hnrk.io.crt /etc/caddy/hnrk.io.key
        encode brotli zstd gzip
        php_fastcgi unix//run/php/php7.3-fpm.sock
        try_files {path} /index.php?{query}
        file_server
}
```

IIRC, Caddy v1 with the same config returned something along the lines of: "abc.hnrk.io is not listining on this interface." with a status code of 404.

Should this be adapted to Caddy v2?

**Comment by mholt** [comment]
@Henrocker I remember we had this discussion on our dev Slack a while ago, and I think the conclusion we came to is that in Caddy 2 we're trying to keep it simple and avoid turning things on by default that are difficult/awkward to turn off. The v1 behavior also leaks information (which a certain vocal minority hates, but I disagree that is a "leak" but that's another topic).

In the case of a file server, it is very easy to define when a 404 is returned: when a requested file isn't found. In general, though, it is not easy to answer this question, because specs and other docs typically use the term "resource", but the questions are, what constitutes a resource? Is it something transparent to the client (such as a "route" in Caddy 2 configland), or something more concrete like a file? Is a DNS zone entry a "resource"? Is that even relevant to the HTTP request+response in these cases? 🤷‍♂  Anyway, it's complicated. A discussion on the proper semantics of HTTP could be had on [our forum](https://caddy.community) instead.
