### ISSUE TITLE
How to redirct http traffic to https

### ISSUE THREAD

**Issue by sysadmin-james** [caddyserver/caddy#3106]
i wanna redirect my http to https using caddy server.
I am using caddy version 0.10.0
 here is my Caddyfile

              `:5601 {
                  basicauth / admin xxxxxxxxx
                  bind {$ADDRESS}
                  proxy / kibana:5601 {
                  transparent
                }

                 redir 301 {
                    if {scheme} is http
                    / https://{host}{uri}
                 }
                }

                 errors stderr

                  tls /etc/pki/tls/certs/cert.crt /etc/pki/tls/private/cert.key
                 }`
my traffic is not getting redirected to https once a request comes on http. I had to explicitly add https to the url to get to my site.
What needs to be done to fix this.
I running caddy as a  docker container.

**Comment by mholt** [comment]
Thanks for your question, and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

**Comment by Arcitec** [comment]
For people coming from Google (since this page is the top result):

- There are plenty of ways to redirect HTTP to HTTPS when using standard web ports `:80` and `:443` in Caddy. Repetition of those docs is unnecessary here.
- The most common issue self-hosters run into is that you've put your HTTPS server on a non-standard port such as `:20000`, which makes Caddy bind HTTPS (TLS) on that port, without any HTTP listener.
- Browsers default to `http://` if no protocol is listed in a link.
- Browsers trying to connect to your server can therefore end up on `http://example.com:20000`. The Go internet socket library that Caddy uses then inspects the traffic, sees that there's plain unencrypted HTTP traffic, and it then outputs an error saying `Client sent an HTTP request to an HTTPS server.` (this error comes from Go, not from Caddy).
- Since the error happens at the Go internet socket layer, there's no chance for Caddy to intercept it and perform any actions on the HTTP traffic coming to your HTTPS port. Caddy just receives a "TLS handshake error" from the Go socket library.
- But thankfully, @francislavoie has put in the hard work of making Caddy capable of inspecting the traffic and auto-redirecting HTTP to HTTPS. He did this by creating a listener layer that pre-inspects the traffic before Go's TLS handler takes over. Very smart solution.

Just add this to your Caddyfile to enable the data inspection and auto-redirect from HTTP to HTTPS when you're hosting on a non-standard port (I'll also include an example self-host domain configured for HTTPS on an a custom port):

```
{
  servers :20000 {
    listener_wrappers {
      http_redirect
      tls
    }
  }
}

home.example.com:20000 {
  tls {
    dns cloudflare {env.CLOUDFLARE_API_TOKEN}
  }
  reverse_proxy filebrowser:20005
}
```

Note that `servers :20000` intentionally narrows down this injection to specific ports (20000 in this example), to only add the HTTP-to-HTTPS redirect on the non-standard HTTPS socket. This is a good idea if you're actually hosting real HTTP (80) and HTTPS (443) ports on the same server and don't want the injection handler on all ports. But if you're hosting multiple HTTPS services and all of them are on non-standard ports, then you can change it to `servers {}` instead, if you want Caddy to handle HTTP-to-HTTPS redirect injection on every listening port.

More information about `listener_wrappers: http_redirect` below:

- https://caddy.community/t/caddy-v2-redirect-non-ssl-http-traffic-to-https-on-same-non-standard-port/9089/11
- https://caddyserver.com/docs/caddyfile/options#listener-wrappers
- https://github.com/caddyserver/caddy/pull/4585
