### ISSUE TITLE
broken link: https://caddyserver.com/features

### ISSUE THREAD

**Issue by ghostsquad** [caddyserver/caddy#3114]
The readme points to this link which appears to be broken (returns a 404)

**Comment by francislavoie** [comment]
Thanks, that's mainly because the README you see on the repo front page is for Caddy v1, but the site has moved to Caddy v2, and the v1 site is now at https://caddyserver.com/v1.

The link "should" be https://caddyserver.com/#features for the v2 features but if we were to update it on the master branch, it would point to the feature page for the wrong version.
