### ISSUE TITLE
Add donation option in Readme via OpenCollective

### ISSUE THREAD

**Issue by ghostsquad** [caddyserver/caddy#3117]
I'd like to donate to the project, but a recurring donation at the pre-defined tiers via GitHub Sponsor don't work well for me.

If you had an OpenCollective link (and badge) and such, I could donate to this cause.

example:

https://opencollective.com/gacp
https://github.com/vivaxy/gacp#financial-contributors

**Comment by mholt** [comment]
Thanks for bringing this up, and for your offer to donate!

I've looked at OpenCollective before but their fees are really high - 5% on top of what Stripe collects. GitHub sponsorships are free, and they'll even match all donations through this May.

I want sponsors/donors to get the most for their money rather than it being tied up in extra fees. Could you create a sponsorship with GitHub and then cancel after the first month, maybe?

**Comment by ghostsquad** [comment]
What about something like this?

https://www.buymeacoffee.com/

**Comment by mholt** [comment]
Same fees.

Also I don't like coffee 😆

**Comment by ghostsquad** [comment]
Though I understand that you don't want the fees, as those always suck. Is better to receive $0.90 ($1 with 10% taken off) or $0 because there's no method of donation that I'm comfortable with?

You could always add a note in the readme that your preferred donation method is the GitHub Sponsorship because of the lack of fees. But I still think you should give people some choices. At the end of the day, I'm paying the fee, not you.

**Comment by mholt** [comment]
@ghostsquad Thanks for the thought-provoking comments!

What's wrong with GitHub sponsors, exactly? I undersand having to cancel after the first month to do a one-time donation may be inconvenient, but is that all?

$1 donations -- or any small, one-time donations -- do have a few subtle side-effects:

- All donations incur some tax and accounting overhead. Even when using accounting apps, all transactions require a manual review. This administrative overhead can cost more than the amounts of the small one-time donations. Further, not all accounting apps are free or trustworthy; and free, self-hosted accounting apps require more effort to set up and maintain. Frankly, reporting a bunch of small transactions is harder. Inviting small donations is also inviting even _more_ work for the developer, which is somewhat counterproductive. I just don't wish this work upon myself (or other FOSS devs).

- Small donations are unsustainable at the current popularity of the Caddy project, especially for one-time donations: there just isn't enough volume for those donations to make a tangible difference to offset living costs, stress levels, or social expectations. In fact, they end up raising social expectations, because even though I (and any FOSS developer) would be grateful for any donation, expressing that gratitude for all small/$1 donations feels obligatory, because it _is_ still a kind donation and gesture, which should be acknowledged by implied social contract. I know, you may say "Nah no thanks required" but that's not natural on a FOSS developer's conscience.

- If small, one-time donations become "the going rate", it has a tendency to lock the market/industry into those rates. It's like the difference at tipping a street performer and tipping at a nice upscale restaurant. Few people tip street performers what they're worth because that's just how people tip; but tip too low at an upscale restaurant, and you're kind of marked, ya know? By asking for non-trivial and recurring donations, I am trying to make a statement that will help keep OSS more sustainable.

That said, I'd be happy to accept your support.

The best thing you can do to help the Caddy project -- other than using Caddy and filing issues and reviewing PRs, etc. -- is to _share it_. Let everyone know you use it and like it, and convince people to start using it. That has little-to-no monetary cost for you, and benefits the project much more than a $1 donation.

So, rather than small, one-time donations, I would rather that generosity be directed toward spreading the project far and wide.

I hope that is acceptable!

**Comment by ghostsquad** [comment]
@mholt you make a compelling argument. I was introduced to Caddy by a friend/co-worker @ctbarrett, and have loved and followed it ever since, spreading the word as it was relevant.

> If small, one-time donations become "the going rate", it has a tendency to lock the market/industry into those rates. It's like the difference at tipping a street performer and tipping at a nice upscale restaurant. Few people tip street performers what they're worth because that's just how people tip; but tip too low at an upscale restaurant, and you're kind of marked, ya know? By asking for non-trivial and recurring donations, I am trying to make a statement that will help keep OSS more sustainable.

I guess my _only_ point is that $1 is better than $0, and if the "cost of entry" is too high, you may not get as many donors.

This statement is coming from someone who supports several creators on Patreon, tips consistently when there's no obligation to do so, and supports Kickstarter projects with the "no-reward" tiers. I feel like this is like voting. It kind of feels like a single vote doesn't matter, but 1000 votes do matter. 

I have monthly donation/tipping budget, and I have a lot of people I'd love to give more money to. $1/mo is equivalent to $12/yr or maybe paying your bill for lunch 1/yr. It's not a lot, but if you had 365 people doing that, you'd have free lunch every day. Sounds pretty great! Anyways...

Regardless of what you decide, you got a $25 sponsorship from me. :)

Keep it up! I love your work.

**Comment by mholt** [comment]
Thanks :) 💚 

Yes, if we had anywhere _near_ the volume of thousands of "voters" (donors), then I could consider the < $10 range, but that's just not feasible here.

I appreciate the discussion and your support! Please continue to share the project. :+1:
