### ISSUE TITLE
When I run the caddy it does this

### ISSUE THREAD

**Issue by troydatboi** [caddyserver/caddy#3123]
2020/03/06 16:12:19 [INFO] [root] acme: Obtaining bundled SAN certificate
2020/03/06 16:12:20 [INFO] [root] acme: Obtaining bundled SAN certificate
2020/03/06 16:12:22 [INFO] [root] acme: Obtaining bundled SAN certificate
2020/03/06 16:12:23 [INFO] [root] acme: Obtaining bundled SAN certificate
2020/03/06 16:12:24 [INFO] [root] acme: Obtaining bundled SAN certificate
2020/03/06 16:12:25 failed to obtain certificate: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for "root": Domain name needs at least one dot, url:

**Comment by mholt** [comment]
Thanks for your question, and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
