### ISSUE TITLE
v2: http -> https redirect pointing to wrong site

### ISSUE THREAD

**Issue by anoadragon453** [caddyserver/caddy#3127]
I have a Caddyfile containing the following:

```
## Main site ##

chat.horse {

  file_server {
    root /var/www/html
  }

}

## Riot ##

client.chat.horse {

  file_server {
    root /var/www/riot
  }

}

## Dimension ##

dimension.chat.horse {

  reverse_proxy * localhost:8184

}

## Client-Server API ##

matrix.chat.horse {

  reverse_proxy /_matrix/media* localhost:8333 {
    header_up Host chat.horse
  }

  # All other requests on this port are forwarded to the homeserver
  reverse_proxy /_matrix/* localhost:8008

}

## Federation API ##

matrix.chat.horse:8448 {

  # Media requests over federation are directed to TravisR's media repo
  reverse_proxy /_matrix/media* localhost:8333 {
    header_up Host chat.horse
  }

  # All other requests on this port are forwarded to the homeserver
  reverse_proxy /_matrix/* localhost:8008

}
```

When one visits http://chat.horse, they are 308 redirected to https://chat.horse:8448, which is odd. I'd expect them to be redirected to https://chat.horse:443. Is this a bug, or expected behaviour somehow?

caddy startup logs:

```
Mar 08 07:14:17 anoa systemd[1]: Starting Caddy Webserver...
Mar 08 07:14:17 anoa caddy[1786]: 2020/03/08 07:14:17.361        INFO        using adjacent Caddyfile
Mar 08 07:14:17 anoa caddy[1786]: 2020/03/08 07:14:17.366        INFO        admin        admin endpoint started        {"address": "localhost:2019", "enforce_origin": false, "origins": ["localhost:2019"]}
Mar 08 07:14:17 anoa caddy[1786]: 2020/03/08 07:14:17.367        INFO        http        server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS        {"server_n
Mar 08 07:14:17 anoa caddy[1786]: 2020/03/08 07:14:17.367        INFO        http        enabling automatic HTTP->HTTPS redirects        {"server_name": "srv0"}
Mar 08 07:14:17 anoa caddy[1786]: 2020/03/08 07:14:17.367        INFO        http        enabling automatic HTTP->HTTPS redirects        {"server_name": "srv1"}
Mar 08 07:14:17 anoa caddy[1786]: 2020/03/08 07:14:17.368        INFO        http        enabling automatic TLS certificate management        {"domains": ["matrix.chat.horse", "chat.horse", "dimension.chat.hors
Mar 08 07:14:17 anoa caddy[1786]: 2020/03/08 07:14:17.368        INFO        http        enabling automatic TLS certificate management        {"domains": ["matrix.chat.horse"]}
Mar 08 07:14:17 anoa caddy[1786]: 2020/03/08 07:14:17.371        INFO        tls        cleaned up storage units
Mar 08 07:14:17 anoa caddy[1786]: 2020/03/08 07:14:17.371        INFO        autosaved config        {"file": "/var/www/.config/caddy/autosave.json"}
Mar 08 07:14:17 anoa caddy[1786]: 2020/03/08 07:14:17.371        INFO        serving initial configuration
Mar 08 07:14:17 anoa caddy[1786]: 2020/03/08 07:14:17 [INFO][cache:0xc000499270] Started certificate maintenance routine
Mar 08 07:14:17 anoa caddy[1786]: Successfully started Caddy (pid=1804)
Mar 08 07:14:17 anoa systemd[1]: Started Caddy Webserver.
```

Thanks!

**Comment by mholt** [comment]
Thanks for the report, and for not redacting anything crucial like most people do. :) I've identified the bug, but I don't know if you'll like the fix.

You have `matrix.chat.horse` used on both port :443 ("Client-Server API") and port :8448 ("Federation API"). I can fix it so that Caddy redirects `chat.horse` to port 443, but which port should `matrix.chat.horse` be redirected to? That domain name serves HTTPS on two ports: 443 and 8448.

I'm not yet sure which one will be easier to implement... but I'm guessing the redirect to the 443 port. Is that OK with you?

**Comment by francislavoie** [comment]
I'm pretty sure if no port is specified for a domain, we should always assume `80` and `443` (or the `http_port` and `https_port` global options values if specified, I guess). There is a port specified for the federation site, so it shouldn't be involved in the redirects.

**Comment by anoadragon453** [comment]
Yeah, I'd vote for assuming `443`, but having a way of specifying another port if desired (which you could just do with a redirect rule?)

**Comment by mholt** [comment]
@anoadragon453 I've rewritten the algorithm that makes the automatic HTTP->HTTPS redirects. Turns out, it's actually a really difficult problem! (And I mean that in the computing sense, too -- it is hard to find an efficient algorithm that is correct as config grows larger.)

Can you please pull down the branch at https://github.com/caddyserver/caddy/pull/3128 and see if it works for you? It appears to do the trick for me, but it's late here so I haven't tested it thoroughly. Please try a few variations of your config as well and see if you get any unexpected results. Thanks!
