### ISSUE TITLE
v2: Directive `uri strip_prefix` will strip all '/' when proxy request

### ISSUE THREAD

**Issue by wzhzzmzzy** [caddyserver/caddy#3169]
### My Caddy Version
`v2.0.0-beta.18 h1:N8CR8nO+n9Sk16CBx6ysVZWIZv0hgtU1J84st1bFWgI=`

### What happened

- Caddyfile
```
:8080 {
  route /login/* {
    uri strip_prefix login/
    reverse_proxy 127.0.0.1:8002
  }
}
```

- Request url after proxy
```
201 POST / (127.0.0.1)
404 GET healthcheck (127.0.0.1)
```

Shouldn't it be `/healthcheck` ?

And when I change `strip_prefix login/` to `strip_prefix login`, caddy works as expected.
```
200 GET /healthcheck (127.0.0.1)
200 GET / (127.0.0.1)
```

So [The Examples in Directive Document](https://caddyserver.com/docs/caddyfile/directives/uri) is wrong or not?

**Comment by mholt** [comment]
Oh... yeah... I guess the example in the docs is wrong, the example should probably be `uri strip_prefix /api` so as to preserve the slash that becomes the new leading slash.

I suppose we _could_ make it so that we always add that leading slash back in, but I don't want to take that flexibility away from users unless we really need to. I think for now, I'll fix the example in the docs. In your case, using either `login` or `/login` would probably work.

Thanks for the question!
