### ISSUE TITLE
False MiTM Detection

### ISSUE THREAD

**Issue by cihanisma** [caddyserver/caddy#3197]
### https://mitm.watch/ Result:
**On MacOS Chrome Version 80.0.3987.149 (Official Build) (64-bit)**
<img width="872" alt="chrome" src="https://user-images.githubusercontent.com/59100702/77765906-36088500-703f-11ea-8c6e-3d0c5acbcf58.png">

**On MacOS Chromium Version 83.0.4094.0 (Developer Build) (64-bit)**
<img width="872" alt="chromium" src="https://user-images.githubusercontent.com/59100702/77766016-5fc1ac00-703f-11ea-85bd-94dc1abb2b53.png">

The results are taken in the same time period.

**Comment by francislavoie** [comment]
https://mitm.watch is using Caddy v1, which is no longer under active maintenance.

The plan is to integrate [Cloudflare's MITM library](https://github.com/cloudflare/mitmengine) into Caddy v2 at some point instead of running our own implementation. See https://github.com/caddyserver/caddy/issues/2530

**Comment by mholt** [comment]
That site is also not owned or maintained by us :P They could probably take it down since they've got their own lib for it now.
