### ISSUE TITLE
Configuration encoding specified in Caddyfile

### ISSUE THREAD

**Issue by thenewguy** [caddyserver/caddy#3210]
I think it would be handy if the Caddyfile specified its own encoding.

I.e. a global configuration parameter "encoding" that is set to a given value for different adapters.  I.e. "json", "caddyfile", "json5", etc.

Then it would be straightforward for adapters to be applied automatically by attempting to load and match each installed adapter until one returns with a valid response and matching "encoding".

File extensions are not super reliable and it would be easier to tell someone just use the encoding you want and place your file at /etc/caddy/Caddyfile

Example, I just spent a few hours working on loading a json configuration and it turns out the file just needed the json file extension.  Not super clear

**Comment by mholt** [comment]
Can you be more specific?

Caddy doesn't care about file extensions, but as a special case it will look for a file called `Caddyfile` in the current directory and if it exists, it will use that in the same way that `--config Caddyfile --adapter caddyfile` works, because the Caddyfile is so common, unless it has a `.json` extension in which case it is not a Caddyfile since the Caddyfile is not JSON format.

In every other case, Caddy doesn't even look at the file extension and just assumes JSON unless `--adaper` is specified. So, as the docs say, use `--adapter` to specify the config adapter, it has nothing to do with file extension.
