### ISSUE TITLE
Wrong CLI help text in 2.0-RC1

### ISSUE THREAD

**Issue by fortysixandtwoahead** [caddyserver/caddy#3220]
Caddy help outputs the following. In usage it says --config, while in the flags text it says -config. The latter is correct, so the dash needs to be removed in the usage text.

```caddy2 help start
Starts the Caddy process, optionally bootstrapped with an initial config file.
This command unblocks after the server starts running or fails to run.

On Windows, the spawned child process will remain attached to the terminal, so
closing the window will forcefully stop Caddy; to avoid forgetting this, try
using 'caddy run' instead to keep it in the foreground.

usage:
  caddy start [--config <path> [--adapter <name>]] [--watch]

flags:
  -adapter string
    	Name of config adapter to apply
  -config string
    	Configuration file
  -watch
    	Reload changed config file automatically
```

**Comment by mholt** [comment]
Both are actually allowed. The Go flag package permits either single or double dashes, and that package is responsible for printing the list of flags, but the syntax at the top is hand written. Since most people prefer the double dashes, I've gone with those typically, but you can use either.

Thanks for using Caddy!
