### ISSUE TITLE
"not" matcher syntax example needed

### ISSUE THREAD

**Issue by yonghui-app** [caddyserver/caddy#3233]
The v2 RC1 changed "not" matcher behavior, but it also breaks my json configuration.

The below config used to work before RC1:
`"match": [
    {
        "not": {
            "host": [
                "example.com"
            ]
        }
    }
]
`

But now it is causing this error message:
> setting up route matchers: route 4: loading matcher modules: module name 'not': decoding module config: http.matchers.not: json: cannot unmarshal object into Go value of type []caddy.ModuleMap

Any suggestions on how to change the config?

**Comment by Mohammed90** [comment]
The `not` matcher takes an array of matchers instead of a single one. So your config should now be:
```
"match": [ 
    { 
        "not": [
            { "host": [ "example.com" ] }
        ]
    } 
]

```

**Comment by mholt** [comment]
I think you're both right! :sweat_smile: The generated docs are wrong because the Not matcher implements its own UnmarshalJSON method to give you that nice pretty JSON interface, but the automated docs won't pick up on it. Hmm. I will have to explain the actual structure in the godoc comments I guess.
