### ISSUE TITLE
Add pidfile support

### ISSUE THREAD

**Issue by otbutz** [caddyserver/caddy#3235]
caddy2 seems to lack support for creating a pid file. At least i couldn't find anything in the documentation and both `caddy help start` / `caddy help run` didn't list anything related to it.

**Comment by mholt** [comment]
What do you need a pid file for?

**Comment by otbutz** [comment]
e.g for easy monit integration:

```
check process caddy with pidfile /var/run/caddy/caddy.pid
```

**Comment by francislavoie** [comment]
@otbutz I can think of two different ways you could do this with Monit instead of a pid file.

- Use the remote host check to see if the admin API is alive:
  `CHECK HOST caddy ADDRESS localhost:2019`
- Configure Caddy to use a unix socket for the admin endpoint (e.g. `admin unix//run/caddy.sock`) and then use the file check to see if the admin API is alive:
  `CHECK FILE caddy PATH /run/caddy.sock`

While it's definitely possible to add a pidfile option, I'm not convinced it's really necessary here. There are alternate approaches to check if Caddy is alive that fit better with the model Caddy is aiming for.

**Comment by otbutz** [comment]
While i agree that there are plenty of alternatives for monit, this was just an example. If it's simple to add the option it would be nice to keep it as was it also provided by caddy v1.

**Comment by JACK-THINK** [comment]
> e.g for easy monit integration:
> 
> ```
> check process caddy with pidfile /var/run/caddy/caddy.pid
> ```

@mholt @francislavoie 

This feature is also what I want.

**Comment by mholt** [comment]
@otbutz @JACK-THINK Implemented in 4df56c7.

**Comment by windware-ono** [comment]
Thanks for adding the `--pidfile` flag.

However, this can only be specified at command line, which is not so easy to do without modifying the systemd unit file, which is not practical when the unit file gets overridden on package updates.

Can you add `--pidfile /var/run/caddy.pid` in the systemd unit file from the official package?

**Comment by windware-ono** [comment]
@francislavoie, By letting `monit` monitor a process by PID, it gives you the ability to monitor its CPU, memory and disk IO usage which cannot be done by just monitoring the port or the socket that it listens on.

**Comment by mholt** [comment]
@windware-ono Can you please open a new issue? What you're asking for is something different than this issue is, and this issue was closed about 2 years ago.
