### ISSUE TITLE
Add realm parameter to basicauth directive for Caddyfile

### ISSUE THREAD

**Issue by Eadinator** [caddyserver/caddy#3252]
This is possible with the JSON structure but not with a Caddyfile (which I am using solely for now at least and would be desirable to have).

For example,

```
basicauth [<matcher>] [<hash_algorithm>] [<realm>] {
	<username> <hashed_password_base64> [<salt_base64>]
	...
}
```

Thanks for your consideration.

**Comment by mholt** [comment]
Hmm, with that syntax it's impossible to know whether the argument after the matcher is supposed to be the algorithm or the realm. We'll need something more like:

```
basicauth [<matcher>] [<hash_algorithm> [<realm>]]
```

In other words, if you specify a realm, you must also specify the hash algorithm.

Want to submit a PR?

**Comment by Eadinator** [comment]
That's a caveat. If you want to specify a hash_algorithm, do you also have to specify a matcher?

**Comment by mholt** [comment]
Matchers are optional and a little special because they have to be one of 3 kinds of values to be considered: https://caddyserver.com/docs/caddyfile/matchers#syntax - if they don't look like one of those, then it's not a matcher.

I guess we could do something similar for the hash algorithm, but it depends how much flexibility we want or how complex we want the parsing logic to be. If you ever wanted a realm named the same as a hash algorithm (haha?) then you'd have to repeat the value twice.

I guess I'm fine with either..

**Comment by Eadinator** [comment]
Typically i guess it's done with key-value pairs, e.g.
basicauth realm=restricted hash_algorithm=algo {
}

Which also allows flexibility in the order, but that seems way more involved and beyond the scope of just this request.

I would submit a PR but this is way beyond my comfort level.

**Comment by francislavoie** [comment]
Considering `<hash_algorithm>` has a default of `bcrypt`, I don't think there's much harm in asking the user to specify that again if they need to also set the realm. I think anything else wouldn't fit well with the current syntax and parsing of the Caddyfile.

```
basicauth /secret/* bcrypt restricted {
    Bob JDJhJDEwJEVCNmdaNEg2Ti5iejRMYkF3MFZhZ3VtV3E1SzBWZEZ5Q3VWc0tzOEJwZE9TaFlZdEVkZDhX
}
```

I'll look into implementing this soon.
