### ISSUE TITLE
unrecognized directive: log

### ISSUE THREAD

**Issue by struCoder** [caddyserver/caddy#3257]
Hello:
My caddy version:
```bash
v2.0.0-beta.13 h1:QL0JAepFvLVtOatABqniuDRQ4HmtvWuuSWZW24qVVtk=
```
OS: `centos7`

caddy config
```bash
tt.domain.com {
    reverse_proxy 127.0.0.1:8990
    log {
        output file /var/log/caddy/access.log
    }
}
```
Reload caddy by:
```bash
systemctl reload caddy
```

I got this error:
```bash
 reload: adapting config using caddyfile: /etc/caddy/Caddyfile:12: unrecognized directive: log
```

**Comment by francislavoie** [comment]
You're using v2.0.0-beta.13 which is quite an old version, which didn't support `log` yet. Please use the latest version!

**Comment by guotie** [comment]
I use 2.7.6, still has this problem

**Comment by guotie** [comment]
```
log {
        output file /var/log/caddy.log
}
```

error:
```
Error: adapting config using caddyfile: /etc/caddy/Caddyfile:11: unrecognized directive: output
```

version:
v2.7.6 h1:w0NymbG2m9PcvKWsrXO6EEkY9Ru4FJK8uQbYcev1p3A=

**Comment by mohammed90** [comment]
> ```
> log {
>         output file /var/log/caddy.log
> }
> ```
> 
> error:
> 
> ```
> Error: adapting config using caddyfile: /etc/caddy/Caddyfile:11: unrecognized directive: output
> ```
> 
> version: v2.7.6 h1:w0NymbG2m9PcvKWsrXO6EEkY9Ru4FJK8uQbYcev1p3A=

Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

**Comment by francislavoie** [comment]
Directives go within site blocks. Make sure to read https://caddyserver.com/docs/caddyfile/concepts#structure
