### ISSUE TITLE
Suggestions for new functions

### ISSUE THREAD

**Issue by etinifninfinite** [caddyserver/caddy#3292]
Want to add a new feature: make different websites use the same port.

thanks

**Comment by mholt** [comment]
Thanks for your question, and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
