### ISSUE TITLE
Replace oxy, which indirectly depends on a Launchpad/Bazaar dependency

### ISSUE THREAD

**Issue by diamondburned** [caddyserver/caddy#3331]
This isn't really Caddy's issue but rather oxy's, however the maintainer refused to merge the PR. Because of this, I have created a fork and changed the dependency.

More information can be found in the other issue, which also explains why this should be done: https://github.com/vulcand/oxy/issues/196.

The new dependency URL is https://github.com/diamondburned/oxy.

**Comment by mholt** [comment]
@diamondburned Thanks for bringing this up and for making a fork!

We could probably write a simpler circuit breaker that does not use the oxy/memmetrics pckage.

I am not sure the circuit breaker is commonly used by most people. Since it's apparently getting in the way of builds, there's still time for us to extract it into a separate repository. So we could keep [the current circuit breaker](https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/reverseproxy/circuitbreaker.go) in a separate repo until it is rewritten without that dependency. If people need it, they can plug it in just like any other modules, no problem. We could even adjust it right away to use your fork as well.

So, I propose:

- We move our standard circuit breaker into a different repo
- We swap out its vulcand/oxy dependency for your fork
- Eventually, we or somebody in the community rewrites it to not require that dependency

What do you think?

**Comment by diamondburned** [comment]
I think that's the best idea.

**Comment by mholt** [comment]
@diamondburned I'm ready to push, but your fork's `go.mod` still declares itself as `github.com/vulcand/oxy` -- I am not 100% sure but I'm pretty sure all occurrences of `vulcand/oxy` and any other package that you forked needs to be replaced with your fork's path, including the go.mod name. (Otherwise we have to use `replace` in downstream go.mod... I think.)

**Comment by diamondburned** [comment]
Oh, sorry. I'll do that right now.

**Comment by diamondburned** [comment]
That took me a while, I `sed`ded the wrong one.

It is now pushed though: https://github.com/diamondburned/oxy/commit/e78a994a595fe88e838f58f73af29e43f4d88425. If you need a version, tell me.

**Comment by mholt** [comment]
@diamondburned Thanks! Almost there :)

Now I am getting this:

```
$ go mod tidy
go: finding module for package gopkg.in/ahmetb/go-linq.v3
go: found gopkg.in/ahmetb/go-linq.v3 in gopkg.in/ahmetb/go-linq.v3 v3.1.0
go: github.com/caddyserver/circuitbreaker imports
        github.com/diamondburned/oxy/memmetrics imports
        github.com/mailgun/holster tested by
        github.com/mailgun/holster.test imports
        gopkg.in/ahmetb/go-linq.v3: gopkg.in/ahmetb/go-linq.v3@v3.1.0: parsing go.mod:
        module declares its path as: github.com/ahmetb/go-linq/v3
                but was required as: gopkg.in/ahmetb/go-linq.v3
```

I am not sure what caused this though.

My current `go.mod` is:

```
module github.com/caddyserver/circuitbreaker

go 1.14

require (
	github.com/caddyserver/caddy/v2 v2.0.0-test.4
	github.com/diamondburned/oxy v1.1.1-0.20200502015114-e78a994a595f
)
```

**Comment by diamondburned** [comment]
Right, I actually get this issue as well, and it seems to be caused by yet another dependency. I'll probably have to fix it with yet another PR to a dependency.

However, this worked for me as a workaround. If you want, I can probably make a PR after a couple of minutes then update this issue.

The workaround:

```
replace gopkg.in/ahmetb/go-linq.v3 => github.com/ahmetb/go-linq/v3 v3.1.0
```

**Comment by mholt** [comment]
@diamondburned Ah, that works.

That's fine since that replace goes in the circuitbreaker module, not in this core caddy repo. It can be temporary anyway. Pushing...

**Comment by mholt** [comment]
Okay, great! I just pushed a507a5bbc72b70cba4e252b8ec7cbffdc09b4a86 which removes the module from this repo, and that code now lives at https://github.com/caddyserver/circuitbreaker using your fork.

Thanks for the help!

**Comment by diamondburned** [comment]
Something worth mentioning: I forgot to tidy up `go.mod`, so I did that just now. It would be great if you could update them on the new repo as well.

**Comment by mholt** [comment]
Done, thanks!
