### ISSUE TITLE
caddy reload does not return to the command line when finished

### ISSUE THREAD

**Issue by tobyliu415** [caddyserver/caddy#3341]
Steps:
1. caddy start
2. Modify Caddyfile
3. caddy reload
Expected: reload the configure file and return to the command line.

**Comment by mholt** [comment]
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by tobyliu415** [comment]
## 1. Environment
### 1a. Operating system and version
CentOS Linux release 7.8.2003 (Core)

### 1b. Caddy version (run `caddy version` or paste commit SHA)
[root@course etc]# sha1sum /usr/local/bin/caddy
436fde49dd9b9785e7469e7efeb08b3196472308  /usr/local/bin/caddy
[root@course etc]# caddy version
v2.0.0-rc.3 h1:z2H/QnaRscip6aZJxwTbghu3zhC88Vo8l/K57WUce4Q=

### 1c. Go version (if building Caddy from source; run `go version`)
Not building from source

## 2. Description

### 2a. What happens (briefly explain what is wrong)
I've tried to reload the configure file, but it never return to the command unless I pressed Ctrl-C.

### 2b. Why it's a bug (if it's not obvious)


### 2c. Log output
[root@course etc]# vim Caddyfile
[root@course etc]# caddy reload
2020/05/04 15:24:49.381 INFO    using adjacent Caddyfile
^C2020/05/04 15:24:54.407       INFO    shutting down   {"signal": "SIGINT"}
2020/05/04 15:24:54.408 INFO    shutdown done   {"signal": "SIGINT"}

### 2d. Workaround(s)
Using Ctrl-C to Break it

### 2e. Relevant links


## 3. Tutorial (minimal steps to reproduce the bug)
*** always reproduce on my system ***
Content of Caddyfile:
------------Cut Here---------------
http://www.educg.net.cn {
        file_server {
                root /home/zch/educg.net.cn
                index index.html
        }
}

http://educg.net.cn {
        redir http://www.educg.net.cn
}

http://course.educg.net {
        reverse_proxy http://127.0.0.1:8080
}

http://compiler.educg.net {
        redir http://course.educg.net/acm
}
------------Cut Here---------------
** Another bug? It does not redirect http://compiler.educg.net/help to http://course.educg.net/acm
[root@hpsrv1 toby]# curl -I http://compiler.educg.net/help
HTTP/1.1 200 OK
Server: Caddy
Date: Mon, 04 May 2020 15:27:31 GMT

[root@hpsrv1 toby]#

**Comment by Xembie** [comment]
Does this still occur on the latest v2.0.0 release?

**Comment by tobyliu415** [comment]
No. It does not occur on v2.0.0 release. Thanks

**Comment by ale-rinaldi** [comment]
Hello, I'm experiencing this same behaviour on latest v2.1.1 release (didn't happen on 2.0.0).
```
caddy@myserver:~$ caddy version
v2.1.1 h1:X9k1+ehZPYYrSqBvf/ocUgdLSRIuiNiMo7CvyGUQKeA=
```

This is what happens:

```
caddy@myserver:~$ caddy reload --config /etc/caddy/Caddyfile
2020/07/01 10:55:14.457	INFO	using provided configuration	{"config_file": "/etc/caddy/Caddyfile", "config_adapter": ""}

```

and stays like this until I hit CTRL-C.
As a consequence, even `sudo systemctl reload caddy` is failing for timeout.

My Caddyfile is quite simple (I just replaced the domain since it's a customer's one):

```
monitor.mydomain.com {
    route /netdata/* {
        uri strip_prefix /netdata
        reverse_proxy 127.0.0.1:19999
    }
    redir /netdata /netdata/

    basicauth /netdata/* {
        bob JDJhJDEwJEVCNmdaNEg2Ti5iejRMYkF3MFZhZ3VtV3E1SzBWZEZ5Q3VWc0tzOEJwZE9TaFlZdEVkZDhX
    }
}

http://sub1.mydomain.com,
https://sub1.mydomain.com {
    reverse_proxy 127.0.0.1:8000
}

http://sub2.mydomain.com,
https://sub2.mydomain.com {
    reverse_proxy 127.0.0.1:8001
}

http://sub3.mydomain.com,
https://sub3.mydomain.com {
    reverse_proxy 127.0.0.1:8002
}

http://sub4.mydomain.com,
https://sub4.mydomain.com {
    reverse_proxy 127.0.0.1:8003
}
```
