### ISSUE TITLE
How to create a TLS tunnel by Caddy?

### ISSUE THREAD

**Issue by okudayukiko** [caddyserver/caddy#3406]
Create a TLS tunnel that encrypt raw TCP data. Raw TCP host:port is localhost:50, TLS tunnel host:port is 0.0.0.0:51 and [::0]:51.

**Comment by mholt** [comment]
Thanks for your question, and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Are you looking for [forwardproxy](https://github.com/caddyserver/forwardproxy)?

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

**Comment by mholt** [comment]
@okudayukiko Actually on second read-through, you might be looking for a new layer4 app that I'm about to publish, which handles raw TCP connections and TLS and stuff.

**Comment by stemcc** [comment]
@mholt I'm interested in similar behavior using Caddy, could you point to this new layer4 app you published which could do this?

**Comment by francislavoie** [comment]
https://github.com/mholt/conncept
