### ISSUE TITLE
Allow setting On-demand TLS ask URL inside site block

### ISSUE THREAD

**Issue by theel0ja** [caddyserver/caddy#3413]
When having multiple IP addresses on a single machine, allowing setting On-demand-TLS's `ask` URL inside site block would be great to have so the user doesn't have to run multiple instances of Caddy.

## Proposed example configuration

```
:443 {
   bind 192.0.2.10

   tls {
       on_demand {
           ask https://example.com/ask-10
       }
   }

   response "Hello 10"
}

:443 {
   bind 192.0.2.20

   tls {
       on_demand {
           ask https://example.com/ask-20
       }
   }

   response "Hello 20"
}
```

Also, having multiple `:443` ("wildcard") instances with separate bind addresses doesn't seem to work on Caddy:

```
run: adapting config using caddyfile: duplicate site address not allowed: ':443' in [:443] (site block 2, key 0)
```

Currently it looks like it is possible to only use [Global options](https://caddyserver.com/docs/caddyfile/options) for this.

**Comment by mholt** [comment]
This came up in v1, but the problem with this is that there's no way for Caddy+CertMagic to know which 'ask' endpoint to use -- especially since certificates may be managed without any HTTP servers at all! So, the 'ask' endpoint is in fact a global config setting: https://caddyserver.com/docs/json/apps/tls/automation/on_demand/

You can't have duplicate site addresses, since you can only bind one listener to a given port.

Thanks for the suggestion! (Closing, but feel free to continue discussion if necessary.)

**Comment by francislavoie** [comment]
@mholt is there room for reconsidering this now that acmez is a thing, or do you think it's still not viable? (No specific usecase in mind, just came across this and I'm wondering if the assumptions have changed)

**Comment by mholt** [comment]
@francislavoie I'm afraid not. It really has nothing to do with ACME or the ACME library, it's more about design abstractions.

In Caddy 2, certificate management happens in the background, and does not correspond to any one TLS listener. When a certificate needs to be renewed, there is usual

On-Demand TLS is handy in that it defers the loading of certificates until they are "in demand" but this is actually a bad abstraction, unfortunately. We load the cert during a TLS handshake which _happens to be_ within the context of a TLS listener, but only right then: because management (normally) happens in the background, we can't assume there's always a TLS listener available to choose this or that config.
