### ISSUE TITLE
Transport received Server's graceful shutdown GOAWAY

### ISSUE THREAD

**Issue by otbutz** [caddyserver/caddy#3428]
The following error log shows up sometimes while using caddy2 as a reverse proxy with a http2 backend:

```
May 19 01:22:33 proxy caddy[4945]: {"level":"error","ts":1589851353.4765556,"logger":"http.log.error","msg":"http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY] after Request.Body was written; define Request.GetBody to avoid this error","request":{"method":"POST","uri":"/api/v4/users/ids?since=1589207602627","proto":"HTTP/2.0", ... }, "tls":{"resumed":true,"version":771,"ciphersuite":49196,"proto":"h2","proto_mutual":true,"server_name":"chat.optitool.de"}},"duration":0.004429116,"status":502,"err_id":"c6gsnirvw","err_trace":"reverseproxy.(*Handler).ServeHTTP (reverseproxy.go:380)"}
```

**Comment by mholt** [comment]
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by otbutz** [comment]
## 1. Environment

### 1a. Operating system and version

```
Ubuntu 18.04.4
```

### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.0.0 h1:pQSaIJGFluFvu8KDGDODV8u4/QRED/OPyIR+MWYYse8=
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)

The aforementioned error is getting logged while the backend server is working properly.


### 2b. Why it's a bug (if it's not obvious)

The backend transport should handle a GOAWAY frame without logging an error.


### 2c. Log output

see above


## 3. Tutorial (minimal steps to reproduce the bug)
I have caddy configured to work as a reverse proxy for our internal Mattermost server which is using nginx 1.14.0. Nginx uses a certificate from our internal CA and therefore provides access via HTTP2. 

Relevant snippet of my Caddyfile:
```
chat.optitool.de {
        reverse_proxy https://chat.corp.optitool.de
}
```
I already checked the error and access logs of nginx but couldn't find anything suspicious.

**Comment by otbutz** [comment]
@mholt you should add this as an [issue template](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)

**Comment by mholt** [comment]
@otbutz 

> you should add this as an issue template

We did, but then everyone got upset about it because it requires effort, so now I use it only if needed.

Unfortunately, I don't know what to do with the provided information. I can't use that Caddyfile because I don't own the domain `chat.optitool.de` - and even if I change it to something I own, I get:

```
2020/05/20 16:14:30.768 ERROR http.log.error  dial tcp: lookup chat.corp.optitool.de: no such host      {"request": {"method": "GET", "uri": "/", "proto": "HTTP/2.0", "remote_addr": "127.0.0.1:61464", "host": "issue3428.https.dev:2443", "headers": {"Accept": ["*/*"], "User-Agent": ["curl/7.64.1"]}, "tls": {"resumed": false, "version": 771, "ciphersuite": 49196, "proto": "h2", "proto_mutual": true, "server_name": "issue3428.https.dev"}}, "duration": 0.566416881, "status": 502, "err_id": "gbv81pdxr", "err_trace": "reverseproxy.(*Handler).ServeHTTP (reverseproxy.go:380)"}
```

which is not the same error you're seeing.

We'll be spending our time to help troubleshoot this, but if you could spend a few minutes to make sure we can reproduce the problem, that would be helpful and necessary.

Thank you! We'll reopen this once it is actionable.

**Comment by otbutz** [comment]
> We did, but then everyone got upset about it because it requires effort, so now I use it only if needed.

You could provide multiple templates. I think that it's fair to request more details when filling a bug report.

> Unfortunately, I don't know what to do with the provided information.

It's kinda hard to come up with a reproducible test case for this as i'm not sure how to trigger the issue. I only see the error showing up in the log from time to time. If i had to guess i'd say that reverseproxy.go isn't properly handling GOAWAY frames or at least shouldn't log them as an error.

I'll try to find a way to properly reproduce the issue.

**Comment by asalatkamal** [comment]
This issue is closed but any insight on it @otbutz ?

**Comment by francislavoie** [comment]
@asalatkamal please open a topic on the forums, and fill out the help topic template. https://caddy.community

It's not productive to ask questions on long-since-closed issues, because you may not even have the same problem, even if you think you do.

**Comment by Gunni** [comment]
I had this issue myself today, trying to use OpenTelemetry via betterstack.com, get this when having sentry send those in, maybe a chance to test it?

[Potential solution blogpost](https://ragoragino.dev/tech/2022-02-05-goaway-test/)?

**Comment by pendolf** [comment]
> I had this issue myself today, trying to use OpenTelemetry via betterstack.com, get this when having sentry send those in, maybe a chance to test it?
> 
> [Potential solution blogpost](https://ragoragino.dev/tech/2022-02-05-goaway-test/)?

Hi, I'm facing same problem. Did you find the solution?

**Comment by Gunni** [comment]
> > I had this issue myself today, trying to use OpenTelemetry via betterstack.com, get this when having sentry send those in, maybe a chance to test it?
> > 
> > [Potential solution blogpost](https://ragoragino.dev/tech/2022-02-05-goaway-test/)?
> 
> Hi, I'm facing same problem. Did you find the solution?

I did not but I did ask betterstack to take a look at this issue but I don't know if they have done so.
