### ISSUE TITLE
Running in Docker: “cannot assign requested address”

### ISSUE THREAD

**Issue by elmehalawi** [caddyserver/caddy#3440]
I'm trying to run the official Caddy 2 docker image. According to that page, to do that you should run:

```
docker run -p 80:80 \ 
    -v $PWD/index.html:/usr/share/caddy/index.html \
    -v caddy_data:/data \
    caddy
```

When I run this, I get the following error:

> {"level":"info","ts":1590185286.853735,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"} run: loading initial config: loading new config: starting caddy administration endpoint: listen tcp 45.90.28.0:2019: bind: cannot assign requested address

Why is it trying to bind to that address? How can I get this to work? Should I prefer Caddy 1 at this point?

**Comment by francislavoie** [comment]
Caddy tries to bind to `localhost:2019` for the admin API, which is used for changing and reloading Caddy's configuration while running.

I think something on your machine is making `localhost` resolve to `45.90.28.0`, which is very strange. This is an issue with your environment.

Please open a thread on the [Caddy community forums](https://caddy.community) for further help. We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so that we can help you!

**Comment by elmehalawi** [comment]
Huh very strange indeed. I have no idea why it would be doing that. Thanks for the help @francislavoie!

**Comment by slide64** [comment]
Hello

recreate container

into Advanced container -> Network -> **Primary DNS Server**
write **localthost**

deploy container

if you use portainer you must modified the port 9000 because portainer use it.

**Comment by francislavoie** [comment]
@slide64 I'm not sure what you're trying to say. 

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by slide64** [comment]
Bonjour,

C'était juste une réponse au problème de elmehalawi.
Car j'ai eu le même problème avec la distribution Mealie (receipes cookbook).
Le container renvoyé une mauvaise ip pour caddy.
Toutes mes excuses,
Cordialement
