### ISSUE TITLE
Request for CGI plugin

### ISSUE THREAD

**Issue by wbudic** [caddyserver/caddy#3449]
I tried to build lates caddy v2.0.0 with the caddy_cgi module. From Kurt.
And run into problems. Love caddy server concept and easy systemctl service control, https, etc.

However, it is disappointing, that old package dependencies need to be local, to "possibly" build it from the source, and finally eventually make to work with older plugins or those that keep up with the latest in caddy.

CGI, is very important, how come not part of internal modules>

Cheers.

**Comment by francislavoie** [comment]
> I tried to build lates caddy v2.0.0 with the caddy_cgi module

Caddy v1 modules aren't compatible with Caddy v2. Caddy v2 is a complete rewrite from Caddy v1, and was necessary in order to solve a huge amount of design problems that made Caddy v1 inflexible.

You'll notice that https://github.com/jung-kurt/caddy-cgi was archived, it's no longer maintained because it was a Caddy v1 plugin.

> CGI, is very important, how come not part of internal modules

You're the first person I've seen since Caddy v2 released to ask about CGI support. We tend to only support things that almost everyone will need in Caddy's core. We try to keep it slim.

All it takes is for someone to port the v1 plugin to v2, which shouldn't be that large of an undertaking; it's not that complex of a plugin, and the core handling is almost the same as in Caddy v1. Some work would need to be done to hook into v2's module system and to implement the Caddyfile directives.

**Comment by wbudic** [comment]
Oh, thanks, for the quick response. 
Yes, I am a Perl currently programer. Need a good web server, with CGI support. To run it. 
Don't want to use older releases.
:)

**Comment by francislavoie** [comment]
For the time being, you can use any other server that supports CGI, then use Caddy in front of it as a reverse proxy which terminates TLS, etc.

**Comment by mholt** [comment]
There is this plugin, it might do roughly what you want: https://github.com/abiosoft/caddy-exec

**Comment by wbudic** [comment]
I will check it out. With caddy, I wanted to upgrade what I am already
using. I'll keep an eye on caddy.
Thank you,
Will

**Comment by mholt** [comment]
See also #29 -- which was updated 20 days ago. :)

**Comment by wbudic** [comment]
Had a look into Perl's CGI::Fast and FastCGI specification. It allows for
in-process server communication,all the way up to TCP.

So theoretically, caddy could spawn a thread in parallel for serving to
FastCGI, simple either for only plain dynamic execution of scripts,
have Perl preprocessed scripts cached, database pools and DB adapters
providing it to fetch initiated scripts. The FastCGI would be responsible
for security, and the webserver would provide for configuration, transport,
and file access and permissions checks.

Logging also should be passed back to the webservers origin. Keeping all
together in one place.

Very interesting.
Regards,
Will
