### ISSUE TITLE
TLS Off

### ISSUE THREAD

**Issue by sharego** [caddyserver/caddy#3457]
# version
v2.0.0 h1:pQSaIJGFluFvu8KDGDODV8u4/QRED/OPyIR+MWYYse8=

# Config
```
0.0.0.0:8090
tls off
 file_server {
 root /var/www/html
}
encode gzip
```

# Result

`run: adapting config using caddyfile: parsing caddyfile tokens for 'tls': /etc/caddy/Caddyfile:3 - Error during parsing: single argument must either be 'internal' or an email address`

# Expect

TLS off

# Question

Is real need force enable tls?

**Comment by mholt** [comment]
Thanks for your question, and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. You can find the docs for the tls directive here: https://caddyserver.com/docs/caddyfile/directives/tls

To disable HTTPS in the Caddyfile, specify `http://` in your site address directly.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
