### ISSUE TITLE
Can't configure caddyserver v2 for dokuwiki with example provided

### ISSUE THREAD

**Issue by guizmoau** [caddyserver/caddy#3477]
I am trying to configure dokuwiki with caddyserver.

I found this example :
https://github.com/caddyserver/examples/blob/master/dokuwiki/Caddyfile_root

I managed to adapt it to v2 a bit but I am stuck with the last one :
#rewrite {
        #       if {path} not_match /lib/.*
        #       if {path} not_match /forbidden
        #       r /(.*)
        #       to {uri} /doku.php?id={1}&{query}
        #}

Those ones I transforms without error when lauching the service but still hasn't got any wiki running :(

php_fastcgi / unix//var/run/php-fpm/php-fpm.sock
rewrite /(data/|conf/|bin/|inc/|install.php) /forbidden
        rewrite /_media(.*) /lib/exe/fetch.php?media={1}
        rewrite /_detail(.*) /lib/exe/detail.php?media={1}
        rewrite /_export/([^/]+)/(.*) /doku.php?do=export_{1}&id={2}

If anyone can advise 

Thanks !

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
