### ISSUE TITLE
How to proxy upstream http2

### ISSUE THREAD

**Issue by littlesum** [caddyserver/caddy#3485]
```
http://zod.wiki {                                                      
   redir https://zod.wiki{url}                                         
}                                                                            
https://zod.wiki {                                                     
#     tls /etc/xxx/fullchain.cer /etc/xxx/zod.wiki.key           
        reverse_proxy  https://home.xxx:4443 {                         
        header_up X-Forwarded-Proto "https"                                  
        insecure_skip_verify                                                 
        header_up Host "                                
    }                                                                        
}                  
```                                                          

          Ps: how to set log file in caddy2      

I can’t proxy upstream http2 ,plz help me

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
