### ISSUE TITLE
how to add middleware before request and reponse

### ISSUE THREAD

**Issue by yangyunjie999** [caddyserver/caddy#3532]
how to add middleware before request and reponse in V2，doc example is not work

**Comment by yangyunjie999** [comment]
i want to edit request body and reponse body by reverse_proxy

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there -- with more information than one sentence -- and thanks for understanding!
