### ISSUE TITLE
Document deployment for services using the reverse_proxy

### ISSUE THREAD

**Issue by bojanz** [caddyserver/caddy#3541]
Thank you for Caddy! It is an incredibly impressive piece of software in a surprisingly small amount of code. My plan is to deploy and test v2 for a variety of use cases. One of them is reverse_proxy.

What I'm missing is documentation for best practices around (blue/green) deployment, and the current tradeoffs.  I have tried searching both GitHub issues and the support forums but found only fragments of v1 conversations, mostly indicating that health checks are the way to achieve fallover.

So, let's assume I am using Caddy to reverse proxy to a Go app running on port 2490. I want to start a new version of the application, make it serve new requests, then when the old version drains (no requests served), shut it down.
I am assuming the following steps:
- Start new version of the application on a new port.
- Add a new upstream to the config file, and tell Caddy to reload it.
- Send a shutdown signal to the old version of the application. Once the current requests are done, it will shut down and make the health check fail.
- Remove the old version from the config file.

Is this the optimal way to do this? If yes, how do I tell Caddy to stop sending new requests to the old application, once the new one is up? Is there a lb_policy that can help me here? Would it make sense to first drain the old app, and then start sending traffic to the new one, risking small downtime but gaining easier db handling (== safe to run migrations)? If so, is there a way to do that? Maybe by always using a single upstream and a single config refresh (new app starts => Caddy config is updated to point to it. Old app is done once it's done)?

Naturally, I would be happy to send a PR with suggested documentation once the recommended process is explained in this issue.

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

To avoid config reloads, I'd recommend looking into using SRV DNS for getting your list of upstreams. You can combine this with active health checks so that when you mark one of your upstreams to shut down, they can start returning unhealthy responses while still responding to the remaining requests, then you can turn off your backend when it's done. It probably won't matter which lb policy you pick for this, because Caddy will only pick from the healthy backends.

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by bojanz** [comment]
Apologies, I assumed this would be the place to discuss improvements to the documentation, since I saw a "documentation" tag.

**Comment by francislavoie** [comment]
Our docs are on https://github.com/caddyserver/website, the docs label is typically used for comments in code or when there's obviously actionable changes to be made that come from other discussions that happen here.

**Comment by bojanz** [comment]
Thanks, opened https://github.com/caddyserver/website/issues/60
