### ISSUE TITLE
Why validate scheme and port?

### ISSUE THREAD

**Issue by ackerleytng** [caddyserver/caddy#3544]
caddy validates scheme (https/http) against the configured port (80/443) here https://github.com/caddyserver/caddy/blob/4b10ae5ce6c930b5acd46cb5c569481f349e336c/modules/caddyhttp/reverseproxy/caddyfile.go#L127

I was wondering if you'd consider relaxing this validation? I love caddy's simplified syntax for reverse proxying (compared to nginx's), but due to some constraints, I happen to need to proxy to an upstream listening on port 443 without https.

**Comment by francislavoie** [comment]
If you really must, you can adapt your Caddyfile config to JSON and change the port there, then run using JSON instead, since this validation check only happens in the Caddyfile adapter (haven't double-checked the code but I think that's true).

I don't think it really makes sense to allow absurd scheme/port combinations, all this check does it prevent people from shooting themselves in the foot for the 99% case. I really can't think of a single good reason for running http on port 443.

**Comment by ackerleytng** [comment]
Thanks @francislavoie!

We plan to use another port soon. If anyone else is here looking for a hotfix, here's what I have

```
FROM golang:1.14.4-buster

# Patch out the part that checks for conflicting scheme
RUN git clone https://github.com/caddyserver/caddy.git && \
    sed -i '/return "", d.Err("upstream address has conflicting scheme/d' caddy/modules/caddyhttp/reverseproxy/caddyfile.go && \
    cd caddy/cmd/caddy/ && \
    go build && \
    mv caddy /tmp/caddy
```

**Comment by mholt** [comment]
Yeah, I think it is mostly so that you don't shoot yourself in the foot so easily with the Caddyfile. Serving HTTPS over port 80 and HTTP over port 443 are both bad practices and will break most clients, so... don't do that.

![rob pike don't do that](https://user-images.githubusercontent.com/1128849/86486676-28872900-bd19-11ea-8de5-0034ebdb8bb7.gif)

You have near-complete control with the raw JSON config though.
