### ISSUE TITLE
Difficult error message to debug with DNS Provider

### ISSUE THREAD

**Issue by jalevin** [caddyserver/caddy#3565]
When using https://github.com/caddy-dns/route53 plugin and the DNS resolver we started running into the error message:

`acme: cleaning up failed: no memory of presenting a DNS record for`

While searching for this we came across #3474 and started diving into the code on Lego to see if we might be able to fix the upstream dependency.

After much struggle we realized we had improperly configured our iAM roles for Route53- clearly not a Caddy problem. 

I'd love to save developers some future time if possible by filing this issue and also seeing if there is a place we might be able to hook into that allows us to provide a better error message.

**Comment by mholt** [comment]
Ah yes, error handling right now needs some improvements, and that's the goal of https://github.com/mholt/acme which, as soon as I get the chance, will essentially be a rewrite of lego, our current ACME client. I don't know if that's the permanent place for the repo but it's where my WIP will go, anyway.

Even though that (portion of -- did you know you only pasted some of the error message? in the future please post the whole log output) error message originates in caddy, it is caused because of problems underlying Caddy. So, I'm going to close this since it's not something that can be fixed in Caddy, but it is on my list and will be resolved in the future through other work which is much greater scope than a single issue can cover.

Thanks for explaining what you found the problem to be, btw! Hopefully it will help future searchers because, yeah, that error message is awful.
