### ISSUE TITLE
v2: caddy-realip equivalent

### ISSUE THREAD

**Issue by delthas** [caddyserver/caddy#3597]
If Caddy is run behind a reverse proxy, it may receive requests forwarded by that proxy from several clients. It would be useful to have a way to tell Caddy that for a list of whitelisted IPs, requests from that whitelist that have the `X-Forwarded-For` header set should trust that header, and treat the request as if sent from that IP, for logging and request handling and matching purposes.

In v1, this was done with the [realip](https://github.com/captncraig/caddy-realip) module.

In v2, there is no such module and no built-in way to support this important feature.

See: https://caddy.community/t/v2-equivalent-of-v1-realip-plugin

**Comment by angristan** [comment]
I'm also interested in this, and I couldn't understand from the forum topic if this was achievable in Caddy v2 or not.

**Comment by mholt** [comment]
You can filter/match requests based on IP address natively in Caddy 2: https://caddyserver.com/docs/modules/http.matchers.remote_ip

What isn't native is the databases mapping IP ranges to various regions or providers. That'd have to be layered on top, either by your own pre-processing of the config or by a plugin.

In any case, I don't think we'll integrate those databases into Caddy core, since that's not really in the scope of Caddy's core function -- and it takes a lot of maintenance and can add a lot of bloat, and the needs vary widely for each user. So I'll close this, but feel free to continue discussion if you're going to write a new plugin for v2.

**Comment by angristan** [comment]
Thanks for the hints.

For a realip equivalent we would need to:

- match queries based on their remote address with `http.matchers.remote_ip`
- extract the IP from the `X-Forwarded-For` header with `http.matchers.header `
- set the remote address as the value extracted above

I'm missing the last step, is there a a way to change the remote address of a request from a Caddyfile?

**Comment by mholt** [comment]
What do you mean by "set/change the remote address"? The remote address is the IP the client is connecting from, how can that be changed after the connection is made?

**Comment by delthas** [comment]
That's what caddy-realip did in V1. Replace the remote address so that
anything that uses that (logs, matchers, etc) transparently use that
address rather than the real one.

**Comment by mholt** [comment]
Oh, I see... I am not sure that is a good idea since you'll lose the _real_ remote address (ironically), but since these are third party plugins you can do what you want, I guess. 🤷‍♂️

**Comment by francislavoie** [comment]
For reference, the code for the v1 plugin is here:

https://github.com/captncraig/caddy-realip/blob/master/module.go#L69

**Comment by delthas** [comment]
Yeah that's the whole point. Replace the proxy IP which I don't care
about with the client IP that the proxy is forwarding.

**Comment by mholt** [comment]
But isn't that literally what X-Forwarded-For is for?

**Comment by delthas** [comment]
X-Forwarded-For is used to transmit that info to Caddy, but I'd like to use the normal IP matchers and normal log functions and see the clients IP, not `127.0.0.1` in my logs. I could spend some time setting my own log format, using matchers that read the X-Forwarded-For header, but I'd rather have this all handled transprently for me with a plugin.

**Comment by angristan** [comment]
> Oh, I see... I am not sure that is a good idea since you'll lose the real remote address (ironically)

Unless the remote address is know and always the same like a reverse proxy or a CDN in front of Caddy. Which is why the `X-Forwarded-For` header exists.

This is not an exotic request btw, for example it's available on [nginx](http://nginx.org/en/docs/http/ngx_http_realip_module.html): 

> The `ngx_http_realip_module` module is used to change the client address and optional port to those sent in the specified header field.

Or [Apache's `mod_remoteip`](https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html):

> Replaces the original client IP address for the connection with the useragent IP address list presented by a proxies or a load balancer via the request headers.

The point is either logging (but JSON logging with Caddy logs headers so it's fine), or sending the real client IPs to the backend app, which a hard requirements in a lot of cases. (IP<>User association for logging, security, rate-limiting (let's say, WordPress) moderation (Mastodon), or tracking (Matomo)).

Caddy will indeed rarely be used behind reverse proxies or load balancers compared to Nginx or Apache because it will most likely handle TLS termination, but on the other hand CDNs are prevalent these days, especially Cloudflare.

In my case, I had to disable Cloudflare on my Mastodon instances after upgrading to v2, because users are being associated with Cloudflare IPs so it totally messes up rate limiting and moderation. It's my fault for not having checked beforehand, but I assumed the realip thing would be native by now, considering how widespread it is in CDN/load-balanced environments. 

I hope this clearer things up!

**Comment by angristan** [comment]
Of course you could argue that it is backend apps that should implement `X-Forwarded-For` support, but it's rarely the case and the task is usually left to the reverse proxy 🙂

**Comment by francislavoie** [comment]
> rate-limiting (let's say, WordPress)

I'm certain WordPress can do this without `realip`, using the X-Forwarded-For header (aka `$_SERVER["HTTP_X_FORWARDED_FOR"]` in PHP)

**Comment by emersion** [comment]
Note: this module can be used to add PROXY protocol support to Caddy: https://github.com/mastercactapus/caddy2-proxyprotocol

As of writing, it can only be used with pass-through proxies. TLS termination proxies won't work because the module doesn't forward the ALPN protocol.

**Comment by francislavoie** [comment]
Just to properly close off this thread, there's a Caddy v2 module for this now: https://github.com/kirsch33/realip
