### ISSUE TITLE
Inconsistent log format (structured json/text with timestamp)

### ISSUE THREAD

**Issue by rumpelsepp** [caddyserver/caddy#3610]
Hi; I love caddy2, but I am a bit unhappy with the log format in the systemd journal. It looks like this:

```
Jul 27 12:24:54 batuu caddy[388696]: {"level":"error","ts":1595845494.4680724,"logger":"http.log.error","msg":"unexpected EOF","request":{"method":"POST","uri":"/XXX>
Jul 27 12:24:56 batuu caddy[388696]: 2020/07/27 12:24:56 http: TLS handshake error from XXX:56868: EOF
Jul 27 12:25:00 batuu caddy[388696]: 2020/07/27 12:25:00 http: TLS handshake error from XXX:40209: remote error: tls: bad certificate
Jul 27 12:25:00 batuu caddy[388696]: 2020/07/27 12:25:00 http: TLS handshake error from XXX:40210: remote error: tls: bad certificate
Jul 27 12:25:20 batuu caddy[388696]: 2020/07/27 12:25:20 http: TLS handshake error from XXX:48728: remote error: tls: bad certificate
Jul 27 12:25:20 batuu caddy[388696]: 2020/07/27 12:25:20 http: TLS handshake error from XXX:48729: remote error: tls: bad certificate
Jul 27 12:25:22 batuu caddy[388696]: 2020/07/27 12:25:22 http: TLS handshake error from XXX:34030: remote error: tls: bad certificate
Jul 27 12:25:22 batuu caddy[388696]: 2020/07/27 12:25:22 http: TLS handshake error from XXX:34032: remote error: tls: bad certificate
Jul 27 12:25:27 batuu caddy[388696]: {"level":"error","ts":1595845527.0831642,"logger":"http.log.error","msg":"unexpected EOF","request":{"method":"POST","uri":"/XXX>
Jul 27 12:25:27 batuu caddy[388696]: 2020/07/27 12:25:27 http: TLS handshake error from XXX:64632: tls: no cipher suite supported by both client and server
Jul 27 12:25:28 batuu caddy[388696]: 2020/07/27 12:25:28 http: TLS handshake error from XXX:64633: tls: no cipher suite supported by both client and server
Jul 27 12:25:42 batuu caddy[388696]: 2020/07/27 12:25:42 http: TLS handshake error from XXX:40281: remote error: tls: bad certificate
Jul 27 12:25:42 batuu caddy[388696]: 2020/07/27 12:25:42 http: TLS handshake error from XXX:40282: remote error: tls: bad certificate
Jul 27 12:25:49 batuu caddy[388696]: {"level":"error","ts":1595845549.624513,"logger":"http.log.error","msg":"unexpected EOF","request":{"method":"POST","uri":"/XXX>
Jul 27 12:25:49 batuu caddy[388696]: {"level":"error","ts":1595845549.627202,"logger":"http.log.error","msg":"unexpected EOF","request":{"method":"POST","uri":"/XXX>
Jul 27 12:25:54 batuu caddy[388696]: 2020/07/27 12:25:54 http: TLS handshake error from XXX:38784: EOF
Jul 27 12:25:54 batuu caddy[388696]: 2020/07/27 12:25:54 http: TLS handshake error from XXX:22144: EOF
```

It is difficult to use in the current state. Since caddy logs structured data anyway, I suggest using the journal's structured logging functionality with e.g. [go-systemd](https://github.com/coreos/go-systemd/blob/master/journal/journal.go). The available fields are documented [here](https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#).

**Comment by francislavoie** [comment]
If you're speaking to the lines that aren't JSON, those come from either the Go stdlib or from some dependency of Caddy. My understanding is that Caddy doesn't get the opportunity to rewrite those log lines because they get spit out directly. Are you suggesting that that's a fix for that problem?

**Comment by rumpelsepp** [comment]
I suggest to fix both of them. Structured logging is nice, but it is useless in the current state when running caddy using the system provided logging facility. Also it is inconsistent when some lines are not structured and some are. Working around with jq can work, but that's not a solution, especially when the system provided logging facility is aware of structured logs.

**Comment by francislavoie** [comment]
Calling it "useless" is a bit strong. I agree it's slightly inconvenient, but it's not hard to work around.

Also, please note that whatever solution is used for handling the log sink needs to work on all platforms, not just those that use systemd.

You could write an encoder plugin that writes the logs in the format you prefer: https://caddyserver.com/docs/json/logging/, see the plugin docs here: https://caddyserver.com/docs/extending-caddy

**Comment by rumpelsepp** [comment]
> Calling it "useless" is a bit strong. I agree it's slightly inconvenient, but it's not hard to work around.

I agree. Will change this, sorry.

**Comment by rumpelsepp** [comment]
> You could write an encoder plugin that writes the logs in the format you prefer: https://caddyserver.com/docs/json/logging/, see the plugin docs here: https://caddyserver.com/docs/extending-caddy

That's a valuable approach.

> Also, please note that whatever solution is used for handling the log sink needs to work on all platforms, not just those that use systemd.

I agree with this as well, but, the logs MUST be consistent. So what's left from my concerns is that it's either all JSON or all text. The data never should be using mixed formats, since post processing tools cannot assume how the data will look like. So for systemd, a plugin is fine.

**Comment by mholt** [comment]
@rumpelsepp I get what you're saying. Unfortunately, there is no standard logging in Go programs. A library may use `log.Println()` which simply emits a literal string to stderr, or `log.Printf()` to emit a formatted string to stderr. That gives you these lines:

```
Jul 27 12:25:00 batuu caddy[388696]: 2020/07/27 12:25:00 http: TLS handshake error from XXX:40209: remote error: tls: bad certificate
```

The `Jul 27 12:25:00 batuu caddy[388696]:` prefix comes from journald, which is your log aggregator for systemd services, that is not controllable by any program running as the service (Go or not).

Caddy uses _structured logging_ by convention and by default: https://caddyserver.com/docs/logging

As the docs explain, structured logs have no encoding in and of themselves. Caddy lets you customize that: if you don't like JSON, use another encoding instead! You can even filter fields you don't want or ignore certain loggers entirely.

Caddy 2 gives you a wide degree of control over log emissions, but ultimately, a log entry originates from the part of the code that emits it. If it doesn't choose to use Caddy's logs, there's nothing we can do to stop it.

This is not really a Caddy issue though: logs from any program can be messy (especially if a program has errors or exceptions/panics), and log consumers MUST be liberal in what they accept. If they cannot parse a line, maybe warn the user and skip that line. (With JSON, this is easy: if the first character is not `{`, skip the line.)

The doc I linked to explains the Caddy logging philosophy in more detail.

FWIW, structured logs are _more consistent_ and _more useful_ and _more efficient_ and _more detailed_ than any `log.Printf()` emissions because the latter are just strings. With structured logs, you're guaranteed to get nice, structured, well-formatted information on every line.

Will close this issue since this is not really a Caddy problem. An encoder module that formats structured logs as systemd is welcome of course, but probably not in the core of the server (for now). So, you or anyone else are welcome to implement this functionality as a plugin! It can then be posted on the Caddy website to be documented and even downloaded by users.

**Comment by rumpelsepp** [comment]
Thank you for your answer! One question is still in my mind, you wrote:

> FWIW, structured logs are more consistent and more useful and more efficient and more detailed than any log.Printf() emissions because the latter are just strings. With structured logs, you're guaranteed to get nice, structured, well-formatted information on every line.

Why don't we just cleanup all calls to `log.Printf()` and replace them with the structured logger caddy uses?

```
$  rg --fixed-strings "log.Printf"
listeners.go
78:             log.Printf("[DEBUG] %s: Usage counter should not go above 2 or maybe 3, is now: %d", lnKey, atomic.LoadInt32(&lnGlobal.usage)) // TODO: remove

caddy.go
457:                    log.Printf("[ERROR] stop %s: %v", name, err)

context.go
68:                                             log.Printf("[ERROR] %s (%p): cleanup: %v", modName, inst, err)
320:            log.Printf("[WARNING] ModuleInfo.New() for module '%s' did not return a pointer,"+

logging.go
195:                    log.Printf("[ERROR] Closing log writer %v: %v", key, err)
290:                    log.Printf("[INFO] Redirecting sink to: %s", wo)
292:                    log.Printf("[INFO] Redirected sink to here (%s)", wo)

cmd/main.go
200:                    log.Printf("[PANIC] watching config file: %v\n%s", err, debug.Stack())

modules/caddytls/tls.go
390:                            log.Printf("[PANIC] storage cleaner: %v\n%s", err, debug.Stack())

modules/caddytls/standardstek/stek.go
87:                     log.Printf("[PANIC] standard STEK rotation: %v\n%s", err, debug.Stack())
103:                            log.Printf("[ERROR] Generating STEK: %v", err)

modules/caddytls/sessiontickets.go
125:                    log.Printf("[PANIC] session ticket service: %v\n%s", err, debug.Stack())

modules/caddypki/maintain.go
30:                     log.Printf("[PANIC] PKI maintenance: %v\n%s", err, debug.Stack())

caddytest/caddytest.go
90:     log.Printf("%s took %s", name, elapsed)
263:            log.Printf("caddytest: redirecting the dialer from %s to %s", addr, destAddr)

modules/caddytls/distributedstek/distributedstek.go
202:                    log.Printf("[PANIC] distributed STEK rotation: %v\n%s", err, debug.Stack())
211:                            log.Printf("[ERROR] Loading STEK: %v", err)

modules/caddyhttp/reverseproxy/healthchecks.go
131:                    log.Printf("[PANIC] active health checks: %v\n%s", err, debug.Stack())
155:                                    log.Printf("[PANIC] active health check: %v\n%s", err, debug.Stack())
352:                            log.Printf("[PANIC] health check failure forgetter: %v\n%s", err, debug.Stack())

modules/caddyhttp/caddyauth/caddyauth.go
70:                     log.Printf("[ERROR] Authenticating with %s: %v", provName, err)

modules/caddyhttp/reverseproxy/fastcgi/client_test.go
63:             log.Printf("[ERROR] failed to parse: %v", err)
203:                    log.Printf("[ERROR] failed to write buffer: %v\n", err)
206:                    log.Printf("[ERROR] failed to write buffer: %v\n", err)

caddyconfig/caddyfile/parse.go
339:                            log.Printf("[WARNING] No files matching import glob pattern: %s", importPattern)

modules/caddyhttp/fileserver/command.go
132:    log.Printf("Caddy 2 serving static files on %s", listen)
```

This should be doable, and improve the consistency of caddys logs.

**Comment by mholt** [comment]
> Why don't we just cleanup all calls to log.Printf() and replace them with the structured logger caddy uses?

Sometimes it's that easy, but it also requires some plumbing: to emit a structured log from anywhere in the code base, any given line of code needs to have access to a logger value. All Caddy modules have access pretty readily to loggers because they can call `ctx.Logger()` but there are a lot of nooks and crannies in the code base (outside of Caddy modules) that require more effort to add structured logs.

It's like adding a new sink to your house. It's easy to add a second one to a master bathroom for example because the plumbing is already there, but it's hard to add a sink to a mudroom or office: you'd have to rip up walls and flooring to extend plumbing to those areas. Or like electrical wiring: you can add more outlets and switches, but you have to run the wires first.

Just scanning those occurrences you found, we could probably replace a few of those with structured logs easily enough, but others will require some effort to get a properly-configured logger value into those parts of the code base. Not impossible, just takes some effort. Contributions would be welcomed here.

Also, most of those are (thankfully) very rare or niche code paths, which I have never seen executed, ever. So most of them you won't ever see anyway -- it's a law of diminishing returns. Sure, we could and probably should structure them, but it just hasn't been worth my time yet considering almost nobody will encounter them. If this is important to you, though, I would be happy to review a pull request!
