### ISSUE TITLE
[Feat]: `auto_https disable_redirects` should not require to be more explicit than default automatic https feature

### ISSUE THREAD

**Issue by polarathene** [caddyserver/caddy#3636]
Per experience [detailed here](https://github.com/caddyserver/caddy/issues/3635), `disable_redirects` should not require explicit handling of protocol/ports if the automatic https feature can work implicitly on a hostname. 

This feature setting should be a transparent toggle and do as it states, provide HTTPS automatically while disabling the HTTP to HTTPS redirect.

---

Additionally, docs should clarify earlier that:

> Caddy keeps all certificates renewed, and redirects HTTP (default port 80) to HTTPS (default port 443) automatically.

Is not about the HTTP default ports alone, but when ports are implicit to the address, having a configuration with explicit port that matches the HTTP port, will opt-out of automatic HTTPS regardless of `disable_redirects`.

These changes reduce friction requiring more thorough reading of docs by helping users [fall into the pit of success](https://blog.codinghorror.com/falling-into-the-pit-of-success/), while better supporting this statement:

> You won't have to know or do anything else about it. It should "just work"!

**Comment by francislavoie** [comment]
I think there's a fundamental misunderstanding here.

Caddy will not serve a site that has Automatic HTTPS activated over HTTP _unless specifically configured_. Disabling the redirect means just that. Disabling the redirect. That does not imply that Caddy will then serve over HTTP, because it doesn't to begin with. The HTTP->HTTPS redirect is effectively just Automatic HTTPS adding the below to your config:

```
http://localhost {
	redir https://localhost{uri}
}
```

Setting `disable_redirects` just means that Caddy will not add that. The redirect doesn't "hide" an HTTP server, because Caddy never even serves HTTP if Automatic HTTPS is activated.

This is working as intended.

That said, the [Automatic HTTPS documentation](https://caddyserver.com/docs/automatic-https) could be improved to clarify the effect of disabling redirects. Please open an issue on https://github.com/caddyserver/website or a PR with suggested edits to the documentation.
