### ISSUE TITLE
Feature Request: Allow entry point for post certificate provisioning hooks

### ISSUE THREAD

**Issue by hoshsadiq** [caddyserver/caddy#3643]
It would be nice to have a way to run commands after a certificate has been provisioned. This is useful when provisioning certificates for an application that needs to be reloaded or something. In my case I'd like to use Caddy to get certificates for a PostgreSQL instance, and reload PostgreSQL when a certificate is issued. I'm already using Caddy for the front-end, so I'd like to avoid using another tool just for PostgreSQL.

As mentioned in #3604, this used to be provided by the `on` plugin, which has since been removed.

Relates to https://github.com/abiosoft/caddy-exec/issues/2

**Comment by francislavoie** [comment]
Related issue for event stuff: https://github.com/caddyserver/caddy/issues/2344

**Comment by virtualdxs** [comment]
Any updates on this? I use Caddy to manage certificates for my mail server and as of right now I have to reload my mail server manually when the certs expire, which is sort of antithetical to the purpose of automatic cert management.

**Comment by mholt** [comment]
Well, hang on -- ideally, the mail server should be automatically renewing its own certificate in the first place. 😉 

I haven't really looked at this issue since it was opened in 2020 since there hasn't been any activity on it. But now I see it has 16 thumbs up, so I guess there is demand for it.

We can work this into Caddy by v2.6 I think.

**Comment by virtualdxs** [comment]
I don't necessarily disagree that the mailserver should probably do that itself, but even if it did I'm not sure I'd trust it to be as robust as Caddy's cert logic. Plus, it can't bind to 443 so it would need to do DNS-based challenges which require additional configuration.

I think ideally I'd be having Caddy front it with Conncept, but until that's stable, this seems like a good workaround :)

**Comment by mholt** [comment]
@virtualdxs Personally, I think you can use Project Conncept, it has settled down a bit and seems to work well. Won't know until more people use it. 🤷 

We'll probably be finishing Francis' work on the eventing system this year.

**Comment by virtualdxs** [comment]
Unfortunately, I just realized that won't work as it turns out. Unlike with an HTTP reverse proxy, the mail server wouldn't have a way to get the remote IP address to do things like SPF checks. So external cert management seems to be the only option. (Or some crazy idea involving tunneling SMTP in HTTP and a mailserver that understands that :smile:)

**Comment by IndeedNotJames** [comment]
@virtualdxs Just a little fyi :innocent: 
> Unlike with an HTTP reverse proxy, the mail server wouldn't have a way to get the remote IP address to do things like SPF checks.

Most mailserver setups are very much capable of running behind a load balancer/proxy.
[Project Conncept (caddy-l4)](https://github.com/mholt/caddy-l4) has native support for [HAProxy's PROXY protocol](https://www.haproxy.org/download/1.9/doc/proxy-protocol.txt) (both v1 & v2), which is basically \*the\* industry standard for arbitrary TCP proxying while also passing the clients' IP to upstream.

Unfortunately, the only encryption SMTP hosts/relays support to send mails between each other is still [STARTTLS](https://en.wikipedia.org/wiki/Opportunistic_TLS) :roll_eyes:.
Opportunistic encryption, which negotiates at the application layer.

So you could very much have [caddy-l4](https://github.com/mholt/caddy-l4) (or any other proxy like nginx, traefik, haproxy, envoy, etc.) in front of your user facing endpoints (IMAPs/POP3s/SMTPs for clients) and SMTP for mailserver to mailserver traffic, but would still have to support STARTTLS on `:25` for other mailservers.

And for your MX to support STARTTLS, you would have to pass it a certificate.
Otherwise, any other MTA would only be able to send you their mails unencrypted, which is really really bad.

---

> So external cert management seems to be the only option.

Yes, sadly :(
At least for the server to server traffic between MTAs and MX hosts in SMTP.
Just for a slightly different reason :slightly_smiling_face:

**Comment by virtualdxs** [comment]
@IndeedNotJames That's good to know, I hadn't heard of the PROXY protocol. Thanks!

**Comment by francislavoie** [comment]
For the record, my WIP work on events is here: https://github.com/caddyserver/caddy/compare/event. It's functional, it's possible to subscribe to certificate issuance events, but we don't have any event listener plugins yet, so it's not too useful on its own.

**Comment by mholt** [comment]
Implemented in https://github.com/caddyserver/caddy/pull/4984

**Comment by cyqsimon** [comment]
Hijacking this thread to offer an alternative, since this is a common landing point if you search things like "caddy renew hook":

If you are like me and prefer using the caddy binary packaged by your distribution (as opposed to using xcaddy) and therefore can't use `on cert_obtained exec`, here's how you can do the same using systemd.

Systemd offers `.path` units ([`man systemd.path`](https://manned.org/man/systemd.path)), in which you can use `PathModified=` to track the modification of arbitrary files. Caddy only writes to the certificate files during renewal, so we can take advantage and make this the trigger.

Just create the following two files in `/etc/systemd/system/`:

```ini
# caddy-cert-watch.path
[Unit]
Description=Run post-renewal actions after Caddy certificate renewal

[Path]
PathModified=/path/to/caddy/certificate.crt
PathModified=/path/to/caddy/certificate.key
Unit=caddy-post-renew.service

[Install]
WantedBy=caddy.service
```

```ini
# caddy-post-renew.service
[Unit]
Description=Run Caddy post-renewal actions
After=network.target

[Service]
Type=oneshot
ExecStart=/path/to/your/script
```

Feel free to add other hardening options as you please, but this is the basics.

Then `systemctl daemon-reload && systemctl enable --now caddy-cert-watch.path`.
