### ISSUE TITLE
Support for more variables in on_demand_tls { ask } URL

### ISSUE THREAD

**Issue by zemaj** [caddyserver/caddy#3647]
Recently switched over to using Caddy from another Let's Encrypt server. Loving how much easier Caddy is to configure. A 20 line Caddyfile accomplishes the same thing which took a several files in the other solution.

The only thing I haven't been able to replicate is passing over more information to the URL entered in the on_demand_tls { ask } field.

Specifically I'm looking for something like this;

```
{
	admin off
	email certs@domain-name.com
	on_demand_tls {
		ask https://domain-name.com/validate-domain?remote_ip={http.request.remote.host}&key=xxxxxxxxx&domain={domain}
		interval 1h
		burst 30
	}
}
```

Being able to pass over the remote host adds an additional layer of protection and would allow us to block someone from spoofing requests and trying a wide range of domain names.

In general it would be nice if all [http placeholders](https://caddyserver.com/docs/json/apps/http/) were supported here. The `{domain}` parameter could be a placeholder as well to give people more flexibility in constructing the ask request. Perhaps for backwards compatibility, if the `{domain}` placeholder isn't found in the URL, then `?domain={domain}` could be added automatically.

**Comment by mholt** [comment]
I'm afraid that the HTTP placeholders won't be available. It's impossible, since HTTP requests cannot be made until a TLS connection is established (when using TLS, but which is obviously the only scenario that applies to this feature request).

The other difficulty is that certificates may be managed in more contexts than just active TLS connections. Most certificates are managed in the background.

The kind of security you're looking for isn't really security, or is misplaced:

> Being able to pass over the remote host adds an additional layer of protection and would allow us to block someone from spoofing requests and trying a wide range of domain names.

You should be doing this independently of certificate management, for example with a firewall or a [layer 4 module](https://github.com/mholt/conncept). Ultimately, the purpose of the `ask` endpoint is to assess whether Caddy is authorized by your system to claim control over the domain name. I can't think of a good reason why that would be tied to who the client is. Either your application is the designated server for the domain name or it is not; for example, a customer signs up to use their domain name with your service, so you add it to your database, you now have a third party attesting that they will allow your service to use this domain name -- that is reason enough to allow Caddy to _try_ to get a certificate for it if it gets a TLS ClientHello for it. If it passes the ACME challenge then indeed that proves the party in control of the domain name is allowing your service to represent that domain name.

Your `ask` endpoint can do whatever it wants, but blocking clients who are hammering your servers is not its job.

Closing, but feel free to continue discussion if necessary. Thanks!
