### ISSUE TITLE
How to reverse_proxy incoming websocket request to http backend?

### ISSUE THREAD

**Issue by exzachlyvv** [caddyserver/caddy#3648]
Right now I have the following architecture:

Incoming request: Client -> websocket proxy -> HTTP backend ...
Outgoing response: ... HTTP backend -> websocket proxy -> Client

The API is entirely standard REST, while the client appears to be communicating through websockets. 

Is there a way Caddy can replicate this?

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

**Comment by jerrychong25** [comment]
> Right now I have the following architecture:
> 
> Incoming request: Client -> websocket proxy -> HTTP backend ... Outgoing response: ... HTTP backend -> websocket proxy -> Client
> 
> The API is entirely standard REST, while the client appears to be communicating through websockets.
> 
> Is there a way Caddy can replicate this?

Hi @exzachlyvv ,

Do you found a solution on how to reverse proxy client incoming websocket request to http backend and vice versa (HTTP backend websocket request to client side)?

If yes, mind to share how you achieve this?

Thanks.

**Comment by exzachlyvv** [comment]
I ended up going a different direction and didn't pursue. Good luck!

**Comment by jerrychong25** [comment]
> I ended up going a different direction and didn't pursue. Good luck!

Hi @exzachlyvv ,

Alright, thanks for letting me know =)
