### ISSUE TITLE
Improve admin endpoint bind failure error messages

### ISSUE THREAD

**Issue by 0az** [caddyserver/caddy#3651]
This usually happens when I forget I have another Caddy process running somewhere and try executing `caddy run`.

Knowing exactly which Caddy invocation, including the initial config file, would be *great*. One possible solution of many is to expose this information on the Admin API, through a hypothetical `GET /process` API that exposes a read only view of `argv[0]`, the Caddy version, and the current working directory, among others.

Instead of this:
```
$ caddy run
2020/08/12 01:43:27.969 INFO    using adjacent Caddyfile
run: loading initial config: loading new config: starting caddy administration endpoint: listen tcp 127.0.0.1:2019: bind: address already in use
```

We might see:
```
$ caddy run
2020/08/12 01:43:27.969 INFO    using adjacent Caddyfile
run: loading initial config: loading new config: starting caddy administration endpoint: listen tcp 127.0.0.1:2019: bind: address already in use
run: found running caddy server at 127.0.0.1:2019, at /usr/bin/caddy, with config from /etc/caddy/Caddyfile, started by systemctl because of /lib/systemd/system/caddy.service
```

Not sure if this should get implemented, but for future me, don't forget to use `ps aux | grep caddy` before jumping into `ss -tpl`.

**Comment by francislavoie** [comment]
Yeah that's not a bad idea, `caddy run` could try to see if port 2019 already has a Caddy instance by sending a quick API call to the endpoint if it couldn't bind. I'm not sure if it could give all that information (config filepath, or service file, but binary path should be easy enough) because that isn't information that's actually kept.

**Comment by 0az** [comment]
> Yeah that's not a bad idea, `caddy run` could try to see if port 2019 already has a Caddy instance by sending a quick API call to the endpoint if it couldn't bind. I'm not sure if it could give all that information (config filepath, or service file, but binary path should be easy enough) because that isn't information that's actually kept.

Do you think it's sensible to *keep* this information, though?

**Comment by mholt** [comment]
This is a nice idea, but there's no guarantee we'd be able to access that endpoint because we don't know what kinds of protections the operator has configured, like the Origin policy for example.

> Do you think it's sensible to keep this information, though?

Only if it doesn't break/leak any abstractions, and it doesn't reveal any information to unauthenticated requests (for example, if it fails the Origin check).

---

This feature request would require a few hoops to jump through to make it happen safely and correctly.

Is an error message like "already running" really going to save you any time or energy? You'll still need to take corrective action yourself with both the current and proposed error messages. And it only takes about 10 seconds either way.

**Comment by francislavoie** [comment]
I think the effort outweighs the benefit here, and there hasn't been any other feedback from anyone since, so I'll close this for now. We might reopen this if new ideas are presented.
