### ISSUE TITLE
"Started certificate maintenance routine" takes long

### ISSUE THREAD

**Issue by gbhrdt** [caddyserver/caddy#3656]
Hi, we have about 8.000 Certs (which have been migrated from Caddy 1). When we now startup our server (which has been normally shutdown with SIGTERM, not SIGKILL) we always experience the following logs:

```
2020/08/14 19:21:31.113	INFO	using provided configuration	{"config_file": "/etc/caddy/Caddyfile", "config_adapter": "caddyfile"}
2020/08/14 19:21:31.115	INFO	admin	admin endpoint started	{"address": "tcp/localhost:2019", "enforce_origin": false, "origins": ["localhost:2019", "[::1]:2019", "127.0.0.1:2019"]}
2020/08/14 19:21:31 [INFO][cache:0xc00003a180] Started certificate maintenance routine
2020/08/14 19:21:31.148	INFO	http	server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS	{"server_name": "srv0", "https_port": 443}
2020/08/14 19:21:31.148	INFO	http	enabling automatic HTTP->HTTPS redirects	{"server_name": "srv0"}
```

It then takes about 5-10mins until Caddy listens on port 443 and 80. We did not have this with Caddy v1.
Is there anything we can do about this?

After that we see:

```
2020/08/14 19:25:44.199	INFO	tls	cleaned up storage units
2020/08/14 19:25:44.205	INFO	autosaved config	{"file": "/config/caddy/autosave.json"}
2020/08/14 19:25:44.205	INFO	serving initial configuration
```

Caddy version: `2.1.1 (Docker caddy:2-alpine)`

Cadddyfile:

```
{
  email support@example.com
  on_demand_tls {
    ask https://api.example.com/domain-allowed
  }
}

:443 {
  tls {
    on_demand
  }
  rewrite * {path}?{query}
  reverse_proxy https://page.example.com
}
```

**Comment by francislavoie** [comment]
@mholt will be able to answer the specifics regarding the certificate maintenance routine, but I have one question. What's the purpose of this rewrite?

```
rewrite * {path}?{query}
```

I don't think that's necessary, that should be a no-op.

**Comment by mholt** [comment]
@gbhrdt How many certificates do you have under management?

Is that your full and complete Caddyfile?

Are those the full and unredacted logs?

Does this happen every time?

Does it still happen if you build Caddy from master? https://github.com/caddyserver/caddy/commit/efc0cc5e8557ebc54dd30931a27767139e808c80

Btw, this:

> Started certificate maintenance routine

Is supposed to run the entire duration of the server, you don't want it to be done quickly.

**Comment by gbhrdt** [comment]
Hi -

@francislavoie  You're totally right, I can remove this line in my Caddyfile. This was just for testing something.

@mholt 


> How many certificates do you have under management?

We manage around 8.000 certs.

> Is that your full and complete Caddyfile?

This is our full Caddyfile (we changed our real domain to example.com, do you need the real one?).

> Are those the full and unredacted logs?

No, but the logs contain customer domains, unfortunately I would have to mask all of them if I post them here. It does some certificate cleanup (like it is supposed to) like removing old certs and so on.

> Does this happen every time?

Yes, happens every time.

> Does it still happen if you build Caddy from master?

I did not try yet but the commit looks very promising! I will try that.

I've had some issues with the latest docker file so we now use `2.0.0` in production (https://github.com/caddyserver/caddy/issues/3004#issuecomment-674269026). Has this been fixed or should I open a new issue for this?

**Comment by mholt** [comment]
> We manage around 8.000 certs.

Oh right, I now see that in your original post, derp.

Anyway, yeah, I think we've fixed this problem.

@gbhrdt As for https://github.com/caddyserver/caddy/issues/3004#issuecomment-674269026, there's not enough information there to know what's going on. Caddy can't find a cert to satisfy that TLS handshake. Can you please open a new issue with this information:

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>
