### ISSUE TITLE
ACME sites not working with custom SSL certificates set

### ISSUE THREAD

**Issue by gbhrdt** [caddyserver/caddy#3670]
This might be a reintroduction of issue #3004

### 1a. Operating system and version

Linux

Dockerfile:

```
{
  email support@example.com
  on_demand_tls {
    ask https://api.example.com/domain-allowed
  }
}

https://*.example.com {
  tls /etc/caddy-ssl/tls.crt /etc/caddy-ssl/tls.key
  reverse_proxy https://page.example.com
}

https://example.com {
  tls /etc/caddy-ssl/tls.crt /etc/caddy-ssl/tls.key
  reverse_proxy https://page.example.com
}

:443 {
  tls {
    on_demand
  }
  reverse_proxy https://page.example.com
}
```

### 1b. Caddy version (run `caddy version` or paste commit SHA)

2.1.1
https://hub.docker.com/layers/caddy/library/caddy/2.1.1/images/sha256-c8dd4b191727d7eccb50cdf3f3d26fe19abbd23be153dfd53a11f01059002928?context=explore

### 1c. Go version (if building Caddy from source; run `go version`)

We tried Caddy 2.1.1 and 2.1.0 from docker hub.
Only 2.0.0 works for us.

### 2a. What happens (briefly explain what is wrong)

Caddy does not serve any certificates anymore.

### 2b. Why it's a bug (if it's not obvious)

Caddy should serve ACME certificates and custom certificates in parallel.

### 2c. Log output

```
{"level":"info","ts":1595231297.6785583,"msg":"serving initial configuration"}
2020/07/20 07:48:32 http: TLS handshake error from 49.37.128.229:56978: no server TLS configuration available for ClientHello: &{CipherSuites:[64250 4865 4866 4867 49195 49199 49196 49200 52393 52392 49171 49172 156 157 47 53] ServerName:internal-staging.test.co SupportedCurves:[14906 29 23 24] SupportedPoints:[0] SignatureSchemes:[1027 2052 1025 1283 2053 1281 2054 1537] SupportedProtos:[h2 http/1.1] SupportedVersions:[23130 772 771 770 769] Conn:0xc000188580 config:0xc000609800}
2020/07/20 07:48:32 http: TLS handshake error from 49.37.128.229:56980: no server TLS configuration available for ClientHello: &{CipherSuites:[43690 4865 4866 4867 49195 49199 49196 49200 52393 52392 49171 49172 156 157 47 53] ServerName:internal-staging.test.co SupportedCurves:[6682 29 23 24] SupportedPoints:[0] SignatureSchemes:[1027 2052 1025 1283 2053 1281 2054 1537] SupportedProtos:[h2 http/1.1] SupportedVersions:[47802 772 771 770 769] Conn:0xc0001885a8 config:0xc000609800}
2020/07/20 07:48:32 http: TLS handshake error from 49.37.128.229:56982: no server TLS configuration available for ClientHello: &{CipherSuites:[14906 4865 4866 4867 49195 49199 49196 49200 52393 52392 49171 49172 156 157 47 53] ServerName:internal-staging.test.co SupportedCurves:[47802 29 23 24] SupportedPoints:[0] SignatureSchemes:[1027 2052 1025 1283 2053 1281 2054 1537] SupportedProtos:[h2 http/1.1] SupportedVersions:[19018 772 771 770 769] Conn:0xc0001885c0 config:0xc000609800}
```

### 2d. Workaround(s)

Downgrade to caddy 2.0.0

### 2e. Relevant links

-

## 3. Tutorial (minimal steps to reproduce the bug)

Spin up caddy with 2.1.1 and my above Caddyfile.

**Comment by mholt** [comment]
Thanks for the issue. Can you please post your actual config? I can't troubleshoot this if the values aren't exactly what you are using. I need to be able to reproduce it and hiding information isn't going to get us anywhere.

Here's a template to help:

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by lobovkin** [comment]
Hello. I have the same problem with the same environment (Caddy 2.1.1 on Ubuntu Linux).
My Caddyfile (minimal configuration):

> mydomain.com {
  respond "mydomain.com"
  tls /etc/caddy/mydomain.com.pem /etc/caddy/mydomain.com.key
}
:443 {
  respond "other domain"
  tls mail@mydomain.com {
    on_demand
  }
}

>curl https://otherdomain.com

Gives the same log output: "no server TLS configuration available for ClientHello..."
So On-Demand TLS doesn't work if cert_file and key_file was specified for at least one site.
Caddy 2.0.0 hasn't this problem.

**Comment by mholt** [comment]
@lobovkin Can you please fill out the issue template I posted above? ^ Following the instructions will help ensure I get all the necessary information.

**Comment by mholt** [comment]
Is anyone willing/able to provide the requested information? I'm in the process of looking into this but can't verify that what I'm seeing is the same since I don't have enough information.

**Comment by mholt** [comment]
This appears to be the same problem as reported on the forum here: https://caddy.community/t/combining-on-demand-tls-with-custom-ssl-certs-doesnt-seem-to-work-in-2-1-1/9719?u=matt - thankfully, that config was not redacted so it did not hamper my debugging efforts/

GitHub auto-closed this and I will leave it that way unless someone confirms that the problem is still not resolved. Thanks

**Comment by lobovkin** [comment]
I built from source with https://github.com/caddyserver/caddy/commit/4217217badf220d7d2c25f43f955fdc8454f2c64, the problem was solved. Thank you.
