### ISSUE TITLE
reverse_proxy migrate from v1 to v2

### ISSUE THREAD

**Issue by baileyglen** [caddyserver/caddy#3700]
I am migrating from caddy 0.11 to 2. I am running into an issue with reverse proxy. 
previous code:
proxy /url host:port
reverse_proxy /url/* host:port

The addition of the traling slash works, but requires out users to directly put the trailing slash into the url. This was not the case for the original implementation. Is there a way around this?

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing.

However, I'll give you a quick hint -- Caddy's proxy doesn't mess with ("rewrite") the URL so you have to do that yourself if you want to manipulate trailing slashes: https://caddyserver.com/docs/caddyfile/directives/rewrite  - in fact, our docs have a whole section dedicated just to trailing slashes: https://caddyserver.com/docs/caddyfile/patterns#trailing-slashes

Anyway I hope you'll ask your question there, and thanks for understanding!

**Comment by francislavoie** [comment]
You can simply do this:

```
reverse_proxy /url* host:port
```

To have the same behaviour as before.
