### ISSUE TITLE
caddyfile: add handle_response blocks to reverse_proxy

### ISSUE THREAD

**Issue by maxatome** [caddyserver/caddy#3707]
Caddyfile support for the `handle_response` option of `reverse_proxy` would be nice.

See the JSON configuration here:

https://caddyserver.com/docs/json/apps/http/servers/errors/routes/handle/reverse_proxy/handle_response/

Maybe it could look something like this in the Caddyfile:

```
reverse_proxy ... {
	...
	handle_response header X-Accel-Redirect {
		... 
	}
	handle_response status 4xx {
		...
	}
	handle_response {
		...
	}
}
```

(Responses can be matched by headers or status code. Just showing a few examples here.)

_Originally posted by @mholt in https://github.com/caddyserver/caddy/issues/3347#issuecomment-683959748_

**Comment by maxatome** [comment]
@mholt do you have an idea of how represent "routes" list in handle_response block?

```
handle_response [header <field>|status <status>] {
    status <status>
    routes?
}
```
I didn't find an other place where it is `UnmarshalCaddyfile`d so I prefer to ask before doing it the wrong way...

**Comment by francislavoie** [comment]
I don't think you'd have `status <status>` inside of it, I think that would need to be isolated to the same-line args because it's not a real handler directive.

But for "routes", take a look at how the `handle` directive is parsed, i.e. `parseHandle` -> `ParseSegmentAsSubroute`:

https://github.com/caddyserver/caddy/blob/24f34780b61fc82df6507cf95535c3dfc9f78058/caddyconfig/httpcaddyfile/directives.go#L268-L278

**Comment by maxatome** [comment]
Thanks @francislavoie, what do you think of #3712?
I am not sure I did it the right way, so tell me...

**Comment by mholt** [comment]
Done in #4021.
