### ISSUE TITLE
hi guys, caddy looks and sounds good BUT how do we make it really dummy for everyone to have http3 + automatic letsencrypt for ALL domain names?

### ISSUE THREAD

**Issue by gitmko0** [caddyserver/caddy#3721]
Look at this code, it's fasthttp and automagically u get https 
https://play.golang.org/p/GPzMpGZIeLN

i'm not saying from a code's point of view but even the coding is easy to understand and deploy.

I've read through A LOT about Caddy's documentation and https and this and that CaddyFile setting etc... and there's no no-brainer guide on how to use Caddy with http3 and all domain names enabled with letsencrypt.

come on. seriously... if the --enable-quic is obsolete etc, can please not put in to confuse the setting up? what's the latest that is usable? coz there seems like 3 versions of how to set up caddy on 3 different versions of caddy etc.

I prefer CaddyFile please, the latest. please help coz i've never read through any documentation that is so frustrating for something that should be so simple and straight forward.

1. http3 
2. letsencrypt
3. all domain names automatic https

is that a lot to ask for? i can do the reverse proxy thereafter... hopefully.
p.s. : truly sorry coz it's first time i've tried so many styles on something like this. i think maybe u guys can consider doing some documentation of versioning. e.g. caddy 2.0 doc or something.

**Comment by Mohammed90** [comment]
Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your questions there, and thanks for understanding!

You're just looking for the global option `experimental_http3`, as [documented here](https://caddyserver.com/docs/caddyfile/options). The auto-HTTPS with Let's Encrypt is managed by default anyways. For further clarifications, let's move this to the forum.
