### ISSUE TITLE
site address problem

### ISSUE THREAD

**Issue by phrazer** [caddyserver/caddy#3731]
I found a problem with address like this:
https://*-host.domain.tld
- or this one -
https://*host.domain.tld

This would be good because it is hard/impossible to have SSL wildcard with second subhost, like dev.host.domain.tld, you have to use dev-host.domain.tld as solution. Just an idea. Since addresses you wrote in docs are quite vague, this could be great addon, and i belive not hard to implement. Thanks for great software.

This all works as in docs:
localhost
example.com
:443
http://example.com
localhost:8080
127.0.0.1
[::1]:2015
example.com/foo/*
*.example.com
http://

**Comment by mholt** [comment]
> This would be good because it is hard/impossible to have SSL wildcard with second subhost, like dev.host.domain.tld, you have to use dev-host.domain.tld as solution.

What do you mean by this, exactly? You can use `*.example.com` as a site address _and_ as a subject name in a wildcard certificate. But `*sub.example.com` cannot be used, because it is not compliant with [RFC 6125](https://tools.ietf.org/html/rfc6125#section-6.4.3).

> Since addresses you wrote in docs are quite vague,

What part of the docs?

Will close this, since if I read your question right, I believe it has been answered.
