### ISSUE TITLE
Error log in Caddyfile (Feature request)

### ISSUE THREAD

**Issue by hvisage** [caddyserver/caddy#3744]
referring to: https://caddy.community/t/where-to-put-error-log-in-caddyfile/9896/2

Currently Caddyfile configs doesn't have a error logging place/method, only access_logs. 

Problem here is that logging to files is needed and useful without resorting to JSON configs

**Comment by danlsgiga** [comment]
Same thing here... I just realized caddy is exposing a lot of sensitive information in the error log / stderr by logging the entire http call, including headers due to failing to resolve the upstream address.

**Comment by mholt** [comment]
The logging constructs are described here: https://caddyserver.com/docs/logging

Ultimately: Caddy emits high efficiency structured logs, it's up to your log processor or aggregator to consume them, and thus handle them the way you want, etc. Caddy is just an emitter (unless somebody writes a log consumer app module for Caddy).

You can prevent Caddy from logging certain fields using log filters. You can also log to files instead of stderr.

This is all configurable via: https://caddyserver.com/docs/json/logging/

**Comment by francislavoie** [comment]
@mholt I think we can provide this via global options though. I don't think it's the right time to close this, I was going to take a crack at this at some point.

**Comment by mholt** [comment]
What needs to be done? There are numerous kinds of error logs, but based on the linked forum thread it's just any logs from the logger named `http.log.error`.

**Comment by francislavoie** [comment]
The output, encoding, include/exclude should be configurable from the Caddyfile. Right now, it only ever goes to stdout, but if you want to log to file (because you're running Caddy with `caddy start` instead of `caddy run` for example), you're forced to use JSON to configure those things.

**Comment by mholt** [comment]
Ok. I think that should be more clearly described and proposed in a new issue then, or something. This issue sounds like something different.

**Comment by kujenga** [comment]
I opened a new issue here along the lines of what it sounds like was described in the discussion here post-close of this issue, for more generic support of configuration for error logs in the Caddyfile, along the lines of what is possible for access logs: https://github.com/caddyserver/caddy/issues/3958
