### ISSUE TITLE
Caddy behind Proxy server on 80 port 

### ISSUE THREAD

**Issue by danyanya** [caddyserver/caddy#3751]
It's **impossible** to put Caddy server (v1 or v2, doesn't matter) behind any other proxy servers on 80 port because of ACME challenge (HTTP-01). 
Link to doc [here](https://caddyserver.com/docs/automatic-https#http-challenge).

Main question - **why**? 
Or is it any workaround? (instead of one day in three months run Caddy on 80 port to renew cert).

**Comment by mholt** [comment]
> It's impossible to put Caddy server (v1 or v2, doesn't matter) behind any other proxy servers on 80 port because of ACME challenge (HTTP-01).

That's not true. Why do you say that?

The docs say:

> This challenge requires port 80 to be externally accessible. If Caddy cannot listen on port 80, packets from port 80 must be forwarded to Caddy's HTTP port.

It's a proxy's job to forward packets, so, what is the problem, exactly?

> Main question - why?

Why what?

**Comment by danyanya** [comment]
@mholt, sorry for disturbing) 

My installation needs Nginx to serve 80 port and Caddy for easy HTTPS cert.
So the first time when I ran only Caddy, I successfully got cert and all was fine. 

Now after 3 months it's time to renew. 
So I tried two different layouts:

- serve directory with files with challenge token (like _caddy-dir/acme/letsencrypt-dir/challenge_tokens/_)
- proxied from Nginx to caddy acme-challenge requests  

Results: 
1) on this part in Caddy logs got after   404 error `acme: Trying to solve HTTP-01`

2) tried to set up Nginx and proxied Http challenge requests with simple config:
```
location /.well-known/acme-challenge {
    proxy_pass http://caddy-server;
}
```

but in logs caddy server didn't pass step `acme: Trying to solve HTTP-01` with 502 error. That's because Caddy doesn't start a server before it gets cert.

That's my concern -- I didn't find right combination to get cert behind Nginx...

**Comment by mholt** [comment]
Ah... this looks more like a question about how to use Caddy rather than a bug report or feature request.

Forwarding HTTP requests for the ACME challenge to Caddy should work with the HTTP challenge just fine.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there with more details and full logs; and thanks for understanding!
