### ISSUE TITLE
provision http.handlers.reverse_proxy: invalid start port: strconv.ParseUint: parsing "": invalid syntax

### ISSUE THREAD

**Issue by royaltongue** [caddyserver/caddy#3761]
I've had docker running for a few months without changing anything, and today realized that I can't reach any of my services using my domain.

When looking at the caddy logs, I see this repeated over and over:

```

{"level":"info","ts":1601329684.1808348,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}


{"level":"info","ts":1601329684.1934514,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}


{"level":"info","ts":1601329684.1977303,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00035c2a0"}


{"level":"info","ts":1601329684.1986465,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}


{"level":"info","ts":1601329684.198754,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}


{"level":"info","ts":1601329684.200086,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc00035c2a0"}


run: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 6: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'reverse_proxy': provision http.handlers.reverse_proxy: invalid start port: strconv.ParseUint: parsing "": invalid syntax
```

I run caddy through Docker-Compose, so here's my portion in my YAML for caddy:

```
  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ${domain}
    volumes:
      - ${storagepath}/caddy/config/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${storagepath}/caddy/config/:/config/
      - ${storagepath}/caddy/data/:/data/
    hostname: caddy
    networks:
      - caddy_net
    restart: unless-stopped
```

And here's my Caddyfile:
```
### caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile

{
    email anemail@gmail.com
    acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
}

whoami.domain.me
    reverse_proxy whoami
}

nginx.domain.me {
    reverse_proxy nginx:80
}

port.domain.me {
    reverse_proxy portainer:9000
}

pi.domain.me {
    redir / /admin
    reverse_proxy pihole:80
}

dash.domain.me {
    redir / /login
    reverse_proxy dashmachine:5000
}

taut.domain.me {
    reverse_proxy tautulli:8181
}

plex.domain.me {
    reverse_proxy plex:32400
}

ombi.domain.me {
    reverse_proxy ombi:3579
}

sonarr.domain.me {
    reverse_proxy sonarr4K:8989
}

sonarr1080.domain.me {
    reverse_proxy sonarr1080:8989
}

radarr.domain.me {
    reverse_proxy radarr4K:7878
}

radarr1080.domain.me {
    reverse_proxy radarr1080:7878
}

jackett.domain.me {
    reverse_proxy jackett:9117
}

bazarr.domain.me {
    reverse_proxy bazarr:6767
}

qbit.domain.me {
    reverse_proxy qbittorrent4K:8090
}

qbit1080.domain.me {
    reverse_proxy qbittorrent1080:8090
}

hydra.domain.me {
    reverse_proxy nzbhydra2:5076
}

nzb.domain.me {
    reverse_proxy nzbget:6789
}

nzb1080.domain.me {
    reverse_proxy nzbget1080:6789
}

droppy.domain.me {
    reverse_proxy droppy:8989
}

hand.domain.me {
    reverse_proxy handbrake:5800
}

hass.domain.me {
    reverse_proxy hass:8123
}

firefly.domain.me {
    reverse_proxy fireflyiii:8080
}
Portainer says it's running and healthy
guiltykeyboardToday at 5:34 PM
You running a docker container?
DamagedDimensionToday at 5:35 PM
Yeah
  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ${domain}
    volumes:
      - ${storagepath}/caddy/config/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${storagepath}/caddy/config/:/config/
      - ${storagepath}/caddy/data/:/data/
    hostname: caddy
    networks:
      - caddy_net
    restart: unless-stopped
```

I've tried the following:

- Restarting the container

- Restarting the host machine

- Deleting the container and creating a new one

- Deleting the container, deleting the caddy directory and the files within it (while preserving the Caddyfile itself), and creating a new container

P.S. Sorry about the shitty title, I wasn't really sure what to call it

**Comment by francislavoie** [comment]
Thanks for opening an issue! We'll look into this.

It's not immediately clear to us what is going on, so we'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by royaltongue** [comment]
That was it, thanks!
