### ISSUE TITLE
basicauth not working: unrecognized directive

### ISSUE THREAD

**Issue by hildebro** [caddyserver/caddy#3792]
This is my Caddyfile:
```
(common) {
    log stdout
}
www.example.com {
    redir https://example.com/{uri}
}
example.com {
    respond "Under maintenance"
}
files.example.com {
    root * /www/files
    file_server browse
}
private.example.com {
    root * /www/private
    file_server browse
}
```
This configuration works as intended. I then tried to add basic auth to protect files in `/www/private` by sticking to [this example](https://caddyserver.com/docs/caddyfile/directives/basicauth#examples). I added the following block above the `private.example.com` block:
```
basicauth /www/private/* {
    foo bar
}
```
`bar` represents a password generated through `caddy hash-password`. When I reload my caddy server, I get the error `unrecognized directive: foo`. Apparently caddy treats the username in the block as a directive, which would indicate a syntax error on my part. However, I don't see a difference between my block and the example I linked above.

**Comment by francislavoie** [comment]
`basicauth` is a directive, and directives must go inside site blocks. Also, the matcher can be a URL path, not a filesystem path. So what you want is this (you don't need a matcher for `basicauth` here because it will apply to all requests to that site):

```
private.example.com {
    root * /www/private
    basicauth {
        foo bar
    }
    file_server browse
}
```

Please read through this docs page to get a better sense for how a Caddyfile is structured: https://caddyserver.com/docs/caddyfile/concepts

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
