### ISSUE TITLE
Abysmal reload and shutdown times

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [caddyserver/caddy#3818]
I'm not sure what could be causing this - but my Caddy installation on both v2.2.0 and v2.2.1 takes an abysmal time to reload (over 10 seconds) after a configuration change (`caddy reload`), and it takes a very long time to actually quit when sending any termination signal (via ctrl-c, a service manager, etc.).

There aren't any useful logs (just standard `reloading` and `got SIGTERM` log messages), as far as I can tell. I would love to provide more but there's not much I can find, I can reliably reproduce these issues however.

**Comment by mholt** [comment]
Caddy waits for connections to become idle before closing sockets -- that's how graceful reloads are performed. Otherwise clients get errors. But if a request takes a long time (for example, long file download, or a websocket connection), Caddy will eventually terminate the connection forcefully to free up resources. Does that sound like what's happening? If so, that's normal; you can adjust this timeout, it's called the grace period: https://caddyserver.com/docs/json/apps/http/#grace_period

**Comment by ThatNerdyPikachu** [comment]
@mholt Yes, this sounds like what is happening.

Can I adjust it via the API once and still have it persist as I call `caddy --reload`? Also: what is the default value for this option (I think 0? If it is, what does a value of 0 do? (I can't easily find where the value is even used, only the field in the struct definition - probably looking in the wrong place.)

**Comment by hairyhenderson** [comment]
> I think 0? If it is, what does a value of 0 do?

Yup, the default is 0. 0 means "wait forever", which is reasonable in _some_ situations, but certainly not all!

**Comment by mholt** [comment]
@ThatNerdyPikachu 

> Can I adjust it via the API once and still have it persist as I call caddy --reload?

(I assume you mean `caddy reload`?) Be careful with this. As our [Getting Started guide points out](https://caddyserver.com/docs/getting-started#api-vs-config-files), it is best to have one source of truth: either a config file, or whatever was loaded via the API (though you might use a config file to bootstrap sometimes).

Dave is right, by default grace periods are off, so you can try setting it to a small value like 2s and see if that helps.
