### ISSUE TITLE
force new certificate from acme server

### ISSUE THREAD

**Issue by delfick** [caddyserver/caddy#3823]
Hello,

I have step-ca as a local ACME server for certificates to my local setup. I set the expiry date it uses to create certificates too long and now my chrome tells me it's insecure cause the expiry is too far in the future.

I changed the options in step-ca but I can't figure out how to force Caddy to ask for a new cert.

Is there a command I can run to do this?

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy!

Just delete the cert from storage and Caddy will generate a new certificate next time it runs.

This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

**Comment by delfick** [comment]
ah, there they are. Excellent. Thanks! I'll keep the forum in mind next time I have a question.
