### ISSUE TITLE
Embedding Caddy

### ISSUE THREAD

**Issue by ranisalt** [caddyserver/caddy#3831]
Hello!

I am writing a service and considering embedding caddy into it. I don't want to extend Caddy with a plugin to avoid locking my server to Caddy, instead I want to create a Caddy instance, set up the configuration through Go code and have Caddy listen to port 443.

I couldn't find a way to do this, it would require being able to control Caddy using internal structures, only way I found was to use `Load` and pass a huge JSON blob which is very far from decent. There's also `Run`, which takes a config pointer, but I could not find a way to initialize the attributes of the config structure.

How can I embed Caddy into my server (which does other things) and control it through programming code? The HTTP API would not be sufficient for me.

**Comment by francislavoie** [comment]
Caddy v2 wasn't designed with that in mind. It's designed essentially as an "app platform" where you plug in your own functionality, and Caddy takes care of config reloads. Read more about it here: https://caddyserver.com/docs/architecture

The nice thing is that you can just use standard http middleware handlers to implement your own functionality, so you can make a clear separation of concerns if you implement your plugin. Write the code that does what you want in one place, then write the glue code that plugs it into Caddy.

I'll close this because it's more of a question rather than a bug or feature request. We typically point people to ask usage questions on the forums https://caddy.community but feel free to continue discussion here.

**Comment by mholt** [comment]
> considering embedding caddy into it. 

Why? If you're already writing a Go program, why not use a Go library?
