### ISSUE TITLE
Err invalid redirect

### ISSUE THREAD

**Issue by matty111** [caddyserver/caddy#3851]
Hi,

I have many microservices in docker on 8080 port and a ui angular.

My caddyfile is:

localhost
handle /app1/* {
    Reverseproxy app1:8080
}
.....
handle /*  {
  Reverseproxy  ui:8080
} 

My ui can't call backend microservice and return ERR INVALID REDIRECT.

My microservices are all in localhost on 80 port with this caddyfile

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
