### ISSUE TITLE
log directive not create log files 

### ISSUE THREAD

**Issue by bjdaijun** [caddyserver/caddy#3853]
This is my Caddyfile:

`
:180 {
	file_server 
	root * /var/www/html

	log {
		output file /var/log/access.log
	}
}
`

After restart caddy,  and refresh my webbrowser , I checked  /var/log  director, No access.log created.

And if I create /var/log/access.log ,and chown it to caddy:caddy, then refresh the browser, I can see the log writen to access.log

So, should I create the log file myself?
Or there was somthing wrong with my operations.

My caddy version:   v2.1.1 h1:X9k1+ehZPYYrSqBvf/ocUgdLSRIuiNiMo7CvyGUQKeA=
OS:  ubuntu 18.04

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
