### ISSUE TITLE
How to set it?

### ISSUE THREAD

**Issue by Y-A-K-E** [caddyserver/caddy#3866]
If (caddy2) quic is enabled by default,.
AJAX or pjax requests PHP sites to not work.

How to set it?
www.abc.com  (PHP website) is set to http/2,
static.abc.com  (JS, CSS, IMG...) is set to http/3.

**Comment by Mohammed90** [comment]
Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding! Please ensure you fill out the template to help us help you!
