### ISSUE TITLE
Consider improvements to default route handling when no server or handler match

### ISSUE THREAD

**Issue by segevfiner** [caddyserver/caddy#3879]
Caddy's current behavior when no site or handler match is to return a 200 status and empty body. The idea behind this is that the server defaults to answering with 200 and an empty body with no configuration without any "magic"/"convenience" behavior in certain cases to do otherwise. You need to explicitly match all routes to with the behavior you need. This is sadly not well documented and the documentation should likely explicitly state this and give examples.

Personally a 200 and an empty body might make sense if there are no handlers configured at all, but it can be argued that a 404 or even just closing the connection might be a better behavior when there are any handlers configured, as otherwise receiving a 200 and an empty body is highly confusing and it took me quite a while to figure out what is going on. Still that is "magic" behavior that some may like and some may not.

The other issue is that this is not that easy to do with the Caddyfile, forcing you to eschew some of the shorthand syntax and convenience it tries to provide. Let's imagine a Caddyfile that just does a plain `reverse_proxy` under some `/api/` route:
```
localhost

reverse_proxy /api/ upstream
```

Any request to something not under `/api/` will respond with a 200 and an empty body. Normally users coming from other servers will expect a 404, but since Caddy prefers to be explicit, this is not the case and you need to add that yourself. The problem? It is not possible to achieve this easily with just the simple "behavior-first" style configuration without using `route` or `handle`, as there is no support for configuring a "fallback" route that will match, if no other route does, in that style of configuration. You are forced to use either one of the more verbose:
```
localhost

route {
    reverse_proxy /api/ upstream
    respond 404
}
```
Or:
```
localhost

handle /api/ {
    reverse_proxy upstream
}

handle {
    respond 404
}
```

This is not only more verbose, but because this is such a commonly desired behavior IMHO, this simply eschews the use of the "behavior-first" style without `route` or `handle` at all.

The same problem also applies to site host matching, Caddy will respond with a 200 and an empty body for any unmatching host, when the site address includes a host in the Caddyfile. Forcing you to use the more verbose form of the Caddyfile with curly braces, eschewing the use of the shorthand without them at all:
```
localhost {
    handle /api/ {
        reverse_proxy upstream
    }

    handle {
        respond 404
    }
}

:80 {
     respond 404
}
```

This issue causes the loss of much of the convenience the Caddyfile shorthand syntax aims to offer, unless additional constructs are added to tackle this issue in a concise way (Or the default behavior is changed, but even then, some users might want to override it).

There are two things that could be added (Both or maybe just one of them):
1. Defining a fallback route in a server when no other handler matches. (A special matcher? Shorthand Caddyfile syntax for it, like for paths?), this can also be useful to implement other kinds of configurations without resorting to `route` or `handle`.
2. Defining a default handler/behavior that takes effect if no handler or server matches at all. (Without having to add curly braces to the server perhaps? In the global config block?)

**Comment by mholt** [comment]
Thanks for the issue; it's already been pretty thoroughly discussed, especially during v2's beta period over the course of about a year. So this is a very well-understood behavior, but I agree we could make it clearer in our documentation.

So first, as summary to what I'm about to write: Caddy's behavior is correct and optimal for most users, but I agree improvements to the documentation are in order.

> The other issue is that this is not that easy to do with the Caddyfile, forcing you to eschew some of the shorthand syntax and convenience it tries to provide.

I'll disagree with you here. Adding a single line that says `route {` or `handle {` is hardly difficult or inconvenient. Notably, this style is the _only_ way to write nginx configs; with Caddy you get the flexibility to use behavior-first config if it fits your needs better, but if it doesn't, don't use it.

I do want to re-emphasize that the Caddyfile, though useful, is not always the best way to configure Caddy, nor is it Caddy's native mode of configuration. It is designed to serve sites by hostname, and if your server's use case doesn't fit that design, then the Caddyfile will be more awkward. The Caddyfile will not be a good fit for all use cases. That said, what you want to do is easily achievable using `route` and `handle` as you demonstrated.

> The problem? It is not possible to achieve this easily with just the simple "behavior-first" style configuration without using route or handle, as there is no support for configuring a "fallback" route that will match, if no other route does, in that style of configuration.

This is exactly why `route` and `handle` exist; and is often the style of configuration I prefer, since it leaves no room for question about ordering.

Fallback routes are supported too; they usually take on an implicit form based on terminal handlers or routes without any matchers. It's all about the order of the handlers and whether terminal handlers are used.

> This is not only more verbose, but because this is such a commonly desired behavior IMHO, this simply eschews the use of the "behavior-first" style without route or handle at all.

I could probably (if I invested valuable time) link you to just as many use cases where the opposite is the "commonly deseired behavior", i.e. where users want to `respond` or `reverse_proxy` only some requests, then fall back to the `file_server`, etc. (But I can say from experience it is the most common use case for myself and many people we've helped in issues and on the forum. Unfortunately we had to shut down telemetry because it was expensive and everyone whined about it so we'll never actually know for sure.) This is really about [directive ordering](https://caddyserver.com/docs/caddyfile/directives#directive-order) and it's something that you can take full control over if the defaults aren't suitable for you -- but mind you, these defaults exist because they were useful during the beta period (and are still useful now); it wasn't an arbitrary choice.

Respectfully, I'm closing this issue since I'm not convinced this is really a significant problem (I've written lots of Caddy configs, including those with fallback routes, and not felt inconvenienced). However, I will be updating the website to describe the default responses of `200 OK` as per your feedback. Thanks!

**Comment by segevfiner** [comment]
Thanks for taking the time to read through this and respond. Honestly I was just surprised by this default and found it slightly awkward to have to add `handle`/`route` just to change it, where they weren't used previously in that Caddyfile, and than further having to add that extra address block just for the fallback where the Caddyfile omitted the curly braces before, felt a bit more verbose than what examples show and something that most users will not know about until they encounter that behaviour when making a typo or writing wrong configuration.

> I'll disagree with you here. Adding a single line that says route { or handle { is hardly difficult or inconvenient. Notably, this style is the only way to write nginx configs; with Caddy you get the flexibility to use behavior-first config if it fits your needs better, but if it doesn't, don't use it.

I'm not talking about the case of just adding a `route` or `handle`, I'm talking about not being able to use the shorthand of not using curly braces when you have a single address, I have to add a fallback address and curly braces to define the fallback to 404 on unknown hosts. And I have to pay careful attention to what that address is, i.e. with automatic HTTPS listening on two ports.

> I do want to re-emphasize that the Caddyfile, though useful, is not always the best way to configure Caddy, nor is it Caddy's native mode of configuration. It is designed to serve sites by hostname, and if your server's use case doesn't fit that design, then the Caddyfile will be more awkward. The Caddyfile will not be a good fit for all use cases. That said, what you want to do is easily achievable using route and handle as you demonstrated.

I'm serving a site by host, just need/want it to fallback to 404 on unknown paths or hosts rather than a blank 200.

> Fallback routes are supported too; they usually take on an implicit form based on terminal handlers or routes without any matchers. It's all about the order of the handlers and whether terminal handlers are used.

Indeed they are when using `route` or `handle`, but not without them. Which is what I tried to point out. Using `route` means you need to be more careful with directives order and using `handle` is a different style, and while I like using `handle` too, I found it weird there wasn't a way to achieve that without them. They aren't pointed out that much in the documentation as the recommended style as far as I've seen.

**Comment by mholt** [comment]
If you really want to simplify your config even more, here's what I would do instead (I assume you are trying to match `/api/*` and not just literally `/api/` alone):

```
localhost/api/* {
	reverse_proxy upstream
}

:80, :443 {
	respond 404
}
```

**Comment by francislavoie** [comment]
And to be clear, `localhost/api/*` just a shortcut for also wrapping with `handle /api/*`, basically.

FWIW I wouldn't recommend using path matchers in site addresses because it hides too much magic and can result in reduced clarity of behaviour. But that's my opinion. I know @mholt disagrees with me on this one (if I had my way it would be deprecated).

**Comment by mholt** [comment]
Related: #3445
