### ISSUE TITLE
Redirect root to www virtual host and provision certs on demand

### ISSUE THREAD

**Issue by dennyNDTC** [caddyserver/caddy#3885]
Struggling to get a working config over here. What am I missing?

```
{
    tls_on_demand {
        ask localhost
    }
}

:80 {
    redir https://www.{host}{uri}
}

:443 {
    tls tls@example.com { on_demand }
    reverse_proxy localhost:8080
}
```
Thank you!

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
