### ISSUE TITLE
I can't strip_prefix correctly

### ISSUE THREAD

**Issue by laspinacristian** [caddyserver/caddy#3904]
I'm trying to use caddy v2 to make a reverse proxy to [code-server](https://github.com/cdr/code-server).

This is my Caddyfile:

```
mydomain.com {
    route /myroute/* {
        uri strip_prefix /myroute
        reverse_proxy 127.0.0.1:3000
    }
}
```

If I make a request to `mydomain.com/myroute` i get no response back.
If I add a trailing slash and make a request to `mydomain.com/myroute/` it works correctly and I'm redirected to `mydomain.com/myroute/login`

How can i make the request to `mydomain.com/myroute` work the same as `mydomain.com/myroute/` ?

Sorry for the repetitions.

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

`/myroute/*` won't match `/myroute` because it's lacking a `/`. Change it to `/myroute*`. Also, you can just use `handle_path` instead of `route`, and remove `uri strip_prefix`. The `handle_path` directive has built-in path stripping logic.

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
