### ISSUE TITLE
Can't find RESTful API.

### ISSUE THREAD

**Issue by matianhe3** [caddyserver/caddy#3912]
```
:8888 {
encode gzip
root * /home/dist
reverse_proxy /api/* localhost:9000
file_server
try_files {path} /index.html
log {
output stdout
}
}
```

```
server {
	listen	8000;
	server_name	localhost;
	root	/home/dist;
	location / {
		try_files $uri $uri/ /index.html;
	}
        location /api {
    		proxy_pass http://127.0.0.1:9000;
        	proxy_set_header   X-Forwarded-Proto $scheme;
        	proxy_set_header   X-Real-IP         $remote_addr;
	}
}
```

In API log , no requset acess. what's wrong with me? Nginx config is ok.

**Comment by matianhe3** [comment]
The try_files cover reverse_proxy ?

**Comment by Mohammed90** [comment]
Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

Please make sure you fill out the template for smoother troubleshooting 🙂

**Comment by matianhe3** [comment]
> The try_files cover reverse_proxy ?

resolve

https://caddy.community/t/try-files-and-reverse-proxy/7436/2

**Comment by nadirvishun** [comment]
can try this  link [https://caddy.community/t/reverse-proxy-isnt-working/12343/2](https://caddy.community/t/reverse-proxy-isnt-working/12343/2), use `handle` wrap：
```
:8888 {
    handle {
        encode gzip
        root * /home/dist
        file_server
        try_files {path} /index.html
        log {
            output stdout
        }
    }
    handle /api/* {
        reverse_proxy localhost:9000
    }
}
```
