### ISSUE TITLE
Hello, is there any binary package that can support mipsel architecture

### ISSUE THREAD

**Issue by caifenglin** [caddyserver/caddy#3930]
Hello, is there a binary package that can support mipsel architecture? I like caddy very much, but I can't install it. My device is mipsel architecture,I hope you can help me

**Comment by francislavoie** [comment]
We don't currently build releases for mips because it's not a very popular architecture, but you can build yourself from source very easily using `xcaddy` and specifying the mips architecture.

https://caddyserver.com/docs/build#xcaddy

https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63

**Comment by mholt** [comment]
:point_up_2:  yep to that

Just curious, what is your device @caifenglin ?
