### ISSUE TITLE
How to listen 80 both ipv4 and ipv6

### ISSUE THREAD

**Issue by fscarmen** [caddyserver/caddy#3960]
I built a site on ipv6 only vps. Now it just listens ipv6.
I want that it can be accessed using ipv4 and ipv6.

_**lsof -i:80**_
COMMAND   PID USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME
caddy   17486 root    7u  IPv6 2709493606      0t0  TCP *:http (LISTEN)

**_vim /usr/local/caddy/Caddyfile_**
http://:80 {
 root * /usr/local/ServerStatus/web
 encode gzip
 file_server
}

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. I think you are looking for the `bind` directive.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
