### ISSUE TITLE
Is there any easy way to install and configure php with caddy?

### ISSUE THREAD

**Issue by josephmiller2000** [caddyserver/caddy#3965]
I'm looking for an easy way to configure and install php along with caddy server. I have seen few configurations examples out there on other sites, but looking for more easy to use way.

There is always a room for improvement for any application, Lets make caddy more developer friendly and easy to access.

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
