### ISSUE TITLE
where to get caddy_v1.0.4_linux_386.tar.gz with IPFILTER module compiled in ?

### ISSUE THREAD

**Issue by nmr50** [caddyserver/caddy#3984]
subj, Thanks ! :)
-t

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
