### ISSUE TITLE
Add some form of shutdown hook

### ISSUE THREAD

**Issue by jjiang-stripe** [caddyserver/caddy#4030]
Hello! I'm building a custom Caddy binary, so this use case might not actually be that common.

I have some global state that I'd like to set up once Caddy starts up, and also some cleanup to do before shutting down. The problem I'm running into is that, while I can just throw the setup into an `init()` somewhere, I don't have a way of making sure the cleanup runs. Caddy v1 had a [shutdown hook](https://pkg.go.dev/github.com/caddyserver/caddy#Controller.OnFinalShutdown) that looks like it does what I'm looking for, but v2 doesn't seem to have anything similar. 

The workaround I've come up with is to just throw this state into its own `App` that I set up on `Start()` and clean up on `Stop()`, but the downside of this is that `Stop()` also gets called on config reloads, when I really only care about full shutdowns. 

Would it be possible to support this type of behaviour, either through setting a shutdown hook, or having some `App`-level function that only gets called on full shut downs? I'm also open to other alternatives!

**Comment by francislavoie** [comment]
This functionality is provided by a plugin: https://github.com/abiosoft/caddy-exec

**Comment by jjiang-stripe** [comment]
ooh! while that looks like it only works for shell commands (i.e. I can't just set up some `client` in Golang and use that `client` in code in another module), I think I can adapt the intelligent startup/shutdown from that plugin to do what I want. this is _very_ useful, thanks! 

I think this is enough for me to close this issue (but I may reappear if I fail 😅 )

**Comment by francislavoie** [comment]
To explain how that works, make sure you've read https://caddyserver.com/docs/architecture. Basically when config reloads happen, Caddy keeps the original config running, then provisions and starts the new one, then shuts down the old one. Because it's done in this order, using an atomic counter, you can tell when there's overlap between configs. If there's overlap (i.e. 2 starts have happened so far) then you know it's a config reload. If there's no overlap then it's a shutdown at the end.
