### ISSUE TITLE
caddy2  reverse proxy changes address in browser

### ISSUE THREAD

**Issue by ironpython2001** [caddyserver/caddy#4032]
I am using caddy as reverse proxy for my asp.net core application. I am new to caddy webserver

**asp.net core demo application runnin on port 5000**

![image](https://user-images.githubusercontent.com/1304388/108647147-ee53dd00-74dd-11eb-92d9-f72de852dc6a.png)

**caddy2 running** 
![image](https://user-images.githubusercontent.com/1304388/108647236-1e02e500-74de-11eb-83f1-50e7e5be384a.png)

**my caddy file** 
localhost {
    reverse_proxy  {
        to localhost:5000
        header_up Host {http.reverse_proxy.upstream.host}
        
    }
}

**when i type http://localhost in my browser it is showing https://localhost:5001/ & subsequent links are showing https://localhost:5001/Home/Privacy**

![image](https://user-images.githubusercontent.com/1304388/108647290-45f24880-74de-11eb-8f57-2eb7de1eda4d.png)

https://localhost:5001/Home/Privacy

![image](https://user-images.githubusercontent.com/1304388/108647348-6f12d900-74de-11eb-81c0-eef44d2b284b.png)

I don't wanted to display like that i wanted display as https://localhost/Home/Privacy

Am i missing something ..? or my caddy file is incorrect  ..? or is this a issue in caddy..? Please correct me

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request.

It's probably a cached redirect or something like that. Please try using `curl -v` instead of a web browser to see what's going on under the hood, without any browser weirdness.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there if the curl trick does not answer your question sufficiently, and thanks for understanding!
