### ISSUE TITLE
the ignore_loaded_certificates config for Caddyfile

### ISSUE THREAD

**Issue by shynome** [caddyserver/caddy#4048]
I can't find the ignore_loaded_certificates config for Caddyfile

I have some domain behind cloudfare strict https so I need use cloudfare wildcard certificates, but I also have some domains is direct to my host and these domains need autohttps, but now I can't do that, because I can't find this config https://caddyserver.com/docs/json/apps/http/servers/automatic_https/#ignore_loaded_certificates

**Comment by simaotwx** [comment]
Just leaving some information here.

The config is here: https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/autohttps.go#L58
And the code that handles it is here: https://github.com/caddyserver/caddy/blob/8ec90f1c402b5e1aa1eea59e45f700aeb45da6ba/modules/caddyhttp/autohttps.go#L175

I think further investigation is needed if this is a bug.

Can you provide an error message or observed behavior to track down what the issue is?

**Comment by shynome** [comment]
the caddy v1 config `tls a.crt a.key` is just for this domain, but caddy v2 save the certificate to certificate store and use it for each matched domain

a sample config, in json config I can use ignore_loaded_certificates, but I don't know how to make it work in caddyfile
```conf
cf.example.com {
  tls wildcard.cf.crt wildcard.cf.key
}
host.example.com {
  tls {
    autohttps always # don't use last block wildcard certificate *.example.com
  }
}
```

**Comment by francislavoie** [comment]
I opened #4077 to solve this -- FYI this must be configured via global options, since `ignore_loaded_certificates` is a server-level option, not at the site level or automation policy.
