### ISSUE TITLE
Feature request: log filter - request>headers>Authorization

### ISSUE THREAD

**Issue by udf2457** [caddyserver/caddy#4052]
Looking through the docs (https://caddyserver.com/docs/caddyfile/directives/log), they show the following example:
```
log {
	format filter {
		wrap console
		fields {
			request>headers>Authorization delete
		}
	}
}
```

This brings to mind two feature suggestions:

1. As a security focused server, surely Caddy should default to a state where `request>headers>Authorization` is omitted from any logs because it is highly likely to contain security sensitive information ?  So my feature request here is that you default to _**off**_ and you force people to turn it _**on**_ when they need it.
2. Building on (1), Caddy could (should ?)  provide an `obfuscated` option for `request>headers>Authorization`, so instead of dumping the whole string into the logs, Caddy would only write a truncated Auth header.

**Comment by francislavoie** [comment]
Unfortunately 1. is likely impossible because control is somewhat limited by how zap (our logging lib) works, for performance reasons. If we defaulted it having it off, it don't really have any good way of turning it back on.

But fortunately 2. is likely coming in a future version, see https://github.com/caddyserver/caddy/pull/4029.

What I recommend in general is to do any filtering you need external to Caddy, with a tool like jq or something, and throw away the rest that you don't need.

**Comment by udf2457** [comment]
Unfortunate about 1.  But happy to hear about #4029.  I'll shake hands on that compromise. 👍
