### ISSUE TITLE
Unable to follow a symlink to a directory

### ISSUE THREAD

**Issue by Xalaxis** [caddyserver/caddy#4062]
I think I'm still seeing the behaviour of #3838 in Caddy v2.3.0. Perhaps the issue has been reintroduced?

I am unable to follow a symlink to a linked directory. Attempting to do so results in a 404 error.

## Symlinked directory showing as file

![image](https://user-images.githubusercontent.com/12937964/111051363-66148800-844a-11eb-8450-9adca0287b6a.png)

![image](https://user-images.githubusercontent.com/12937964/111051377-7462a400-844a-11eb-984e-b71a24c170f1.png)

### Caddy version

![image](https://user-images.githubusercontent.com/12937964/111051371-6c0a6900-844a-11eb-8902-1a9133edf917.png)

**Comment by francislavoie** [comment]
That looks correct, that icon is the symlink icon.

It was fixed in https://github.com/caddyserver/caddy/commit/0a7721dcfe30b76c66c6364ccb6874a2eadcba21

Look at the template in https://github.com/caddyserver/caddy/blob/0d7fe36007d5fbadaa6057b6543500d63147e6c0/modules/caddyhttp/fileserver/browsetpl.go, you can see `xlink:href="#file{{if .IsSymlink}}-shortcut{{end}}"`, i.e. if it's a symlink, it adds `-shortcut` to the SVG href, which you can find near the bottom of the template, i.e. `file-shortcut`.

**Comment by Xalaxis** [comment]
Ah, sorry, I realize I should have included more details about the problem.

Unfortunately even though the symlink icon is displayed, attempting to access the link results in a 404 rather than a fresh directory listing. In the first screenshot of #3838 the symlink icon appears to be correctly displayed as well, even though the link itself is not accessible, so I suspected it was related to  my issue.

**Comment by francislavoie** [comment]
Does the `caddy` user have permissions to read files from there?

I notice that your symlink has two `/` at the end, might that be an issue? Are you sure your symlink is correct?

**Comment by Xalaxis** [comment]
I'm very sorry about this. The user permissions were correct and the symlink was valid... outside of the Docker container. I hadn't realized that within the container the link wouldn't resolve anymore 😅.

Thanks for your help resolving this and your quick responses 🙂.
