### ISSUE TITLE
Feature: Cache DNS requests

### ISSUE THREAD

**Issue by theblazehen** [caddyserver/caddy#4108]
When running Caddy as a reverse proxy with hostnames as the target, it appears to do a DNS request for each HTTP call.

It would be helpful it we could specify how long Caddy can cache a DNS result, something similar to `valid` as for example in http://nginx.org/en/docs/http/ngx_http_core_module.html#resolver

I have found https://github.com/rs/dnscache which somewhat appears to be a drop in replacement for net.Resolver

**Comment by rumpelsepp** [comment]
The relevant DNS resolver should cache anyway, doesn't it?

**Comment by theblazehen** [comment]
I've seen higher-than-expected CPU usage when using systemd-resolved, but could change to dnsmasq perhaps if this feature doesn't get implemented.

**Comment by francislavoie** [comment]
Since we support `srv://`, it would need to _not_ cache if srv is used. We will need to be careful with this.

**Comment by Forza-tng** [comment]
> I've seen higher-than-expected CPU usage when using systemd-resolved, but could change to dnsmasq perhaps if this feature doesn't get implemented.

If DNS performance is needed I suggest to switch to [Unbound](https://nlnetlabs.nl/projects/unbound/about/) or similar caching DNS server.

**Comment by francislavoie** [comment]
I think https://github.com/caddyserver/caddy/pull/4470 will essentially cover these requirements. A custom `UpstreamSource` module could be written which caches DNS queries. Or the `AUpstreams` implementation could be augmented to have optional caching.

But I feel like we might close this because this requirement doesn't affect the large majority of users. DNS is sufficiently fast for most everyone.

**Comment by mholt** [comment]
I don't understand why the system resolver isn't caching it, like why do we have to do the caching :thinking: 

Am OK with closing it, we can reopen this if it turns out to be an issue within Caddy.
