### ISSUE TITLE
[Question] Reverse Proxy Unavailable handling

### ISSUE THREAD

**Issue by FrozenSource** [caddyserver/caddy#4116]
Hello guys,

I have a question. I have a lot of reverse proxy entries. Something I would like is to provide a webpage or at least a message if a reverse proxy origin is unavailable.

I went searching and found this https://caddyserver.com/docs/caddyfile/directives/handle_errors assuming that unavailability would provide an error code.

This however appears not to be the case.
Am I missing something or should I have gone at it some other way.

server: docker - caddy2 + cloudflare.

Sincerely,

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
