### ISSUE TITLE
[Question] How to change caddy itself's log output format while I using caddyfile with systemd

### ISSUE THREAD

**Issue by Mosney** [caddyserver/caddy#4121]
I deploy caddy on my homeserver, so just need simple reverse proxy than complex&human-unfriendly JSON/API coordinate with others. Looks no way to change log output format after I read docments, so I have to post question here, could someone help me?

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
