### ISSUE TITLE
Race Condition when clustering Caddy2 with the caddy run --watch.

### ISSUE THREAD

**Issue by RyanPrice-King** [caddyserver/caddy#4138]
There is a race-condition with clustered Caddy nodes when simultaneously modifying multiple configuration requests by admin API. It takes approximately 1 minute for each node to recognise the configuration changes and apply.  Caddy2 needs to give time for each node in the cluster to update changes before processing another modification request, else some requests get overridden and do not apply.

**Comment by mholt** [comment]
Looks like this was carried into the forum with more detail: https://caddy.community/t/race-condition-when-clustering-caddy2-with-the-caddy-run-watch/12310

Since the forum topic has more information, will close this and, if we decide we need to take development action, we can move it back into this issue and reopen it.
