### ISSUE TITLE
Invalide localhost SSL Certificate on all browsers (docker)

### ISSUE THREAD

**Issue by ibousfiha** [caddyserver/caddy#4139]
Hi,

I'm currently facing a problem of invalid localhost Certificate on all browsers on Caddy v2.3.0 used in docker (Api-platform project)

On Brave:
```
Your connection is not private
Attackers might be trying to steal your information from localhost (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID
```

On Firefox:
```
Warning: Potential Security Risk Ahead

Firefox detected a potential security threat and did not continue to localhost. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.

What can you do about it?

The issue is most likely with the website, and there is nothing you can do to resolve it.

If you are on a corporate network or using anti-virus software, you can reach out to the support teams for assistance. You can also notify the website’s administrator about the problem.

Learn more…
```

is that normal ?
I tried `caddy untrust` and `caddy trust` as mentioned here (I don't know if it is related) => https://github.com/caddyserver/caddy/issues/3535#issuecomment-698626774
But it doesn't help anyway.

Any idea of how to make this work properly please ?

**Comment by francislavoie** [comment]
If you're running Caddy in Docker, then Caddy cannot install the root certificate to your system's trust store, because it's in a container (isolated from the rest of your system). So you'll need to install the root certificate from the local CA manually. You can find the certificate at `/data/pki/authorities/local/root.crt` in the container (mapped to wherever you mounted the `/data` volume on your host).

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
