### ISSUE TITLE
file matcher should not match `/`

### ISSUE THREAD

**Issue by princemaple** [caddyserver/caddy#4146]
On Caddy 2.3

------

```
@is_file {
  file
}

handle @is_file {
  file_server
}

handle {
  reverse_proxy ...
}
```

Going to `/` seems to match `is_file` even though `/` isn't a file and there isn't a `index.html`. This causes 404 directly from caddy while the intended response is from upstream server.

```
@is_file {
  file {path}
}

handle @is_file {
  file_server
}

handle {
  reverse_proxy ...
}
```

Note the `{path}`, works as expected.

Wondering if it's by design?

**Comment by francislavoie** [comment]
Hmm, yeah I guess this might be a bug.

For @mholt, the explanation:

If `TryFiles` is empty, we fill it with `r.URL.Path`. In this case, this is `/`. Then later, in `prepareFilePath()`, we run the replacer (which turns `{path}` into `/` at that point) but `file` remains the original value (and the placeholder is still the placeholder there).

So then `strings.HasSuffix(file, "/")` will be `false` for the placeholder, but `true` for the empty `TryFiles` codepath, because `file` was `/` due to being set to the actual request value beforehand.

This means that `suffix` becomes `//` in that case, so after `sanitizedPathJoin`, it becomes `./`, so `strictFileExists`'s `strings.HasSuffix(file, separator)` codepath will return true.

I think we should change the `m.TryFiles == nil` codepath to `m.TryFiles = []string{"{http.request.uri.path}"}` for consistency. (And maybe consider hoisting this to `Provision` cause there's no point doing this on every request). I don't think this "optimization" of directly using `r.URL.Path` is so valuable, cause it causes this edgecase with directories.
