### ISSUE TITLE
fuzz-replacer: Out-of-memory in fuzz-replacer 

### ISSUE THREAD

**Issue by mohammed90** [caddyserver/caddy#4168]
Detailed Report: https://oss-fuzz.com/testcase?key=5357691619901440

Project: caddy
Fuzzing Engine: libFuzzer
Fuzz Target: fuzz-replacer
Job Type: libfuzzer_asan_caddy
Platform Id: linux

Crash Type: Out-of-memory (exceeds 2560 MB)
Crash Address: 
Crash State:
  fuzz-replacer
  
Sanitizer: address (ASAN)

Crash Revision: https://oss-fuzz.com/revisions?job=libfuzzer_asan_caddy&revision=202105130617

Reproducer test case: [clusterfuzz-testcase-minimized-fuzz-replacer-5357691619901440](https://github.com/caddyserver/caddy/files/6488298/clusterfuzz-testcase-minimized-fuzz-replacer-5357691619901440.txt)

Issue on oss-fuzz tracker: [Issue 34273](https://crbug.com/oss-fuzz/34273)

**Comment by mholt** [comment]
I finally put this test case verbatim into a unit test (yes it's a ridiculously long line -- and I've replaced the NUL bytes with \x00 so the test will compile). I think the problem is that every empty placeholder -- of which there are a _million or so_ -- is being replaced with half the input -- which is also about a million bytes (give or take half of that, you get the idea) -- the allocations take time and it uses a ton of memory.

We could easily introduce artificial limits and say "we're done, this is too big," but I think the notion of ~doubling the input size for every _empty placeholder_ and then having _millions of empty placeholders_ is not a real-world scenario. Nor is the use of `ReplaceAll()` with an untrusted input (or especially an untrusted "empty" value) a practical, real-world scenario.

In other words, I think this test case:

```
ReplaceAll(string(data[:len(data)/2]), string(data[len(data)/2:])) 
```

is not really representative of anything meaningful. Yes, it could be considered a bug technically, but the only good fix I can think of is "don't grow the string by orders of magnitude for every 2 bytes of input" :man_shrugging: 

Thanks for the fuzz testing! :+1:

**Comment by mohammed90** [comment]
> In other words, I think this test case:
> 
> ```
> ReplaceAll(string(data[:len(data)/2]), string(data[len(data)/2:])) 
> ```
> 
> is not really representative of anything meaningful.

Do you propose we remove it from the fuzzing code? I added it to be as pathological as possible. I've seen this pattern in some of stdlib fuzzers, so I fllowed suit.

**Comment by mholt** [comment]
Maybe? I dunno. It did technically find a bug: the purpose of the Replacer is to expand strings, and I guess expanding a huge string factorially with itself is going to exhaust memory. Should we add an arbitrary limit to number of replacements or string size? I dunno. That would only fix it on one system, but not another with fewer resources.

Any thoughts?
