### ISSUE TITLE
modify access-control-allow-origin: * header

### ISSUE THREAD

**Issue by SvenDowideit** [caddyserver/caddy#4188]
So I have an application container that outputs `access-control-allow-origin: *`, and then I'm using caddy to add auth and proxy it for xhr use.

so far, I've tried a bunch of ways to express either

* remove the header and add a new one (with, and without defer

```
header -access-control-allow-origin
header +access-control-allow-origin newvalue
```

or

```
header -access-control-allow-origin
header ?access-control-allow-origin newvalue
```

* various attempts at replace

```
header access-control-allow-origin "*" {{index labels "virtual.cors"}}
header access-control-allow-origin "\*" {{index labels "virtual.cors"}}
header access-control-allow-origin "[^h]" {{index labels "virtual.cors"}}
```

and nothing I've tried works - I'm presuming that the `*` makes it really complicated for the regex parser

its not clear to me from https://caddyserver.com/docs/caddyfile/directives/header how caddy wants the user to achieve this kind of mutation.

**Comment by mholt** [comment]
Try using `header_down` in your `reverse_proxy` block.

This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
