### ISSUE TITLE
different values of MaxIdleConns and MaxIdleConnsPerHost

### ISSUE THREAD

**Issue by akosyakov** [caddyserver/caddy#4201]
Maybe I'm missing something but it does not seem to be possible because `keepalive_idle_conns` always overrides `max_idle_conns_per_host`: https://github.com/caddyserver/caddy/blob/5ef76ff3e6e73282deb59df8b1a14bb966de36be/modules/caddyhttp/reverseproxy/httptransport.go#L200-L225

**Comment by mholt** [comment]
Hmm that does seem like an oversight, oops.

@francislavoie What if we deprecate `h.MaxIdleConnsPerHost` (since it's a property of keep-alive) and remove it later, since it's a bug. (I'll take care of this.)

**Comment by mholt** [comment]
Hm ok so here's what I'm gonna do: I'm just gonna remove `h.MaxIdleConnsPerHost` since currently, people's configs are _silently_ broken if they specify both (since one overwrites the other). We could return an error if both are specified and the values are different, but that's still an error all the same as if we just remove it, and I'd rather delete code than add code, especially adding it just temporarily.

So, this could break some people's configs, but it fixes a bug that they're already experiencing anyway, so this will bring their configs in line to not be buggy anymore.

**Comment by mholt** [comment]
Dangit, forgot to run the tests before I pushed. Sigh...

**Comment by chandrawisnu** [comment]
reverseproxy: Fix overwriting of max_idle_conns_per_host (closes
