### ISSUE TITLE
why caddy windows client cannot start

### ISSUE THREAD

**Issue by xixingya** [caddyserver/caddy#4223]
: listen tcp 127.0.0.1:2019: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by Mohammed90** [comment]
This could be due to various reasons, amongst them:
- Firewall and/or antivirus: "An attempt was made to access a socket in a way forbidden by its - Microsoft Community" https://answers.microsoft.com/en-us/ie/forum/all/an-attempt-was-made-to-access-a-socket-in-a-way/4a955300-4cc6-4b2f-b426-6d6f07e4eddc
- "An attempt was made to access a socket in a way forbidden by its access permissions - Stack Overflow" https://stackoverflow.com/questions/15619921/an-attempt-was-made-to-access-a-socket-in-a-way-forbidden-by-its-access-permissi


Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there in the future, and thanks for understanding!
