### ISSUE TITLE
Feature Request: option for auto_https redirect behavior

### ISSUE THREAD

**Issue by karmanyaahm** [caddyserver/caddy#4227]
I often use the following snippet
```Caddyfile
(upgrade) {
        @upgradable {
                header Upgrade-Insecure-Requests 1
                protocol http
        }

        redir @upgradable https://{host}{uri} 308
}
```
and then `import upgrade` into each of my host blocks.
This makes it so only modern web browsers get redirected to HTTPS. Older/vintage computers, or embedded systems which might be incapable of doing TLS; clients such as curl, where it might be slightly inconvenient to go through redirects; etc. continue accessing the site through HTTP. 

It would be nice if the `auto_https` global option had an `auto_https needed` (or some other word) option, just like `auto_https disable_redirects` which integrates the above snippet into Caddy's auto_https directive.

See also: <https://jcs.org/2021/01/06/plaintext>

**Comment by francislavoie** [comment]
I don't see this as desirable. Only upgrading _sometimes_ is just as bad as never doing it IMO. I don't think this is something Caddy should support, especially since the goal is to bring security by default. I think your approach is fine to do manually when you need it. I don't think Caddy should carry the burden of this mode which is only useful for legacy browsers (legacy browsers should die ASAP, supporting insecure browsers is counterproductive).

**Comment by karmanyaahm** [comment]
> Only upgrading sometimes is just as bad as never doing it IMO.

Just wanted to clarify, the goal for this redirect behavior is to value compatibility over security.
> Caddy .. the goal is to bring strong security by default

okay, I understand that's better for most use cases.

P.S.: I recently switched to Caddy, thanks for making such a nice webserver :)
