### ISSUE TITLE
JSON configfile parsing errors should be more insightful and give useful detail

### ISSUE THREAD

**Issue by meglio** [caddyserver/caddy#4270]
Here is an example of an error log I see when using Caddy through an official docker container:

> caddy_1       | run: loading initial config: loading new config: loading http app module: provision http: server nextjs: setting up route handlers: route 0: loading handler modules: position 0: loading module 'reverse_proxy': provision http.handlers.reverse_proxy: loading transport: json: cannot unmarshal string into Go value of type map[string]interface {}

Such an error is very difficult to read and act upon. Especially this part: **json: cannot unmarshal string into Go value of type map[string]interface {}**

It would be useful to tell what failed exactly and why it did not understand the JSON config file:

- was it a missing field?
- was it an incorrect value for some field?
- was it an incorrect field name, a typo (as an example, think of a git command than hints you - did you mean this or that command instead?)

In this thread / feature request, please avoid explaining the technicalities that lead to this generic error that is useless and makes for a bad UX (that's what I feel as the user). We all know that programming is here for us to solve any such trivial problems - we can parse the JSON input and compare it to the expected schema, detect the cases as described above, and give useful feedback on the JSON validation errors.

So my suggestion here is to add this to the roadmap and improve error handling and make errors easy to act upon. Invalid JSON format reports could be a good starting point. -- thanks, Anton

**Comment by mholt** [comment]
I agree the error message could be better.

At least you know it's in the transport of the reverse_proxy module, in handler 0 of route 0, of the server nextjs. That gets you pretty close. But yes, the error message doesn't take you the last 9 yards to the finish line. It only gets you close.

I think this information would be best known by the [`encoding/json` package](https://pkg.go.dev/encoding/json), which is in the Go standard library. So I think in order to improve these errors, we'd need to do that upstream in [golang/go](https://github.com/golang/go). They seem to be receptive to proposals that enhance error messages, so it's worth a try.

Closing, since this is more of an upstream issue, but feel free to continue discussion as needed.

**Comment by meglio** [comment]
We won't get far by providing excuses and referencing upstream. Why not generate json schema, validate against the schema, and report meaningful errors? It has nothing to do to the encoding/json package.

**Comment by mholt** [comment]
Isn't that a lot more work than just improving the error message, which would also benefit thousands of other applications?

**Comment by meglio** [comment]
Yes and no. If you rely on the package, you may wait for the improvement for ages.

> Isn't that a lot more work

Yes, I'd say it's a proactive, anti-lazy way of delivering value to the people :) What's wrong about doing more work if it brings value to the people?

**Comment by mholt** [comment]
I think improving the error message in the encoding/json package is the best solution.

But to compare, how would we do it ourselves? What would the change look like? Would it be complicated?
