### ISSUE TITLE
Support for Hashicorp Vault as certificate source

### ISSUE THREAD

**Issue by cyr** [caddyserver/caddy#4271]
I am using Vault, with their pki-engine as CA in my internal environment. It would really neat to have support for getting certificates, as an alternative to ACME. The only other service I know that implements this is Traefik, and only via their enterprise license.

**Comment by francislavoie** [comment]
I think this is the sort of feature that would require sponsored work to implement. I don't think this is something that would be valuable to a large number of users, since it's a pretty niche usecase. You may reach out at https://caddyserver.com/business if it's important for you.

If someone wants to take a shot at implementing it, it would probably involve writing a custom `tls.issuance.*` module, see https://caddyserver.com/docs/json/apps/tls/automation/policies/issuers/.

**Comment by mholt** [comment]
Yeah, we can develop this, but probably will need some funding. Let me know if your company is interested!
