### ISSUE TITLE
Caddy error obtaining home directory, please define environment variable HOME.

### ISSUE THREAD

**Issue by Dimitri2020007** [caddyserver/caddy#4284]
Enviorment：
                     alpine:edge
                     dockerfile deploy container

Caddy version:
                    v2.4.3 h1:Y1FaV2N4WO3rBqxSYA8UZsZTQdN+PwcoOcAiZTM8C0I=

Error log:

```
{"level":"warn","ts":1629167856.1931417,"msg":"unable to determine directory for user configuration; falling back to current directory","error":"neither $XDG_CONFIG_HOME nor $HOME are defined"}
Error obtaining home directory, please define environment variable HOME.
```

Current config (I have deleted parts of the files for confidentiality reasons):

```
:$PORT

root * ******
file_server browse

tls internal

header {
    Permissions-Policy interest-cohort=()
    Strict-Transport-Security max-age=31536000;
    X-Robots-Tag none
    X-Content-Type-Options nosniff
    X-Frame-Options DENY
    Referrer-Policy no-referrer-when-downgrade
}

basicauth ****** {
    ****** ******
}

@websocket_****** {
    header Connection *Upgrade*
    header Upgrade    websocket
    path ******
}
reverse_proxy @websocket****** ******
```

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! So far, this doesn't look like a bug in Caddy. It looks more like a question about how to use Caddy rather than a bug report or feature request.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!
