### ISSUE TITLE
Text files served by file_server should include encoding along with the mime-type within the content-type header

### ISSUE THREAD

**Issue by idontusenumbers** [caddyserver/caddy#4315]
Using a caddy file with something like:

```
handle /static/* {
  file_server {
	  root /app/static
  }
}
```

JavaScript files should have the following header:
```
Content-Type: application/javascript; charset=utf-8
```
Instead, they have this header:
```
Content-Type: application/javascript
```

**Comment by francislavoie** [comment]
Content types come from your system's MIME package, which the Go stdlib reads from. Caddy does nothing special to handle these.

https://github.com/caddyserver/caddy/blob/f43fd6f3884d957afc391da3ca689a43ba27eccb/modules/caddyhttp/fileserver/staticfiles.go#L322

Closing, because there's nothing actionable here, not enough information to show that there's an actual problem in Caddy (next time, please provider your version, _full config_, logs, installation method, etc).

**Comment by idontusenumbers** [comment]
Caddy version v2.3.0

I don't believe the typeByExtension method will include the encoding.

I don't think this is a critical issue but Edge is directing me to https://webhint.io/docs/user-guide/hints/hint-content-type/ to fix this issue.

**Comment by francislavoie** [comment]
> I don't believe the typeByExtension method will include the encoding.

It does, actually. See the code in the Go stdlib. It does handle encodings.

**Comment by idontusenumbers** [comment]
I'll update; thanks.

I found the corresponding line in the go src: https://go.googlesource.com/go/+/refs/heads/master/src/mime/type.go#175

It doesn't seem to add the charset to application/javascript (among other non `text/*` types). Somewhat humorously, the default mime type map for when no others can be loaded contains (the apparently obsolete) `text/javascript` with encoding.

I checked the mime types from the official docker image (latest I saw was 2.4.3, seems 2.4.4 was released 6 hours ago but the docker image hasn't been built/pushed). Seems the first mime type file it loads is `/etc/mime.types` (skipping the non-existent glob files), and this doesn't contain the charsets.
