### ISSUE TITLE
Active health check not separated for same upstream

### ISSUE THREAD

**Issue by ulrichSchreiner** [caddyserver/caddy#4341]
hi,

i already posted a question here (https://caddy.community/t/healthcheck-not-working-with-multiple-servers/13563) and the answer was to create a feature request (if needed). in the forum there is also an example `caddy.json` .

first my problem: i use caddy as a reverse proxy in front of another reverse proxy. the "backend" proxy has one IP address and distinguishes the requests with different HOST-headers to the real backend. in my concrect environment the backend is a nginx which is the default ingress controller in a K8S cluster.

for some hosts we place a caddyserver in front because caddy has some nice plugins and features (and a really nice plugin API);  my caddy config has different servers configured which all have the same upstream but use different settings for the health-check: the healthcheck overwrite the "Host" header so the backend-proxy can delegate to the correct backend system.

but although i have configured two healthchecks, caddy only uses one of them to get the healthy state of the upstream. in my question in the forum (https://caddy.community/t/healthcheck-not-working-with-multiple-servers/13563) i created an example with `httpbin.org` and two different healthcheck-URI's; this is different to my private usecase where i use host-headers but both have the same result: caddy only uses one of them, altough i configured two different healthchecks.

i'm not sure if i should request new feature or if it is a bug. imho it should be possible to chain two reverse-proxies, simply think of caddy-1 behind caddy-2. the caddy-2 must have the chance to mirror all the configured hosts of caddy-1 with a correspoding healtcheck.

what is my current workaround? well as i provision my servers dynamically, i can create hosts-entries for my backends with the same IP address. so i create host-entries "server-1", "server-2", ... all with the same IP and i reference them as upstreams. this works, but is really a hack. and i'm not sure i can do this in every environment.

i think if one has multiple server-blocks in `caddy.json` and every server has its own upstreams and its own healthchecks these should be separated. or you should at least make it clear in the documentation that multiple upstreams with the same `dial` address take one random healtheck, perhaps not the one you configured in the `server`-block. so it can happen that caddy marks your server as "healthy" although in realilty it is unhealthy.

**Comment by francislavoie** [comment]
> Despite appearing in two places in the config, they are the exact same host -- they are **not** distinct -- so really, it is not possible for it to be healthy and unhealthy (not down, and down) at the same time. 

This is only true if you consider "health" to have the narrow definition of "the server is reachable". Health can actually be much broader than that, such as application/business level "maintenance modes" or "the database for one customer is down but not the other databases", etc. An upstream could be another proxy serving many sites, where one might be down, but not all of them.

The backend app can have a "go/no go" style checklist that checks if everything is ok before allowing requests, like checking for valid configuration, all dependent services are reachable, etc. That's the power that `health_uri` active health checks brings.

**Comment by mholt** [comment]
This will be in progress on the [`proxy-refactor` branch](https://github.com/caddyserver/caddy/tree/proxy-refactor).

**Comment by 73VW** [comment]
This was auto-closed by #4470 (dynamic upstreams, SRV + A/AAAA), but I don't think that PR addresses the problem reported here. It's still reproducible on v2.11.1.

The core issue isn't resolving upstream *addresses* dynamically — it's that an upstream's **health state is keyed solely by its dial address in the global host pool**, and is therefore shared across every `reverse_proxy` handler that dials the same `host:port`, regardless of each handler's health-check config.

Concretely: two handlers fronting the same backend node but serving different vhosts (each rewriting `Host`/`X-Forwarded-Host` and using a different `health_uri`) share a single `Host` object. Only one active checker's result "wins", so a vhost that is actually unhealthy on that node can be reported healthy (and vice-versa) — and an admin-path outage can evict the node from the data path too.

Minimal repro: two `reverse_proxy` blocks, same `to` address, different `health_uri` + `health_headers`. `GET /reverse_proxy/upstreams` returns a **single entry** for that address even though two distinct health checks are configured:

```
[
  { "address": "node01.example:443", "num_requests": 0, "fails": 0 }
]
```

Dynamic upstreams (#4470) don't cover this: active health checks don't run on per-request dynamic upstreams, and giving each vhost a distinct DNS name is exactly the static "N hostnames for one IP" workaround already noted in this thread — it sidesteps the shared state rather than fixing it.

I understand the dial-address key is intentional (it also backs `least_conn` connection counts and state preservation across reloads), so fully splitting state is non-trivial. But at minimum it would help to:
- document that multiple active health checks against the same dial address collapse into one shared state (the original report explicitly asked for at least this), and ideally
- warn at provision time when two active checkers target the same dial address with differing config, and/or
- allow opting into health state scoped per handler / per health-check identity.

Could this be reopened? Happy to share a full repro config.

**Comment by mholt** [comment]
I believe this was before alternate URI could be configured for active checks, so the host was (moreso) equivalent to the active health check.

Would you mind opening a new issue to discuss this? Please follow the bug report template so we can be exactly on the same page as you.

**Comment by 73VW** [comment]
@mholt done here: https://github.com/caddyserver/caddy/issues/7870
