### ISSUE TITLE
Site addresses cannot contain a comma 

### ISSUE THREAD

**Issue by ttys3** [caddyserver/caddy#4343]
the config:

```

{$SITE_ADDRESS:"http://example.com, https://example.com"} {
    root * /app/public
    file_server
}
```

I just want the same config block applied to both `http` and `https`

it's OK if I use `http://example.com, https://example.com`

it is also OK if I use `{$SITE_ADDRESS}` and run with `-e SITE_ADDRESS="http://example.com, https://example.com"`

but when I set `{$SITE_ADDRESS:"http://example.com, https://example.com"}` it report an error:

`Error during parsing: Site addresses cannot contain a comma ','`

ref https://caddyserver.com/docs/caddyfile/concepts#addresses

**Comment by francislavoie** [comment]
Don't use double quotes when setting a default value. If you do, it gets treated as a single token, which is invalid: https://caddyserver.com/docs/caddyfile/concepts#tokens-and-quotes

Try this instead:

```
{$SITE_ADDRESS:http://example.com, https://example.com} {
    root * /app/public
    file_server
}
```

**Comment by ttys3** [comment]
Thanks point out and gave the right answer, I did read the doc but not understand the doc very clear.

I use double quote because I thought it already has `:`, I feel it will fail to parse a second `:` after `http`.

the doc says:

> You can also use a backtick ` to quote tokens:

```
directive `"foo bar"`
```

could you give a suggestion:

Is this better ?
```
{$SITE_ADDRESS:`http://example.com, https://example.com`}
```
 Or just use this is enough ?
```
{$SITE_ADDRESS:http://example.com, https://example.com}
```

**Comment by francislavoie** [comment]
Backticks are just an alternative way to wrap text that may have whitespace to make it a single token. It's main usecase is when JSON text might be used as the value, because JSON uses double quotes, so escaping all double quotes would be too tedious.

In this case, you definitely _don't_ want it treated as a single token, because that means Caddy would think the literal text `http://example.com, https://example.com` is a single address, which doesn't make sense.

So the correct thing _is_ this:

```
{$SITE_ADDRESS:http://example.com, https://example.com}
```

**Comment by ttys3** [comment]
Thanks, I tried and suddenly relised I was wrong again.
