### ISSUE TITLE
Extend `remote_ip` matcher to resolve DNS

### ISSUE THREAD

**Issue by muety** [caddyserver/caddy#4365]
I would love to have a request matcher like `http.matchers.remote_ip` but extended in a way that not only static IPs and CIDRs can be passed as an argument, but domain names. In that case, the matcher would dynamically try to resolve (`A` / `AAAA`) the given domain to a single IP address and do request matching based there upon. 

A specific use case would be to restrict HTTP access to some virtual host for clients that use dynamic DNS instead of having a static IP. An alternative solution for this would be to have a script, that regularly polls the domain's DNS entries and then calls Caddy's config API to update the matcher's IP parameter. However, having this built into Caddy directly would be more convenient.

I am aware that this request is pretty specific, so feel free to close it if you consider it too much of a niche feature.

**Comment by francislavoie** [comment]
The nice thing about Caddy's design is that everything is a module. You could easily write a plugin which implements a new matcher that does what you need. See https://caddyserver.com/docs/extending-caddy

I think this feature would overload the `remote_ip` matcher. It's better to keep matchers smaller and focused.

I'll close this because I'm unconvinced this would have broad use, so it's unlikely to be a fit as a standard Caddy module. Seems pretty specific to an individual need, so a plugin is probably a better fit for this.

**Comment by muety** [comment]
Just for the record, I created https://github.com/muety/caddy-remote-host.

**Comment by mholt** [comment]
Very cool! Glad to see it on the website too. Nice work.
