### ISSUE TITLE
"server" HTTP header can't be removed when part of the "basicauth" matcher

### ISSUE THREAD

**Issue by eidenschink** [caddyserver/caddy#4366]
caddy 2.4.5, using a Caddyfile

`header -server` is ignored when `basicauth /*` is set. **server: Caddy** is emitted in the response when requesting any ressource (e.g. `curl -I https://example.com`).

Changing path to e.g. `basicauth /foo/*` and requesting **/** removes the header (=respects the header directive removal). A request to **/foo** includes it.

**Comment by Mohammed90** [comment]
Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there.

Please ensure you fill out the template. Thanks for understanding!
