### ISSUE TITLE
Prevent Caddy from adding any headers with reverse_proxy

### ISSUE THREAD

**Issue by justablob** [caddyserver/caddy#4375]
Good Morning

I want to prevent Caddy from adding any headers when using reverse_proxy (specifically X-Forwarded-For). The reason why I want to do this is because I need to use a setup where I have two reverse proxies, and I want to keep the X-Forwarded-For header given by the first proxy without having the second proxy append any value. Security is not an issue as the second proxy only accepts requests from the first one, this is enforced by firewall rules.

**Comment by francislavoie** [comment]
@ledlamp that actually doesn't work, because by that point, the request header will already have been temporarily transformed by `reverse_proxy`, so that becomes a no-op (also FYI that placeholder can be shortened to `{header.X-Forwarded-For}`, see https://caddyserver.com/docs/caddyfile/concepts#placeholders)

I did a bit of experimenting, and this works:

```
@extractXFF header_regexp XFF X-Forwarded-For (.*)
route @extractXFF

reverse_proxy localhost:8882 {
	header_up X-Forwarded-For {re.XFF.1}
}
```

To explain, here we're using a `header_regexp` matcher to extract the value from the incoming `X-Forwarded-For` header, and the capture group result gets stored in the placeholder replacer. We're using a dummy `route` here because matchers need a handler attached to them for them to run, so we can just use `route` as a no-op handler. Then, in `reverse_proxy`, the value from the regexp capture is used to overwrite the value of the header after `reverse_proxy` modified it.
