### ISSUE TITLE
file-server: downloading a directory

### ISSUE THREAD

**Issue by ghost** [caddyserver/caddy#4384]
When directory browsing is enabled provide a way to download an archived (and compressed) copy of a directory in a few popular formats

**Comment by francislavoie** [comment]
You'd probably be better served by using https://github.com/filebrowser/filebrowser for this. You can use Caddy to `reverse_proxy` to it.

I don't think we necessarily want to add more complexity to `file_server`. It's not always desirable to allow downloading entire directories, because that can add significant CPU cost to zip up the directory before sending it to the client. It would _have_ to be opt-in to enable it, which is complicated.

**Comment by frogtile** [comment]
> It would have to be opt-in to enable it, which is complicated

A flag?

**Comment by francislavoie** [comment]
Yes, but a flag that we would have to check in many different places, including the `browse` template. Better to keep it simple.

**Comment by mholt** [comment]
This was already thoroughly proposed and discussed over in https://github.com/caddyserver/caddy/pull/2830
