### ISSUE TITLE
2.4.6: caddyfile with brackets can not be formatted

### ISSUE THREAD

**Issue by 12f23eddde** [caddyserver/caddy#4416]
Hi There :) I'm running caddy with docker. After a version update to v2.4.6, My configuration no longer works.

My caddy version:
```
$ caddy version
v2.4.6 h1:HGkGICFGvyrodcqOOclHKfvJC0qTU7vny/7FhYp9hNw=
```

runtime environment:
Ubuntu 20.04 LTS
an oracle VPS (ampere  arm64 processor)

a simple config for replication:
```
localhost:2016 {
	respond "Goodbye, world!"
}
```

run the following command
```
docker run --rm -v `realpath .`/test.caddyfile:/etc/caddy/Caddyfile caddy
```

caddy v2.4.6 gave me this error:
```
{"level":"warn","ts":1636742970.6282396,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":1}
```

However, with version v2.2.1:
```
{"level":"info","ts":1636743148.6654737,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
```

Is it something with my configuration or a regression bug with caddy (I hope not)?

**Comment by francislavoie** [comment]
The `fmt` warning was only added in v2.3.0 I believe.

All this warning is saying is that we recommend you run `caddy fmt` on your config to clean up the syntax. It's not fool-proof, but it's a suggestion that maybe you should run it so that it has more consistent style.

> My configuration no longer works.

What do you mean? What no longer works?

Warnings are not errors, they're just suggestions that something _might_ be wrong, but they can generally be ignored.

**Comment by 12f23eddde** [comment]
Thank you for your response! Well, it is something with my configuration generator... Caddy runs again after a quick fix, so you may close this issue. 
This message can be a little misleading for newcomers (I thought caddyfile adapter was not parsing my config when troubleshooting), would something like "Format your config with `caddy fmt` for a more consistent style" be better?
