### ISSUE TITLE
backend weight and backup option

### ISSUE THREAD

**Issue by dazoot** [caddyserver/caddy#4446]
In nginx / haproxy i can set `weight` for specific backends and `backup` (stand by failover) options.
Would love to have this in caddy too.

**Comment by francislavoie** [comment]
We're working on a rewrite of how upstreams are configured, and having weights is planned (because it'll support using SRV lookups for configuring upstreams, which has weights).

For `backup`, you can already do this, essentially, by using `lb_policy first` and enabling health checks so that the primary upstream is marked as unhealthy, which would trigger falling back to the next upstream.

**Comment by mholt** [comment]
SRV upstreams implemented in #4470 now honor the weight (and priority) fields of SRV records, which should do what you need.

If not, feel free to reopen this issue and explain more specifically what is required. Thanks!
