### ISSUE TITLE
v2.4.6 broke go install because "The go.mod file for the module providing named packages contains one or more replace directives"

### ISSUE THREAD

**Issue by gedw99** [caddyserver/caddy#4474]
v2.4.5 installs fine.

v2.4.6, which is also latest, fails due to replace directives

## reproduction

````

go install github.com/caddyserver/caddy/v2/cmd/caddy@v2.4.5

go install github.com/caddyserver/caddy/v2/cmd/caddy@latest
go install: github.com/caddyserver/caddy/v2/cmd/caddy@latest (in github.com/caddyserver/caddy/v2@v2.4.6):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.

go install github.com/caddyserver/caddy/v2/cmd/caddy@v2.4.6
go install: github.com/caddyserver/caddy/v2/cmd/caddy@v2.4.6 (in github.com/caddyserver/caddy/v2@v2.4.6):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.

````

## nature of bug

dependency and versions to do with **promtpui** and **juju**.

https://github.com/caddyserver/caddy/blob/master/go.mod#L37

## workaround

Looks like this will eventually be fixed. Will use older version for now.

**Comment by francislavoie** [comment]
Hmm. I don't think we generally recommend using `go install`, in favor of using `go build` (see the README) or `xcaddy` for building, or downloading a release from github or the https://caddyserver.com/download page, or via a package manager https://caddyserver.com/docs/install. I'm not sure this is too big a deal.

Since https://github.com/manifoldco/promptui/releases/tag/v0.9.0 is now released, we'll be able to remove the `replace` once the go.mod is updated upstream https://github.com/smallstep/certificates/pull/728#discussion_r766486606

**Comment by gedw99** [comment]
Thanks @francislavoie for super quick fix 

it used in the provisioning bootstrapper to bare metal servers which only have golang I stalled
