### ISSUE TITLE
Need help setting up a simple file server

### ISSUE THREAD

**Issue by HeCorr** [caddyserver/caddy#4483]
Hello, for some reason my configuration is not working at all and I don't know what to do. I tried everything.

Here's my Caddyfile:
```
:80 {
        file_server /files/public/* browse {
                root    /var/files/public
        }
        file_server /files/private/* {
                root    /var/files/private
        }
}
```

I expected it to work but both `http://<server-ip>/files/public` and `http://<server-ip>/files/private` give me status 200 and a blank page.

The folders do exist, and I even set the permissions to 777 to make sure, but still nothing.
![image](https://user-images.githubusercontent.com/75134774/146432063-0766deb2-7410-45a2-b699-b0ba892ad024.png)

If I run this config it does work:
```
:80 {
        root * /files/public
        file_server /files/public/* browse
}
```
But I need more than one file server, and at a specific path, not /.

Am I doing something wrong?

**Comment by HeCorr** [comment]
also, I have a file at `/var/files/public` and when accessing it directly I'm getting a 404.

**Comment by mholt** [comment]
Your request path `/files/public` does not match `/files/public/*` -- notice the trailing slash in your config. You'll need to make the request to `/files/public/`.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question. The Help category in the forum even provides a template you can fill out.

**Comment by HeCorr** [comment]
After a **lot** of research, I figured it out. It seems that you have to strip the prefix for it to work, similar to Go http routes.

```
rewrite /files/public /files/public/

handle /files/public/* {
        uri strip_prefix /files/public
        file_server {
                browse
                root /var/files/public
        }
}
```

It was probably looking for `/var/files/public/files/public` or something but I don't know how to debug that.

[Useful link](https://caddy.community/t/file-server-basics/8843)
