### ISSUE TITLE
how to change the port 2019

### ISSUE THREAD

**Issue by Yuanyp8** [caddyserver/caddy#4489]
the 2019 port  will be listened by caddy's api , but another service alreay bind in 2019, how to change the candy api 's port by caddyfile

**Comment by mohammed90** [comment]
You can use the [`admin`](https://caddyserver.com/docs/caddyfile/options#admin) global option of the Caddyfile.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. Please ask your question there the next time, and thanks for understanding!
