### ISSUE TITLE
The product kinda sucks

### ISSUE THREAD

**Issue by travisjroark** [caddyserver/caddy#4492]
I have be honest, this is so frustrating to figure. I've plugged your own examples from the Caddy2 docs on your site and those don't even work. 

For instance 

reverse_proxy https://example.com {
	header_up Host {upstream_hostport}
	header_up X-Forwarded-Host {host}
}

Caddy then says "run: adapting config using caddyfile: Caddyfile:8: unrecognized directive: header_up"

**Comment by travisjroark** [comment]
And another straight from your side

log {
	output file /var/log/access.log {
		roll_size 1gb
		roll_keep 5
		roll_keep_for 720h
	}
}

run: adapting config using caddyfile: Caddyfile:22: unrecognized directive: output

**Comment by mohammed90** [comment]
Thank you for the constructive feedback. The examples on the pages of the directives are examples of the directive usage within a site block, not as standalone full-fledged config. 


If you had gone through the **Tutorials** list of pages in the navigation list, you wouldn't have had the frustrating experience. I recommend you read and work your way through those, then you should go through the [**Concepts** page](https://caddyserver.com/docs/caddyfile/concepts) of the Caddyfile documentation to understand the necessity of having directives nested inside site blocks.

This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
