### ISSUE TITLE
SIGSEGV in sendClientCertificate

### ISSUE THREAD

**Issue by hntrmrrs** [caddyserver/caddy#4509]
When using Caddy to reverse proxy a connection using mTLS with ACME-issued certificates, I've encountered a troubling segfault.

This machine (`ingress-001.gwar`) also has DNS record `ingress.gwar` which wants to reverse proxy all requests to `service1.gwar:4601`. `service1` requires Caddy to use a client cert issued by its trusty ca (`ca.gwar`). If `ingress-001` tries to use the same cert for client auth as it uses for serving on port 443, I get the segfault.

If I remove `tls_client_auth`, make a request (thereby getting the ACME cert issued), and then add `tls_client_auth` back, it works without issue (I haven't waited for certificate renewal yet to confirm if it continues working--certs in this test env have a ~240h expiry).

`Caddyfile`:

```
{
  email acme@mail.gwar
  acme_ca https://ca.gwar/acme/acme/directory
  acme_ca_root /opt/certs/root_ca.crt
  cert_issuer acme
}

ingress-001.gwar:443 {
  respond 404
}

ingress.gwar:443 {
  reverse_proxy {
    to https://service1.gwar:4601
    health_uri /u/up
    transport http {
      tls_client_auth ingress.gwar
    }
  }
}
```

Syslog:

```
Jan  1 00:00:00 ingress caddy[101]: {"level":"info","ts":1640995200.408815,"msg":"serving initial configuration"}
Jan  1 00:00:00 ingress caddy[101]: {"level":"info","ts":1640995200.4100556,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/var/lib/caddy/.local/share/caddy"}
Jan  1 00:00:00 ingress caddy[101]: {"level":"info","ts":1640995200.4105682,"logger":"tls","msg":"finished cleaning storage units"}
Jan  1 00:00:00 ingress caddy[101]: {"level":"info","ts":1640995200.4106896,"logger":"tls.obtain","msg":"lock acquired","identifier":"ingress.gwar"}
Jan  1 00:00:00 ingress caddy[101]: {"level":"info","ts":1640995200.4116905,"logger":"tls.issuance.acme","msg":"waiting on internal rate limiter","identifiers":["ingress.gwar"],"ca":"https://ca.gwar/acme/acme/directory","account":"acme@mail.gwar"}
Jan  1 00:00:00 ingress caddy[101]: {"level":"info","ts":1640995200.4118679,"logger":"tls.issuance.acme","msg":"done waiting on internal rate limiter","identifiers":["ingress.gwar"],"ca":"https://ca.gwar/acme/acme/directory","account":"acme@mail.gwar"}
Jan  1 00:00:00 ingress caddy[101]: panic: runtime error: invalid memory address or nil pointer dereference
Jan  1 00:00:00 ingress caddy[101]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x61fe54]
Jan  1 00:00:00 ingress caddy[101]: goroutine 55 [running]:
Jan  1 00:00:00 ingress caddy[101]: crypto/tls.(*clientHandshakeStateTLS13).sendClientCertificate(0xc000517d98)
Jan  1 00:00:00 ingress caddy[101]: #011crypto/tls/handshake_client_tls13.go:562 +0x134
Jan  1 00:00:00 ingress caddy[101]: crypto/tls.(*clientHandshakeStateTLS13).handshake(0xc000517d98)
Jan  1 00:00:00 ingress caddy[101]: #011crypto/tls/handshake_client_tls13.go:93 +0x205
Jan  1 00:00:00 ingress caddy[101]: crypto/tls.(*Conn).clientHandshake(0xc000252a80, {0x1943e30, 0xc000409980})
Jan  1 00:00:00 ingress caddy[101]: #011crypto/tls/handshake_client.go:219 +0x585
Jan  1 00:00:00 ingress caddy[101]: crypto/tls.(*Conn).handshakeContext(0xc000252a80, {0x1943ea0, 0xc0001ce1e0})
Jan  1 00:00:00 ingress caddy[101]: #011crypto/tls/conn.go:1445 +0x3d1
```

I'm new to reading Caddy source, so I haven't really gotten to the bottom of what might be causing this, but I'll add comments as I figure out more.

Thanks!

**Comment by francislavoie** [comment]
The segfault happens inside the Go stdlib.

What I'm getting from this is that the cert on the first load ends up being nil because it doesn't exist yet, and it never gets set on the proxy transport if issuance happens asynchronously (the proxy never gets a chance to react after the cert is issued). Kinda tricky.

Might be possible to detect a nil cert in this situation at runtime (before trying to proxy the request) and set it on the transport if it was issued.

I think @mholt might have a better idea here.

**Comment by mholt** [comment]
Hmm, is that the full log? Stack trace seems truncated. But yeah, I guess I'm inclined to agree with Francis that the cert just isn't available yet and we should check for that case. Did a request come in and that's when the segfault happened?

**Comment by hntrmrrs** [comment]
Yeah it was the full stack trace in syslog. The segfault actually happened before I opened the inbound 443 port, so my best guess at the moment is perhaps the health check? I'll try to put together a minimal reproduction.

**Comment by mholt** [comment]
Ah, yeah health checks might do it. Thanks

**Comment by francislavoie** [comment]
@hntrmrrs were you able to find time to dig deeper on this?

**Comment by francislavoie** [comment]
Okay I think I see the problem. So the relevant code for this is here:

https://github.com/caddyserver/caddy/blob/741b0502ee7cb0ecbd6dd0517c4f186729f52718/modules/caddyhttp/reverseproxy/httptransport.go#L358-L368

So basically this set up a custom callback to be used when the HTTP transport wants to grab a client cert to use for the connection.

I think what ends up happening is `return nil, nil` happens, essentially. This is because `var err error` defines `err` as `nil` (obviously) and if no cert is found (because automation didn't finish yet) then it runs past the loop and lands on the last line, `return nil, err`.

Looking at the stdlib code that calls this, it checks that `err != nil` and uses the left return value (the certificate) if so. So then yeah, it blows up because it tries to use a nil cert.

So I think we just need to put a `if err == nil` check just before that last return and set a default error. Simple.

But I'm not sure how the error should read. WDYT @mholt?

**Comment by hntrmrrs** [comment]
Sorry I haven't had as much time to investigate this as I would have liked!

I'll try your patch, Francis, and get back to you.

**Comment by mholt** [comment]
@francislavoie Yeah, that error looks good. I merged the change. @hntrmrrs Would still appreciate a confirmation that this works for you if you could, please :)
