### ISSUE TITLE
Add support for checking for file existence in config

### ISSUE THREAD

**Issue by charlax** [caddyserver/caddy#4540]
I have the following use case: on some deployments, I have already existing TLS certificates, while on others I don't. I'd like caddy to use them only if they are here, and otherwise use letsencrypt.

Something like that (this is just an example)?

```
if -d /certs/cert.pem {
  tls /certs/cert.pem /certs/key.pem
}
```

For inspiration, it seems nginx supports `if` with `-f` operator: http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#if

I saw this https://caddy.community/t/testing-file-existence/3431 but the link to the PR is dead...

Thanks!

**Comment by francislavoie** [comment]
Caddy's _actual_ config language is JSON. Implementing `if` for JSON would essentially be impossible, because it has a very specific structure. It would add _a lot_ of complexity to the system.

I think this is something you should do by performing your own scripting in front of your deployments to generate your config.

Or another option is to use environment variables to control Caddy's config. You could an env var to `CADDY_TLS_MODE="tls /certs/cert.pem /certs/key.pem"` or `CADDY_TLS_MODE=` for empty, then use it in your Caddyfile like this: `{$CADDY_TLS_MODE}`. See the docs: https://caddyserver.com/docs/caddyfile/concepts#environment-variables

**Comment by charlax** [comment]
👍  awesome seems to be working fine!

**Comment by mholt** [comment]
Well, if all you're going for is knowing whether a file exists at HTTP-request-time, then you probably want the `file` matcher: https://caddyserver.com/docs/caddyfile/matchers#file
