### ISSUE TITLE
What io model used in caddy？What mechanism of thread/goroutine to process a request?

### ISSUE THREAD

**Issue by victory460** [caddyserver/caddy#4547]
**It is a great server.**  Can answer a few of my questions briefly? I didn't find it in the documentation. Thanks a lot.
- What io model used in caddy？

- What mechanism of thread/goroutine to process a request?

- If we want to improve performance, what can we do？change a config or something.

**Comment by francislavoie** [comment]
> What io model used in caddy?

I'm not sure what IO you're asking about specifically. Please be more specific.

> What mechanism of thread/goroutine to process a request?

Each request spawns a goroutine to handle it. Depending on additional config, other goroutines may be spawned off that request in various conditions

> If we want to improve performance, what can we do？change a config or something.

Are you seeing any specific bottlenecks? Do some benchmarking and try to figure out what's taking the most amount of time. We can't really answer that question because we don't know your config, nor do we know the performance characteristics of what you're doing with Caddy (if you're proxying, the bottleneck will almost always be the upstream application).

**Comment by victory460** [comment]
> > What io model used in caddy?
> 
> I'm not sure what IO you're asking about specifically. Please be more specific.
> 


Thanks a lot. I want to ask that io multiplexing technology used in caddy such as select、poll or epoll ？

**Comment by mholt** [comment]
Go uses epoll and kqueue from the kernel. https://go.dev/src/runtime/netpoll_epoll.go

**Comment by victory460** [comment]
> > What mechanism of thread/goroutine to process a request?
> 
> Each request spawns a goroutine to handle it. Depending on additional config, other goroutines may be spawned off that request in various conditions
> 

What additional config may to change goroutines, can give some reference doc? Thanks a lot.

**Comment by francislavoie** [comment]
Active/passive health checking in the reverse proxy module, request/response streaming (websockets mainly), TLS maintenance (issuing certs on the fly if on-demand is enabled, etc)
