### ISSUE TITLE
question: how to enable custom domain https

### ISSUE THREAD

**Issue by chenjiangui** [caddyserver/caddy#4590]
I define a custom domain to 127.0.0.1 in hosts file. 
![image](https://user-images.githubusercontent.com/18565140/154838082-6af40ca5-6494-4cc9-a9fe-dc898be4736b.png)
 my caddyfile:
![image](https://user-images.githubusercontent.com/18565140/154838121-a185527e-4dd3-4f77-86cf-c04dfd171a39.png)
run info:
![image](https://user-images.githubusercontent.com/18565140/154838156-a73f78f8-6972-4a3d-b784-80c0f3a2e2ab.png)

i only need custom domain https, how can i do

**Comment by mohammed90** [comment]
Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
