### ISSUE TITLE
golang http/3 webtransport server and example

### ISSUE THREAD

**Issue by gedw99** [caddyserver/caddy#4600]
This will be useful to caddy and caddy community i think...

https://github.com/adriancable/webtransport-go

and 

https://github.com/adriancable/webtransport-go-example

**Comment by francislavoie** [comment]
Hmm, I'm not sure I see how this could be integrated with Caddy, nor how it would be useful. It requires using that project's `Server` to work, which is probably a no-go for integrating with Caddy at this time (it would probably break the HTTP/3 server we have now). And it's not useful unless specific handlers are written, which would require Go code anyways, so that would be best left for plugins.

Since there's not really anything actionable at this time, I'll close this issue. But if you have a specific plan to suggest where this could be integrated in some way, we could reopen it for discussion.
