### ISSUE TITLE
i cannot run caddy 

### ISSUE THREAD

**Issue by srinivas10247** [caddyserver/caddy#4609]
i am geting this

2022/03/02 12:59:38.185	INFO	admin	admin endpoint started	{"address": "tcp/localhost:2019", "enforce_origin": false, "origins": ["127.0.0.1:2019", "localhost:2019", "[::1]:2019"]}
2022/03/02 12:59:38.185	INFO	serving initial configuration
Successfully started Caddy (pid=10804) - Caddy is running in the background

but in /etc/caddy/caddyfile there is 80

localhost:80 {

	# Set this path to your site's directory.
	root * /usr/share/caddy

	# Enable the static file server.
	file_server

	# Another common task is to set up a reverse proxy:
	# reverse_proxy localhost:8080

	# Or serve a PHP site through php-fpm:
	# php_fastcgi localhost:9000
}

# Refer to the Caddy docs for more information:
# https://caddyserver.com/docs/caddyfile

but still caddy is trying to use 2019.  (http://localhost:80 and http://127.0.0.1:80 not working)

and moreover 2019 port also not working (http://localhost:2019 and http://127.0.0.1:2019 )

wht should i do?

**Comment by mohammed90** [comment]
Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

**Comment by francislavoie** [comment]
You probably have a 2nd instance of Caddy running already. Caddy tries to bind to port 2019 which is its admin API endpoint.

As Mohammed said though, if you need further help, please ask on the forums.
