### ISSUE TITLE
Feature request: Support sockets in reverse-proxy cli

### ISSUE THREAD

**Issue by Ckarles** [caddyserver/caddy#4611]
Reverse proxy support sockets in its configuration but not when used in commandline:

```
$ caddy reverse-proxy -from sandbox-rabbitmq -to unix//tmp/sandbox-rabbitmq.sock
reverse-proxy: paths are not allowed: unix//tmp/sandbox-rabbitmq.sock
```

Would be amazing to support it in commandline too.

**Comment by Ckarles** [comment]
I would contribute to this if I can find the time. On that matter I am wondering, why is there a parsing made in the cli-relted code and not from the

**Comment by Ckarles** [comment]
I've had a quick look over the code and it seems the parsing is made specifically for the cli, do we have split code there ? Would that be possible / acceptable, to use the config files parsers ?

**Comment by francislavoie** [comment]
This required a bit of work to consolidate the parsing logic to make this work, but PR #4616 should now let any upstream address that works in the Caddyfile to work for the command (but the command doesn't support `h2c://` because I didn't feel like spending the effort on that unless someone specifically needs it... and I doubt they would, just use the Caddyfile for that, it's a more advanced usecase anyways)
