### ISSUE TITLE
add available logger names to the documentation 

### ISSUE THREAD

**Issue by ajmandourah** [caddyserver/caddy#4617]
New to Caddy here and I must say its really nice and easy to configure in comparisoin to other tools .

one thing I notice that caddy does not do access logs per default . I wanted to configure a global logging for access ( I know you can do it per site) and in the documentation its written that you can cinfigure it in global with the log [name] {} but no mentions of what are name is and what is my options. with try and error i managed to configure it like with log "access" {} to get the logging for everything, 
It would be nice to mention a list for all possible logging and if you can do global access log for every site in separate files for example. 
my use case is to use it for crowdsec.

**Comment by francislavoie** [comment]
You _must_ enable access logging per-site, otherwise access logs won't appear at all. They're off by default, and the `log` global options alone cannot turn it on.

The `name` in global logging has no special meaning other than the name `default` which is the one that's enabled by default and will write to stdout/stderr by default; you can modify that logger by either omitting the name or specifying `default` explicitly, if you want to send the logs elsewhere (a file maybe) or change the format, etc.

I hear you that the current docs might not be clear enough about that, but the docs aren't incorrect, they don't say that you _can_ configure access logs from global options.

**Comment by ajmandourah** [comment]
Thanks for getting back fast. I understand now. I don't know if its asked before but is there any option to enable access logs for all sites. having the option to choose seems like a good idea. 

great work btw :)

**Comment by mholt** [comment]
Enabling access logs for all sites is trivial in the JSON config -- should just be 1 line -- that doesn't abstract well to the Caddyfile. Just FYI. Can probably be done, but introduces something called cascading, like what CSS has, and we don't think cascading is a good model for the Caddyfile. You can use `import` though, to share commonalities across sites.

**Comment by francislavoie** [comment]
> I don't know if its asked before but is there any option to enable access logs for all sites.

No, but you can just add `log` to each site, or set up a snippet which encapsulates your `log` directive and its options which you can `import` into each site.

See https://caddyserver.com/docs/caddyfile/concepts#snippets

There's no plans to have an option to enable it for all sites. It's best to be specific in the Caddyfile.

**Comment by ajmandourah** [comment]
Thanks for clarifying. I think I will try to read more about the json config. will close this
