### ISSUE TITLE
https will still be enabled with `auto_https off`

### ISSUE THREAD

**Issue by lonble** [caddyserver/caddy#4632]
Caddyfile:
```
{
    auto_https off
}

127.0.0.1 {
    respond "hello"
}
```
```
$ ss -lnt
State   Recv-Q   Send-Q     Local Address:Port      Peer Address:Port  Process  
LISTEN  0        4096           127.0.0.1:2019           0.0.0.0:*              
LISTEN  0        4096                   *:443                  *:*              
```

**Comment by mholt** [comment]
That is expected.

443 is the default port when using the Caddyfile: https://caddyserver.com/docs/v2-upgrade#https-and-ports

> Caddy 2's default port is :443

(We could probably make this clear in the Caddyfile docs.)

Since auto HTTPS is off, you'll notice that Caddy doesn't have a certificate to use when connecting to that site.
