### ISSUE TITLE
Support template string for convenience

### ISSUE THREAD

**Issue by damnever** [caddyserver/caddy#4651]
[templates](https://caddyserver.com/docs/modules/http.handlers.templates) only support files. A function like the below example could make the configuration much simpler:
```json
{
    "handler": "template_string", 
    "template": "{{.Req.Header.Get \"User-Agent\"}}"
}
```

**Comment by mholt** [comment]
@damnever Templates supports any content origin: reverse proxy, static files, or hard-coded responses.

The templates module does not itself originate any content. It only evaluates templates from the response written by a handler downstream in the HTTP route.

So in your case:

```json
[
    {
        "handler": "templates"
    },
    {
        "handler": "static_response",
        "body": {{.Req.Header.Get \"User-Agent\"}}"
    }
]
```

Although, you don't need templates for that particular value, it turns out:

```json
[
    {
        "handler": "static_response",
        "body": {http.request.header.User-Agent}"
    }
]
```

**Comment by damnever** [comment]
Thanks!

I keep forgetting about the flow https://caddyserver.com/docs/json/apps/http/servers/routes/handle/

**Comment by mholt** [comment]
Yeah, no worries. I wish there were more examples in our [wiki](https://caddy.community/c/wiki/13) -- it's a community effort so maybe you could write about this to help others!

**Comment by damnever** [comment]
A note here: static_response does not provide a default Content-Type header.

I will try to add this example later.
