### ISSUE TITLE
Minimal windows service stub

### ISSUE THREAD

**Issue by ealib** [caddyserver/caddy#4670]
It would be a nice addition to integrate [Minimal windows service stub](https://pkg.go.dev/github.com/kardianos/minwinsvc) in Caddy (built for Windows).

At the moment, it is necessary to use for example NSSM to install Caddy as a service on Windows.

See how it becomes much more natural to [install the service and remove it in the case of another project (Gitea) with the Windows tools](https://docs.gitea.io/en-us/windows-service/).

**Comment by francislavoie** [comment]
FYI, we have instructions for running Caddy as a service here: https://caddyserver.com/docs/running#windows-service

**Comment by ealib** [comment]
> FYI, we have instructions for running Caddy as a service here: https://caddyserver.com/docs/running#windows-service

Thanks. I didn't know *WinSW*.

Even under NSSM, however, Caddy runs without problems on various Windows installations I have done.

The real problem behind this issue is the extra step that requires the installation of third-party software to make Caddy work as a service.

**Comment by francislavoie** [comment]
We're generally wary of adding new dependencies to Caddy, for various reasons.

I think we if we add this, we'd likely just copy code into this project (with attribution of course, as [their licence](https://github.com/kardianos/minwinsvc/blob/master/LICENSE) requires) to avoid the added dependency.

I have no other objections, really. Seems pretty harmless to add otherwise.

Thinking we could put it alongside https://github.com/caddyserver/caddy/tree/master/notify (and maybe rename that package from `notify` to `platform`?)

PRs welcome!

**Comment by WingLim** [comment]
I have did some research and make an implement for this in: https://github.com/WingLim/caddy/blob/dev/windows-service/notify/notify_windows.go

But there is a problem, when using `service.msc` to stop service, it can not stop gracefully.
The code in here:
https://github.com/WingLim/caddy/blob/dc0b52111c13ecb3ec9eaa3583fe76b8ac62a04a/notify/notify_windows.go#L40

Do you guys have any idea for it?

**Comment by francislavoie** [comment]
See sigtrap.go which has the shutdown logic

**Comment by mholt** [comment]
Thanks for the PR! Looking forward to merging it soon.

**Comment by ueffel** [comment]
As applications that run as a windows service have no usable stdout and stderr, is there a way to redirect stdout in caddy?
For stderr one could use the global `log directive` like this, I think

```caddy-d
{
	log {
		output file caddy.err
	}
}
```

Is there a way to redirect stdout to a file as well?
