### ISSUE TITLE
Issue with caddy not passing acme challenges

### ISSUE THREAD

**Issue by Father-Dimi** [caddyserver/caddy#4673]
heres my caddy config

'cracken.duckdns.org {
	encode gzip
		log {
			output file C:\caddy\logs\emby_access.log {
				roll true				# Rotate logs, enabled by default
				roll_size_mb 5			# Set max size 5 MB
				roll_gzip true			# Whether to compress rolled files
				roll_local_time true	# Use localhost time
				roll_keep 2				# Keep at most 2 log files
				roll_keep_days 7		# Keep log files for 7 days 
			}
		}
    reverse_proxy ipaddy:8096 
}
)'

but when running 'sudo caddy start' i get this error
https://pastebin.com/giduCR4w

**Comment by Father-Dimi** [comment]
also, im obviouslyusing duckdns.org, it is pointed at my public ip adress, port 80 and 443 are forwarded aswell

**Comment by Father-Dimi** [comment]
i tried this method on my main pc and it works perfectly fine and going to cracken.duckdns.org takes me to the jellyfin on my main pc

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! So far, this doesn't look like a bug in Caddy. It looks more like a question about how to use Caddy rather than a bug report or feature request.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!
