### ISSUE TITLE
How can CADdy enable HTTPS in Windows?

### ISSUE THREAD

**Issue by nangdie** [caddyserver/caddy#4697]
I tried the site many times, but it didn't work; For example, the IP address of the local nodeJS service is localhost:3001 and my domain name is abc.cn

Can you give me a code reference that can open HTTPS?

use Caddyfile ？

**Comment by mohammed90** [comment]
Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
