### ISSUE TITLE
Caddy open bug vulnerability fixed but not announced

### ISSUE THREAD

**Issue by divine** [caddyserver/caddy#4713]
Hello,

Sorry to bump this [fixed issue](https://caddy.community/t/php-fastcgi-phishing-redirection/14542) in #4499, but got aware of this security hole after the report.

May I know why this hasn't been made aware publicly (noted, announced) that the current stable version of Caddy is vulnerable to open redirect vulnerability when used with PHP for at least 3 months after that PR was merged?

Even [v2.5.0-rc.1](https://github.com/caddyserver/caddy/releases/tag/v2.5.0-rc.1) doesn't contain warning about this, only:
https://github.com/caddyserver/caddy/commit/3fe2c73dd04f7769a9d9673236cb94b79ac45659 caddyhttp: Fix MatchPath sanitizing (https://github.com/caddyserver/caddy/pull/4499).

So there are a few thousand vulnerable sites that use Caddy with PHP, quite sad honestly.

Thanks!

**Comment by mholt** [comment]
I don't really know. One reason could be that I was busy preparing to get married at the time and it's likely I couldn't keep track of everything. I've definitely been more scatter-brained during this life transition.

You can watch/subscribe to the project and see the updates in real-time, rather than waiting for a specific kind of release. What kind of announcement would you like?

If you're watching the project because immediate bug fixes are important to you, you'd have already downloaded the latest builds. CI builds Caddy artifacts on every commit, or you could use `xcaddy`, or clone it down yourself. (This is open source, after all.)

In general, we don't really tailor our release schedule to any one consumer, unless we have high-tier sponsors that fund specific release requirements. The vast majority of our users need something stable that "just works" so we try to be careful to release only when we're confident the software is stable and reliable.

Let's be clear: this bug is not known to make the server vulnerable to security exploits. It only affects clients that send garbage input in the first place, and then the clients have to also blindly follow redirects to different hosts resulting from the garbage they sent the server ("GIGO"). That alone is not a "security hole", similar to how links or QR codes themselves are not security vulnerabilities: it's what you do afterwards of your own accord that can cause problems, regardless of how you got there. (I did my masters thesis on this.) I have not been shown any particular exploit using this bug where a threat actor penetrates a client without also manipulating the client out-of-band (which they don't even need a server for anyway) or taking advantage of client functionality that makes itself vulnerable; i.e. any known exploit is orthogonal to this bug and does not affect the servers. I would be very interested, however, if you could pop a shell on either the server or client and run arbitrary code, steal keys, or access restricted memory using this bug.

**Comment by divine** [comment]
Sorry for my "bad" tone, I just wanted to know that the issue with open redirect has been fixed, it's pretty important overall, isn't it?

I can understand this is open source but at least even "small and not important" security issues should be noted, that this has been fixed?

If you don't count this as a security issue, then it's another story, sorry for taking your time, and thanks for the Caddy using it since LET where you've introduced it...

Thanks!
