### ISSUE TITLE
Setting global request_body directive

### ISSUE THREAD

**Issue by colorninja** [caddyserver/caddy#4714]
Hi, I'm trying out the caddy on one of my servers, which has about 30 small websites hosted. Needless to say, I need a good reverse proxy to split the traffic.

I am using the following docker image to help me manage the configs separately: [lucaslorentz/caddy-docker-proxy](https://github.com/lucaslorentz/caddy-docker-proxy)

I am looking for a way to set the max_size in request_body globally and only override it for 1 - 2 site blocks. I've tried to do so and using the following config produces an error:
```
[ERROR]  Removing invalid block: Caddyfile:5: unrecognized global option: request_body\n{\n\tauto_https off\n\tdebug\n\temail email@example.com\n\trequest_body {\n\t\tmax_size 8MB\n\t}\n}\n\n
```

Is this supported at all and if not, does it make sense to implement it?

Edit: Is proxying streamed to the destination? If it is, then limits could be implemented on the service side. If client sends HTTP request with 1TB size, would Caddy have to read all of it before proxying or just the headers?

**Comment by mholt** [comment]
The Caddyfile's focus is simplicity, so while we often get requests for "set globally, override locally," we generally decline because it adds a lot of complexity and confusion.

So, if you want that capability, you can easily do that with [Caddy's native JSON config](https://caddyserver.com/docs/json/). That'd be my first recommendation.

If you insist on using the Caddyfile, my second recommendation is to use snippets to reuse config: https://caddyserver.com/docs/caddyfile/concepts#snippets

Otherwise, maybe a not+host matcher can be used to exclude the request_body directive for select hosts.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. If more help is needed, we hope you'll ask your next question there. Thanks!

**Comment by mholt** [comment]
> Is proxying streamed to the destination?

The request body is, yes.

> If client sends HTTP request with 1TB size, would Caddy have to read all of it before proxying or just the headers?

Just headers (which you can also [limit the size of](https://caddyserver.com/docs/caddyfile/options#max-header-size).
