### ISSUE TITLE
Letsencrypt certificate expiration notice

### ISSUE THREAD

**Issue by CaptainFalcon92** [caddyserver/caddy#4725]
I setup a couple domain on Caddy - super easy. So first i'd like to say thanks for that 👍 
I got certificates established immediately, as expected.

But for several days now i got imminent expiration notice from letsencrypt. It seem like caddy is not going to renew the certificates.

I though according to documentation it was suppose to auto-renew. 
Does anyone know what it is ?

I dug a bit more the doc and read about "_On-Demand TLS_". I'm guessing certs will only be renewed if requested while expired ?
Although i made nothing to specifically turn this feature on.

Thank you 🙂

**Comment by francislavoie** [comment]
It's likely because your current cert was issued by ZeroSSL _instead_ of Let's Encrypt; Caddy has issuer fallback, so if it has a problem with one issuer, it'll try the other (but it'll prefer to reuse the same one if possible).

This means that any expiry emails from issuers might be a lie, because they can't know that you might have a valid certificate from a _different_ issuer instead.

Take a look at your current certificate's details (you can do this with any browser, click the 🔒 icon and inspect it, look at who the issuer is, and when your cert expires).

Since this isn't an actionable, I'm closing this. For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by CaptainFalcon92** [comment]
Interesting.

Indeed cert is valid 'til July, provided by LE themselves. I guess they lost track of a previous cert i'm annoyingly getting notified for.
Any option to turn later notice off ? (a flag for the certbot maybe).
I'm surprised caddy had my email to communicate to LE in the first place.

Thank you for educating me, good day to you.

**Comment by francislavoie** [comment]
> a flag for the certbot maybe

FWIW, we don't use certbot, that's a different piece of software. Under the hood, Caddy uses [CertMagic](https://github.com/caddyserver/certmagic)

> Any option to turn later notice off ?

I guess you could click unsubscribe in the email? I forget if their emails allow you to do that.

> I'm surprised caddy had my email to communicate to LE in the first place.

Did you not put it in your config? 🤔
