### ISSUE TITLE
Figure out why Caddy isn't using sendfile

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#4731]
Context:
- https://twitter.com/WBaryluk/status/1519019831651180544
- https://twitter.com/WBaryluk/status/1519019570140434432

Caddy should use Unix sendfile when there's no TLS and no compression. (And even for TLS, we should look into kTLS. But maybe unsafe, sigh.)

**Comment by francislavoie** [comment]
Found this: https://www.reddit.com/r/golang/comments/b9ewko/comment/hphp294/?utm_source=reddit&utm_medium=web2x&context=3

(Sorry @mohammed90 😅) - We use `http.ServeContent` which calls `io.CopyN`, and that wraps the `src Reader` in a `io.LimitedReader` which _isn't_ an `*os.File`, so `sendfile` doesn't trigger 😢

**Comment by francislavoie** [comment]
There was an attempt to fix it here many years ago, went inactive: https://go-review.googlesource.com/c/go/+/7893/3

**Comment by flga** [comment]
> so `sendfile` doesn't trigger
It should, ReadFrom will unconditionally* invoke `sendFile` which [unwraps](https://cs.opensource.google/go/go/+/refs/tags/go1.19:src/net/sendfile_linux.go;l=25;bpv=0;bpt=0) the LimitReader.

*However this will only apply if the file is larger than 512 bytes as the first 512 byte chunk is [explicitly handled](https://cs.opensource.google/go/go/+/refs/tags/go1.19:src/net/http/server.go;l=590;bpv=0;bpt=1) before triggering sendfile.

I can reproduce this behaviour with bare net/http so the problem is either in the size of the test files, or something else is missing from the equation.

Looking briefly at the file server I don't see any major red flags that would invalidate this, but it's late I'll have a proper look tomorrow night.

**Comment by mholt** [comment]
@flga Ohh, thank you for looking into this. This kernel stuff goes a little over my head "kerrantly" :upside_down_face:

I don't know how to debug this in Caddy; specifically, I've never used `strace` for anything more complicated than a hello-world-style C program, so maybe having confirmation that sendfile() _isn't_ being called would be a good start.

A test config might look like this:

```
:80

root ./sendfile_test
file_server
```

That's HTTP-only, and no `encode` directive means no compression, so I would expect sendfile to work here.

Or, without using a config file:

```
$ caddy file-server --root ./sendfile_test
```

I would also expect that to use sendfile when serving up files.

It would be absolutely awesome if you had a chance to dig into this and help us figure out how to get sendfile to be used (even on TLS*).

* We might be able to get sendfile working over TLS with a setsockopt() call from [what I've read](https://news.ycombinator.com/item?id=19071698).

**Comment by flga** [comment]
Took a peek during lunch, sendfile is indeed not being called in caddy and the reason is that the response writer received in the file server is not a vanilla http responsewriter, it's an instance of our own ResponseRecorder. This type hides the ReadFrom method from io.Copy so the sendfile behaviour is never even considered. Doing a quick & dirty patch so that it exposes ReadFrom causes sendfile to be used again as expected.

ResponseWriterWrapper suffers from the same issue, it's effectively hiding some upgrade interfaces tho it's not clear to me how impactful that is or if it is even relevant.

Anyway, this was just a quick dirty gut check, I'll need to look at the code a little closer to see where best to spend our efforts.

re TLS: I'm not sure this is worth pursuing, it seems to me we would be fighting against net/http and crypto/tls the whole way so the gains would have to be huge in order to be worth it. A quick search for ktls in the go repo came up with this: https://github.com/golang/go/issues/44506 and a related post from Fillo https://words.filippo.io/playing-with-kernel-tls-in-linux-4-13-and-go/
That said it merits a deeper look, even if it does prove to not be worth it, so I'll try to fit it in soon.

**Comment by mholt** [comment]
D'oh, I totally forgot that we wrap all the ResponseWriters with our own recorder type so that we can provide logging:

https://github.com/caddyserver/caddy/blob/8cc8f9fddd2ea717633528322e1bef938bee2415/modules/caddyhttp/server.go#L221-L223

> Doing a quick & dirty patch so that it exposes ReadFrom causes sendfile to be used again as expected.

That's actually pretty reasonable, I would be happy to review that patch!

> ResponseWriterWrapper suffers from the same issue, it's effectively hiding some upgrade interfaces tho it's not clear to me how impactful that is or if it is even relevant given we support the major ones like Flusher.

I wish I knew a better way to wrap the response writer without having to implement all these interfaces, but clearly we are missing some. Again, I'd be happy to add it there, as the purpose of this wrapper type is to make it function like the underlying type.

Re: kTLS, I'm OK with it if we defer/shelve that for now, but if you feel like hacking on it just to see a PoC, I won't stop you! Depending on how aggregious it is (haha) we might not merge it, but if you want to have some fun then go ahead. If it turns out reasonable maybe we can even merge it.

Thanks for looking into things!

**Comment by stapelberg** [comment]
> I wish I knew a better way to wrap the response writer without having to implement all these interfaces, but clearly we are missing some. Again, I'd be happy to add it there, as the purpose of this wrapper type is to make it function like the underlying type.

You can read more about this problem in https://blog.merovius.de/posts/2017-07-30-the-trouble-with-optional-interfaces/

**Comment by baryluk** [comment]
@flga @mholt Thanks a lot.

@zekjur Should we retest on 25Gbps again with new caddy? :D

**Comment by baryluk** [comment]
@flga @mholt Thanks a lot.

@zekjur @stapelberg  Should we retest on 25Gbps again with new caddy? :D

**Comment by mholt** [comment]
@stapelberg Any latency improvements? Even if it's saturating the network I would expect lower latency (TTFB). Make sure your test payload is large enough too.

**Comment by stapelberg** [comment]
I wouldn’t expect the TTFB to be any lower, as the few buffer allocations should be immeasurably quick. Only if you do larger transfers for longer does it add up.

Did you see any TTFB improvements in your tests? Can you share the payload you used, and with which tool you measured?

**Comment by mholt** [comment]
@stapelberg I did see lower latency, but I was just testing on the loopback interface.

My payload and test procedure was very simple, as documented in the linked PR (#5022) -- you can see charts and stats and program output there!

**Comment by mholt** [comment]
Yeah, I think once you get bandwidth that high, tests like this are a little tricky to find reliable.

Still cool if it's saturating your link though!

**Comment by terrywh** [comment]
still cannot use sendfile() in a http handler:

```
file, _ := os.Open("file")
w.(io.ReaderFrom).ReadFrom(file) // 1. cause: the file will be wrapped in fileWithoutWriteTo
```

```
file, _ := os.Open("file")
file.WriteTo(w) // 2. cause: ResponseRecorder does not implement syscall.Conn  zero_copy_linux.go:126
```

@stapelberg @mholt @flga can any help on how can i streaming a file using sendfile()?

**Comment by mholt** [comment]
@terrywh If you could please open a new issue to report a bug, or use the [forums](https://caddy.community) to request help. Thank you! (We'll need enough code, minimally-reproducible example to recreate the issue.)
