### ISSUE TITLE
Add `protocol_min` and `protocol_max` for reverseproxy transport http

### ISSUE THREAD

**Issue by git001** [caddyserver/caddy#4747]
Based on this question in the community  
https://caddy.community/t/https-backend-suddenly-not-reachable-getting-502-although-site-is-up/15791  
would it be helpful to add the options `protocol_min` and `protocol_max` for the reverseproxy module to the transport protocol http to the tls struct and the MakeTLSClientConfig function?

https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/reverseproxy/httptransport.go#L290
https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/reverseproxy/httptransport.go#L322

I think that some Servers out there are not ready to use only TLS 1.2/1.3 and the options `protocol_min` and `protocol_max` could help the users of caddyserver to move to caddyserver in front of such Servers.
What do you think.

**Comment by mholt** [comment]
Hi there. Thanks for submitting a feature request.

One of the goals and values of the project is to lean on secure protocols only, and to be future-facing, not to be going backwards. The lack of advanced TLS tuning between the reverse proxy and the upstreams is intentional to avoid turning knobs that reduce security.

TLS 1.2 is 14 years old. I don't think we need to cater to broken protocol versions at this point, and it would go against the grain of this project.

(Respectfully closing, but feel free to reply if needed.)
