### ISSUE TITLE
how to redirect from http://example.com:8443 to https://example.com:8443

### ISSUE THREAD

**Issue by morytyann** [caddyserver/caddy#4749]
`
{
    http_port 8180
    https_port 8443
}

http://example.com {
    redir https://{host}:8443
}

https://example.com {
    respond "Hello, world!"
}
`
i try to use matcher protocol=http in https server but it not works, so is there any solution?

**Comment by mohammed90** [comment]
Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
