### ISSUE TITLE
Storage logger leaking sensitive values

### ISSUE THREAD

**Issue by gojihotsauce** [caddyserver/caddy#4780]
I was testing some of the alternate storage backends and ran across something potentially disturbing. When using the https://github.com/ss098/certmagic-s3 module, access and secret keys are required parameters, for example:

```
    "storage": {
        "module": "s3",
        "host": "s3.us-east-2.amazonaws.com",
        "bucket": "my-certificates",
        "access_id": "EXAMPLEFODNN7EXAMPLE",
        "secret_key": "EXAMPLEUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
        "prefix": "certs"
    },
```
During server startup these secrets are logged directly:

```
{"level":"info","ts":1652215226.3952494,"logger":"tls","msg":"cleaning storage unit","description":"{0xc0002355c0 0xc0003ae8f0 s3.us-east-2.amazonaws.com my-certificates EXAMPLEFODNN7EXAMPLE EXAMPLEUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY certs false}"}
```
It looks like this is the culprit:
https://github.com/caddyserver/caddy/blob/d06d0e79f839a26ab2cf81b00ba2d180623c57a9/modules/caddytls/tls.go#L498

Is this intentional behavior? Is it possible to suppress this output or otherwise mask sensitive values?

Thanks!

**Comment by francislavoie** [comment]
The plugin should implement the [`Stringer` interface](https://pkg.go.dev/fmt#Stringer), which would let it control how the struct is serialized as a string.

Caddy needs to convert the struct to a string to use as an ID as a unique key for the storage plugin. The plugin can control what that ID is by being a `Stringer`.

Admittedly, this wasn't well documented, so that's partly our-bad.

Either way, we can't recommend using the S3 plugin, because it doesn't properly implement the locking mechanisms required by the storage interface.
