### ISSUE TITLE
Missing Features of Vars / Globals

### ISSUE THREAD

**Issue by iocron** [caddyserver/caddy#4793]
Is there a reason not to allow variables everywhere (e.g. log)? The example (Option 1.) below results in the error "invalid filename for log file: unrecognized placeholder {myvar}" and Option 2. is not available at all:  

```
example.com {
    vars myvar "test123"

    log {
        # Option 1.: 
        output file /var/www/{myvar}/log/caddy.log # invalid filename for log file: unrecognized placeholder {myvar}

        # Option 2.:
        output file /var/www/{hostname}/log/caddy.log # {host} {hostname} or {domainname} placeholders don't exist at all? (Feature?)
    }
}
```

Feature Request: It would be nice to have variables available in more places (e.g. for easier configuration) and maybe some global variables as well (e.g. hostname or hostname.0, hostname.1, ..).

**Comment by francislavoie** [comment]
The problem is that those variables are defined on individual HTTP requests, but the loggers are provisioned at config startup. There's no way to use request placeholders for filenames. Also, it would be very inefficient, because the file handles would need to be reopened on every request in case the file changes.

Instead, you should use some scripting to process your logs after the fact, outside of Caddy. See https://caddyserver.com/docs/logging which explains Caddy's logging philosophy.
