### ISSUE TITLE
Why caddy is not in official repositories, even in 2022

### ISSUE THREAD

**Issue by gtf35** [caddyserver/caddy#4802]
I discovered this project today and fell in love with him, thank you for your efforts

It is a pity that even in 2022 he is still not in the official repo

I see there are plans to add it to the official repo in 2019 ([link](https://github.com/caddyserver/caddy/issues/2786#issuecomment-538593323))

Are you having any trouble?🤗

In my opinion, I don't want to add any unofficial signatures and repositories, but I really, really want to use this project🤩

**Comment by francislavoie** [comment]
It is in COPR repos for rpm-based distros.

But for deb-based distros, the problem is the requirements for official packages are way too strict and complicated for us to maintain. Caddy is in debian experimental now though (see https://salsa.debian.org/go-team/packages/caddy), but I don't know if it will be continually maintained, and I'd be surprised if it was kept up to date at the same pace we release new versions.

We have no plans to put in more effort in getting it officially packaged ourselves, it's not worth our time and frustration. The CloudSmith repo serves us best because we can push to it automatically from CI, and it's signed by Matt's GPG key so you know it's an official release. And as of a few days ago, it now uses `signed-by` so you know the repo won't provide any unsigned packages.

**Comment by gtf35** [comment]
Thannnnnk you for your reply


Really just no Debian repositories(I happen to be using Debian 🙊)


In fact, because Debian's rules are very strict, I can safely try any software that enters the official repository, and it will not break the system. 


 I think entering the official repository is also a credible sign.  


Now that I know the answer, thanks again🤗

**Comment by francislavoie** [comment]
They basically require us to package _every single dependency_ as a separate package. That's way too much for us to reasonably maintain. I have a full-time job, I don't have the time for that on top of maintaining the project itself. Packaging should be easy but Debian's rules make it difficult.

**Comment by gtf35** [comment]
It is indeed difficult to maintain part-time jobs. I can understand that. Thank you for your efforts.  Share the pressure is also the meaning of open source projects.Unfortunately, I'm an Android developer, I just use Debian, so I can't help any(even I really want

**Comment by mholt** [comment]
Well, and that's the rub isn't it. Everyone wants it but no one wants to do the work to make it happen (once they discover that it's actually a lot of work).

I don't know why, in 2022, package managers have the restrictions and requirements they do, but they're keeping us from getting in there.
