### ISSUE TITLE
Headers with newlines in value are not sent with HTTP/2

### ISSUE THREAD

**Issue by sevmonster** [caddyserver/caddy#4805]
I have read directions from many users that with Caddy, it is not only safe but actively encouraged to use newlines in header declarations for their ease of use, and as they introduce little to no overhead in the response. But under HTTPS/2, this appears to be broken.

For example:
```
header Content-Security-Policy "
upgrade-insecure-requests;
default-src 'none';
...
"
```
will work under HTTP/1.1:
```
$ curl --raw --http1.1 -vD - https://example.com
< HTTP/1.1 200 OK
< Content-Security-Policy: upgrade-insecure-requests; default-src 'none'; ...
< Content-Type: text/html; charset=utf-8
```
but not HTTP/2:
```
$ curl --raw --http2 -vD - https://example.com
< HTTP/2 200
< content-type: text/html; charset=utf-8
```
Removing the newlines from the header...
```
header Content-Security-Policy "upgrade-insecure-requests;default-src 'none';..."
```
...fixes the issue:
```
$ curl --raw --http2 -vD - https://example.com
< HTTP/2 200
< content-security-policy: upgrade-insecure-requests;default-src 'none';...
< content-type: text/html; charset=utf-8
```

Caddy 2.4.6 on Alpine Linux.

**Comment by mholt** [comment]
Thanks for the question/report @sevmonster. I'm guessing this has to do with [RFC 7230](https://www.rfc-editor.org/rfc/rfc7230) which deprecates newlines in header values:

>  Historically, HTTP header field values could be extended over
>    multiple lines by preceding each extra line with at least one space
>    or horizontal tab (obs-fold).  This specification deprecates such
>    line folding except within the message/http media type
>    ([Section 8.3.1](https://www.rfc-editor.org/rfc/rfc7230#section-8.3.1)).  A sender MUST NOT generate a message that includes
>    line folding (i.e., that has any field-value that contains a match to
>    the obs-fold rule) unless the message is intended for packaging
>    within the message/http media type.

Since that came out after HTTP/1.1 and before HTTP/2, I wonder if the Go std lib is doing something when setting header values with newlines in an attempt to conform, but also to prevent smuggling.

Some investigation will need to happen to confirm that theory, but if that's the case, then maybe we can just do a strings replace before setting the headers so that newlines are replaced with a space.

**Comment by renbou** [comment]
> Thanks for the question/report @sevmonster. I'm guessing this has to do with [RFC 7230](https://www.rfc-editor.org/rfc/rfc7230) which deprecates newlines in header values:
> 
> > Historically, HTTP header field values could be extended over
> > multiple lines by preceding each extra line with at least one space
> > or horizontal tab (obs-fold).  This specification deprecates such
> > line folding except within the message/http media type
> > ([Section 8.3.1](https://www.rfc-editor.org/rfc/rfc7230#section-8.3.1)).  A sender MUST NOT generate a message that includes
> > line folding (i.e., that has any field-value that contains a match to
> > the obs-fold rule) unless the message is intended for packaging
> > within the message/http media type.
> 
> Since that came out after HTTP/1.1 and before HTTP/2, I wonder if the Go std lib is doing something when setting header values with newlines in an attempt to conform, but also to prevent smuggling.
> 
> Some investigation will need to happen to confirm that theory, but if that's the case, then maybe we can just do a strings replace before setting the headers so that newlines are replaced with a space.

You're totally right, and the relevant code is contained in:
[net/http/header.go#205](https://go.googlesource.com/go/+/refs/tags/go1.18.3/src/net/http/header.go#205) in the case of HTTP/1.1
and
[net/http/h2_bundle.go#10088](https://go.googlesource.com/go/+/refs/tags/go1.18.3/src/net/http/h2_bundle.go#10088) in the case of HTTP/2

So this isn't a Caddy issue. In fact, it's not even a `net/http` issue, since all of the latest RFC's for HTTP/1.1, HTTP/2, HTTP/3 specify, that newlines should not be used anywhere in the headers. I don't think that it makes sense for Caddy to handle such issues as they, well, aren't intended.

**Comment by mholt** [comment]
Bingo, thanks @renbou, for taking the time to find that.

My intuition says we should not attempt to mess with this ourselves. Again, the only thing I think I'd be open to is collapsing newlines to spaces (kind of like Go does for HTTP/1.1 headers) but that they deliberately didn't do that in HTTP/2 makes me wary of doing that as well.

Based on current information, I'd say this is working as intended, and that trying to send newlines in header values in HTTP/2+ is invalid (violates spec), which applications must not do.
