### ISSUE TITLE
TLS handshake error / Caddyserver for Jellyfin

### ISSUE THREAD

**Issue by nanello** [caddyserver/caddy#4812]
1a. Operating system and version
Windows 10

1b. Caddy version 
2.0.0

2. Description
2a. What happens (briefly explain what is wrong)
Caddy shows a lot of TLS handshake errors, but still works.
2b. Why it's a bug (if it's not obvious)
Because I can't use chromecast from my Jellyfin server still.

2c. Log output
C:\caddy>caddy start
2022/05/25 17:26:53.189 ←[34mINFO←[0m   using adjacent Caddyfile
2022/05/25 17:26:53.194 ←[34mINFO←[0m   admin   admin endpoint started  {"address": "tcp/localhost:2019", "enforce_origin": false, "origins": ["localhost:2019", "[::1]:2019", "127.0.0.1:2019"]}
2022/05/25 17:26:53.196 ←[34mINFO←[0m   http    server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS {"server_name": "srv0", "https_port": 443}
2022/05/25 17:26:53.196 ←[34mINFO←[0m   http    enabling automatic HTTP->HTTPS redirects        {"server_name": "srv0"}
2022/05/25 17:26:53.199 ←[34mINFO←[0m   tls     cleaned up storage units
2022/05/25 17:26:53.200 ←[34mINFO←[0m   http    enabling automatic TLS certificate management   {"domains": ["nanello.sytes.net"]}
2022/05/25 17:26:53.209 ←[34mINFO←[0m   autosaved config        {"file": "C:\\Users\\user\\AppData\\Roaming\\Caddy\\autosave.json"}
2022/05/25 17:26:53.209 ←[34mINFO←[0m   serving initial configuration
Successfully started Caddy (pid=10928) - Caddy is running in the background
2022/05/25 19:26:53 [INFO][cache:0xc000595e50] Started certificate maintenance routine
2022/05/25 19:27:26 http: TLS handshake error from 127.0.0.1:62219: no certificate available for 'wpad.homenet.telecomitalia.it'
2022/05/25 19:27:26 http: TLS handshake error from 127.0.0.1:62220: tls: client offered only unsupported versions: [301]
2022/05/25 19:27:26 http: TLS handshake error from 127.0.0.1:62221: EOF

2d. Workaround(s)
None, I don't know how to fix this, as you can read "no certificate available for 'wpad.homenet.telecomitalia.it'", I don't know what to do

2e. Relevant links
None

3. Tutorial (minimal steps to reproduce the bug)
None

I'm pretty new to Caddy and reverse proxies, I'm just trying to make a secure connection for my remote Jellyfin server, I think it's "secure" for now, cause I can access by the url I created on NoIP, but I can't cast through Chromecast unfortunately.

Thank you!

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! So far, this doesn't look like a bug in Caddy. It looks more like a question about how to use Caddy rather than a bug report or feature request.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!
