### ISSUE TITLE
Is caddyserver FIPS compliant?

### ISSUE THREAD

**Issue by iarjunphp** [caddyserver/caddy#4820]
Windows Server 2019, FIPS enabled on the host

**Comment by mholt** [comment]
Closing in reference to duplicated post in forum:

https://caddy.community/t/is-caddyserver-fips-compliant/16145?u=matt

**Comment by red-avalanche** [comment]
Since this Issue comes up in search results, I wanted to comment that Caddy should be able to be built with FIPS 140-3 compliant crypto, given Go's [recent announcement](https://go.dev/blog/fips140) and Caddy's use of the built-in crypto library provided by Go.

To build Caddy with FIPS 140-3 compliant crypto, the following command _should_ work:
```
# GOFIPS140=v1.0.0 will build against the snapshot sent to CVMP
# GODEBUG=fips140=only will cause non-compliant cryptography to throw an error
$ GOFIPS140=v1.0.0 GODEBUG=fips140=only xcaddy build
```
While that command _should_ work, [today it doesn't due to a bug in the crypto library itself](https://github.com/golang/go/issues/73649).
