### ISSUE TITLE
Make reverse proxy's trusted_proxies standalone http handler module

### ISSUE THREAD

**Issue by WeidiDeng** [caddyserver/caddy#4821]
I am currently adapting some of my go services as caddy handler modules. Before they're reverse proxied, xff header spoofing can be prevented. Now as http handler, automatic xff filtering is lost.

I can help extract trusted_proxies functionality, if you want to do this.

**Comment by WeidiDeng** [comment]
So what's your meaning? That I should write a plugin that strip xff header as a standalone plugin. But it will live outside caddy?

**Comment by WeidiDeng** [comment]
Actually I think current header module can do it, just with some matcher magic.

{http.request.remote} placeholder should be fine.

**Comment by francislavoie** [comment]
Yes, write your own plugin to do this. No plans to add this in Caddy at this time, because like I said, it wouldn't be useful for anyone other than users who already use plugins to serve things, like you're doing. The XFF header is only useful for people using `reverse_proxy`, or `php_fastcgi` and `forward_auth` (which are actually just `reverse_proxy` under the hood, under some Caddyfile sugar). XFF is not useful for people using `file_server` for example.

Your suggestion of a placeholder doesn't make sense because you need configuration somehow for trusting proxies, and you can't feed config into placeholders.

**Comment by WeidiDeng** [comment]
`
@non_trusted not remote_ip my_trusted_ip
request_header -X-Forwarded-For
`

Turns out this is all I need.

> Your suggestion of a placeholder doesn't make sense because you need configuration somehow for trusting proxies, and you can't feed config into placeholders.

No, the placeholder is unneccessary because I don't need to mess with xff because request_header already process it.
