### ISSUE TITLE
can reverse proxy to dynamic upstreams by http?

### ISSUE THREAD

**Issue by masx200** [caddyserver/caddy#4845]
https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#dynamic-upstreams

can reverse proxy to dynamic upstreams by http?

```
reverse_proxy {
dynamic http  http://registry.example.org/some-service {
		
		refresh   <interval>
	
		dial_timeout        <duration>
		dial_fallback_delay <duration>
	}
}
```

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! This looks like a question about how to use Caddy rather than a bug report or feature request.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!

**Comment by masx200** [comment]
https://caddy.community/t/can-reverse-proxy-to-dynamic-upstreams-by-http/16338/2
