### ISSUE TITLE
Add "skip" and "skip_certificates" functions from automatic_https to Caddyfile

### ISSUE THREAD

**Issue by JojoBr0** [caddyserver/caddy#4854]
It would be a nice addition to integrate the "skip" and "skip_certificates" options available in [automatic_https](https://caddyserver.com/docs/json/apps/http/servers/automatic_https/) from json config into Caddyfile to be able to exclude tls for specific hostnames.

At the moment, it is necessary to use json to use this.

**Comment by francislavoie** [comment]
Why do you need this exactly? What are you trying to do?

**Comment by JojoBr0** [comment]
I'm using caddy as reverse proxy and the application I want to use in the backend needs to request the cert itself to get it running correctly. So I would need to "disable" auto https or another method to reverse the hostname without any processing to the server behind.

**Comment by mholt** [comment]
> the application I want to use in the backend needs to request the cert itself to get it running correctly

Which application are you using?

> So I would need to "disable" auto https or another method to reverse the hostname without any processing to the server behind.

You'll still need a certificate to serve HTTPS. You can specify it manually though if you prefer.

**Comment by JojoBr0** [comment]
> Which application are you using?

I want to use the [Nextcloud VM](https://github.com/nextcloud/vm) with  the auto setup script for [notify_push](https://github.com/nextcloud/vm/blob/master/apps/notify_push.sh) and for this I need to use the integrated [automatic https cert request](https://github.com/nextcloud/vm/blob/master/lets-encrypt/activate-tls.sh) so everything will get setup correctly.

My thought was to use caddy as input proxy and to forward for the specific hostname (with ports 80 and 443) so the VM can request the cert itself.

**Comment by mholt** [comment]
I guess if another application is managing the certificate, you could tell Caddy to load it explicitly by specifying its key and cert filenames in your config. But you'd have to reload your config every couple of months at least to keep it current.

Another option would be to implement some sort of `certmagic.Manager` type (as a plugin) that can reload a certificate from disk when it is updated.

Or, just double-dip and let both Caddy and your backend get certs. Definitely not ideal, but if it's just 2 certificates instead of 1, you're probably well within Let's Encrypt's rate limits.
