### ISSUE TITLE
new caddy.packages module

### ISSUE THREAD

**Issue by tonyallan** [caddyserver/caddy#4864]
I would really like a new module to check if a list of packages are currently installed when caddy is started and install them if not.

Exactly the same functionality as `add-package`:
```sh
caddy add-package github.com/abiosoft/caddy-exec
```

Anong with a caddy JSON configuration of, say:
```json
{"admin":
    "packages": ["github.com/abiosoft/caddy-exec"],
```

This would be useful if I install and maintain caddy using `sudo apt install caddy` with updates as part of regular system updates. At the moment, I do this as a manual step which I sometimes forget.

See also `https://caddy.community/t/suggesting-a-new-module-to-automatically-add-packages-at-caddy-startup/16471`

**Comment by francislavoie** [comment]
As discussed in the forum topic, I'm leaning towards this not really being viable or ideal. 

Most users this would theoretically be useful for are systemd users, which means Caddy runs as a non-root user, but the `/usr/bin/caddy` binary is owned by the `root` user which means Caddy itself cannot swap out its own binary unless you run as root (e.g. `sudo caddy add-package`).

I'm also worried about the risk of getting stuck in a restart loop because it fails to swap out the binary, which would probably trigger repeated HTTP requests to caddyserver.com for downloading the new binary with the added plugins. It could cause a DDOS of the server if people misuse this feature.

So because of these risks, I think I'll close this for now.

**Comment by septatrix** [comment]
I opened a similar discussion over on discourse which does not suffer from the same problems: https://caddy.community/t/support-for-go-plugins/16724
