### ISSUE TITLE
Support for SSL passphrase

### ISSUE THREAD

**Issue by mmenozzi** [caddyserver/caddy#4873]
Hi guys! Thank you for working on Caddy, it's awesome!
I have a question: is it possible, with Caddy, to use a custom SSL certificate which also has a passphrase?

With Apache is possible and it asks for the passphrase every time the process starts. But it's also possible to avoid this by specifying a file containing the passphrase which is then configured with the [SSLPassPhraseDialog](https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslpassphrasedialog) directive.

Is this supported even with Caddy in any way?

Thank you.

**Comment by francislavoie** [comment]
SSL is a deprecated term. It's been called TLS since 1999.

No, Caddy doesn't have this functionality. I'm not sure we want to add it either, because it would involve a lot of complexity and I highly doubt that it would have much real-world use (probably less than 0.1% of users).

The security benefits of this are pretty questionable. It's better to just control access to the machine you have Caddy running on to make sure nobody has access to it other than trusted parties.

If a bad actor gains access to the machine, they can already do bad things by default, like use the admin API (`http://localhost:2019`) to change Caddy's config.
