### ISSUE TITLE
Improve `caddy version` to include revision information

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#4926]
Go 1.18 adds more information into the build that could be used to make `caddy version` show more useful information for `go build` builds, instead of just showing `(devel)` which is pretty useless. https://tip.golang.org/doc/go1.18#go-version

**Comment by mholt** [comment]
Ok, so this works, but annoyingly not for `go run`, only `go build`. Will open a PR soon.

**Comment by mholt** [comment]
Meh, ok, so it only kinda works. The `vcs.revision` key gives us the commit SHA, but not the tag or "version" like what the current build info does.

I suppose that's what https://github.com/golang/go/issues/29228 and https://github.com/golang/go/issues/50603 are for.

But if no proper version is available, we can still print out something useful instead of `(devel)` or `unknown` this way. Unfortunately we still have to maintain our current build practices of putting Caddy as the non-main package in the meantime.
