### ISSUE TITLE
Windows installer tagged as unsafe

### ISSUE THREAD

**Issue by jfha73** [caddyserver/caddy#4938]
Hey guys,

I just downloaded Caddy Server to try HTTP/3, but when I tried to install it I got a window saying the file is unsafe and I was asked not to run it, any idea why?

**Comment by francislavoie** [comment]
What "windows installer"? We don't ship an installer, just a binary `.exe`.

**Comment by elcore** [comment]
> What "windows installer"? We don't ship an installer, just a binary .exe.

Windows displays a warning if a binary is not signed by a trusted CA and recommends not running it. It is called "Microsoft Smart Screen".

**Comment by mholt** [comment]
But we don't have an installer... I think that's what we're hung up on.

If you have an installer, it's not from the Caddy project.

**Comment by elcore** [comment]
>But we don't have an installer... I think that's what we're hung up on.
>
>If you have an installer, it's not from the Caddy project.

I think this is just a communication mistake. Windows SmartScreen triggers an alarm when the binary is run, I just tried it. It is a huge red pop-up.

**Comment by mholt** [comment]
Mac does the same thing because we don't code-sign our binaries. (It's expensive and tedious.)

The idea of code signing is if the download server becomes compromised, their fancy little gatekeepers can keep you safe because they were signed during compile-time on other infrastructure.

Jokes on them though because our download server is our build server too. (Well, not quite -- they are separate, but not 100% isolated of course; just like how a CA always has their intermediate private key online to sign certificates).

**Comment by elcore** [comment]
We can't really do much here unless the binary is signed. Windows and I guess macOS will always complain... 🥲

@jfha73 If you can provide a screenshot that would be nice (just to confirm). Did you download Caddy from https://caddyserver.com/ ?
