### ISSUE TITLE
TLS `lifetime` directive has error?

### ISSUE THREAD

**Issue by chatii** [caddyserver/caddy#4947]
I tried the below Caddyfile.

```Caddyfile
chatii.localhost:443 {
	tls internal {
		lifetime 365d
	}
	reverse_proxy /* server:80
}
```

`caddy run` (or docker compose...)

```
❯ caddy run
2022/08/10 01:40:50.764	INFO	using adjacent Caddyfile
run: adapting config using caddyfile: parsing caddyfile tokens for 'tls': Caddyfile:4 - Error during parsing: unknown subdirective: lifetime
```

How can I resolve this?

**Comment by francislavoie** [comment]
Ah, I think you need to write it like this:

```
tls {
	issuer internal {
		lifetime <duration>
	}
}
```

This is because `internal` on the same line is just a shortcut for the defaults; `lifetime` isn't a subdirective of `tls`, it's a subdirective of the `internal` issuer.

That said, it's not possible to use a lifetime longer than 7 days, because the intermediate certs have a 7 day lifetime. If the leaf certs were longer than that, then they would no longer be valid once the intermediate expires.

You really shouldn't be changing the lifetime though, as the docs mention. If you're doing it because you want to be able to trust the cert in your browser, then it's _incorrect_ to increase the lifetime of the cert, instead you should be adding the root CA cert to your system/browser's trust store, so that any certs issued by the CA are trusted.

**Comment by chatii** [comment]
@francislavoie Thanks for kindness answer!!
