### ISSUE TITLE
php_fastcgi causes wrong redirect

### ISSUE THREAD

**Issue by AndreKR** [caddyserver/caddy#4956]
To reproduce the issue, create a directory with Caddy, `Caddyfile` and two files of arbitrary contents named `index.php` and `index.html`.

Caddyfile:
```
:8080
root * .
uri strip_prefix /some/prefix/
file_server
error / "Nothing here" 400
```

Run Caddy with the Caddyfile.

Navigate to `http://localhost:8080/some/prefix/index.html`. As expected you will see the contents of `index.html`.  
Navigate to `http://localhost:8080/some/prefix/`. As expected you will again see the contents of `index.html`.

Now add to the Caddyfile:
```
php_fastcgi 127.0.0.1:9000
```
There is no need to actually have PHP running to reproduce the issue, just adding this line causes the problematic behavior.

Reload Caddy, then:  
Navigate to `http://localhost:8080/some/prefix/index.html`. As expected you will see the contents of `index.html`.  
Navigate to `http://localhost:8080/some/prefix/index.php`. As expected you will see an HTTP 502 (or, if you actually have PHP running,  the contents of index.php).  
Navigate to `http://localhost:8080/some/prefix/`. **An HTTP 308 redirect to `http://localhost:8080/` is erroneously performed.** You will see the error configured for `/`.

Caddy version: v2.5.2 h1:eCJdLyEyAGzuQTa5Mh3gETnYWDClo1LjtQm2q9RNZrs=

**Comment by francislavoie** [comment]
TBH, this is as expected. `php_fastcgi` wasn't designed to work with `uri strip_prefix` because of the behaviour it has to correctly only handle PHP requests. See the [Expanded Form](https://caddyserver.com/docs/caddyfile/directives/php_fastcgi#expanded-form) doc which explains what it does.

Keep in mind, directives in the Caddyfile are sorted according to the predetermined [directive order](https://caddyserver.com/docs/caddyfile/directives#directive-order), so `error` runs _before_ `php_fastcgi`, so the rewrite performed by it will not trigger an error.

**Comment by AndreKR** [comment]
Oh, so because my `strip_prefix` removes the slash, the configuration behind `php_fastcgi` will try to add it back.

Ok, I will use the expanded form and customize it to my needs.

**Comment by francislavoie** [comment]
It _might_ work if you use `uri strip_prefix /some/prefix` instead (remove the trailing slash there).
