### ISSUE TITLE
Docker caddy invalid certificat

### ISSUE THREAD

**Issue by soufianebgh** [caddyserver/caddy#4973]
Hi, everyone ! 

I discovered Caddy really recently and the facility of the configuration charmed me. So, I wanted to use it. I'm using the last version in docker container for reverse proxy and also for the https access. My problem is really simple, I was able to get https access but certificat is unable even with good date and issuer.  See this screenshot.

![image](https://user-images.githubusercontent.com/97157776/185873981-0aac0436-a750-4e60-8f86-eb47b060522f.png)

There is a way to fix this ? (I'm pretty beginner in sysadmin world.)

Thanks !

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! So far, this doesn't look like a bug in Caddy. It looks more like a question about how to use Caddy rather than a bug report or feature request.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!
