### ISSUE TITLE
Response code based failovers with caching

### ISSUE THREAD

**Issue by kickthemooon** [caddyserver/caddy#4992]
Could I achieve HTTP response code based failovers with caching using caddy?

What I mean is

- Caddy receives a request and forwards it to the **primary backend**
- If the request fails with e.g. **404**, caddy **retries** the request with a **secondary backend**
- **Failed** primary backend request urls are **cached** e.g. on disc
- For performance, request urls present in the list of cached urls are forwarded to the **secondary backend** skipping the primary

Is this something I could do with caddy?

**Comment by francislavoie** [comment]
Yes, you can re-handle a proxied request with `handle_response`, matching either on status code or by response header. See https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#intercepting-responses. You can configure another `reverse_proxy` inside of that as your secondary.

I can't think of a way the caching/skip-primary thing would work with the tooling that currently exists in Caddy (mainly because your requirement involves it only behaving that way based on remembering failing URLs), but it could definitely be done with a plugin if you want to take a crack at it: https://caddyserver.com/docs/extending-caddy

You could _in general_ use `reverse_proxy`'s passive health checks for this, but this won't take into account the URLs, and will mark the whole upstream as unhealthy if requests fail. You can use `lb_policy first` which will always use the primary, unless the primary is unhealthy in which case it will use the next upstream.

**Comment by kickthemooon** [comment]
Ok. Thanks a lot.
