### ISSUE TITLE
TLS: Option to exit Caddy if obtaining a certificate fails

### ISSUE THREAD

**Issue by lclc** [caddyserver/caddy#4998]
It would be nice to have an option to make Caddy exit if a TLS certificate can't be obtained (maybe configurable after X  tries).

Use-case: Caddy servers a frontend, an internal backend and an external backend on different (sub-)domains. The user makes a spelling error in the external backend domain. Everything looks fine, but the external backend is not reachable.

**Comment by lclc** [comment]
Actually, maybe better would be to error when the domain is unresolvable. That way it catches typos.

**Comment by mholt** [comment]
So actually, we did this for years with Caddy 1, intentionally, and I defended it with very good reasons. But people _HATED_ this behavior:

- https://github.com/caddyserver/caddy/issues/1680 (this was one of the worst days of my adult life)
- https://github.com/caddyserver/caddy/issues/971
- https://github.com/caddyserver/caddy/issues/872
- https://github.com/caddyserver/caddy/issues/1713
- https://github.com/caddyserver/caddy/issues/1992
- https://github.com/caddyserver/caddy/issues/1038
- https://caddy.community/t/how-to-have-bad-domain-in-config-skipped/513?u=matt

> Actually, maybe better would be to error when the domain is unresolvable. That way it catches typos.

This is what nginx does, and it's heavily broken due to infrastructure/DNS configurations, and the cause of many complaints by people.

We have decided it is best that the server process must run even if external factors would suggest otherwise.

The best solution to this problem is: watch your logs for errors.
