### ISSUE TITLE
An idea of autohttps abuse protection

### ISSUE THREAD

**Issue by viktorandreevichmorozov** [caddyserver/caddy#5008]
If i configure caddy to issue certs for any domain on demand, i will get a warning:
` WARN    tls     YOUR SERVER MAY BE VULNERABLE TO ABUSE: on-demand TLS is enabled, but no protections are in place       {"docs": "https://caddyserver.com/docs/automatic-https#on-demand-tls"}`

I think we can make optional protection from this kind of abuse:
1. We will need a new config option with a list of public IPs for this caddy server.
2. We will need a new config option with a trusted dns resolver (8.8.8.8, 1.1.1.1, ...)
3. Now we can check if the requested domain is resolved to one of those IPs with a trusted dns resolver.

I think it will be very useful to those who handle hundreds of domains resolved to the same one caddy instance.

**Comment by francislavoie** [comment]
That doesn't solve the issue.

The vector for abuse is if an attacker points a wildcard CNAME to your domain (or A record to your IP) and then starts making requests like `a.evil.com` then `b.evil.com` then `c.evil.com` to infinity.

This will force your Caddy instance to issue certs for all of these individual domains until you hit rate limits (and get yourself locked out of issuing certs for legitimate domains) or worse, you run out of storage space from all the garbage certs and keys.

You really _must_ configure an `ask` endpoint, because that's the only way Caddy can know what's a legitimate domain and what isn't. You need to keep a database of the domains your users wish to use; have them register their domain with you ahead of time before they set up their CNAME.

**Comment by viktorandreevichmorozov** [comment]
Thank you!
I have completely miss `ask` option :-(
