### ISSUE TITLE
Syntactic sugar for redirects in the Caddyfile

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#5052]
I dunno if anyone needs this, but what if  instead of opening a whole site block for simply doing a redirect:

```
example.com/foo1 {
    redir https://example.com/foo2
}
```

you could simply do:

```
example.com/foo1 -> https://example.com/foo2
```

Of course, there are many kinds of redirects. Maybe you want to redirect a whole domain (and preserve the URI):

```
example.com -> example.net
```

This will preserve the URI because `/` was not used (similar to how `rewrite` works; it only affects URI components that are indicated in the pattern).

Maybe you want to add a prefix:

```
example.com -> example.com/new_prefix{uri}
```

Or maybe you want to redirect ports:

```
:80 -> :8080
```

I think I fiddled with this early on during v2's inception but decided to shelve it since there was a lot of other priorities. But this seems like it could be useful for users doing lots of redirects.

I would probably only implement this feature if people say they need it, and after some good discussion.

**Comment by francislavoie** [comment]
I feel like for most users, this can be done with a Caddyfile snippet with args, if they have a lot of them. So for example:

```
(redir) {
{args.0} {
	redir https://{args.1}{uri}
}
}

import foo.com www.foo.com
import bar.com www.bar.com
```

Some other variations are possible with a snippet as needed.

I'm generally nervous about adding weird new syntax like this, I think it might just be more confusing than generally useful.

**Comment by simaotwx** [comment]
If this is added, I would prefer this syntax:

```
redir foo.com to www.foo.com
redir bar.com to www.bar.com
```

which would be a cleaner way of writing


> ```
> (redir) {
> 	{args.0} {
> 		redir https://{args.1}{uri}
> 	}
> }
> 
> import redir foo.com www.foo.com
> import redir bar.com www.bar.com
> ```

I feel like nowadays we're having less and less redirects like this due to websites being hosted directly under the second level domain (i. e. foo.com).

**Comment by mholt** [comment]
@simaotwx Thanks for the feedback!

Can you tell me why you prefer that syntax instead of this?

```
foo.com -> www.foo.com
bar.com -> www.bar.com
```

The nice thing about the arrow `A -> B` syntax is that it's a good cue to the parser about the redirect. Using `redir A to B` would require parsing the whole line then treating `redir` special if the 3rd site name is `to`. If that makes sense. With the arrow, the parser consumes the site name (`A`) then sees the arrow (`->`) which it then knows to build a site block containing a `redir` to the next token... much simpler parsing I think.

**Comment by simaotwx** [comment]
> Can you tell me why you prefer that syntax instead of this?

The arrow looks odd to me. It does not feel like it belongs there in my eyes. It's easier for me to read if we use words instead of an arrow.

> The nice thing about the arrow A -> B syntax is that it's a good cue to the parser about the redirect. Using redir A to B would require parsing the whole line then treating redir special if the 3rd site name is to. If that makes sense. With the arrow, the parser consumes the site name (A) then sees the arrow (->) which it then knows to build a site block containing a redir to the next token... much simpler parsing I think.

I agree with you.

It feels like that kind of syntax does not combine well with the rest and would be a special case that needs special handling.

We are used to seeing this in a Caddyfile:

```
{
    globals
}
toplevel param

domain {
    directive param
}
```

Adding the syntax you mentioned feels out-of-place.

What if we do it like this

```
example.com/foo1 { redir https://example.com/foo2 }
```

It's still one line, just using the current syntax. This wouldn't work though:

```
run: adapting config using caddyfile: Caddyfile:2 - Error during parsing: Unexpected '}' because no matching opening brace
start: caddy process exited with error: exit status 1
```

So my suggestion would be to adopt the way Kotlin handles [single-expression functions](https://kotlinlang.org/docs/functions.html#single-expression-functions):

```
example.com/foo1 = redir https://example.com/foo2
```

This allows for oneliners, and could be used for anything, not just redir and would make parsing really easy as you just need to switch on a new character `=`. This would be a bigger feature and more flexible.

**Comment by tecosaur** [comment]
Hmmm, I've just taken a glance at this issue and since I found the `=` example slightly confusing thought I'd add my 2c.

Something good about these two forms:
```
redirect a to b
a -> b
```

is that the directional is completely clear.

By comparison, I found with these forms
```
example.com/foo1 { redir https://example.com/foo2 }
example.com/foo1 = redir https://example.com/foo2
```

I had to think for a moment to work out which url was the source and which was the target. I found the `=` example particularly problematic as my brain was trying to work out how equality fit with the directionality of redirects. I initially read these both as "foo1 is a redirect to foo2" (foo1 -> foo2) and "foo1 is a redirection of foo2" (foo2 -> foo1). If using a syntax like this `foo1 { redirect_to foo2 }` would be clear up that little bit of ambiguity I think.

**Comment by simaotwx** [comment]
@tecosaur
> Hmmm, I've just taken a glance at this issue and since I found the = example slightly confusing thought I'd add my 2c.
> [...]
> is that the directional is completely clear.
> [...]
> trying to work out how equality fit with the directionality of redirects.

My idea about the equality sign is to not use it as a direction but rather as a general purpose token to signify that we're writing a oneliner. This means that it could also look like this:

```
example.com = respond "test"
```

or

```
example.com = reverse_proxy :8080
```

But I understand what you're saying and so maybe using the [arrow function syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#try_it) as [ES6](https://262.ecma-international.org/6.0/#sec-arrow-function-definitions) does it could be beneficial:

```
example.com/foo1 => redir hedir https://example.com/foo2
```

Which means other directives would look like following:

```
example.com => respond "test"
```

and

```
example.com => reverse_proxy :8080
```

Which would also kind of show the direction of proxying: `example.com -> :8080`.

**Comment by simaotwx** [comment]
Visually, to my eyes, `=>` looks better than `->`. I wouldn't use it solely for redirects but rather for pretty much anything so that we can easily write oneliners without having to write three lines and use curlies `{}`.

**Comment by mholt** [comment]
The one-liner idea is pretty appealing, I could see that being more generally useful. Good points either way for `=` vs. `=>` vs. `->` so I'm not sure what that would be yet. But I like where that's going.

**Comment by francislavoie** [comment]
Closing this - no plans currently to explore this syntax further
