### ISSUE TITLE
No files matching import glob pattern

### ISSUE THREAD

**Issue by mk3media** [caddyserver/caddy#5061]
Since update to 2.6.0 I am not able to import via `/caddy/sites-enabled/*`. The folder contains symlinks to  `/caddy/sites-available/*`. This config has work before without any problems. I also tried to rename the files to be imported to `filename.config` without success.

To get everything working like before, I had to copy all former imported configs  into the Caddyfile. Any suggestions?

**Comment by mohammed90** [comment]
I'm not able to reproduce it. The import glob is working as expected for me. See:

```zsh
2022-09-21 13:23:50  ~/lab/caddy2-playground/import-expansion $ tree .                                                                             
.
├── Caddyfile
└── sites
    ├── site-1
    └── site-2

1 directory, 3 files
2022-09-21 13:24:54  ~/lab/caddy2-playground/import-expansion $ cat ./Caddyfile                                                                    
import sites/*
2022-09-21 13:24:56  ~/lab/caddy2-playground/import-expansion $ cat sites/site-1                                                                   
localhost {
        file_server
}
2022-09-21 13:25:09  ~/lab/caddy2-playground/import-expansion $ cat sites/site-2                                                                   
example.com {
        reverse_proxy localhost:443
}%                                                                                                                                                  
2022-09-21 13:25:10  ~/lab/caddy2-playground/import-expansion $ ~/caddy adapt                                                                      
2022/09/21 10:25:23.199 INFO    using adjacent Caddyfile
{"apps":{"http":{"servers":{"srv0":{"listen":[":443"],"routes":[{"match":[{"host":["example.com"]}],"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"reverse_proxy","upstreams":[{"dial":"localhost:443"}]}]}]}],"terminal":true},{"match":[{"host":["localhost"]}],"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"file_server","hide":["/Users/mohammed/lab/caddy2-playground/import-expansion/sites/site-1"]}]}]}],"terminal":true}]}}}}}
2022-09-21 13:25:23  ~/lab/caddy2-playground/import-expansion $    
```

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by mk3media** [comment]
Issue solved: I had to move /sites-available and /sites-enabled into /etc/caddy – now it works again like aspected.

**Comment by Zerorigin** [comment]
A possible solution is as follows:
1. Install libcap-setcap package
2. `setcap $(echo 'CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_DAC_READ_SEARCH' | awk '{print tolower($0)}')+ep /path/to/bin/caddy`

Ref.:
1. https://linux.die.net/man/7/capabilities

**Comment by francislavoie** [comment]
@Zerorigin that seems like a horrible idea. Giving Caddy the capability to ignore all file permissions is not good. A web server is particularly security sensitive, if someone manages to find an exploit to read/write important system files with it, it could be disastrous.

**Comment by Zerorigin** [comment]
> @Zerorigin that seems like a horrible idea. Giving Caddy the capability to ignore all file permissions is not good. A web server is particularly security sensitive, if someone manages to find an exploit to read/write important system files with it, it could be disastrous.

Also can chown the workdir owner to caddy run user. (It's recommanded.)
