### ISSUE TITLE
http/3 support in reverse_proxy module

### ISSUE THREAD

**Issue by dPeS** [caddyserver/caddy#5086]
Hi Guys,

I was tweaking with reverse_proxy settings a lot and was unable to proxy http/3 traffic - does RP supports H3?

Cheers,
Daniel

**Comment by mholt** [comment]
No, only an http/3 server is supported for now. What's your use case for http3 to a proxy backend?

**Comment by WeidiDeng** [comment]
[quic-go](https://github.com/lucas-clemente/quic-go) (the http3 library caddy is using) supports http3 transport, but as matt said, what's the use case?

**Comment by lxhao61** [comment]
Reverse proxy to an HTTPS endpoint:
~~~
reverse_proxy https://example.com {
	header_up Host {upstream_hostport}
}
~~~
Does it support reverse proxy HTTP/3 endpoints?

**Comment by francislavoie** [comment]
@lxhao61 but why? What's the benefit for you?

**Comment by mholt** [comment]
Dangit Francis, you did it again! :) Right as I'm writing my comment :rofl: 

Anyway, why is HTTP/3 needed here?

**Comment by lxhao61** [comment]
> @lxhao61 but why? What's the benefit for you?

Such as [naiveproxy (forwardproxy)](https://github.com/klzgrad/naiveproxy) application. If you don't want to build a website that supports HTTP/3 (disguise) on this machine; then reverse proxy to a website that supports HTTP/3, see the following:
```
{
	order forward_proxy before reverse_proxy
}
:443, example1.com {
	forward_proxy {
		basic_auth user pass
		hide_ip
		hide_via
		probe_resistance
	}
	reverse_proxy https://example2.com {
		header_up Host {upstream_hostport}
	}
}
```

**Comment by WeidiDeng** [comment]
@lxhao61 There's no reason to do that, firewall between you and your server will always see the traffics is not http3 even if reverse proxy supports http3 upstream. Enable h3 on caddy instead.

As far as I know, naïve proxy has to explicitly use quic scheme to use h3.

**Comment by lxhao61** [comment]
> @lxhao61 There's no reason to do that, firewall between you and your server will always see the traffics is not http3 even if reverse proxy supports http3 upstream. Enable h3 on caddy instead.
> 
> As far as I know, naïve proxy has to explicitly use quic scheme to use h3.

caddy starts HTTP/3 by default since [v2.6.0](https://github.com/caddyserver/caddy/releases/tag/v2.6.0), and no additional configuration is required.

**Comment by bdr99** [comment]
I'd like to share my particular use case and why I think it would be helpful if `reverse_proxy` supported HTTP/3 for communication with upstream backends.

I run a double-layer Caddy setup with two Caddy instances chained together. One instance runs on a home server in my private network, and the other runs in a public VPS. My home network has the HTTP ports closed, and the public VPS has them open. The public Caddy instance on the VPS routes requests via a Tailscale VPN tunnel to the private Caddy instance running on my home server. This way, my public IP is not visible to users of the sites I'm hosting with Caddy. It also allows me to host private sites that should only be accessible on my local network, by adding them to only the private Caddy instance and not the public one, and doing some DNS trickery to route requests originating from my local network directly to the private instance, bypassing the public one.

So, with this setup, requests to my sites are routed through two Caddy instances. With Caddy 2.6, the traffic between the client device and the public Caddy instance can use HTTP/3, but the traffic between the public Caddy instance and the private one cannot, since `reverse_proxy` does not support HTTP/3. It would be nice it did, since that way, I would be able gain the benefits of HTTP/3 for this additional hop in the chain.

**Comment by bdr99** [comment]
@mholt Thanks! I agree it certainly shouldn't be a high priority. At this point it's just a nice to have.

**Comment by huddhudd** [comment]
i need this

**Comment by francislavoie** [comment]
@huddhudd that's not a helpful comment. Please elaborate. We need to understand people's usecases for needing this. _Why_ do you need it? What would it let you do that you couldn't do before?

**Comment by huddhudd** [comment]
Accelerate my local apps.

App ->（caddyserver ） 127.0.0.1:88 -> （ Cdn ）  Http3 

Because my local application does not support Quic, and there are a large number of multi-threaded segmentation requests

Http Header 
Range: bytes=0-1023

So the speed is very slow.

**Comment by burgerlander** [comment]
> I'd like to share my particular use case and why I think it would be helpful if `reverse_proxy` supported HTTP/3 for communication with upstream backends.
> 
> I run a double-layer Caddy setup with two Caddy instances chained together. One instance runs on a home server in my private network, and the other runs in a public VPS. My home network has the HTTP ports closed, and the public VPS has them open. The public Caddy instance on the VPS routes requests to the private Caddy instance running on my home server via a Tailscale VPN tunnel. This way, my public IP is not visible to users of the sites I'm hosting with Caddy. It also allows me to host private sites that should only be accessible on my local network, by adding them to only the private Caddy instance and not the public one, and doing some DNS trickery to route requests originating from my local network directly to the private instance, bypassing the public one.
> 
> So, with this setup, requests to my sites are routed through two Caddy instances. With Caddy 2.6, the traffic between the client device and the public Caddy instance can use HTTP/3, but the traffic between the public Caddy instance and the private one cannot, since `reverse_proxy` does not support HTTP/3. It would be nice it did, since that way, I would be able gain the benefits of HTTP/3 for this additional hop in the chain.

Chiming in to say that my use case is identical to this one except I'm using a plain wireguard tunnel to chain together both the exposed server and the reverse tunnel client, rather than tailscale. Both servers are located in two different countries, so any latency improvement, no matter how minor, would definitely be welcome.

**Comment by youguys** [comment]
Hey guys:
    In my case:
         UI---->local web server(caddy)----(http/3)--->remote web server(caddy)------(http/1)app

     Only udp port was enable at remote web server, so i need to use http3(udp) as a tunnel
     
     Maybe i should replace "local web server" to "Traefik" which support http3 entrypoint
   `experimental:
  http3: true

entryPoints:
  name:
    http3: {}`

**Comment by joshughes** [comment]
Many cloud providers are beginning to support http/3 on their load balancers. There are many cases where http/3 connections to upstreams could be beneficial such as less reliable networks. It would be an interesting feature for caddy to support http3 as a target protocol for upstream servers. Even more interesting if this could be negotiated like browser decide to upgrade to http/3 use the alt-svc header on an upstream to perform this upgrade.

There are some complications like firewall rules and other things where TCP 443 may be open but UDP 443 may not. But in any case being able to explicitly tell caddy to try http3 on a reverse proxy upstream with a configuration flag would be pretty interesting, useful in many cases, and a differentiator as this currently does not exist in anything that could be found currently.

POC of a http 1.1 to http3 upstream can be seen at https://github.com/AeroNotix/go-quic-proxy

An interesting use case that is maybe specific is IOT devices on less reliable networks. This is where HTTP3 shines. Many times on these devices you will be running software that may or may not have libraries for HTTP3 or may not have mature HTTP3 options. Being able to run a Caddy HTTP3 revers proxy on these devices to give extra reliability and performance on these types of devices would be a huge win.

**Comment by mholt** [comment]
Thanks -- as mentioned above, this isn't a high priority for me right now. If someone would like to sponsor this work, then I can prioritize it; or if someone would like to propose how this would be implemented and then submit a PR that would also help move this along.

**Comment by huddhudd** [comment]
I also have use cases, haven't there been any progress yet

**Comment by LDprg** [comment]
Just want to mention that there is a fork of NPM supporting http3. So maybe caddy should add support too.

**Comment by masx200** [comment]
any update?
I found that the https TLS connection of the existing website was attacked by a man-in-the-middle, and the connection was disconnected, and the connection was successful only by using quic production.hello-word-worker.masx200.workers.dev!

**Comment by mholt** [comment]
Latest update is still https://github.com/caddyserver/caddy/issues/5086#issuecomment-1479803998

If someone would like to sponsor this work, I'd be happy to prioritize it sooner. :+1:

**Comment by mholt** [comment]
@joshughes 

> Even more interesting if this could be negotiated like browser decide to upgrade to http/3 use the alt-svc header on an upstream to perform this upgrade.

But why would the browser care or why should the browser be able to control the connection to the backend? That should be squarely on the proxy to decide IMO.

Also, just to clarify, for everyone suggesting use cases: you are talking about the _specific need_ for a terminated, altered HTTP/3 connection from the proxy to the backend? i.e. NOT a UDP proxy, which routes the HTTP/3 connection directly from the client to the backend without terminating it at the proxy?

If you need unterminated HTTP/3 to go transparently from a client to a backend, you'll want [Project Conncept](https://github.com/mholt/caddy-l4) (a layer 4 plugin for Caddy).

I just want to clarify first that what is needed is for a terminated HTTP/3 connection between proxy and backend... :thinking:

**Comment by mholt** [comment]
@dPeS @demarcush @masx200 @LDprg @burgerlander @huddhudd @bdr99 @lxhao61 (phew, that's a lot of you) I have a PR at #6312 if you'd like to try out HTTP/3 to the backend. I just did a quick test and I have no idea if it'll meet your various needs and use cases, but please give it a shot. (I am skeptical this is _actually_ what you all need, but maybe we'll be pleasantly surprised and it'll just work ...?)

**Comment by joshughes** [comment]
@mholt my case is pretty specific but Caddy is running on an IOT device out in the wild where it will experience vairous degrees of bad wifi or poor connection. If I can use HTTP3 to talk to my servers I can get better overall performance in communication from my IOT device to the cloud. There are various things going in in the Caddy proxy on the device which are helpful and we have written our own little golang http3 proxy with go-quic that then Caddy talks to. It would be nice to be able to remove that which is why I commented on this issue when I came across it. 

Thanks for taking a look at it, I will take your PR for a spin and provide any feedback I can.

**Comment by qrhfz** [comment]
just wanted to share my little benchmark.

my setup is:
```
caddy on vps (Los Angeles) <== wireguard ==> caddy on my home (indonesia)
```

These are memos (https://github.com/usememos/memos) page load time reported by chromium.
h3: 6.92s
h2: 8.80s

21.36% reduction in page load time. i hope this feature will stay.

**Comment by francislavoie** [comment]
@qrhfz if you're going over wireguard, you can probably proxy over HTTP instead and likely get similar or better performance due to avoiding TLS overhead.

**Comment by chetan-reddy** [comment]
Just wanted to report that

`local_h1_client -> local_caddy -> http3_over_350ms_rtt_lossy_wireguard_network -> remote_caddy -> remote_h1_app`

 works much better than 

`local_h1_client -> http1_over_wireguard -> remote_caddy -> remote_h1_app`

I hope this feature will stay.


> [@qrhfz](https://github.com/qrhfz) if you're going over wireguard, you can probably proxy over HTTP instead and likely get similar or better performance due to avoiding TLS overhead.

@francislavoie In my use case even with TLS overhead h3/quic performs better. Is it possible to disable the encryption between local_caddy and remote_caddy since the link is already encrypted by wireguard? I looked for `h3c` analogous to `h2c` but didn't find it. It seems that quic-go itself [doesn't allow](https://github.com/quic-go/quic-go/issues/1402) turning off TLS, but are you aware of any plugins/hacks that would reduce the TLS overhead of HTTP3? Local caddy already has `tls_insecure_skip_verify` set.
