### ISSUE TITLE
Http3 does not work on my web browsers 

### ISSUE THREAD

**Issue by Adam-Kadi** [caddyserver/caddy#5098]
Hello to all, 

I have a small problem to get the QUIC protocol working on my Caddy server. I installed a Caddy server on a docker ubuntu image. You can see in the first image, the configuration of my Caddyfile. 

![Caddyfile_1](https://user-images.githubusercontent.com/111990930/193241178-a1de8ca8-1209-4371-acc7-4200be786c91.png)

When I send a Get request with a go script on the server from the localhost, the communication is done in quic and Http3. 

When I use a web browser (Chromium, Firefox) to navigate on my server, the communication is done in http2 and tcp, 
I don't really understand this because I have activated the quic in the browser settings.

![Wireshark _2](https://user-images.githubusercontent.com/111990930/193241432-5a1c1252-edbe-4fd5-9eb2-e585a455f4b2.png)

**Comment by francislavoie** [comment]
FYI, with `h1 h2c h3`, you're actually disabling `h2`. Is that on purpose? `h2c` won't work unless you have a site listening for HTTP (not HTTPS) so this doesn't really make sense.

The default since v2.6.0 is `h1 h2 h3` so you don't need to configure protocols unless you actually need `h2c` support or want to turn off `h3`.

Caddy doesn't support older QUIC drafts anymore, it only supports HTTP/3 which is the ratified spec from [RFC 9114](https://www.rfc-editor.org/rfc/rfc9114.html).

Either way, this looks like a problem with your browser, and not Caddy.

**Comment by mholt** [comment]
Yeah, I would test with `curl -v --http3` (you'll need a special build of curl to support http3), since we don't know what kind of weird things browsers are doing or what bugs they have.

**Comment by Adam-Kadi** [comment]
Thank you for your feedback, I updated my firefox browser to 105.0.1. I manage to pass quic/http3 however the http2 is still present. Some resources transit with the http3 and others with the quic. Do you know a trick for the resources to transit entirely in quic/http3.

![Inspectweb](https://user-images.githubusercontent.com/111990930/193862894-da5def86-b682-4e12-a65a-66b136941b40.png)

**Comment by mholt** [comment]
Yeah, I've noticed similar in Firefox, and can't explain it. Try asking the browser developers why, I'd be curious to know.
