### ISSUE TITLE
Preferred curve order

### ISSUE THREAD

**Issue by Inetol** [caddyserver/caddy#5113]
## Issue
For some reason beyond my understanding, Caddy will decide that while using <=TLS1.2 and TLS1.3 it will not sort the curves while using only TLS1.3 it will sort them. I checked this using [SSLabs](https://www.ssllabs.com/ssltest/).

### Expected
```
tls {
    protocols tls1.2 tls1.3
    curves x25519 secp256r1
}
```
![ssllab_report_expected](https://user-images.githubusercontent.com/34861290/193521756-d1e321ff-be42-4334-9afc-90a8e787a8a3.png)

### Got
```
tls {
    protocols tls1.2 tls1.3
    curves x25519 secp256r1
}
```
![ssllab_report_got](https://user-images.githubusercontent.com/34861290/193521826-cc4641d2-8d0e-4481-90c6-a83606afefad.png)

## Annex
Following this issue as it is an old one: #3274

**Comment by francislavoie** [comment]
For the same reason as I mentioned in https://github.com/caddyserver/caddy/issues/5112#issuecomment-1265034341, any ordering is now ignored by the Go stdlib.

The default supported curves are `[]CurveID{X25519, CurveP256, CurveP384, CurveP521}` so there's really no reason to specify `curves` at this point.

Also, remove your `protocols` config, it's not good to explicitly configure the same as the defaults, because if later on Caddy adds support for let's say `tls1.4` then you would be turning off support for it with your config. If you leave out the config, then when you upgrade Caddy, you'll automatically get the ideal modern defaults out of the box.
