### ISSUE TITLE
SSL on subdomain not working

### ISSUE THREAD

**Issue by bennetrr** [caddyserver/caddy#5132]
I just tried caddy for routing the traffic to multiple docker containers.

I'm using this Caddyfile:

```
bennetr.me {
        reverse_proxy localhost:8000
}

kafka.bennetr.me {
        reverse_proxy localhost:8100
}
```

I can access `https://bennetr.me` properly, but when I try to open `https://kafka.bennetr.me`, Firefox says me that "The site can't be reached".

When I try to open the page using the port of the container (`https://bennetr.me:8100/`), I get following error message:

```
Error: Secured connection failed

An error occurred while connecting to bennetr.me:8100. SSL received an entry that exceeded the maximum allowed length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG
```

(I hope I translated it right...)

But when I open `http://bennetr.me:8100/`, I can reach the page

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! So far, this doesn't look like a bug in Caddy. It looks more like a question about how to use Caddy rather than a bug report or feature request.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!
