### ISSUE TITLE
reverse_proxy: support following upstream redirects in proxy handler

### ISSUE THREAD

**Issue by Sohalt** [caddyserver/caddy#5141]
I want to have a way to have the reverse_proxy handler follow a redirect from the upstream and serve the content from the redirected location as a response.
e.g. if I have server A listening on a.example.com with

```Caddyfile
a.example.com {
  reverse_proxy b.example.com:8000 {
    rewrirte * /foo
  }
}
```

and  server B listening on b.example.com:8000 with

```Caddy
b.example.com:8000 {
  redir /foo /foo/bar
  respond /foo/bar  "hello"
}
```

I want a request to `a.example.com` result in a 200 response with body "hello" and not in a 302 with `Location /foo/bar`.

Is there a way to accomplish this with Caddy?

There are 2 issues that previously requested this kind of functionality: https://github.com/caddyserver/caddy/issues/1620 and https://github.com/caddyserver/caddy/issues/3460

**Comment by francislavoie** [comment]
That's strange. Redirects are designed to be followed by the original client, because it changes the URL in the browser. Are you sure you don't just want to manipulate the `Location` header's value instead, or something like that? What's the usecase for this, exactly?

That said, you can probably do what you need with `handle_response`. See https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#intercepting-responses. Match on the `Location` header, `rewrite` to that path (unfortunately this wouldn't be able to support redirects to another domain/scheme) then `reverse_proxy` again to your upstream.

**Comment by Sohalt** [comment]
Thanks! `handle_response` looks like it might do the trick!

I agree, it's a bit strange. The use case is hiding some redirection logic behind a custom domain.
