### ISSUE TITLE
two site config same tls crt error

### ISSUE THREAD

**Issue by New2Niu** [caddyserver/caddy#5146]
when config two site and config same tls eg:
site1:
site1.com:443 {
    **tls /path/site1.crt /path/site1.key**
    reverse_proxy  https://10.1.1.1:443 {
        header_up Host {host}
    }
}

site2:
site2.com:8443 {
    **tls /path/site2.crt /path/site2.key**
    reverse_proxy  https://10.1.1.1:8443 {
        header_up Host {host}
    }
}

crt content same

the two site tls crt/key config is same, but caddy load two TLSCertificate with tag site1=>["cert0"] site2=>["cert1"], then cache TLSCertificate by hash, the cached TLSCertificate tags just ["cert0"], so the site2 Handshake will tls error
![image](https://user-images.githubusercontent.com/19551155/195753783-cbb3cb74-b435-45df-b677-22180a10c4d4.png)

**Comment by mholt** [comment]
Thanks for the report. Hmm, that wouldn't surprise me... will look into it. (Or will be happy to review a PR for a faster fix!)

**Comment by mholt** [comment]
@escapezn In your case, does `k.cer` contain a SAN for `b.example.com` also?

**Comment by escapezn** [comment]
k.cer is a wildcard certificate for *.example.com

**Comment by mholt** [comment]
Oh, you know... this might already be fixed in https://github.com/caddyserver/certmagic/commit/a46420babdc80437ac128dc3942ada18be0786db. The original issue was https://github.com/caddyserver/certmagic/issues/211 but unfortunately I never received any confirmation that the patch fixes it for them. @New2Niu that patch should go out with the next release, but before it does, could you verify that it works for you? You'll just need to build Caddy using the latest CertMagic. Let me know if you need help doing that.
