### ISSUE TITLE
When does `caddy upgrade` pick up new releases?

### ISSUE THREAD

**Issue by timkgh** [caddyserver/caddy#5155]
Currently `caddy upgrade` still downloads 2.6.1

Is there a built-in delay for safety reasons?

**Comment by mholt** [comment]
No, it should pick up the latest tagged version (that's not a pre-release).

I'm seeing that happen too. I am not sure why :thinking: I will need to look into it when I have a chance.

**Comment by mholt** [comment]
Hm, ok nevermind, I cleared the build cache on our server and it's downloading 2.6.2 now. 

I remember clearing the build cache after tagging 2.6.2 though, so weird. The build server must not have caught onto the new tag until after a build for 2.6.1 was finished. I really need to fix the build server sometime so that it will download the latest stable and disregard the build cache in that case.
