### ISSUE TITLE
Allow trusted_proxies_header

### ISSUE THREAD

**Issue by aadnehovda** [caddyserver/caddy#5193]
Currently it's only possible to trust a proxy by IP range, but if you run your site behind for example Azure Front Door it makes sense to instead or additionally validate the `X-Azure-FDID` header. The value of this header is set to the ID of the Front Door resource in Azure and is only passed to the backend servers (my server) so it should not leak. 

So for example in a Caddyfile

```
php_fastcgi unix//run/php/php-fpm.sock {
    trusted_proxies_header X-Azure-FDID 9c4888d4-f687-4917-987e-777fe1ed2eaf
}
```
https://learn.microsoft.com/en-us/azure/frontdoor/origin-security?tabs=app-service-functions&pivots=front-door-standard-premium#front-door-identifier

**Comment by francislavoie** [comment]
Huh, interesting.

> When Front Door makes a request to your origin, it adds the X-Azure-FDID request header. Your origin should inspect the header on incoming requests, and reject requests where the value doesn't match your Front Door profile's identifier.

According to this, shouldn't you outright reject requests that don't have this header? You can do that with the `header` matcher, and use the `abort` directive to cancel requests that don't match.

Do you have a usecase for still allowing requests not coming directly from Azure?

**Comment by aadnehovda** [comment]
You are right, a use case would maybe be for debugging or testing purposes, like testing backend servers before adding them to the pool. 

However, as mentioned in the MS docs, all Front Door instances will be using the same IP ranges. Could there be a potenial risk that someone could set up a malicious Front Door instance and reverse proxy your site onto a different domain, spoof or manipulate headers, like the client IP in order to circumvent location aware content on your site or impersonate your site in order to track users, or other privacy issues? 

The list of IP ranges may be changing frequently (someone scripted the updates for download at https://azureipranges.azurewebsites.net/getPrefixes/Public/AzureFrontDoor.Backend), so if we were to only rely on trusted_proxies it needs to be automated somehow, maybe through the API? Not sure, I'm pretty new to Caddy. 

`trusted_proxies` implies that the proxies are in fact trusted, but it seems to me that basing the trust on the IP address alone may not be sufficient in all cases.

**Comment by aadnehovda** [comment]
Another thing I noticed is that there now is a standardized [`Forwarded`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) request header which should probably also be protected from untrusted proxies?

**Comment by francislavoie** [comment]
All that `trusted_proxies` does is tell the proxy that it's ok to read the incoming values for a few `X-Forwarded-*` headers.

If the list of IPs/ranges is too large or dynamic, then you can just use `0.0.0.0/0` to tell Caddy to trust all IPv4, if you're doing your own checks to either reject or sanitize untrusted requests.

If you do need to directly reach your server for debugging, wouldn't you will know the value to use for your header matcher? Then you should be able to add the header to your client making requests for testing as well. Or you use a different secret debugging value for the header as a back door.

Re the `Forwarded` header, we did consider supporting it, but even though it is a "standard", pretty much nobody uses it. Partly because everyone is already satisfied with the `X-` headers and partly because parsing and manipulating its value is more complicated (because it bundles every kind of data in the same header) for very little benefit. If your app does use that header, then you could write a Caddy module to handle it. But for now we deem it not worth it unless the industry makes strides in that direction (unlikely). See https://github.com/caddyserver/caddy/issues/3262 for our research on this.

**Comment by aadnehovda** [comment]
I realize I didn't really look around much for existing discussion around `Forwarded`, it makes sense to ignore it for now (nginx too only provides [config workaround](https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/) for that).

I'll add the header match check and just disable it while debugging, easy enough. Can't really use `trusted_proxies` because of the shared and dynamic IP ranges. Maybe add something more to the [docs](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#defaults) about this issue, since it will also affect similar services like CloudFront, CloudFlare.

(Btw, there seems to be many ways to protect the origin from rogue proxies, e.g. [private networks](https://learn.microsoft.com/en-us/azure/frontdoor/private-link), firewall, iptables, [secrets in headers](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-overview.html#forward-custom-headers-restrict-access) or [TLS client auth](https://blog.cloudflare.com/protecting-the-origin-with-tls-authenticated-origin-pulls/).)

**Comment by francislavoie** [comment]
Yeah. I do plan on setting up a module interface for plugins to implement a trust decision function. The `cloudflare` plugin could provide a module that periodically fetches and caches the CloudFlare IP ranges and compares against that list, or checks client auth for a trusted CA.

I think I'll close this issue though, because I don't think `trusted_proxies_header` is the right approach. Thanks for the discussion though!
