### ISSUE TITLE
How to use the Caddyfile reverse proxy https service？？

### ISSUE THREAD

**Issue by ivanmissu** [caddyserver/caddy#5195]
My reverse proxy server is a self signed https service. How can I configure caddyfile to enable https reverse proxy
The document says it can be set, how to set it

![image](https://user-images.githubusercontent.com/8721615/201017304-cec25208-a315-430d-ab4e-b63ee01214d1.png)

**Comment by mholt** [comment]
You can either install your self-signed cert into the system trust store (how to do that depends on your operating system / environment, so please Google that one) or you can configure Caddy's reverse proxy to trust it; this requires a Caddyfile or JSON config.

In the Caddyfile, customize the `http` transport to accept your CA when connecting with TLS: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#tls_trusted_ca_certs

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your next question there. The Help category in the forum even provides a template you can fill out.

Thanks for using Caddy!
