### ISSUE TITLE
Get placeholder array from index

### ISSUE THREAD

**Issue by davidpanic** [caddyserver/caddy#5202]
I would like to be able to get placeholder values like some programming languages allow to with "rest" arguments. Perhaps it's best explained with an example:

```Caddyfile
(myservice) {
    {args.0}.some.domain {
        reverse_proxy {args.1...} {
            ...a ton of options that I don't want to repeat
        }
    }
}

import myservice service.a http://192.168.60.1:8081 http://192.168.60.2:8081 http://192.168.60.3:8081
import myservice service.b http://192.168.60.4:8181 http://192.168.60.5:8181
```

As you can see there's a different amount of arguments (in this case upstream URLs) defined in the import and I want to just specify them all for the reverse proxy upstreams.

To my knowledge there is currently no way to do this, you must specify the arguments by index which doesn't work for variable length arguments.

**Comment by francislavoie** [comment]
I've thought about implementing something like this before, but I couldn't think of a good way to do it.

It happens here in the codebase if you'd like to take a look:

https://github.com/caddyserver/caddy/blob/master/caddyconfig/caddyfile/parse.go#L345-L352

(And further down, it does ReplaceKnown to actually replace stuff.)

As for the syntax... I think using `...` doesn't look great because we already use a dot in between. It is similar to Go syntax so it has that going for it.

Could be something like `{args.1+}` where the plus means everything starting at arg 1 and after it. Might be more readable that way, I dunno.

I guess one way it could be implemented is by filling the replacer with a `+` variant for each entry that is the current arg and all the following ones, for each index provided. That could work.

**Comment by davidpanic** [comment]
> I guess one way it could be implemented is by filling the replacer with a + variant for each entry that is the current arg and all the following ones, for each index provided. That could work.

Sounds easy enough to add, I'm all for it! I can implement it and make a PR if you'd like.

**Comment by mholt** [comment]
After looking at this more, I'm wondering if we could keep the `:` but instead of the `.`, use square brackets?

So, `args[0]` and `args[-1]` and `args[:3]` instead of `args.0` or `args.-1` or `args.:3`.

**Comment by francislavoie** [comment]
To elaborate on that, I think we can keep the old `{args.0}` syntax around for now, without variadic support. We can introduce the this new `{args[0]}` syntax which includes variadic support.

We can mark the old syntax as deprecated with a Caddyfile adapt warning maybe. But we could defer writing the warning until a later release to not be too annoying.
