### ISSUE TITLE
New OSs illumos solaris

### ISSUE THREAD

**Issue by neuroserve** [caddyserver/caddy#5213]
Hi *,

would it be possible to add artifacts for the OSs illumos (https://illumos.org/) and/or Solaris? If you use xgo anyways, that should be possible.

**Comment by mohammed90** [comment]
The build on Solaris is failing due to `unix.SO_REUSEPORT` not exist in `golang.org/x/sys/unix`.

```
~/projects/caddyserver/caddy/cmd/caddy $ GOOS=solaris go build                                                                                                go1.19.3
# github.com/caddyserver/caddy/v2
../../listen_unix.go:110:71: undefined: unix.SO_REUSEPORT
```

There was a CL to add it, but it got abandoned by the author:
https://go-review.googlesource.com/c/sys/+/331989

If you have access to a Solaris/Illumos machine, maybe you can generate the definition files to fix it upstream. As it stands, we don't have the resources to support Solaris/Illumos, as much as we'd love to.
