### ISSUE TITLE
How to config my Caddfile （change nginx configuration  to caddy ）

### ISSUE THREAD

**Issue by austinuMyaccount** [caddyserver/caddy#5215]
### 1a. Operating system and version

```
CentOS 7
```

### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.6.2 h1:wKoFIxpmOJLGl3QXoo6PNbYvGW4xLEgo32GPBEjWL8o=
```

### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```

### 2a. What happens (briefly explain what is wrong)

1). how to visit my project by directory

for  example  , visit  the website ，https://localhost/admin， browse admin projet,
 
visit  the website ，https://localhost/app， browse app projet.

2). how to  implement such proxy

nginx configuration

```shell
          location /nacos {              
              proxy_pass http://127.0.0.1:8848/nacos;
          }

```

### 2c. Log output

```
paste terminal output or logs here
```

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! So far, this doesn't look like a bug in Caddy. It looks more like a question about how to use Caddy rather than a bug report or feature request.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!
