### ISSUE TITLE
How use automatic HTTPS on some matched domains, and use a custom self signed on all non-matched domains?

### ISSUE THREAD

**Issue by voxsoftware** [caddyserver/caddy#5219]
I am using a JSON file configuration.
I added something like this:

```json 
"match": [
          {
                  "host": [
                          "my.domain.com",
                          "*"
                  ]
          }
  ]

```

and with this, my.domain.com works ok, with automatic SSL got from let's encrypt.
But all other domains (or using IP) over HTTPS shows: 

```bash
Este sitio web no puede proporcionar una conexión segura X.XX.XXX.XXX ha enviado una respuesta no válida.
ERR_SSL_PROTOCOL_ERROR
``` 

If I configure a tls connection policy, now all sites works with my self signed certificate, the problem is **ALL DOMAINS** use the same self-signed certificate (also **my.domain.com**).

Please, my question is: how configure only **my.domain.com** works with automatic, and all other with my custom tls policy?
PLEASE NEED HELP, I read all documentation, and i cannot find the way to do this

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! So far, this doesn't look like a bug in Caddy. It looks more like a question about how to use Caddy rather than a bug report or feature request.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!
