### ISSUE TITLE
Admin API endpoint origins ignored?

### ISSUE THREAD

**Issue by waltherwh1te** [caddyserver/caddy#5226]
Ok, so I have a Caddyfile like this:

```
{
	debug
	admin :2019 {
		origins 172.20.0.2
	}
	servers {
		metrics
	}
}
```

If I then do `curl "http://caddyhost:2019/config/"` from an ip address _other than_ 172.20.0.2, I still get get a valid config response.
What am I missing here? Shouldn't `origins` act as a whitelist?

**Comment by mholt** [comment]
You're missing `enforce_origin` which turns on CORS handling.

The reason it's separate from listing the origins is because we separately do Host checking, which is used for DNS rebinding mitigation, which we always do if a wildcard network interface is _not_ used for the admin endpoint. The list of allowed hosts is derived from the origins in that list. Origin checking is further restrictive, enabling CORS logic, basically.

Hope that helps!
