### ISSUE TITLE
handel https in custome domain ssl

### ISSUE THREAD

**Issue by vahidalvandi** [caddyserver/caddy#5279]
hi
I have a saas system in which the user can define other domains. And by setting the saas server ip on any domain with ssl, it can see saas.
After much research, I came to the conclusion that caddy can solve this problem . do this package can solve my problem??****

(main domain)
sitename.com
customer can create self subdomain like  my.sitename.com . maybe add to self domain like my.example.com 

**i want to handel ssl in my.example.com**

**Comment by mholt** [comment]
You're looking for this article on our wiki: https://caddy.community/t/serving-tens-of-thousands-of-domains-over-https-with-caddy/11179?u=matt

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) that hosts our wiki where you can post further questions. Thanks!
