### ISSUE TITLE
caddy does Dynamic proxy configuration exist?

### ISSUE THREAD

**Issue by yunqiangwu** [caddyserver/caddy#5286]
caddy does Dynamic proxy configuration exist?

nginx config 

```
  server {
    listen 80;
    server_name _;
    location / {
        default_type text/plain;
        if ($http_p_ip = "") {
            return 400 "please set http header p-ip\n";
        }
        if ($http_p_host = "") {
            return 400 "please set http header p-host\n";
        }
        # return 200 "p-host: $http_p_host\np-ip: $http_p_ip\n";
        proxy_set_header Host $http_p_host;
        proxy_pass $http_p_ip;
     }
  }
```

test bash curl

```
curl 127.0.0.1:80 --header "p-host: www.baidu.com" --header "p-ip: http://180.97.34.96"
```

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! So far, this doesn't look like a bug in Caddy. It looks more like a question about how to use Caddy rather than a bug report or feature request.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!
