### ISSUE TITLE
Allow returning 1 if lint fails

### ISSUE THREAD

**Issue by Hongbo-Miao** [caddyserver/caddy#5294]
Right now we have

```shell
Usage:
  caddy fmt [flags]

Flags:
      --diff        Print the differences between the input file and the formatted output
  -h, --help        help for fmt
      --overwrite   Overwrite the input file with the results
```

I originally thought `caddy fmt` will return `1` if failed like most other linters. It turns out not. It returns formatted content instead.
If we don't want to change the behavior of `caddy fmt`, it would be great to provide another flag to allow returning `1` for failure. Thanks! 😃

**Comment by francislavoie** [comment]
Ah yeah, that's a reasonable change.

PRs welcome! Should be very simple.

**Comment by u5surf** [comment]
@Hongbo-Miao @francislavoie 
Hi, I would like to work on this issue.
How is that like this?
```
% ./caddy fmt        
{
        debug
        log stdout
        admin 0.0.0.0:2018
        grace_period 1s
}

:8888 {
        log
        root * /home/u5surf/test
        php_fastcgi unix//run/php/php8.1-fpm.sock {
                #buffer_requests
                #flush_interval -1
        }
}
% echo $?
0
% ./caddy fmt --exit1
{
        debug
        log stdout
        admin 0.0.0.0:2018
        grace_period 1s
}

:8888 {
        log
        root * /home/u5surf/test
        php_fastcgi unix//run/php/php8.1-fpm.sock {
                #buffer_requests
                #flush_interval -1
        }
}
Error: diff found
% echo $?            
1
% diff Caddyfile <(./caddy fmt)
8c8
< :8888  {
---
> :8888 {
```

**Comment by Hongbo-Miao** [comment]
Thanks @u5surf ! Really appreciate! 🚀
Personally I would vote for a breaking change to change the existing behavior of `caddy fmt` as it aligns with all other linters. But let's wait @francislavoie thoughts! 😃

**Comment by francislavoie** [comment]
I agree, I highly doubt anyone was relying on the existing return code. Let's just return 1 by default if the formatted output has any differences.

**Comment by u5surf** [comment]
@Hongbo-Miao @francislavoie 
OK, I agree with your suggestions.
I consider there is only one problem, `caddyCommandToCoral`  ignores the exit code( the first return value) which the command function returns.
Thus if we’d like to be exit 1 in this scenario, it must returns something error messages with `fmt.Errorf` in `runFmt` in case of current `caddyCommandToCoral`.

https://github.com/caddyserver/caddy/blob/223cbe3d0b50487117c785f0755bb80a9ee65010/cmd/cobra.go#L114-L115

**Comment by mohammed90** [comment]
> @Hongbo-Miao @francislavoie 
> OK, I agree with your suggestions.
> I consider there is only one problem, `caddyCommandToCoral`  ignores the exit code( the first return value) which the command function returns.
> Thus if we’d like to be exit 1 in this scenario, it must returns something error messages with `fmt.Errorf` in `runFmt` in case of current `caddyCommandToCoral`.
> 
> https://github.com/caddyserver/caddy/blob/223cbe3d0b50487117c785f0755bb80a9ee65010/cmd/cobra.go#L114-L115

You should look into the `fmtCmd` function, not `cmdToCoral`.

https://github.com/caddyserver/caddy/blob/223cbe3d0b50487117c785f0755bb80a9ee65010/cmd/commandfuncs.go#L532

It should return an error from there if the input and output mismatch. You'll face a tricky part where we're already returning `1` if we fail to read the input. Should the code for both be the same? Perhaps.

@francislavoie, do you think an extra flag is necessary? I doubt it's breaking anyone if we switch from returning 0 to returning 1?

**Comment by francislavoie** [comment]
No I don't think we need a flag at all, as I said above.

**Comment by u5surf** [comment]
@mohammed90 
> You should look into the cmdFmt function, not cmdToCoral.

`runFmt` is a member of `Command` struct, which is the argument of the `RegisterCommand` function.
https://github.com/caddyserver/caddy/blob/223cbe3d0b50487117c785f0755bb80a9ee65010/cmd/commands.go#L304-L308

We can see the `cmdToCoral` function is called at last of `RegisterCommand` function. which received the cmd is the entity　of `Command`.
https://github.com/caddyserver/caddy/blob/223cbe3d0b50487117c785f0755bb80a9ee65010/cmd/commands.go#L491-L507
That is why I focus on the `cmdToCoral`, and I can see the entity of the `runFmt` is called in `cmdToCoral` but the first return value which stands for exit code is ignored in cobra.go L.114

https://github.com/caddyserver/caddy/blob/223cbe3d0b50487117c785f0755bb80a9ee65010/cmd/cobra.go#L107-L117

I'd like to say is `RunE` writes some  error messages if the function returns error which is stands for the second return value in cobra.go L.114. Thus we should set the error messages if the input and output mismatch. 

Alternative: 
If you would like to ignore such messages it can set SilenceErrors is true.
But I consider that it will be a breaking change seriously because it forces to ignore the all of the error messages which are made by its subcommand function.

https://github.com/spf13/cobra/blob/main/command.go#L1050
