### ISSUE TITLE
Getting letsencrypt related errors while trying to reverse proxy

### ISSUE THREAD

**Issue by lilisore** [caddyserver/caddy#5310]
1. Caddy version (caddy version):
v2.6.2 h1:wKoFIxpmOJLGl3QXoo6PNbYvGW4xLEgo32GPBEjWL8o=

2. How I run Caddy:
a. System environment:
Ubuntu 20.04.5 LTS

b. Command:
caddy start

c. My complete Caddyfile or JSON config:
l***.600***.xyz {                                          
    reverse_proxy 127.0.0.1:3703
}

4. The problem I’m having:
As the question already specifes i am simply trying to reverse proxy using the Caddyfile , although i keep getting some letsencrypt related errors . I being pretty new to these stuff have no clue on how do i fix this . Hopefully someone can help me out here . Thanks in advance

5.Domain name resolution method
I use cloudfare in front of my server. I added a DNS A record (name = subdomain, ipv4 address = external ip of my vps)

6.Port check
when i entered my vps’s external ip and check port through this website - [Open Port Check Tool - Test Port Forwarding on Your Router 287](https://www.yougetsignal.com/tools/open-ports/) it told me both 80 and 443 are open
Open Port [443](http://en.wikipedia.org/wiki/Port_443) is open on [l***.600***.xyz](https://l***.600****.xyz/).
Open Port [80](http://en.wikipedia.org/wiki/Port_80) is open on [l***.600***.xyz](https://l***.600****.xyz/).

7. Error messages and/or full log output:
2023/01/16 15:29:12.601 INFO    http.acme_client        trying to solve challenge       {"identifier": "l***.600***.xyz", "challenge_type": "tls-alpn-01", "ca": "https://acme-v02.api.letsencrypt.org/directory"}
2023/01/16 15:29:23.516 ERROR   http.acme_client        challenge failed        {"identifier": "l***.600***.xyz", "challenge_type": "tls-alpn-01", "problem": {"type": "urn:ietf:params:acme:error:connection", "title": "", "detail": "27.0.234.77: Timeout during read (your server may be slow or overloaded)", "instance": "", "subproblems": []}}
2023/01/16 15:29:23.516 ERROR   http.acme_client        validating authorization        {"identifier": "l***.600***.xyz", "problem": {"type": "urn:ietf:params:acme:error:connection", "title": "", "detail": "27.0.234.77: Timeout during read (your server may be slow or overloaded)", "instance": "", "subproblems": []}, "order": "https://acme-v02.api.letsencrypt.org/acme/order/919469537/159166870857", "attempt": 2, "max_attempts": 3}
2023/01/16 15:29:23.516 ERROR   tls.obtain      could not get certificate from issuer   {"identifier": "l***.600***.xyz", "issuer": "acme-v02.api.letsencrypt.org-directory", "error": "HTTP 400 urn:ietf:params:acme:error:connection - 27.0.234.77: Timeout during read (your server may be slow or overloaded)"}
2023/01/16 15:29:23.516 WARN    http    missing email address for ZeroSSL; it is strongly recommended to set one for next time

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! So far, this doesn't look like a bug in Caddy. It looks more like a question about how to use Caddy rather than a bug report or feature request.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!
