### ISSUE TITLE
Caddy Reverse Proxy Getting Really Slow when using TLS | Encryption Overhead?

### ISSUE THREAD

**Issue by BayMax-1010** [caddyserver/caddy#5334]
**This is a valid Caddy Configuration?**

````
  reverse_proxy http://localhost:3000 {
         buffer_requests
         buffer_responses
         flush_interval -1
         max_buffer_size 35MiB
        }
````
 https://github.com/openspeedtest/Speed-Test/issues/67

I am running OpenSpeedTest Container 

````
docker run --restart=unless-stopped --name openspeedtest -d -p 3000:3000 -p 3001:3001 openspeedtest/latest
````

**Caddy Performance**

-  9500 for Download and 9600 for Download when using HTTP

-  5400 for Download and 1200 for Upload when using HTTPS

**Why I am getting very slow performance when I use HTTPS?**

**Test without using Caddy**

- 9500 for Download and 9600 for Download when using HTTP (3000 Docker Port)

- 9500 for Download and 9600 for Download when using HTTPS (3001 Docker Port)

**Comment by mholt** [comment]
> This is a valid Caddy Configuration?

No, it's missing the site address at the top.

So far, this doesn't look like a bug in Caddy. It looks more like a question about OpenSpeedTest rather than a bug report or feature request for Caddy.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!
