### ISSUE TITLE
reverse_proxy enderpoint can not resolve mDNS ".local" domain

### ISSUE THREAD

**Issue by sky96111** [caddyserver/caddy#5372]
https://en.wikipedia.org/wiki/Multicast_DNS

I installed package `avahi` and `nss-mdns`  to provide local mDNS. Device installing Caddy is `asusjwb.local` , reverse_proxy source device is `wireguard.local` . 
All other application can connect to other device by using `wireguard.local`
````
[root@asusjwb ~]# LANG=c ping wireguard.local
PING wireguard.local (192.168.122.101) 56(84) bytes of data.
64 bytes from 192.168.122.101 (192.168.122.101): icmp_seq=1 ttl=64 time=0.084 ms
64 bytes from 192.168.122.101 (192.168.122.101): icmp_seq=2 ttl=64 time=0.101 ms
64 bytes from 192.168.122.101 (192.168.122.101): icmp_seq=3 ttl=64 time=0.081 ms
64 bytes from 192.168.122.101 (192.168.122.101): icmp_seq=4 ttl=64 time=0.072 ms
````
````
[root@asusjwb ~]# LANG=c ssh root@wireguard.local
Web console: https://WireGuard:9090/ or https://192.168.122.101:9090/

Last login: Mon Feb 13 13:10:23 2023
````

While Caddy can not resolve mDNS domain to ip address in reverse_proxy enderpoint, it logs:
````
20:54:49 asusjwb caddy[1226]: {"level":"error","ts":1676292889.38499,"logger":"http.log.error","msg":"dial tcp: lookup wireguard.local on 10.70.51.123:53: no such host","request":{"remote_ip":"10.68.1
74.128","remote_port":"41606","proto":"HTTP/2.0","method":"GET","host":"adg.example.com","uri":"/","headers":{"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0"],"Accept-
Language":["zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2"],"Accept-Encoding":["gzip, deflate, br"],"Cookie":[],"Sec-Fetch-Site":["none"],"Te":["trailers"],"Accept":["text/html,application/xhtm
l+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"],"Upgrade-Insecure-Requests":["1"],"Sec-Fetch-Dest":["document"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-User":["?1"]},"tls":{"resumed":false,"ve
rsion":772,"cipher_suite":4865,"proto":"h2","server_name":"cockpit.example.com"}},"duration":0.310550748,"status":502,"err_id":"ansievdx4","err_trace":"reverseproxy.statusError (reverseproxy.go:1281)"}
````

----
An example of Caddyfile:
````
*.example.com {
	encode gzip zstd
	tls {
		dns cloudflare API_KEY
	}
	
	respond "404" 404 {
		close
	}

	@cockpit host cockpit.example.com
	handle @cockpit {
		reverse_proxy localhost:9090
	}

        @adg host adg.example.com
        handle @adg {
		reverse_proxy wireguard.local:3000
	}
}

````

----
env
```
caddy: v2.6.3 h1:QRVBNIqfpqZ1eJacY44I6eUC1OcxQ8D04EKImzpj7S8=
OS: Rocky Linux 9.1 (Blue Onyx) x86_64
Kernel: 5.14.0-162.12.1.el9_1.0.2.x86_64
```

**Comment by mholt** [comment]
That is not a regular DNS entry, so I don't think Go will find it, according to this: https://stackoverflow.com/questions/52131336/net-lookuphost-outputs-no-such-host-after-using-os-hostname

You could try setting `export GODEBUG=netdns=cgo` and trying again, but Caddy is statically compiled without cgo, so I doubt that will work. (By default Go uses its own resolver.) You could try building it _with_ cgo (CGO_ENABLED=1) and then trying that env var again to see if it'll use the system resolver.

**Comment by sky96111** [comment]
It works good with cgo build
````
export GODEBUG=netdns=cgo
export CGO_ENABLED=1
go build
````

Also, I find a pure go mDNS implementation https://github.com/hashicorp/mdns
Will there be an official implementation of this feature in caddy?

**Comment by mholt** [comment]
I don't think we have plans for it. (We wouldn't know when a domain is mDNS or not, for example; it would get complicated.) We could probably implement it if a sufficiently-tiered sponsor advocates for it.

Glad the cgo build works for you, at least!

**Comment by francislavoie** [comment]
@mholt I think we should work on this at some point. I think it would be pretty easy.

We could add support to the resolvers config in reverse_proxy to use hashicorp/mdns opt-in. We already have resolvers config currently, but we'd just need to allow setting it to a module instead of simply an IP address.

Also I think we should implement an mdns app in Caddy which acts as an mdns responder, which we would auto-configure with auto-https if we see any `.local` host matchers.

**Comment by mholt** [comment]
I'd love to see it, especially if it's easy :sweat_smile:

Some of those might be better as third-party modules for now.

**Comment by icco** [comment]
I also would love to see mdns resolution support. If not in main caddy, in an easy to use flag for xcaddy.

**Comment by sky96111** [comment]
> I also would love to see mdns resolution support. If not in main caddy, in an easy to use flag for xcaddy.

Finally I turned to systemd-resolve to address this problem.
It handles mDNS and  provides a standard UDP DNS server locally (127.0.0.53).
Making app which doesn't use libnss (app written in golang) ability to resolve mDNS address.

**Comment by francislavoie** [comment]
FYI my comment above misrepresented how easy it would be.

The trouble is that most Linux machines already have systemd-resolved bound to port 5353 etc, so it can't really work automatically on most installations. We could go down the path of trying to push config to systemd-resolved, but that locks Caddy into only working on systemd machines.

What if you run in Docker, on a Linux host with systemd, then how do we push config to the host? What about on Windows and Mac?

There's too many question marks here for me so I have no plans to work on this. If someone wants to take it on though, go ahead.

**Comment by pdxrlk** [comment]
> > I also would love to see mdns resolution support. If not in main caddy, in an easy to use flag for xcaddy.
> 
> Finally I turned to systemd-resolve to address this problem. It handles mDNS and provides a standard UDP DNS server locally (127.0.0.53). Making app which doesn't use libnss (app written in golang) ability to resolve mDNS address.

Could you share how you set up systemd-resolve to provide this service?

**Comment by sky96111** [comment]
> > > I also would love to see mdns resolution support. If not in main caddy, in an easy to use flag for xcaddy.
> > 
> > Finally I turned to systemd-resolve to address this problem. It handles mDNS and provides a standard UDP DNS server locally (127.0.0.53). Making app which doesn't use libnss (app written in golang) ability to resolve mDNS address.
> 
> Could you share how you set up systemd-resolve to provide this service? 

Just set MulticastDNS=yes in resolved.conf and enable systemd-resolved.
Then use mdns address in caddyfile. That's all.

**Comment by codeiimon** [comment]
Bit of an old thread but I thought I might post my solution, in case anyone else had the same issue as me.

>Just set MulticastDNS=yes in resolved.conf and enable systemd-resolved.
>Then use mdns address in caddyfile. That's all.

This unfortunately did not work for me on my LXC container running Ubuntu 24.04. Heres what did to get it working:

1. If you are running tailscale, run `tailscale set --accept-dns=false`. If you don't the changes systemd-resolved makes to the /etc/resolv.conf file will out put `search <tailscale ip>` rather than `search .`
2. Go into your systemd-resolved config file with `nano /etc/systemd/resolved.conf` and set `MulticastDNS=yes` like the above comment says. Also set `LLMNR=no` which can conflict with mDNS.
3. Now to create a script that runs on boot. This will run the command `resolvectl mdns eth0 yes` (Even though I should be set in the config we edited earlier, I needed to manually set it this way for some reason). It will also symlink the /etc/resolv.conf file to systemd-resolved's file, as proxmox kept changing my LXC's resolv.conf on boot. You'll need to run `nano /usr/local/bin/enable-mdns.sh` and place this script inside it. Then make it runnable with `chmod +x /usr/local/bin/fix-mdns.sh`:
```
#!/bin/bash

# Wait until eth0 is up
tries=0
while ! resolvectl status eth0 | grep -q "Link"; do
	sleep 0.5
	tries=$((tries+1))
	if [ $tries -gt 20 ]; then
		echo "Timed out waiting for eth0"
		exit 1
	fi
done

# Enable mDNS on eth0
resolvectl mdns eth0 yes

# Wait for stub file to appear
tries=0
while [ ! -f /run/systemd/resolve/stub-resolv.conf ]; do
	sleep 0.5
	tries=$((tries+1))
	if [ $tries -gt 20 ]; then
		echo "Timed out waiting for stub-resolv.conf"
		exit 1
	fi
done

# Replace resolv.conf symlink if necessary
if [ ! -L /etc/resolv.conf ] || [ "$(readlink -f /etc/resolv.conf)" != "/run/systemd/resolve/stub-resolv.conf" ]; then
	echo "Fixing /etc/resolv.conf symlink..."
	rm -f /etc/resolv.conf
	ln -s /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
fi

# Restart systemd-resolved to apply changes
echo "Restarting systemd-resolved..."
systemctl restart systemd-resolved
```
4. Now to create a service to run the service on boot. Use `nano /etc/systemd/system/enable-mdns.service` and write the code below into it:
```
[Unit]
Description=Enable mDNS on eth0 via resolvectl
After=network-online.target systemd-resolved.service
Requires=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/enable-mdns.sh

[Install]
WantedBy=multi-user.target
```
5. Now enable and start it with `systemctl enable enable-mds.service` and `systemctl start enable-mds.service
6. Now you can use .local addresses on your caddyfile!

Disclaimer: This code is very amateur as I'm very new to all this. Please back up your system before performing all these steps if you can. I'm probably making this overly complicated so if you have any suggestion to make it more clean/simple please let me know.
