### ISSUE TITLE
Cannot edit Caddyfile

### ISSUE THREAD

**Issue by pepe-the-saxophonist** [caddyserver/caddy#5373]
When I try to edit the caddyfile with Sublime Text or Text Editor on Ubuntu, it opens as "Read-Only". When I try to edit it with the terminal, it says that I do not have the right permissions. Also, the Terminal says that I cannot make the directories "var/www/html" also because of a permission issue. I'm kinda of new to Unix commands so I have a heavy load on my shoulders. Can somebody help me to ease my pain?

Thanks,
Pepe

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! So far, this doesn't look like a bug in Caddy. It looks more like a question about how to use Linux rather than a bug report or feature request.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!
