### ISSUE TITLE
[idea collection] make caddyfile more modular 

### ISSUE THREAD

**Issue by Neon-44** [caddyserver/caddy#5391]
i didn't want to flood you with issues, so i made a collection of my ideas. 
let me know if i should split this up into separate issues

1. variables in Domain Names (or in general). example:
```
{$local-domain} = local.domain.tld
nextcloud.{$local-domain} {}
gitea.{$local-domain} {}
plex.{$local-domain} {}
*.{$local-domain} {}
```
2. "dictating" wildcard-domainnames. example:
```
(local-only) { 
 @not-local not remote_ip 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
 respond @not-local "website only available to local domains" 
}
*.local.domain.tld {
 dictate import local-only
}
```
which then forces every subdomain of .local.domain.tld to also import the local-only snippet

3. force subdomains to use wildcard tls certificate. example:
```
*.local.domain.tld {
 tls {}
}
plex.local.domain.tld {
 tls {
  managed off
 }
}
```
which would then tie in perfectly with my nr.2:
```
(wildcard-cert) {
tls { managed off }
}
*.local.domain.tld {
tls {}
dictate import wildcard-cert
}
nextcloud.local.domain.tld {
reverse_proxy
}
```
which in turn would tie in perfectly with my nr.1:
```
{$local-domain} = local.domain.tld

(wildcard-cert) { tls {managed off } }

*.{$local-domain} {
 dictate import wildcard-cert
}

nextcloud.{$local-domain} {reverse_proxy}
```

i understand that you already have a solution to nr.3 with handlers, but this solution would allow independent import statements outside of the wildcard domain, which are easier to comment out and/or automate.
i, for example. use caddy-docker-proxy to automatically import corresponding CaddyFiles. this only imports them at the end of the file, making it unable to import handlers into a wildcard-domain

P.S: i think this Project is absolutely amazing and i absolutely love / adore it. this "issue" is meant as a "wow, this project is amazing. look at these cool ideas that would make it _even better_!", and not as a critique
i know that FOSS developers have to put up with rude and snobbish people all the time, so i just wanted to tell you how amazing you are ❤️

**Comment by francislavoie** [comment]
For 1. you can use environment variables: https://caddyserver.com/docs/caddyfile/concepts#environment-variables

For 2. in general we're against any implicit configuration patterns. We intentionally designed the Caddyfile to be explicitly configured so that it's always clear and obvious by reading any site what it does. If we add something like this, we'll inevitably get requests from other users to "unset" this for _some_ sites. And that gets very very complicated. So we rather just never go down the path of implicit config.

For 3. the problem is that Automatic HTTPS specifically depends on the route layout to correctly determine which site addresses should be managed certificates and which shouldn't. Using `handle` blocks is the best way to do it.

Thanks for the kind words!

**Comment by Neon-44** [comment]
sad but understandable.
thanks for all your hard work ❤️
