### ISSUE TITLE
"no upstreams available" when healthcheck used in php_fastcgi

### ISSUE THREAD

**Issue by maidmaid** [caddyserver/caddy#5402]
### 1a. Operating system and version

```
alpine 3.17.2
```

### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.6.4 h1:2hwYqiRwk1tf3VruhMpLcYTg+11fCdr8S3jhNAdnPy8=
```

### 1c. Go version (if building Caddy from source; run `go version`)

```
n/a
```

### 2a. What happens (briefly explain what is wrong)

I'm trying https://github.com/caddyserver/caddy/issues/5281 on my prod and I get a 503 error if I access to the page from the browser while caddy is iterating heathchecks.

### 2b. Why it's a bug (if it's not obvious)

503 response

### 2c. Log output

```json
{
    "ts": 1677436806.2188864,
    "err_id": "iq5jrxxqh",
    "logger": "http.log.error",
    "duration": 0.00016863,
    "status": 503,
    "level": "error",
    "err_trace": "reverseproxy.(*Handler).proxyLoopIteration (reverseproxy.go:547)",
    "msg": "no upstreams available"
}
```

### 2d. Workaround(s)

n/a

### 2e. Relevant links

n/a

## 3. Tutorial (minimal steps to reproduce the bug)

<details>
<summary>Dockerfile</summary>

```Dockerfile
#syntax=docker/dockerfile:1.4

FROM php:8.2-fpm-alpine AS app_php
RUN mkdir -p /var/run/php

RUN apk add caddy

ADD https://github.com/just-containers/s6-overlay/releases/download/v3.1.2.1/s6-overlay-noarch.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v3.1.2.1/s6-overlay-x86_64.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz

COPY <<EOF /etc/services.d/caddy/run
#!/command/with-contenv sh
caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
EOF
RUN chmod +x /etc/services.d/caddy/run

COPY <<EOF /etc/services.d/php-fpm/run
#!/command/with-contenv sh
sleep 10
php-fpm
EOF
RUN chmod +x /etc/services.d/php-fpm/run

COPY <<EOF /usr/local/etc/php-fpm.d/zz-docker.conf
[global]
daemonize = no

[www]
listen = /var/run/php/php-fpm.sock
listen.mode = 0666
ping.path = /ping
EOF

COPY <<EOF /etc/caddy/Caddyfile
{
    auto_https disable_redirects
}
:80,
:443
log
route {
    root * /srv/app/public
    php_fastcgi unix//var/run/php/php-fpm.sock {
        health_uri /ping
        health_interval 1s
    }
    file_server
}
EOF

COPY <<EOF /srv/app/public/index.php
<?php echo "hello";
EOF

ENTRYPOINT ["/init"]

```

</details>

Build and run :

```
$ COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker build . -t caddy-heathcheck-php
$ docker run --rm -it -p 80:80 caddy-heathcheck-php sh
```

Run the curl in the next 10 seconds :

```
curl http://localhost/index.php
```

**Comment by francislavoie** [comment]
Thanks for opening an issue! We'll look into this.

It's not immediately clear to us what is going on, so we'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by maidmaid** [comment]
The caddy version is `v2.6.4 h1:2hwYqiRwk1tf3VruhMpLcYTg+11fCdr8S3jhNAdnPy8=`.

**Comment by francislavoie** [comment]
We need more than just the version and a single log message. Please fill out that template as requested, otherwise we won't be able to help.

**Comment by maidmaid** [comment]
Thanks for your help @francislavoie, I just updated the PR description with the template.

**Comment by francislavoie** [comment]
Can you enable the `debug` global option and show the logs you see with that?

**Comment by maidmaid** [comment]
It looks like there isn't more useful information:

```
2023/02/26 20:43:35.326	INFO	http.handlers.reverse_proxy.health_checker.active	HTTP request failed	{"host": "localhost", "error": "Get \"http://localhost/ping\": dialing backend: dial unix /var/run/php/php-fpm.sock: connect: no such file or directory"}
2023/02/26 20:43:35.854	ERROR	http.log.error	no upstreams available	{"request": {"remote_ip": "172.17.0.1", "remote_port": "40306", "proto": "HTTP/1.1", "method": "GET", "host": "localhost:8080", "uri": "/index.php", "headers": {"User-Agent": ["curl/7.81.0"], "Accept": ["*/*"]}}, "duration": 0.000495611, "status": 503, "err_id": "4zye6nzsn", "err_trace": "reverseproxy.(*Handler).proxyLoopIteration (reverseproxy.go:547)"}
2023/02/26 20:43:35.854	ERROR	http.log.access	handled request	{"request": {"remote_ip": "172.17.0.1", "remote_port": "40306", "proto": "HTTP/1.1", "method": "GET", "host": "localhost:8080", "uri": "/index.php", "headers": {"Accept": ["*/*"], "User-Agent": ["curl/7.81.0"]}}, "user_id": "", "duration": 0.000495611, "size": 0, "status": 503, "resp_headers": {"Server": ["Caddy"]}}
2023/02/26 20:43:36.326	DEBUG	http.reverse_proxy.transport.fastcgi	roundtrip	{"request": {"remote_ip": "", "remote_port": "", "proto": "HTTP/1.1", "method": "GET", "host": "localhost", "uri": "", "headers": {}}, "env": {"CONTENT_LENGTH": "", "PATH_INFO": "", "REMOTE_PORT": "", "REQUEST_METHOD": "GET", "REQUEST_SCHEME": "http", "SERVER_NAME": "localhost", "SERVER_PROTOCOL": "HTTP/1.1", "HTTP_HOST": "localhost", "REMOTE_IDENT": "", "QUERY_STRING": "", "REMOTE_HOST": "", "REMOTE_USER": "", "SERVER_SOFTWARE": "Caddy/unknown", "DOCUMENT_URI": "/ping", "REQUEST_URI": "/ping", "SERVER_PORT": "80", "CONTENT_TYPE": "", "REMOTE_ADDR": "", "AUTH_TYPE": "", "GATEWAY_INTERFACE": "CGI/1.1", "DOCUMENT_ROOT": "/run/s6/legacy-services/caddy", "SCRIPT_FILENAME": "/run/s6/legacy-services/caddy/ping", "SCRIPT_NAME": "/ping"}, "dial": "/var/run/php/php-fpm.sock", "env": {"SERVER_SOFTWARE": "Caddy/unknown", "DOCUMENT_URI": "/ping", "REQUEST_URI": "/ping", "SERVER_PORT": "80", "REMOTE_IDENT": "", "QUERY_STRING": "", "REMOTE_HOST": "", "REMOTE_USER": "", "CONTENT_TYPE": "", "REMOTE_ADDR": "", "SCRIPT_NAME": "/ping", "AUTH_TYPE": "", "GATEWAY_INTERFACE": "CGI/1.1", "DOCUMENT_ROOT": "/run/s6/legacy-services/caddy", "SCRIPT_FILENAME": "/run/s6/legacy-services/caddy/ping", "REQUEST_SCHEME": "http", "SERVER_NAME": "localhost", "SERVER_PROTOCOL": "HTTP/1.1", "HTTP_HOST": "localhost", "CONTENT_LENGTH": "", "PATH_INFO": "", "REMOTE_PORT": "", "REQUEST_METHOD": "GET"}, "request": {"remote_ip": "", "remote_port": "", "proto": "HTTP/1.1", "method": "GET", "host": "localhost", "uri": "", "headers": {}}}
```

**Comment by francislavoie** [comment]
I'm not seeing a problem here at all. This looks to be working as intended.

**Comment by maidmaid** [comment]
I misunderstood the feature. I thought it worked like the kubernetes readiness probe that waits the health check to be green before serving traffic to the service. I thought that the error in the log was unexpected. Sorry for the noise, and thanks for your help !

**Comment by francislavoie** [comment]
Ah. In that case, you want to combine it with `lb_try_duration` to have Caddy hold the request for N seconds, retrying to dial an upstream.

**Comment by maidmaid** [comment]
Works like a charm, thanks for the tip!
