### ISSUE TITLE
websocket + forward_auth sends ws request to the auth server

### ISSUE THREAD

**Issue by martolini** [caddyserver/caddy#5430]
Given a minimal Caddyfile

```
mydomain.com {
  forward_auth "https://my-auth-server.com"

  handle_path * {
    reverse_proxy localhost:8081
  }
}
```

a websocket request will not be written as a `GET` request to the auth service, but rather a websocket request is sent there. Is this by design? I'm trying to validate websocket requests but not upgrade/accept the request.

**Comment by WeidiDeng** [comment]
Websocket has request method as `GET` but only for http version 1.1 and other websocket related headers. Currently caddy don't remove these request headers and these headers have nothing to do with request authentication. What's the problem you're experiencing?

**Comment by francislavoie** [comment]
I think as a workaround you can just strip the `Connection` header from the request which would cause it to be upgraded.

```
forward_auth https://my-auth-server.com {
    header_up -Connection
}
```

@james-d-elliott do you have any insight about how this should work?

**Comment by WeidiDeng** [comment]
> I think as a workaround you can just strip the `Connection` header from the request which would cause it to be upgraded.
> 
> ```
> forward_auth https://my-auth-server.com {
>     header_up -Connection
> }
> ```
> 
> @james-d-elliott do you have any insight about how this should work?

The problem is then if the websocket request passes authentication it won't work (do forward auth uses a copy of original request or modify it in place? I haven't checked the code). I think auth services should just check necessary credential headers instead of trying to upgrade.

If however, the websocket authentication requires message level authentication, then forward auth is not for you.

**Comment by francislavoie** [comment]
> The problem is then if the websocket request passes authentication it won't work 

No it should still work. `header_up` only manipulates a copy of the request, the copy that `forward_auth` uses. After that, the following `reverse_proxy` makes its own copy of the original request.

**Comment by james-d-elliott** [comment]
Yeah all of the [hop-by-hop headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Connection) should be excluded specifically from the forward auth requests but be included in the request to the backend in the success condition from memory.

**Comment by francislavoie** [comment]
Yep, we already handle hop-by-hop headers correctly.

Now that I have some time to look at the code, I don't think there's any bug in Caddy. The websocket connection would only be established if the `forward_auth` upstream responds with status code `101 Switching Protocols`. If it responds with a `2xx` code then `forward_auth` will pass the request through to the next handler.

Make sure your upstream auth app isn't trying to establish a websocket connection by responding with `101`.

**Comment by Cyberbeni** [comment]
I don't know if it is a Caddy or a swift-nio issue but I had an issue with websocket forward_auth requests sometimes not arriving to my swift-nio based application and just receiving a timeout error in the browser after a while. When the request arrived, it was handled properly on my side and the webapp worked as expected. With `header_up -Connection` set, it works every time.

**Comment by francislavoie** [comment]
If you enable the `debug` global option (without the `header_up -Connection`), what do you see in your logs? It would be good to understand how Caddy sees this traffic and what behaviour it has.

**Comment by Cyberbeni** [comment]
Example docker compose setup with my project: https://github.com/Cyberbeni/auth.home.arpa/tree/master/sample_config
Modifications compared to current master:
```diff
diff --git a/sample_config/caddy-etc_caddy/Caddyfile b/sample_config/caddy-etc_caddy/Caddyfile
index ff7cb3d..05f1135 100644
--- a/sample_config/caddy-etc_caddy/Caddyfile
+++ b/sample_config/caddy-etc_caddy/Caddyfile
@@ -1,6 +1,7 @@
 {
        local_certs
        auto_https disable_redirects
+       debug
 }
 
 # writing cookies to home.arpa is restricted, so we need a common subdomain a level deeper
@@ -24,7 +25,7 @@ auth.test.home.arpa {
        forward_auth unix//socket/auth.sock {
                uri /api/auth?redirect={args[0]}
                # https://github.com/caddyserver/caddy/issues/5430#issuecomment-1465216147
-               header_up -Connection
+               # header_up -Connection
        }
 }
 
```
Login is admin/admin
Took a couple page reloads but managed to get into this state: 

<img width="4105" height="2304" alt="Image" src="https://github.com/user-attachments/assets/826d15f0-a30b-4c23-a168-92a27e1d74bc" />

The vscodium log was from before all the retries for the `stable-...` call.
When I press ctrl+C to stop the docker containers, I get a bunch of these logs:
```
caddy     | {"level":"debug","ts":1769602704.1611733,"logger":"http.handlers.reverse_proxy","msg":"upstream roundtrip","upstream":"unix//socket/auth.sock","duration":907.508950285,"request":{"remote_ip":"172.18.0.1","remote_port":"38060","client_ip":"172.18.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost","uri":"/api/auth?redirect=http://localhost:9999","headers":{"Sec-Websocket-Extensions":["permessage-deflate"],"Cookie":["REDACTED"],"Cache-Control":["no-cache"],"Accept-Encoding":["gzip, deflate, br, zstd"],"Accept-Language":["en,hu;q=0.9"],"Sec-Fetch-Dest":["empty"],"Upgrade":["websocket"],"Sec-Websocket-Key":["x38WcvVuwnAgywMg13WIYA=="],"Accept":["*/*"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0"],"Via":["1.1 Caddy"],"X-Forwarded-For":["172.18.0.1"],"Sec-Websocket-Version":["13"],"Origin":["http://localhost"],"Connection":["Upgrade"],"Sec-Fetch-Mode":["websocket"],"X-Forwarded-Method":["GET"],"X-Forwarded-Proto":["http"],"X-Forwarded-Uri":["/stable-aafba0d66e7c8203c7e890a32383eecef870560c?reconnectionToken=fa5e0098-3dce-4c29-9d10-0caa39246325&reconnection=false&skipWebSocketFrames=false"],"Sec-Gpc":["1"],"X-Forwarded-Host":["localhost"],"Pragma":["no-cache"],"Sec-Fetch-Site":["same-origin"]}},"error":"dial unix /socket/auth.sock: connect: no such file or directory"}
caddy     | {"level":"error","ts":1769602704.1617339,"logger":"http.log.error","msg":"dial unix /socket/auth.sock: connect: no such file or directory","request":{"remote_ip":"172.18.0.1","remote_port":"38060","client_ip":"172.18.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost","uri":"/stable-aafba0d66e7c8203c7e890a32383eecef870560c?reconnectionToken=fa5e0098-3dce-4c29-9d10-0caa39246325&reconnection=false&skipWebSocketFrames=false","headers":{"Sec-Websocket-Version":["13"],"Sec-Fetch-Dest":["empty"],"Pragma":["no-cache"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0"],"Accept-Encoding":["gzip, deflate, br, zstd"],"Sec-Gpc":["1"],"Connection":["Upgrade"],"Cache-Control":["no-cache"],"Sec-Fetch-Mode":["websocket"],"Sec-Fetch-Site":["same-origin"],"Sec-Websocket-Extensions":["permessage-deflate"],"Cookie":["REDACTED"],"Accept":["*/*"],"Accept-Language":["en,hu;q=0.9"],"Origin":["http://localhost"],"Upgrade":["websocket"],"Sec-Websocket-Key":["x38WcvVuwnAgywMg13WIYA=="]}},"duration":907.509583918,"status":502,"err_id":"7u7m1mw2p","err_trace":"reverseproxy.statusError (reverseproxy.go:1390)"}
```

**Comment by francislavoie** [comment]
Uh.. well `"error":"dial unix /socket/auth.sock: connect: no such file or directory"` seems like your issue...?

**Comment by Cyberbeni** [comment]
> Uh.. well `"error":"dial unix /socket/auth.sock: connect: no such file or directory"` seems like your issue...?

That is caused by pressing ctrl-c to stop everything. That log has a duration of 15 minutes, the socket was there for the previous 15 minutes.

**Comment by francislavoie** [comment]
Ah I see. Yeah that still looks like a bug with your auth server to me, like it actually established the WS connection instead of returning a `200` right away. But your workaround also seems fine. I don't think we really need to do anything in Caddy itself.

**Comment by Cyberbeni** [comment]
Wouldn't the browser display 101 if the websocket connection was established? Or shouldn't Caddy log an error for unexpected response from forward_auth? Is there a known working app that just forwards one socket to another and logs the messages? Same thing happens when communication goes through a port number instead of a Unix socket. (Except that doesn't work with `network: none` in docker compose)

**Comment by francislavoie** [comment]
The point of `forward_auth` is that it doesn't write the response back to the client, cause it's just doing an internal request to get an auth result, then continues the handler chain. So no, you wouldn't see `101` in the browser if WS was established in `forward_auth`, you'd just see this exact behaviour where the request hangs forever.

You can easily make a custom build of Caddy with extra logs to help you figure things out, but I'm 99% sure this is a buggy auth app which is configured to establish WS connections even for `/api/auth` paths, which it should not.

**Comment by Cyberbeni** [comment]
If forward_auth doesn't write non-2xx responses back to the client then how come a 302 response from it results in the browser being redirected?

You also completely ignored my previous question. The best logging would be to see the raw data that is going through that unix socket. If you are correct and the issue is in my app then more logs from Caddy are less useful than the raw data from the socket.

**Comment by francislavoie** [comment]
Because that's what it's designed to do. See https://caddyserver.com/docs/caddyfile/directives/forward_auth#expanded-form, only `2xx` responses get handled specially causing routing to continue, any 3xx or 4xx or 5xx will be written back to the client.

Since `forward_auth` is basically just sugar for `reverse_proxy` with a `handle_response`, if the upstream responds with `101` then it triggers `reverse_proxy`'s connection upgrade logic. The problem there isn't that `reverse_proxy` has this behaviour, the problem is that the upstream responded with `101` in the first place, which implies broken handling of requests to the `/api/auth` path.

> You also completely ignored my previous question. The best logging would be to see the raw data that is going through that unix socket. If you are correct and the issue is in my app then more logs from Caddy are less useful than the raw data from the socket.

The issue isn't with the traffic Caddy sends to to your auth app (in fact, you _can_ see that traffic in that debug log above once you killed the server). But like I said, the best way to see the traffic in-context would be to make a custom build of Caddy which adds those extra logs.

**Comment by Cyberbeni** [comment]
If responding 101 was the issue then wouldn't this also solve it?
```
	reverse_proxy unix//socket/auth.sock {
		method GET
		rewrite /api/auth?redirect={args[0]}
		header_up X-Forwarded-Method {method}
		header_up X-Forwarded-Uri {uri}
		@good status 2xx
		handle_response @good {
		}
		@othergood status 1xx
		handle_response @othergood {
		}
	}
```

I also updated my code to respond with 101 instead of 204 when authentication is successful.

The result of all these changes is that it still has the same behavior. The ws connection sometimes succeeds and sometimes hangs forever even after multiple retries in the browser, everything else works fine as before.

If I keep responding with 101 instead of 204 but comment out the 1xx special handling then Caddy produces this error log:

```
caddy     | {"level":"debug","ts":1769616028.9906623,"logger":"http.handlers.reverse_proxy","msg":"upstream roundtrip","upstream":"unix//socket/auth.sock","duration":0.001083609,"request":{"remote_ip":"172.18.0.1","remote_port":"47618","client_ip":"172.18.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost","uri":"/api/auth?redirect=http://localhost:9999","headers":{"Sec-Fetch-User":["?1"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],"X-Forwarded-For":["172.18.0.1"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-Site":["none"],"X-Forwarded-Method":["GET"],"Sec-Gpc":["1"],"X-Forwarded-Host":["localhost"],"Accept-Language":["en,hu;q=0.9"],"X-Forwarded-Proto":["http"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0"],"Priority":["u=0, i"],"Via":["1.1 Caddy"],"Cookie":["REDACTED"],"Accept-Encoding":["gzip, deflate, br, zstd"],"Upgrade-Insecure-Requests":["1"],"X-Forwarded-Uri":["/?folder=/config/workspace"],"Sec-Fetch-Dest":["document"]}},"headers":{"Date":["Wed, 28 Jan 2026 16:00:28 GMT"]},"status":101}
caddy     | {"level":"error","ts":1769616028.99068,"logger":"http.handlers.reverse_proxy","msg":"internal error: 101 switching protocols response with non-writable body","upstream":"unix//socket/auth.sock","duration":0.001083609,"request":{"remote_ip":"172.18.0.1","remote_port":"47618","client_ip":"172.18.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost","uri":"/api/auth?redirect=http://localhost:9999","headers":{"Sec-Fetch-User":["?1"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],"X-Forwarded-For":["172.18.0.1"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-Site":["none"],"X-Forwarded-Method":["GET"],"Sec-Gpc":["1"],"X-Forwarded-Host":["localhost"],"Accept-Language":["en,hu;q=0.9"],"X-Forwarded-Proto":["http"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0"],"Priority":["u=0, i"],"Via":["1.1 Caddy"],"Cookie":["REDACTED"],"Accept-Encoding":["gzip, deflate, br, zstd"],"Upgrade-Insecure-Requests":["1"],"X-Forwarded-Uri":["/?folder=/config/workspace"],"Sec-Fetch-Dest":["document"]}}}
```

The ~35 lines of code that I wrote that handle this are 100% correct. If I add logging to the start of it then it logs when it works and doesn't log when the connection is hanging.

I also added LoggingMiddleware to the beginning of the chain for the networking library that I use. Same result.

This networking library is built on top of Apple's library that wraps the OS specific stuff.

I'm 99% sure that the issue is somewhere in Apple's code or any of the code that Caddy depends on. I'm trying to find where exactly but you just keep deflecting and repeating that Caddy is 99% correct.

I also tried what you are suggesting is happening and only responded 101 when the "Connection" header is "Upgrade", that behaves differently than what I previously seen, this has logs about the 101 response:

<img width="4095" height="2304" alt="Image" src="https://github.com/user-attachments/assets/d2016028-ff41-4726-b28f-51eb56f79852" />

**Comment by Cyberbeni** [comment]
diff in my code for the image:

```diff
diff --git a/Sources/auth_home_arpa/Routes/Routes+ForwardAuth.swift b/Sources/auth_home_arpa/Routes/Routes+ForwardAuth.swift
index 63bb5cd..3a6dec4 100644
--- a/Sources/auth_home_arpa/Routes/Routes+ForwardAuth.swift
+++ b/Sources/auth_home_arpa/Routes/Routes+ForwardAuth.swift
@@ -12,9 +12,15 @@ extension Router {
 			if let cookie = request.cookies[Constants.cookieName],
 			   userService.checkCookie(cookie.value)
 			{
-				return Response(
-					status: .noContent,
-				)
+				if request.headers[HTTPField.Name.connection] == "Upgrade" {
+					return Response(
+						status: .switchingProtocols,
+					)
+				} else {
+					return Response(
+						status: .noContent,
+					)
+				}
 			} else {
 				guard
 					let redirectString = request.uri.queryParameters["redirect"],
diff --git a/sample_config/caddy-etc_caddy/Caddyfile b/sample_config/caddy-etc_caddy/Caddyfile
index ff7cb3d..c59f49e 100644
--- a/sample_config/caddy-etc_caddy/Caddyfile
+++ b/sample_config/caddy-etc_caddy/Caddyfile
@@ -1,6 +1,7 @@
 {
 	local_certs
 	auto_https disable_redirects
+	debug
 }
 
 # writing cookies to home.arpa is restricted, so we need a common subdomain a level deeper
@@ -21,11 +22,23 @@ auth.test.home.arpa {
 # args:
 # 0: redirect url
 (forward_auth) {
-	forward_auth unix//socket/auth.sock {
-		uri /api/auth?redirect={args[0]}
-		# https://github.com/caddyserver/caddy/issues/5430#issuecomment-1465216147
-		header_up -Connection
+	reverse_proxy unix//socket/auth.sock {
+		method GET
+		rewrite /api/auth?redirect={args[0]}
+		header_up X-Forwarded-Method {method}
+		header_up X-Forwarded-Uri {uri}
+		@good status 2xx
+		handle_response @good {
+		}
+		# @othergood status 1xx
+		# handle_response @othergood {
+		# }
 	}
+	# forward_auth unix//socket/auth.sock {
+	# 	uri /api/auth?redirect={args[0]}
+	# 	# https://github.com/caddyserver/caddy/issues/5430#issuecomment-1465216147
+	# 	header_up -Connection
+	# }
 }
 
 # args:

```

**Comment by Cyberbeni** [comment]
I intentionally added a 600 second wait before the 101 answer and when I initially load the site and VSCodium keeps repeating the request, Caddy keeps logging that request (see image). Keep in my that before when it got to this state after multiple refreshes, there were no logs for these retries in Caddy. This to me 100% proves that the issue is with Caddy.

<img width="4105" height="2304" alt="Image" src="https://github.com/user-attachments/assets/110ad977-d717-4dfc-8dd6-eef7f0332bca" />

Since I already have a workaround with removing that header and I don't want to learn the ins and outs of a new-to-me programming language, I don't intend to do any further investigation regarding this.

**Comment by francislavoie** [comment]
`handle_response` happens _after_ the `101` handling happens in `reverse_proxy`, so configuring that wouldn't do anything useful.

You did show that your upstream auth app _is in fact_ responding with 101 which is the problem. It shouldn't, it should respond with 2xx (to match `forward_auth` expectations).

We do it the same way as Traefik, so I assume it would (mis)behave the same way with Traefik as well.

> I'm trying to find where exactly but you just keep deflecting and repeating that Caddy is 99% correct.

I'm not deflecting, I'm discussing. I don't know why you're getting that impression.

> I also tried what you are suggesting is happening and only responded 101 when the "Connection" header is "Upgrade", that behaves differently than what I previously seen, this has logs about the 101 response

No what I was suggesting is to disable websocket handling for the `/api/auth` endpoint in the auth server, _regardless_ of the connection headers.

An auth server is supposed to get all the request's headers to validate how the request was received by the web server (e.g. you could have some rules like "user X cannot use websockets but user Y can" and you could implement that rule by checking whether the original request contained a `Connection: upgrade` header).

> I intentionally added a 600 second wait before the 101 answer and when I initially load the site and VSCodium keeps repeating the request, Caddy keeps logging that request (see image). Keep in my that before when it got to this state after multiple refreshes, there were no logs for these retries in Caddy. This to me 100% proves that the issue is with Caddy.

But... the issue is that your auth server responds with 101 at all, not with how Caddy handles a 101.

> Since I already have a workaround with removing that header and I don't want to learn the ins and outs of a new-to-me programming language, I don't intend to do any further investigation regarding this.

That's totally fine 👍 

I'm of course going to discuss it publicly anyways for the benefit of anyone else reading this now or in the future.

**Comment by Cyberbeni** [comment]
> But... the issue is that your auth server responds with 101 at all, not with how Caddy handles a 101.

I'm sorry but I think you have reading comprehension issues.

We have 3 test cases:

1. If I leave my code as is, ws connection sometimes works, sometimes doesn't. When it doesn't, there aren't even logs in Caddy for when VSCodium is retrying the ws connection.

2. If I intentionally modify my code to return 101 instead of 204 when `Connection: Upgrade` then ws connection breaks in a different way from VSCodium's side, and Caddy logs include that it got unexpected 101 answer.

3. If I intentionally modify my code to not answer for 10 minutes when `Connection: Upgrade` then ws connection instantly breaks from VSCodium's side the same way as the 1st case but from Caddy's side, I see a log for every retry. It doesn't matter whether my code would return 101 or 204 after the 10 minutes as the test took less than 10 minutes.

**Comment by francislavoie** [comment]
> I'm sorry but I think you have reading comprehension issues.

Why are you being rude? Let's focus on the technical stuff, leave out the personal attacks.

> We have 3 test cases:

Sure, but in none of those are you specially handling `/api/auth` to entirely disable websocket upgrades, right? That's what I'm suggesting.

**Comment by Cyberbeni** [comment]
> Sure, but in none of those are you specially handling `/api/auth` to entirely disable websocket upgrades, right? That's what I'm suggesting.

Websocket upgrades are not enabled, if they were enabled then how would the 1st test case work properly the first time and only break after multiple refreshes?

**Comment by francislavoie** [comment]
I'm not sure, I don't think I've seen the evidence of that, I haven't seen how that looks like in your logs, I think. What do the logs look like when it succeeds, then what do the logs look like when it fails, side by side?

**Comment by Cyberbeni** [comment]
> I'm not sure, I don't think I've seen the evidence of that, I haven't seen how that looks like in your logs, I think. What do the logs look like when it succeeds, then what do the logs look like when it fails, side by side?

I included in my very first comment:

> I don't know if it is a Caddy or a swift-nio issue but I had an issue with websocket forward_auth requests sometimes not arriving to my swift-nio based application and just receiving a timeout error in the browser after a while. When the request arrived, it was handled properly on my side and the webapp worked as expected. With header_up -Connection set, it works every time.

I have also repeated it at least 2 more times since then:

> The result of all these changes is that it still has the same behavior. The ws connection sometimes succeeds and sometimes hangs forever even after multiple retries in the browser, everything else works fine as before.

> If I leave my code as is, ws connection sometimes works, sometimes doesn't. When it doesn't, there aren't even logs in Caddy for when VSCodium is retrying the ws connection.

The issue should be fully reproducible with a `docker compose up --build` (or using `ghcr.io/cyberbeni/auth.home.arpa:v1.0.3` instead of building the image) with the example setup that I linked, feel free to reproduce the issue locally.
