### ISSUE TITLE
Support custom repository for caddy upgrade or caddy add-package

### ISSUE THREAD

**Issue by thomasarmel** [caddyserver/caddy#5445]
Hi,
I use caddy on my FreeBSD server, and commands `caddy upgrade` or `caddy add-package` don't work, due to a bug on caddyserver.com (https://caddy.community/t/remote-build-request-doesnt-work-for-freebsd-amd64/18456).

Would it be possible to add the possibility to define a **custom repository** to request builds, instead of https://caddyserver.com/api/download ? (https://github.com/caddyserver/caddy/blob/master/cmd/packagesfuncs.go#L303)

`CADDY_DOWNLOAD_PATH=https://my-custom-server.com/api/download caddy upgrade`

Regards

**Comment by mholt** [comment]
To clarify, the bug is actually in the `go` command. Because of this, no matter where the package comes from, the command may still hang. In other words, I'm not sure if this is going to work around the problem in a way you are expecting.

The `caddy upgrade` (and add-package/remove-package commands) require contacting a remote (or theoretically, local) instance of `xcaddy` to perform a custom build. So if you had a compatible xcaddy server at your endpoint, that could work, except you'd still hit the bug. Even if you don't use xcaddy and use the `go` command directly, you could still hit the bug (this happened to me again yesterday).

**Comment by francislavoie** [comment]
I think I'll close this and mark it as deferred for now. I don't think we'll realistically work on this anytime soon.

Thing is, I don't expect that `caddy upgrade` or `caddy add-package` to be used commonly enough that users would actually run their own endpoints.

If you plan on wanting to build things yourself, you're much more likely to just directly use `xcaddy build` directly. Running your own build server just to put a tiny endpoint that wraps `xcaddy build` anyway seems like a lot of faff.
