### ISSUE TITLE
请问能反向代理samba服务吗？

### ISSUE THREAD

**Issue by moonfdd** [caddyserver/caddy#5457]
`
    :61612 {
      reverse_proxy /smb smb://用户名:密码@ip:445
    }

`
我这么写，发现访问不了。

**Comment by mohammed90** [comment]
I don't read Chinese, so my answer is as good as Google Translate work.

SMB is a TCP protocol. You should try with github.com/mholt/caddy-l4.

This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
