### ISSUE TITLE
Clear removed upstreams metrics on config reload

### ISSUE THREAD

**Issue by husam212** [caddyserver/caddy#5496]
If an upstream is removed from the configuration file, then Caddy is reloaded with `reload` command, the removed upstream will keep showing in Prometheus metrics, the value of the metric is stuck at the last state of the removed upstream.

Caddy version: 2.6.4

**Comment by hairyhenderson** [comment]
Can you provide more details? An example, maybe? This shouldn't be a problem in general for counters or histograms, since they won't be growing.

**Comment by francislavoie** [comment]
FYI @david-szabo97 since you implemented the upstream metrics

**Comment by husam212** [comment]
@francislavoie sure, considering the following example configuration.
```
{
  servers {
    metrics
  }
}

:9000 {
  metrics
}

example.com {
  reverse_proxy * {
    to 10.0.0.1:8000
    to 10.0.0.2:8000
    health_uri /ping
    health_headers {
      Host example.com
    }
  }
}
```

Checking the metrics with the above config would result in something like this:
```
caddy_reverse_proxy_upstreams_healthy{upstream="10.0.0.1:8000"} 1
caddy_reverse_proxy_upstreams_healthy{upstream="10.0.0.2:8000"} 1
```

Now If I removed one of the upstreams, lets say 10.0.0.1:8000, then reloaded Caddy, I would still get the same output from the metrics endpoint.

**Comment by hairyhenderson** [comment]
Thanks @husam212 - this is indeed a problem, especially since that metric is a gauge, and so is misrepresenting reality.

**Comment by u5surf** [comment]
@husam212  @francislavoie @david-szabo97 
We had the same problem.
We dove deeply the issue, we can find this `sync.Once` in `newMetricsUpstreamsHealthyUpdater` is unnecessary which is called by `reverseproxy.Provision` exactly once per `caddy run/start`. Thus it never call by `caddy reload` because it has already called in `caddy run/start` at only once.

https://github.com/caddyserver/caddy/blob/998c6e06a75030cccabcc08790bc32642791aff7/modules/caddyhttp/reverseproxy/reverseproxy.go#L419-L420

https://github.com/caddyserver/caddy/blob/998c6e06a75030cccabcc08790bc32642791aff7/modules/caddyhttp/reverseproxy/metrics.go#L38-L40

And moreover, It is necessary to reinitialize with prometheus.Unregister.

https://github.com/prometheus/client_golang/issues/475#issuecomment-428142144

We can be prepared our workaround patches which seems to work fine, but it might have cover only our particular usecase.
