### ISSUE TITLE
Global `acme_ca` option not working

### ISSUE THREAD

**Issue by mrexodia** [caddyserver/caddy#5512]
I have my own `step-ca` server running at `udr.me.local`. I am trying to use this ACME server as the default for all endpoints, but the new `Caddyfile` documentation is really confusing.

I got it working with the `tls` option for the site:

```
ubuntu-kms, ubuntu-kms.me.local {
        root * /root
        file_server browse
        tls duncan@me.local {
                ca https://udr.me.local:4443/acme/acme/directory
        }
}
```

Now I want to host a few sites, so I found the global [`acme_ca`](https://caddyserver.com/docs/caddyfile/options#acme-ca) option:

```
{
        email duncan@me.local
        acme_ca https://udr.me.local:4443/acme/acme/directory
}


ubuntu-kms, ubuntu-kms.me.local {
        root * /root
        file_server browse
}
```

There is no error, but Caddy does not use the ACME server and instead creates self-signed certificates...

**Comment by IndeedNotJames** [comment]
`.local` domains will use the `internal` CA by default.
See https://caddyserver.com/docs/automatic-https#hostname-requirements

Those are values hard-coded in https://github.com/caddyserver/certmagic/blob/15a8b4f4c5a11fcf8a410b93d0bdb111b1096b48/certificates.go#L400-L404

You can use _snippets_ though, so you don't have to repeat yourself as much.
https://caddyserver.com/docs/caddyfile/concepts#snippets

Changes are, you want to enable `encode zstd gzip` on all vhosts as well. E.g:
```Caddyfile
(defaults) {
	encode zstd gzip
	tls duncan@me.local {
		ca https://udr.me.local:4443/acme/acme/directory
	}
}

ubuntu-kms, ubuntu-kms.me.local {
	root * /root
	file_server browse
	import defaults
}
```

**Comment by mrexodia** [comment]
Thanks for the quick answer! I don't know if this should be closed though. The documentation might be updated to specify this (at the actual `acme_ca` part where I was looking) and additionally I would expect a hard error for this.

Also I feel the check for `localhost` and `.local` is quite inconsistent. Here is a list of other domains I might have picked:
- https://www.rfc-editor.org/rfc/rfc6762#section-3
- https://www.iana.org/assignments/special-use-domain-names/special-use-domain-names.xhtml
- https://www.rfc-editor.org/rfc/rfc2606#section-2

If I chose `me.home` everything would work as expected...

**Comment by mholt** [comment]
Those links include domains such as `example`, `example.com`, `example.org,` example.net`, `onion`, `.invalid`, and many others that don't make sense for our use case.

I think the current behavior makes sense because the global option is less specific than site-specific config such as the site's hostname or a `tls` directive inside it.

Why not use `.internal` for your hostnames, or use snippets?

**Comment by mrexodia** [comment]
Yeah I switched to using snippets and my setup works, really appreciate the quick response!

I guess the main reason the current behavior is strange to me is that I am not able to do the (for me) intuitive thing of replacing Caddy's local CA with my own CA and an ACME server. In my case my router is running `step-ca` as well as the DNS server for the `.local` domain (it's set as a custom domain in DHCP), so it would be great if I could easily point Caddy instances there to fetch their certificates.

The thing about `.onion` etc was only used as an illustration. My point was that you cannot get certificates for them from any CA either (just like IP addresses), so why are they allowed and `.local` isn't? I don't think `localhost` and `.local` are at all related and my `.local` domains resolve without any issues at all on Linux/Mac/Windows.

To (hopefully) help the next person confused by this I updated the documentation and created a PR. The wording perhaps isn't the best, but I'm sure this can be fixed.

**Comment by mholt** [comment]
It's hard to draw a line between intuitive and annoying when it comes to stuff like this; we figured that `.localhost` and `.local` are intended to be self-signed. The Caddyfile has to make some assumptions by design, but the JSON config would give you full flexibility over this.

Basically, we needed an easy toggle for users' internal domains without requiring extra config if possible. On internal networks, IPs are very commonly used directly, so that was an obvious choice. Then we figured `.localhost` and `.local` fit the bill. Other TLDs like `.onion` don't, but can still be configured to issue a self-signed certificate.

Maybe, just maybe, there's a case for only doing self-signed certs on IPs and `.localhost` domains, and leaving `.local` to the configured CA. I might be open to that. Based on what I hear about the `.local` TLD it sounds like almost nobody is probably using it anyway.
