### ISSUE TITLE
TCP or UDP proxy

### ISSUE THREAD

**Issue by curiosity-00** [caddyserver/caddy#5523]
proxy tcp://ip:port , How to configure TCP proxy ???  Can someone give me an example that I can use ?

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! So far, this doesn't look like a bug in Caddy. It looks more like a question about how to use Caddy rather than a bug report or feature request.

You're looking for [caddy-l4](https://github.com/mholt/caddy-l4).

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!

**Comment by curiosity-00** [comment]
Thank you very much for your reply! @mholt
