### ISSUE TITLE
X-Accel-Redirect setup doesn't work for requests other than GET and HEAD.

### ISSUE THREAD

**Issue by lemniskett** [caddyserver/caddy#5529]
Hi, I'm trying to serve protected static files using X-Accel-Redirect-like setup in Caddy. 

```
domain.tld {
    reverse_proxy /* backend:8069 {
        @accel header X-Accel-Redirect *
        handle_response @accel {
            root * /path/to/protected/static/files/dir
            rewrite * {rp.header.X-Accel-Redirect}
            file_server
            header X-Served-From "Accel"
            copy_response_headers {
                include Etag Date Last-Modified Access-Control-Allow-Methods Access-Control-Allow-Origin Cache-Control Content-Disposition Content-Type
            }
        }
    }
}
```

This Caddyfile works for GET & HEAD requests, but doesn't for other methods, it just responded with `405 Method Not Allowed`, possibly because `file_server` doesn't accept other methods than GET & HEAD? is it possible to override this? I read the documentation of `file_server` and can't find anything useful for this issue.

Our use case is to get a PDF file that were generated from backend using a POST request.

**Comment by francislavoie** [comment]
This is because of this change:

https://github.com/caddyserver/caddy/commit/a3ae146cbdf2cfbdbdf5feea52e8bf407cce2b31

The problem was the Go stdlib `http.ServeContent` would do nothing if the method was anything else, and this was confusing because it didn't produce any traceable error.

Good news is there's the https://caddyserver.com/docs/caddyfile/directives/method directive which you can use to rewrite the method to GET internally during `handle_response` before `file_server` gets at it. I haven't tried this, but I imagine it should work fine.

I agree this should probably be clarified in the docs. PRs welcome on the https://github.com/caddyserver/website repo if you'd like to take a crack at it.

**Comment by lemniskett** [comment]
Thanks for pointing that out! the following configuration worked fine:

```
domain.tld {
    reverse_proxy /* backend:8069 {
        @accel header X-Accel-Redirect *
        handle_response @accel {
            root * /path/to/protected/static/files/dir
            rewrite * {rp.header.X-Accel-Redirect}
            method * GET
            file_server
            header X-Served-From "Accel"
            copy_response_headers {
                include Etag Date Last-Modified Access-Control-Allow-Methods Access-Control-Allow-Origin Cache-Control Content-Disposition Content-Type
            }
        }
    }
}
```
