### ISSUE TITLE
Default error page for Firefox?

### ISSUE THREAD

**Issue by pistasjis** [caddyserver/caddy#5544]
I remember the first time I was using Caddy, I saw that I just got a blank page whenever I went on a page that didn't exist, which confused me, since I was used to things like NGINX having a default error page. From what I understand now, Firefox doesn't implement an error page for 404, 502 errors etc, but Chromium does. I can see some issues with having a default error page, like it not being localized, but I think it's a lot easier for someone to read "404" and realize what's wrong than seeing a blank page and having to go to Developer Tools to figure out what error they got. 

What I think could work is a check if the User-Agent matches Firefox and serve an error page if it does. It's a lot friendlier to see an error page provided to you by the browser, but again, Firefox doesn't do this and I think even having a basic plaintext response saying "404: Not Found" by default for Firefox users is more user friendly than seeing a blank page.

**Comment by mholt** [comment]
Yeah. Browsers are not good HTTP server debugging agents in general, even with dev tools (though devtools are a little better). I always suggest (and in bug reports, _require_) that people use `curl -v` to prove symptoms. Otherwise a lot of assumptions are made, often wrongly, because of how different browsers behave in different situations.

Default pages/responses have been discussed before and ultimately rejected because of the added complexity in reconfiguring them -- it is better, and it is our project's philosophy, that the server should offer more of a blank slate that you can scribble on, rather than being required to erase or overwrite default scribbles first, if that makes sense.

We can't assume what the server is being used for. We know that Caddy sees extremely high use in non-browser connections (APIs, proxy situations, etc) and serving a non-empty error response can be confusing in a lot of situations, as it makes a lot of assumptions (for example, that the client can render HTML -- or that it even reads the response body at all).

Thanks for the issue though!
