### ISSUE TITLE
caddyfile子路由配置问题（caddyfile subrouting static page proxy）

### ISSUE THREAD

**Issue by heiwa9** [caddyserver/caddy#5580]
caddy version: `caddy-2.4.6-6.el9.x86_64`
caddyfile:

```
tools.boo.foo {
    encode zstd gzip

    handle /newpage/* {
        root * /srv/www/tools_newpage
        try_files {path} /index.html
        file_server
    }
}
```

# expect
Successfully loaded the page and obtained the resource file

# result
index.html is successfully opened, but its related resource files cannot be accessed, and the requests for resource files are all covered by index.html

# screenshot
<img width="859" alt="image" src="https://github.com/caddyserver/caddy/assets/54386147/0f82fc99-bf83-4efe-8f16-990310f475a6">

**Comment by francislavoie** [comment]
We can't provide support for old versions of Caddy. Please update to the latest version.

**Comment by mholt** [comment]
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_ **using the latest version of Caddy.** This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

This should be the latest version of Caddy:

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Instructions -- please heed otherwise we cannot help you (help us help you!)

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222) Please enable debug and access logs.
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by heiwa9** [comment]
## 1. Environment

### 1a. Operating system and version

```
server: Rocky Linux release 9.2 (Blue Onyx)
brower: Vivaldi 6.1.3035.84
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

This should be the latest version of Caddy:

```
v2.6.4 h1:2hwYqiRwk1tf3VruhMpLcYTg+11fCdr8S3jhNAdnPy8=
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)
a static file server is configured on the child route, but he cannot access the static resources, and all requests will open index.html


### 2c. Log output

```
2023/06/20 05:30:54.692 DEBUG   http.handlers.rewrite   rewrote request {"request": {"remote_ip": "60.12.139.34", "remote_port": "63572", "proto": "HTTP/2.0", "method": "GET", "host": "tools.geekland.cc", "uri": "/sql2struct/", "headers": {"Cache-Control": ["no-cache"], "Sec-Ch-Ua-Mobile": ["?0"], "Upgrade-Insecure-Requests": ["1"], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"], "Sec-Fetch-User": ["?1"], "Sec-Fetch-Dest": ["document"], "Accept-Encoding": ["gzip, deflate, br"], "Pragma": ["no-cache"], "Sec-Ch-Ua": ["\"Not.A/Brand\";v=\"8\", \"Chromium\";v=\"114\", \"Google Chrome\";v=\"114\""], "Sec-Fetch-Mode": ["navigate"], "Accept-Language": ["zh-CN,zh;q=0.9,und;q=0.8,zh-Hans;q=0.7"], "Sec-Ch-Ua-Platform": ["\"macOS\""], "User-Agent": ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"], "Sec-Fetch-Site": ["none"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "h2", "server_name": "tools.geekland.cc"}}, "method": "GET", "uri": "/index.html"}
2023/06/20 05:30:54.692 DEBUG   http.handlers.file_server       sanitized path join     {"site_root": "/srv/www/tools_sql2struct", "request_path": "/index.html", "result": "/srv/www/tools_sql2struct/index.html"}
2023/06/20 05:30:54.692 DEBUG   http.handlers.file_server       opening file    {"filename": "/srv/www/tools_sql2struct/index.html"}
2023/06/20 05:30:54.743 DEBUG   http.handlers.rewrite   rewrote request {"request": {"remote_ip": "60.12.139.34", "remote_port": "63572", "proto": "HTTP/2.0", "method": "GET", "host": "tools.geekland.cc", "uri": "/sql2struct/assets/index.6a6e443a.js", "headers": {"Accept": ["*/*"], "Accept-Encoding": ["gzip, deflate, br"], "Accept-Language": ["zh-CN,zh;q=0.9,und;q=0.8,zh-Hans;q=0.7"], "Sec-Fetch-Site": ["same-origin"], "Sec-Fetch-Dest": ["script"], "Cache-Control": ["no-cache"], "Sec-Ch-Ua": ["\"Not.A/Brand\";v=\"8\", \"Chromium\";v=\"114\", \"Google Chrome\";v=\"114\""], "Origin": ["https://tools.geekland.cc"], "Referer": ["https://tools.geekland.cc/sql2struct/"], "Sec-Ch-Ua-Mobile": ["?0"], "User-Agent": ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"], "Sec-Fetch-Mode": ["cors"], "Pragma": ["no-cache"], "Sec-Ch-Ua-Platform": ["\"macOS\""]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "h2", "server_name": "tools.geekland.cc"}}, "method": "GET", "uri": "/index.html"}
2023/06/20 05:30:54.743 DEBUG   http.handlers.file_server       sanitized path join     {"site_root": "/srv/www/tools_sql2struct", "request_path": "/index.html", "result": "/srv/www/tools_sql2struct/index.html"}
2023/06/20 05:30:54.743 DEBUG   http.handlers.file_server       opening file    {"filename": "/srv/www/tools_sql2struct/index.html"}
2023/06/20 05:30:54.743 DEBUG   http.handlers.rewrite   rewrote request {"request": {"remote_ip": "60.12.139.34", "remote_port": "63572", "proto": "HTTP/2.0", "method": "GET", "host": "tools.geekland.cc", "uri": "/sql2struct/assets/index.6731616e.css", "headers": {"Sec-Ch-Ua-Platform": ["\"macOS\""], "Accept": ["text/css,*/*;q=0.1"], "Sec-Fetch-Site": ["same-origin"], "Sec-Fetch-Mode": ["no-cors"], "Accept-Encoding": ["gzip, deflate, br"], "Pragma": ["no-cache"], "Cache-Control": ["no-cache"], "Sec-Ch-Ua-Mobile": ["?0"], "Accept-Language": ["zh-CN,zh;q=0.9,und;q=0.8,zh-Hans;q=0.7"], "Referer": ["https://tools.geekland.cc/sql2struct/"], "Sec-Ch-Ua": ["\"Not.A/Brand\";v=\"8\", \"Chromium\";v=\"114\", \"Google Chrome\";v=\"114\""], "User-Agent": ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"], "Sec-Fetch-Dest": ["style"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "h2", "server_name": "tools.geekland.cc"}}, "method": "GET", "uri": "/index.html"}
2023/06/20 05:30:54.743 DEBUG   http.handlers.file_server       sanitized path join     {"site_root": "/srv/www/tools_sql2struct", "request_path": "/index.html", "result": "/srv/www/tools_sql2struct/index.html"}
2023/06/20 05:30:54.743 DEBUG   http.handlers.file_server       opening file    {"filename": "/srv/www/tools_sql2struct/index.html"}
```



### 2d. Workaround(s)
try to remove try_files ，but still failed


## 3. Tutorial (minimal steps to reproduce the bug)

caddyfile use this configuration
```
your.domain.name {
    encode zstd gzip

    handle /newpage/* {
        root * /srv/www/newpage
        try_files {path} /index.html
        file_server
    }
}

```

**Comment by francislavoie** [comment]
`handle` does not strip the path, so Caddy is looking in `/srv/www/tools_sql2struct/sql2struct/assets/index.6a6e443a.js` for the file and not finding it. Use `handle_path` instead. See the docs.

**Comment by heiwa9** [comment]
Thank you very much, my problem has been successfully solved.
