### ISSUE TITLE
How do I configure the logging response body in Caddyfile 

### ISSUE THREAD

**Issue by victory460** [caddyserver/caddy#5582]

**Comment by mohammed90** [comment]
Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

**Comment by mholt** [comment]
Also just curious what the use case is for this :thinking:
