### ISSUE TITLE
use browse flag when folder has index.html

### ISSUE THREAD

**Issue by jaronnie** [caddyserver/caddy#5601]
use browse flag when folder has index.html

```shell
$ tree            
.
├── Caddyfile
├── Caddyfile-browse
├── README.md
└── index.html

0 directories, 4 files
```

```shell
addy run --config ./Caddyfile-browse
```

but 
![image](https://github.com/caddyserver/caddy/assets/77253497/3a744fc8-2858-44ae-b665-f6d4203339d6)

**Comment by mohammed90** [comment]
Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question. Please don't forget to fill out the help template in full. I hope you'll ask your question there, and thanks for understanding!
