### ISSUE TITLE
Proxy protocol not working for HTTP (port 80) connections

### ISSUE THREAD

**Issue by QvanK** [caddyserver/caddy#5602]
When placing a load balancer (HAproxy) in front of two Caddy servers (Running on Windows) with the Proxy Protocol enabled on both the load balancer and the Caddy servers, we notice the following behaviour:

Caddy version: Version 2.7 beta 2

Port 80 traffic:
With Proxy protocol ENABLED (both version 1 and version 2) on the load balancer:
400 response, bad request
```
< HTTP/1.1 400 Bad Request
< Content-Type: text/plain; charset=utf-8
< Connection: close
```
With proxy protocol DISABLED on the load balancer:
```
< HTTP/1.1 308 Permanent Redirect
< Connection: close
< Location: https://[IP]/test
< Server: Caddy
< Date: Wed, 28 Jun 2023 13:10:18 GMT
< Content-Length: 0
```

Port 443 Traffic:
Expected "regular" response.

Caddyfile:
```
{
	servers {
		listener_wrappers {
			proxy_protocol {
				timeout 2s
				allow 192.168.0.1/32 192.168.0.2/32
			}	
			tls
		}
	}
	log {
		output file d:\caddy\logs\default.json
		format json {
			time_format iso8601
			duration_format nano
		}
	}
}

proxytest {	
	respond /test "Healthy" 200 {	
		close
	}
}
```

Did I perchance misconfigure te Caddyfile?

**Comment by francislavoie** [comment]
When using Auto HTTPS, the HTTP server is created at runtime just before Caddy starts, so it doesn't exist when the config is being parsed. This means that using the `servers` global option will not apply to HTTP because there doesn't exist an HTTP config to apply configuration to.

The fix in your case is similar to the note in the docs regarding `name` config https://caddyserver.com/docs/caddyfile/options#name. You'll need to make an empty `http://` site so that an `:80` server exists in the config, and then you can apply server config to that. You'll need to repeat your listener wrapper config for both `:443` and `:80`, except that you need to remove `tls` for `:80` of course.

**Comment by QvanK** [comment]
@francislavoie Thanks so much for the huge hint, that helped a lot! Closing the issue.
