### ISSUE TITLE
[Help / Question] - How to convert rewrite cond like this into caddy2 configuration

### ISSUE THREAD

**Issue by makanSukros** [caddyserver/caddy#5620]
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^([^\.]+)$ $1.php [NC,L]

RewriteRule ^admin/create create.php [L]
RewriteRule ^lists/(.*)$ contacts.php?slug=$1 [QSA]
RewriteRule ^apps/settings/(.*)$ apps_settings.php?slug=$1 [QSA]

Thanks for advance

**Comment by mohammed90** [comment]
Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

**Comment by makanSukros** [comment]
Okay @mohammed90 , I have made a post regarding the issue here 

https://caddy.community/t/how-to-convert-rewrite-cond-like-this-into-caddy2-configuration/20727
