### ISSUE TITLE
file browser: v2.7.0-beta.2:  layout for FILES versus Grid has gap

### ISSUE THREAD

**Issue by gedw99** [caddyserver/caddy#5633]
using https://github.com/caddyserver/caddy/releases/tag/v2.7.0-beta.2

Its minor but annoying - see the gap ??

<img width="1280" alt="Screenshot 2023-07-17 at 09 41 52" src="https://github.com/caddyserver/caddy/assets/53147028/f8777b08-2457-4e63-b06d-eaf2fcc62b4b">
<img width="1280" alt="Screenshot 2023-07-17 at 09 41 57" src="https://github.com/caddyserver/caddy/assets/53147028/6aee3335-6751-48c8-9c7a-190be384458b">

**Comment by francislavoie** [comment]
I'm not sure I understand. By the gap do you mean the empty space to the right? That's intentional, so that grid items have a consistent size. It's more obvious if you have more than one row. See https://github.com/caddyserver/caddy/pull/5564 where the change was made.

**Comment by gedw99** [comment]
In the 2nd screen shot, there is a grey gap.
In the 1st there is none.


It is a minor thing but it brings down the cognitive information quality. I think it is worth making the 2 screens consistent.

**Comment by francislavoie** [comment]
I really don't know which gap you're talking about. It looks fine to me.

**Comment by gedw99** [comment]
<img width="1280" alt="253879849-6aee3335-6751-48c8-9c7a-190be384458b" src="https://github.com/caddyserver/caddy/assets/53147028/19130a2f-5f53-4f25-b739-794cc2553e8b">

**Comment by francislavoie** [comment]
Oh you're talking about the background, not a gap.

The purpose of the grid view is to take up as much width as possible to make use of screen space, especially useful for images and such. I'm not sure it makes sense for the background to go behind the grid because the view modes have different goals.

But anyway I'll leave it up to @mholt to decide.

**Comment by gedw99** [comment]
Yep i agree that screen footprint is important as you say.

The problem i have with it that it is jarring for the user as you flip between File and Grid views. 

One suggestion is to have a gap for both the File and Grid views, but make the gap about half what it is now.

**Comment by francislavoie** [comment]
I think we have different definitions of the word "gap". I don't know what you mean when you use that word. There's like 5 different things in the screenshots I would consider a gap, and the background is not one of them.

**Comment by gedw99** [comment]
I mean the red squiggles for the File view that i uploaded here: https://github.com/caddyserver/caddy/issues/5633#issuecomment-1637801736

**Comment by francislavoie** [comment]
Right, that's the background of the page, not a gap.

**Comment by gedw99** [comment]
that's what I mean when i say gap.

If you compare it to the Files view where there is no gap like that.

**Comment by mholt** [comment]
Ah, ok, so this is what I consider to be _margins_ or _padding_.

The layout is intentional. The reason being that the grid layout needs to use the full width for optimal use of screen space.

Caddy's old ("current", as of 2.6, but old as of 2.7) file browser actually has the list view go all the way across the screen width (ok, technically it's some % short of the full 100%, but my 45"-wide monitor makes it VERY apparent) and it's _simply too wide_. There is not enough information to need that kind of width, and it makes it hard to visually connect the left side to the right, even with the hover color. You're basically turning your neck to just see the filename and then the size or mod date.

The new layout limits the width of the list so that it can be scanned visually much easier (that is the point of the list). Whereas the purpose of the grid view is to have a more immersive experience, to be able to preview images, etc. I find the grid view much more tolerable at a full 45" wide than the list view.

I don't expect users to be flipping between the two very frequently.

Thanks for the feedback!
