### ISSUE TITLE
caddy_build_info metric

### ISSUE THREAD

**Issue by jpds** [caddyserver/caddy#5653]
At some point, I'd compiled `caddy` with:

```
xcaddy build master --with github.com/corazawaf/coraza-caddy/v2
```

Weeks later, I wanted to verify which commit had been deployed, however I discovered that `go_build_info` only lists `version="(devel)"` (though this info is also available in `caddy version`).

`caddy_build_info` should be added which mimics what `prometheus_build_info` does: https://github.com/prometheus/prometheus/blob/657da2eb98451210ef81b9b1dbe377fc725cc994/web/api/v1/api.go#L126-L134

**Comment by mholt** [comment]
The commit is in the output of `caddy version` as you mention:

```
$ xcaddy build master --with github.com/corazawaf/coraza-caddy/v2
...

╔[matt@shadowfax:~]
╚>$ ./caddy version
v2.7.0-beta.2.0.20230725154156-18c309b5fa18 h1:QeEaO1pPKiBxP38PnLuBLjTj6QTYQlBXf7iK4iWXHTA=
```

In this case, as per Go module conventions, the nearest tag is `v2.7.0-beta.2` and the commit is `18c309b5fa18`.

**Comment by jpds** [comment]
Yes, but the point is that this would all be useful to expose as a Prometheus metric - so it's simple to query and see what version is where.

Now that I've taken a closer look at my frontend servers, I did notice that in the Prometheus `go_build_info` metric - I have one Caddy server that has `version="(devel)"`, but actually, what's installed came from the FreeBSD package:

```
# pkg info caddy
caddy-2.6.4_4
Name           : caddy
Version        : 2.6.4_4
Installed on   : Tue May 23 21:08:08 2023 UTC
Origin         : www/caddy
Architecture   : FreeBSD:13:amd64
Prefix         : /usr/local
Categories     : www
Licenses       : APACHE20
Maintainer     : adamw@FreeBSD.org
WWW            : https://caddyserver.com
Comment        : Fast, cross-platform HTTP/2 web server with automatic HTTPS
Annotations    :
	FreeBSD_version: 1301000
	cpe            : cpe:2.3:a:caddyserver:caddy:2.6.4:::::freebsd13:x64:4
	repo_type      : binary
	repository     : FreeBSD
Flat size      : 38.3MiB
Description    :
Caddy is a powerful, enterprise-ready, open source web server with automatic
HTTPS written in Go.
...
WWW: https://caddyserver.com
# ls -l /usr/local/bin/caddy
-r-xr-xr-x  1 root  wheel  56335560 May 23 21:08 /usr/local/bin/caddy
```

**Comment by mohammed90** [comment]
> Yes, but the point is that this would all be useful to expose as a Prometheus metric - so it's simple to query and see what version is where.
> 
> Now that I've taken a closer look at my frontend servers, I did notice that in the Prometheus `go_build_info` metric - I have one Caddy server that has `version="(devel)"`, but actually, what's installed came from the FreeBSD package:
> 
> ```
> # pkg info caddy
> caddy-2.6.4_4
> Name           : caddy
> Version        : 2.6.4_4
> Installed on   : Tue May 23 21:08:08 2023 UTC
> Origin         : www/caddy
> Architecture   : FreeBSD:13:amd64
> Prefix         : /usr/local
> Categories     : www
> Licenses       : APACHE20
> Maintainer     : adamw@FreeBSD.org
> WWW            : https://caddyserver.com
> Comment        : Fast, cross-platform HTTP/2 web server with automatic HTTPS
> Annotations    :
> 	FreeBSD_version: 1301000
> 	cpe            : cpe:2.3:a:caddyserver:caddy:2.6.4:::::freebsd13:x64:4
> 	repo_type      : binary
> 	repository     : FreeBSD
> Flat size      : 38.3MiB
> Description    :
> Caddy is a powerful, enterprise-ready, open source web server with automatic
> HTTPS written in Go.
> ...
> WWW: https://caddyserver.com
> # ls -l /usr/local/bin/caddy
> -r-xr-xr-x  1 root  wheel  56335560 May 23 21:08 /usr/local/bin/caddy
> # caddy version
> 3a63ef7e9af5e735148a27468246af18afbf78ae (23 May 23 20:44 UTC)
> ```

Pretty sure this has to do with how FreeBSD ports builds caddy. Do you happen to know the reference website/repo of where the caddy port is? I'd like to take a look. We might be able to guide them on how to build it in a way that retains the version.

**Comment by jpds** [comment]
It's over at: https://cgit.freebsd.org/ports/tree/www/caddy/Makefile ( maintained by @assistcontrol )

**Comment by assistcontrol** [comment]
That’s pretty odd. The port should be reporting the `${DISTVERSION}`. I’m the guy who submitted the `CustomVersion` patch to caddy, specifically so that FreeBSD could report the correct version.

In a clean jail using the same pkg version as you:

```
nobody@apnoea:~ % pkg info
caddy-2.6.4_4                  Fast, cross-platform HTTP/2 web server with automatic HTTPS
pkg-1.20.4                     Package manager
nobody@apnoea:~ % caddy version
v2.6.4
```

@jpds, Is there any chance that you have a caddy binary somewhere else in your `$PATH`?

And, @mohammed90, because it always comes up when FreeBSD shows up in caddy bug reports: FreeBSD cannot use xcaddy to build caddy packages. Our build process explicitly prevents network access during build, so we have to build from the release tarball and an inventory of all dependent packages (which are fetched before the build starts). We do have an xcaddy package for people who want to build caddy locally, and I did add a [caddy-custom](https://cgit.freebsd.org/ports/tree/www/caddy-custom) port that uses xcaddy for a proper build, but requires punching a hole in the builder.

**Comment by mohammed90** [comment]
> And, @mohammed90, because it always comes up when FreeBSD shows up in caddy bug reports: FreeBSD cannot use xcaddy to build caddy packages. Our build process explicitly prevents network access during build, so we have to build from the release tarball and an inventory of all dependent packages (which are fetched before the build starts)

**Comment by mohammed90** [comment]
Since this metric comes from the exported metrics, I'll have to investigate how the prometheus client generates this value. I'll give it a look.

> And, @mohammed90, because it always comes up when FreeBSD shows up in caddy bug reports: FreeBSD cannot use xcaddy to build caddy packages. Our build process explicitly prevents network access during build, so we have to build from the release tarball and an inventory of all dependent packages (which are fetched before the build starts).

Our release assets now include `caddy_<version>_buildable-artifact.tar.gz`, which includes a packaged Go module with all the deps vendored, including Caddy. It's constructed in a way that preserves the build info. Check it here in the beta release:
https://github.com/caddyserver/caddy/releases/tag/v2.7.0-beta.2
