### ISSUE TITLE
Discuss TLS self_signed and insecure_secrets_log

### ISSUE THREAD

**Issue by nguyenthanhtrungbkhn** [caddyserver/caddy#5655]
Dear @mholt and everyone,
I set up a secure listener, which is required for TLS and QUIC connections. I want to use both self_signed and insecure_secrets_log in tls but it does not work. Can you help me?

https://10.0.2.2:4242 {
    root /path/example/
    tls {
        self_signed
        insecure_secrets_log keys.log
    }
    log stdout
}

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! So far, this doesn't look like a bug in Caddy. It looks more like a question about how to use Caddy rather than a bug report or feature request.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!
