### ISSUE TITLE
handle match parent path rather than the subpath with both wildcard suffix if the subpath reverse_proxy respond 405

### ISSUE THREAD

**Issue by ulion** [caddyserver/caddy#5666]
```    
    handle /api/xxx* {
        reverse_proxy 127.0.0.1:3000
    }
    handle /api/* {
         reverse_proxy 127.0.0.1:3001
    }
```
above config result /api/xxx is indeed called, but if the reverse_proxy got 405 error, the final result is served by the /api/* handler, that's unexpected, because we except the matching handler reverse_proxy passthrough what ever the reverse proxy backend server respond, instead of failure then fallback to the other matched path?
change reverse_proxy to respond does not result this result, just the failure reverse_proxy does.

**Comment by francislavoie** [comment]
Please show a full config example and `curl -v` commands to show the behaviour you're seeing. We need to be able to minimally reproduce this if there's indeed a bug.

**Comment by ulion** [comment]
@francislavoie I did some test, now shrank the issue to reverse_proxy fail-safe issue. but it should not. I did not see any config related to reverse_proxy fail-safe, try other matching handle related info in doc. is it a bug or how to stop it by config?

**Comment by francislavoie** [comment]
Again, please post your full config, full logs, and an example `curl -v` command. Without that, we cannot help. We need to be on the same page here, and with only partial information, I have to make assumptions or guesses as to what you're doing, and that's a waste of time for both of us.

**Comment by ulion** [comment]
above config is all you need, just make sure the first reverse_proxy respond 405, then the request to /api/xxx will try to get result from the 2nd reverse_proxy.

**Comment by francislavoie** [comment]
No, it's not all we need. _We need a full and minimally reproducible config to verify the behaviour_.

**Comment by mholt** [comment]
Ideally, we need to be able to reproduce the bug _in the most minimal way possible_ **using the latest version of Caddy.** This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

This should be the latest version of Caddy:

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Instructions -- please heed otherwise we cannot help you (help us help you!)

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222) Please enable debug and access logs.
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by ulion** [comment]
sorry, this is not an issue of caddy. is the first reverse proxy server, that server did then request caddy which match the 2nd handle path.

**Comment by mholt** [comment]
Ok. Not entirely sure I understand, but thanks for letting us know :)
