### ISSUE TITLE
Placeholder {args[0]} index is out of bounds, only 0 argument(s) exist

### ISSUE THREAD

**Issue by vibbow** [caddyserver/caddy#5701]
Hi there,

Today I upgrade my caddy to 2.7.3, and modified `Caddyfile` by replace `{args.0}` to `{args[0]}`

I have some config snip like this:

```
(log_conf)
{
  log {
    output file /var/log/caddy/{args[0]}_access.log {
      roll_size 100MiB
      roll_keep 10
      roll_keep_for 90d
    }
  }
}
```

And they are calling by Caddyfile like this:

```
https://my_domain.com {
	import log_conf my_domain
	reverse_proxy http://web
}
```

Now I saw some warning when start caddy

`{"level":"warn","ts":1691284809.3552647,"logger":"caddyfile","msg":"Placeholder {args[0]} index is out of bounds, only 0 argument(s) exist"}`

But everything seems works fine.

**Comment by WeidiDeng** [comment]
You should define snippet like this:

```
(log_conf) {
  log {
    output file /var/log/caddy/{args[0]}_access.log {
      roll_size 100MiB
      roll_keep 10
      roll_keep_for 90d
    }
  }
}
```

as in official [documentation](https://caddyserver.com/docs/caddyfile/concepts#snippets).

The warning is because when parsing Caddyfile we tried to determine if a token is part of a snippet and it only checks for formatted caddy configuration.And since the opening brace is on a new line, parser failed to recognize it is part of snippet and tried to replace the placeholder during the first import (importing files containing snippet definition), hence the warning.

The configuration works fine because during the second import, snippets are already defined and it's simply replaced with value from the arguments.

**Comment by mholt** [comment]
Thanks for the answer, Weidi :100:
