### ISSUE TITLE
[Caddyfile] HTML response using heredoc syntax default Content-type is not HTML

### ISSUE THREAD

**Issue by Lan-Hekary** [caddyserver/caddy#5715]
Hello Team,
According to the respond directive [docs](https://caddyserver.com/docs/caddyfile/directives/respond) the default Content-Type is `text/plain`.
But in the case of heredoc syntax, the response is supposed to be a valid HTML.
So the Content-Type header should be set by default in this case only to `text/html` to avoid the explicit use of the header directive.

I admit that this is an opinionated request, but it just seems logical to me in the case of returning HTML with heredoc.
This will simplify the code and reduce errors. as it does seem intuitive to send Content-Type header for html with heredoc syntax nor it's not mentioned in the docs.

**Comment by mohammed90** [comment]
> But in the case of heredoc syntax, the response is supposed to be a valid HTML.

Not really. The `HTML` used in the documentation is only a marker for opening and closing the body, per the heredoc syntax. The content of heredoc can be anything, JSON, YAML, plain text, anything. If you want to set the correct `Content-Type` for your response body, use the `header` directive as such:

```
localhost {
	header Content-Type text/html
	respond <<HTML
	<html>
	  <head><title>Foo</title></head>
	  <body>Foo</body>
	</html>
	HTML 200
}
```

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing.

**Comment by francislavoie** [comment]
@mohammed90 is correct, heredocs have nothing to do with response headers, it's just a way to write multi-line tokens, and that's it.

You're right though that it would probably make sense to document in that example that `header Content-Type text/html` should be used.
