### ISSUE TITLE
Automate docker builds

### ISSUE THREAD

**Issue by douglasparker** [caddyserver/caddy#5732]
I have my own automated caddy builds that check for new stable and beta releases, but I frequently get errors because certain beta releases (and now stable releases) do not have docker releases for both caddy and caddy builder.

I still don't quite understand why docker releases for caddy are not automated, but it really causes issues with my own timely releases of docker builds (with the cloudflare dns plugin).

I end up missing versions that never get built and never have an idea if it's just delayed or not being built at all (like the last beta release).

Is there no way to automate this at all like most other software? Surely, if there is a will, there is a way.

See issue: https://github.com/caddyserver/caddy-docker/issues/307

Furthermore, it looks like people who haven't contributed to caddy-docker are unable to open issues, which is why I had to open an issue here.

I'm really getting the impression that the caddy team isn't open to discussion on how the docker release process can be improved.

**Comment by Jiehong** [comment]
> Furthermore, it looks like people who haven't contributed to caddy-docker are unable to open issues, which is why I had to open an issue here.

This restriction seems to be new, because yesterday I could comment on that issue, today I no longer can.

**Comment by mholt** [comment]
> I still don't quite understand why docker releases for caddy are not automated

I don't understand it all either, but the final step in the process is a manual review regardless, that's Docker's policy.

I had to put a temporary limit in place on the caddy-docker and (for some reason!?) the caddy-dns/cloudflare repo because of too many duplicate issues about the Docker image.

> I'm really getting the impression that the caddy team isn't open to discussion on how the docker release process can be improved.

We are, but as stated in the issue you linked to, it just so happens that our one _unpaid, volunteer_ Docker image maintainer is vacation and out of connectivity until after the weekend. Closing duplicate issues wastes our time and detracts our mental bandwidth from actual actionable items.

Please be patient.

**Comment by mholt** [comment]
Meanwhile, I'm being impatient for GitHub to finish transferring this issue, which, QUITE ironically, created a disjoint duplicate discussion :unamused:

Closing in favor of partially-transferred issue: https://github.com/caddyserver/caddy-docker/issues/312
