### ISSUE TITLE
error msg on docker run caddy

### ISSUE THREAD

**Issue by toyo2333** [caddyserver/caddy#5740]
{"level":"warn","ts":1691902074.8880541,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}

{"level":"info","ts":1691902074.9152985,"msg":"failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details."}

this is my Caddyfile
```
xxx.xxxxxxxx.xyz {
    reverse_proxy containerName:1200
}
```

the servies worked fine,but every time i restart caddy i got the msg above.

1、the Caddyfile is just copy from the example from the caddy official website document,what is wrong with the its format?
2、i did not enable any udp feature like http3 or grpc (the paremeter of docker run is "docker run -d -p 80:80 -p 443:443",  so why give me a warning about UDP? why can not caddy log msg gracefully？Pls Do NOT output log messages that have nothing to do with my current application configuration?

**Comment by mohammed90** [comment]
> 1、the Caddyfile is just copy from the example from the caddy official website document,what is wrong with the its format?

Your editor might have converted tabs to spaces or probably have an extra newline at the bottom of the file. Either of those caused the warning. You can run `caddy fmt --overwrite`

> 2、i did not enable any udp feature like http3 or grpc (the paremeter of docker run is "docker run -d -p 80:80 -p 443:443", so why give me a warning about UDP?

HTTP/3 is enabled by default in Caddy since [v2.6.0](https://github.com/caddyserver/caddy/releases/tag/v2.6.0), and it has been this way since [RFC-9114](https://datatracker.ietf.org/doc/rfc9114/) become standard. HTTP/3 works over UDP. You can use the [`protocols` global option](https://caddyserver.com/docs/caddyfile/options#protocols) in the Caddyfile to disable it.

> why can not caddy log msg gracefully？Pls Do NOT output log messages that have nothing to do with my current application configuration?

It did log gracefully and has everything to do with your configuration. The server did not crash and your deployment accepts HTTP/3 per the configuration! The first log line was a _warning_ (not fatal nor error), and the second log line was _info_ (again, not fatal nor error).

This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community). For the future, please ask questions in the forum.

**Comment by francislavoie** [comment]
FYI you'll also need to add `-p 443:443/udp` to your docker command to accept UDP traffic. By default only TCP is used in Docker.
