### ISSUE TITLE
Timed hashes for load balancers

### ISSUE THREAD

**Issue by PoneyClairDeLune** [caddyserver/caddy#5762]
Is it possible to add a directive like `lb_time_hash`?

With policies utilizing sticky hashes in place, the same IP addresses and ports may get mapped to a single upstream indefinitely. Introducing an additional hash that refreshes with a given time interval helps avoid single upstreams getting constant use from a single IP address.

The idea goes as follows:
1. `lb_time_hash` is disabled by default, and only accepts a time value higher than 10 seconds (or other more appropriate values). Values above `0s` and below `10s` get treated as if `10s` is set, and any non-positive time value gets interpreted as `lb_time_hash` being disabled.
2. When `lb_time_hash` gets enabled, it only gets applied to sticky hash-based policies, namely `ip_hash`, `client_ip_hash`, `uri_hash`, `query`, `header` and `cookie`.
3. When calculating sticky hashes, the additional hash provided by `lb_time_hash` is introduced along with other inputs. The additional hash only updates to a different randomized value in relation to the launch time of Caddy itself, not system time.

Here is an example.
1. A Caddy server with three upstreams (A, B, C) is configured to have IP hash configured with `lb_time_hash` set to `60s`.
2. After boot up with initial time hash randomized, Caddy will route traffic from `10.0.0.1` to upstream A.
3. After the first 60 seconds, the time hash gets updated with a random value, causing Caddy to route traffic from said IP to upstream C instead.
...

**Comment by francislavoie** [comment]
Interesting idea.

I'm not sure how it would work algorithmically though. I guess we'd do something like:

```
time = currentTimeSecs - (currentTimeSecs % configSecs)
```

The idea is we subtract the modulo so that it stays the same time until the next `configSecs` window is ellapsed. Does this make sense?

I'm considering whether it should be configured as part of the lb policy or as a separate option. We have `fallback` now for many policies, so having options for policies has precedent now.

**Comment by mholt** [comment]
Thanks for opening an issue.

> Introducing an additional hash that refreshes with a given time interval helps avoid single upstreams getting constant use from a single IP address.

What is the problem with this though?

The whole point of IP-hash-based LB is to keep clients with the same backend as long as it exists. If that's not what you want, then use a different policy.

I guess I fail to see the motivation for this feature.

If it does get implemented, it'd probably be best as a separate plugin for now to see if it would become popular enough to be included in the core.

**Comment by PoneyClairDeLune** [comment]
> The whole point of IP-hash-based LB is to keep clients with the same backend as long as it exists. If that's not what you want, then use a different policy.

The hash-based load balancer isn't just for mapping an IP to the same backend, but rather reproducible and (somewhat) predictable load balancing. The introduction of time in these hash-based load balancers becomes more like a mild measure preventing a single server from being blasted by requests, while still having all the benefits hashes provide.

**Comment by PoneyClairDeLune** [comment]
> ```
> time = currentTimeSecs - (currentTimeSecs % configSecs)
> ```
> 
> The idea is we subtract the modulo so that it stays the same time until the next `configSecs` window is ellapsed. Does this make sense?

I'm actually thinking of something like

```go
time = rand.Uint32();
```

With the value getting refreshed to a new one after the set interval. This may be the cheaper way, as no additional modulo operations are introduced for every hash attempt.

**Comment by mholt** [comment]
> The hash-based load balancer isn't just for mapping an IP to the same backend, but rather reproducible and (somewhat) predictable load balancing. The introduction of time in these hash-based load balancers becomes more like a mild measure preventing a single server from being overloaded by requests, while still having all the benefits hashes provide.

I still don't really understand this; is there any reading material about this you could point me to? I'm not sure the benefits of sharding by timestamp, since a client that is overwhelming server A at first will just start overwhelming server B a little later.

It sounds like a job for a rate limiter.

**Comment by mholt** [comment]
Re-reading this very carefully I think I understand a little better what is being asked. Basically IP+timeblock as part of the LB hash. But I still don't fully understand the motivation:

> helps avoid single upstreams getting constant use from a single IP address.

(I guess I am not sure why this is a problem.)

Still, I'd be curious if someone implements this as a load balancing policy plugin, and sees real-world benefits with it, then we can more easily reconsider :smiley:

**Comment by ThaDaVos** [comment]
I myself am looking for this too - I want to use the `uri_hash` or `query` policy (as I have a specific query param to differentiate the users) - but I don't want to have this stay sticky for ever - as the reason I am using a load balancer is not for load balancing perse - the backend behind it has a bug which I cannot solve (I haven't written it), the bug is, if two requests come in at exactly the same time, something gets mixed up in the backend and data from the first request, gets stored at the second requests database - so I thought, why not spin up extra instances (as it uses an MSSQL Server anyway) to balance out the requests to multiple instances to prevent the situation of two requests coming in to the exact same instance - I wanted to use `least_conn` but as the API keeps session state - it would be better to stick a specific user to a specific upstream **temporarily** - so what I am looking for would be the above but more like `least_conn` combined with the `hashing` policies, only keeping the `hash` with a moving time window - so when another request from the same hash gets in, the expiration shifts - so as long as the requests keep coming, the hash stays

I hope this gives enough motivation for something like a hash based policy with expiration

**Comment by francislavoie** [comment]
@ThaDaVos If you want to take a shot at implementing what you need, you can just copy-paste one of the modules from https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/reverseproxy/selectionpolicies.go into a custom plugin (see https://caddyserver.com/docs/extending-caddy) and implement it to your needs. It doesn't need to be in Caddy itself.

**Comment by mholt** [comment]
If it becomes popular and generally useful, we can see about bringing it in later. But yeah I'd agree that a separate plugin might be a good start!

**Comment by PoneyClairDeLune** [comment]
@francislavoie @mholt I'm not sure if this counts as "generally useful", but a similar behaviour is already present in HAProxy called stick table, which can be paired with the least connection strategy to achieve the same behaviour.

@ThaDaVos I myself wrote Floaty for such, but due to performance considerations I already moved on to HAProxy, as such I no longer have such need in Caddy. You might find this helpful if you want this ready asap.

**Comment by ThaDaVos** [comment]
> @francislavoie @mholt I'm not sure if this counts as "generally useful", but a similar behaviour is already present in HAProxy called stick table, which can be paired with the least connection strategy to achieve the same behaviour.
> 
> @ThaDaVos I myself wrote Ditzy for such, but due to performance considerations I already moved on to HAProxy, as such I no longer have such need in Caddy. You might find this helpful if you want this ready asap.

I myself moved to a manually compiled HAProxy too (running on Windows) as for some reason in the stack I was using (Browser - PHP with Curl - Caddy - Clarion with Nettalk Server) certain requests weren't decodable in php after being received through Caddy (eof errors) - same request using curl or Postman didn't EOF - so I swapped out Caddy with HAProxy and issue was gone
