### ISSUE TITLE
cors configuration doesn't work

### ISSUE THREAD

**Issue by 0xEclair** [caddyserver/caddy#5785]
caddy version: 2.6.4
```
(cors) {
	@origin header Origin {args.0}
	header @origin {
		header_down Access-Control-Allow-Origin "{args.0}"
		header_down Access-Control-Request-Method *
	}
}

example.com {
	encode gzip zstd
	file_server
	header {
		Strict-Transport-Security max-age=31536000;
		Referrer-Policy strict-origin-when-cross-origin
	}
	import cors https://example.com
	reverse_proxy localhost:port
}

example.org {
	encode gzip zstd
	file_server
	header {
		Strict-Transport-Security max-age=31536000;
		Referrer-Policy strict-origin-when-cross-origin
	}
	import cors https://example.org
	reverse_proxy remote_host:port
}
```

When i use `reverse_proxy` for remote_host(example.org), there are no headers about cors in the response. But it worked for localhost.

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! So far, this doesn't look like a bug in Caddy. It looks more like a question about how to use Caddy rather than a bug report or feature request.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced than I am with the specific issue you're facing. I hope you'll ask your question there. The Help category in the forum even provides a template you can fill out.

If I'm wrong, and this does turn out to be a bug after further investigation, we can reopen this. Thanks for understanding!
