### ISSUE TITLE
Include `http.request.uuid` field in access logs?

### ISSUE THREAD

**Issue by sleeyax** [caddyserver/caddy#5820]
I have a reverse proxy setup and I'm trying to 'link' access logs to upstream server events. What I've got so far is the following Caddy file:

```nginx
localhost {
	reverse_proxy {
		to https://localhost:5000
		header_up X-Request-Id "{http.request.uuid}"
		transport http {
			tls
			tls_insecure_skip_verify
			read_buffer 8192
		}
	}
	log {
		level info
		# somehow include an additional field {..., requestId: "{http.request.uuid}"} in the log?
	}
}
```

The HTTP server at `https://localhost:5000` can read the incoming `X-Request-Id` header just fine. But how can I  write the same request ID to the access log to link them together (for deeper analysis in case of upstream server errors)?

Perhaps someone knows a work-around for this issue?

**Comment by mholt** [comment]
We don't actually generate the UUID until the placeholder is used, however, so if we add it to the logs, it would always be generated. (Not that that's bad... it just brings us ever closer to that meteor strike. ... jk)

The access logs are designed to show the requests as the client sent them, but I suppose it would make sense to add that UUID if we have it. Since the log line is deferred to after the request, maybe we can add it. I'll play with this in a bit.

**Comment by HeCorr** [comment]
A workaround I found is to copy the header sent by Caddy at the upstream as a response header (it shows up in Caddy's logs at `request.resp_headers`), but then there's no point in getting the ID from Caddy since it has to go through the upstream server and back, so might as well just generate it there.

This does make the request ID also visible to the client but IMO that's often not an issue and could even be useful for error reports if exposed to the user.

**Comment by francislavoie** [comment]
Implemented in https://github.com/caddyserver/caddy/pull/5859
