### ISSUE TITLE
Limit maximum connection to upstream server

### ISSUE THREAD

**Issue by b4stien** [caddyserver/caddy#5831]
Hi team, thanks for your work on Caddy! I wonder if there is a way to limit concurrent connection to an upstream server?

On our scenario we currently use nginx in front of gunicorn and are using nginx's [`max_conns`](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#max_conns) (and considering using [`queue`](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#queue) on the commercial version) to limit connection and queuing to our upstream servers (gunicorn workers).

_This is exactly the same need / issue than https://github.com/caddyserver/caddy/issues/613. A feature was developed to resolve this issue in Caddy 1, it's unclear for me if the feature still exists on Caddy 2. #613 was closed/locked following my message, I'm not sure why, I'm pretty sure my request there is sound but it doesn't matter. **What does matter** is that a potential answer to this issue is linked there, because #613 appears on search results / web pages everywhere and is no longer relevant._

**Comment by mholt** [comment]
Yes, in fact it's better than that - you can limit the number of concurrent _requests_, which are actual units of work for HTTP servers, rather than connections which are just pipes for the work.

This advanced capability is available in the JSON config here when you define proxy upstreams: https://caddyserver.com/docs/modules/http.handlers.reverse_proxy#upstreams/max_requests

You can, however, also limit the number of connections to each host using HTTP transport config: https://caddyserver.com/docs/modules/http.reverse_proxy.transport.http#max_conns_per_host

The transport options are also available in the Caddyfile: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#the-http-transport

**Comment by b4stien** [comment]
Thanks a ton, it looks perfect. Do you think you can post a comment on #613 to point here for future readers?
