### ISSUE TITLE
API, UX: Init caddy with an empty default config instead of null

### ISSUE THREAD

**Issue by tetra12** [caddyserver/caddy#5842]
Caddy: v2.7.4+ (master)
Go: v1.21.1
OS: Ubuntu 22.04

**Issue**: 
I wanna add a new server listener with API as per [docs](https://caddyserver.com/docs/api#post-configpath). However, when caddy starts, the config object doesn't exist and an explicit initialization with an extra API call is required.

**Reproduce**:
1. Start without config: `caddy run`
2. Check initial config: `curl localhost:2019/config/`: `null`
3. Save a basic JSON config as below to `hello.json`:
```json
{
  "hello": {
    "listen": [":4443"],
    "routes": [
      {
        "handle": [
          {
            "handler": "static_response",
            "body": "Hello, world!"
          }
        ]
      }
    ]
  }
}
```
4. Add a static route with API: `curl localhost:2019/config/apps/http/servers <<< $(cat hello.json)`
```sh
{"error":"invalid traversal path at: config/apps"}
```
**Workaround**:
1. Save `init.json` with the following:
```json
{            
  "apps": {
    "http": {
      "servers": {}
     }
   }
}
```
2. Init caddy with: `curl localhost:2019/load <<< $(cat init.json)`
3. Add a static route with API: `curl localhost:2019/config/apps/http/servers <<< $(cat hello.json)`
`{"apps":{"http":{"servers":{"bye":{"listen":[":4443"],"routes":[{"handle":[{"body":"Hello, world!","handler":"static_response"}]}]}}}}}`

**Comment by francislavoie** [comment]
Caddy might not be actually used for the `http` app at all, so any default other than an empty config does not make sense.

It's your responsibility to initialize the config with a default that makes sense for you.

**Comment by mholt** [comment]
I see what you're saying -- you'd like to be able to implicitly create the config path even if it doesn't exist yet. I chose not to do that (by default) for a few reasons, namely that we don't actually know the structure of the config until it is POSTed and loaded (since the config is modular we don't know ahead of time what to fill in each path component as -- is it an object, an array, etc?), and because users may find it surprising that a request to a non-existent path succeeds and oops, now they just created a huge tree in their config that they didn't mean for it to exist.

So yeah, we really try not to make assumptions here. Is there anything wrong with starting Caddy with an initial config?

**Comment by tetra12** [comment]
@mholt Thanks for a detailed explanation :smile: . I don't see any problem adding an extra API call during `caddy` initialization. There are always trade-offs between user and developer experience, but keeping things small and simple is usually the right choise :+1: 
Futher, `caddy` initialization with API is not the hottest feature and there's a little to zero call to change anything now.
Closing this as out of scope feature.

**Comment by mholt** [comment]
Ok cool -- thanks for understanding!
