### ISSUE TITLE
`map` output placeholder values not being read by `tls`

### ISSUE THREAD

**Issue by Inetol** [caddyserver/caddy#5920]
In a nutshell, when the `tls` directive reads the value of the placeholder {ZZtls_cert} or {ZZtls_key} from `map` it returns this error:
```
Error: loading initial config: loading new config: loading http app module: provision http: getting tls app: loading tls app module: provision tls: loading certificates: open {ZZtls_cert}: no such file or directory
```

Used Caddyfile format config:
```java
map {args[0]} {ZZtls_cert} {ZZtls_key} {
	rac5000 "/path/to/certificate" "/path/to/key"
	rac5001 "/another/path/to/certificate" "/another/path/to/key"
	rac5002 "/path/to/another/certificate" "/path/to/another/key"
	...
}

tls {ZZtls_cert} {ZZtls_key} {
	...
}
```

```
v2.7.5 h1:HoysvZkLcN2xJExEepaFHK92Qgs7xAiCFydN5x5Hs6Q=
```

**Comment by francislavoie** [comment]
Yes, you can't use HTTP-context placeholders in `tls` because TLS happens _before_ the HTTP handshake happens. The `map` directive is run as an HTTP handler, so those placeholders don't exist.

You'll need to rework your Caddyfile snippets to directly put the cert/key arguments on the `tls` directive, so that it's set in the config when the Caddyfile is parsed.
