### ISSUE TITLE
Client sent an HTTP request to an HTTPS server. ︽

### ISSUE THREAD

**Issue by visualwind** [caddyserver/caddy#5925]
Hello every one,
My 80 and 443 port are blocked, so I change  https_port to 1443,
when I open https://raspi.abc.me:1443, it works correctly.
But when I open http://raspi.abc.me:1443,
the web page show"Client sent an HTTP request to an HTTPS server."
How can I redir http://raspi.abc.me:1443 to https://raspi.abc.me:1443
Thank you!

**Comment by francislavoie** [comment]
See https://caddyserver.com/docs/caddyfile/options#listener-wrappers you're looking for the `http_redirect` listener wrapper.

Please note that the current release of Caddy has broken that feature, but it will be fixed in the next version. So you might want to wait to enable it until 2.7.6 is released.
