### ISSUE TITLE
Caddyfile `handle_errors` optional status code argument 

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#5928]
The [`handle_errors`](https://caddyserver.com/docs/caddyfile/directives/handle_errors) directive is useful for implementing custom error pages and such.

Currently, its ergonomics are not great, because matching errors by status code needs to be done via a `handle` with an `expression` matcher (see examples in the docs).

I suggest that we add an optional status code argument (or variadic multiple status codes) to `handle_errors` as a shortcut for wrapping the routes in a status code matcher. For example:

```
handle_errors 404 410 {
	<directives...>
}
```

This would effectively be the same as:

```
handle_errors {
	@codes expression `{http.error.status_code} in [404, 410]`
	handle @codes {
		<directives...>		
	}
}
```

Using `handle_errors` this way multiple times should simply append more routes. A `handle_errors` with no arguments (no matcher) should always be inserted last to ensure it acts as a fallback.

**Comment by mholt** [comment]
I like this idea.

**Comment by pkkht** [comment]
Hi, 
I would like to work on this task. Can I pick it up?

**Comment by francislavoie** [comment]
Sure @pkkht, PRs welcome.

**Comment by pkkht** [comment]
Ah,, unable to contribute due to change in circumstances. Sorry about that!

**Comment by armadi1809** [comment]
Hello, I would like to contribute. Can I pick this issue up?

**Comment by mholt** [comment]
Sure 👍

**Comment by armadi1809** [comment]
Thank you! I am on it then!

**Comment by armadi1809** [comment]
In the description of the issue, does **multiple** status codes just mean two status codes? From the looks of it we are looking at ranges here right? 

Also, how do you suggest going about enforcing that a handle_error directive without arguments should come last?

**Comment by mohammed90** [comment]
> does **multiple** status codes just mean two status codes? From the looks of it we are looking at ranges here right?

Not only 2. It can be any number of arguments or something like `4xx`, see example in the [Response Matcher of `reverse_proxy`](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#response-matcher).

> how do you suggest going about enforcing that a handle_error directive without arguments should come last?

You can either keep it aside in the parsing process then append it at the end after parsing all other handlers, or manage the sorting logic in your implementation of the [`sort.Interface`](https://pkg.go.dev/sort#Interface).

**Comment by armadi1809** [comment]
Sorry for the multiple follow ups and maybe the "trivial" questions,  but I guess I am a little bit confused on how I should be approaching this. Is the idea here to build a new `handle_errors` parser from scratch where we programmatically add expressions based on the status codes arguments (instead of the user having to type them)? 

Also, we need to make sure that if someone has the arguments, they are not allowed to have the current `expression / handle` syntax or are we getting rid of that syntax completely?

**Comment by francislavoie** [comment]
See `handle_path` for example:

https://github.com/caddyserver/caddy/blob/18f34290d26d10b6dd62c848b6bd5180d56d7f3a/modules/caddyhttp/rewrite/caddyfile.go#L155

Basically just need to do `h.RemainingArgs()` and if that slice is non-empty then you create a `caddyhttp.MatchExpression` (with field `Expr` set) which is a string like `"{http.error.status_code} in [" + strings.Join(", ", args) + "]"` effectively.

Bonus points for handling `4xx` style strings (which means any 400-499 status, a convention we support in most places with status code matching), which should separately expand to something like `"{http.error.status_code} >= 200 && {http.error.status_code} <= 299", and join that with an `||` if there's any args with no `xx`.

**Comment by armadi1809** [comment]
Thank you for the detailed response!

**Comment by armadi1809** [comment]
@francislavoie, I think I am almost there, I got individual `handle_errors` directives to work with both of the status codes formats. One problem I am facing now is that only the first `hanlde_errors` directive in the `CaddyFile` is triggered and all the others are omitted. Can I get some guidance on where in the code we are enforcing this, because up until the code you showed above from `httptype.go` I can see all the `handle_errors` routes inside the `errorSubrouteVals`. 

Thanks in advance for your help!

**Comment by mholt** [comment]
Hmm, are you referring to the one argument being the `caddyhttp.Handler` value? You should only need 1 handler, as it has all the tokens for the segment in it. Does that make sense?

> Again, sorry if my questions are very trivial, I am still learning the way we want to do things here.

Not at all; you're contributing in a place that very few other people have even read the code for.
