### ISSUE TITLE
Request queue server configuration

### ISSUE THREAD

**Issue by AxelTheGerman** [caddyserver/caddy#5943]
This is related to #1745 - I'd like to report on request queue time (e.g. as [documented by New Relic](https://docs.newrelic.com/docs/apm/applications-menu/features/request-queue-server-configuration-examples/)).

The monitoring tool is expecting one of the following headers containing a unix formatted timestamp - ideally in milliseconds:
- `X-Request-Start`
- `X-Queue-Start`

This works out of the box with ninx but I'm a little lost if/how this is possible to set up with Caddy (I believe the linked ticket above might be for an older Caddy version?)

Thank you!

**Comment by mohammed90** [comment]
You can combine the use of [`header_up` directive](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#headers) of `reverse_proxy` and `{time.now.unix_ms}` [placeholder](https://caddyserver.com/docs/conventions#placeholders).

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing.

**Comment by francislavoie** [comment]
Additionally if you're using `reverse_proxy`, there's a bunch more timing placeholders you can use https://caddyserver.com/docs/json/apps/http/servers/routes/handle/reverse_proxy/#docs (most can only be used after the response is written). And also https://caddyserver.com/docs/json/apps/http/#docs which has `duration` placeholders which is "time since the request started" which I guess can act like the "queue time"?
