### ISSUE TITLE
Problems with reverse_proxy and WS://

### ISSUE THREAD

**Issue by alejandroserrag** [caddyserver/caddy#5947]
We he ve problems with reverse_proxy and WS://
This are the code:
	route /api/ws/* {
          reverse_proxy ws://localhost:5555
	}
And the error:
Error: adapting config using caddyfile: parsing caddyfile tokens for 'route': parsing caddyfile tokens for 'reverse_proxy': parsing upstream 'ws://localhost:5555': the scheme ws:// is only supported in browsers; use http:// instead, at /etc/caddy/Caddyfile:71, at /etc/caddy/Caddyfile:72

He are using Ubuntu 22.04 and Caddy 2.7.5. 
On previous instalation with CentOs and Cady 2.7.4, the save Caddyfile work fine.

Someone can help me.

Thanks.

**Comment by mohammed90** [comment]
> ws://localhost:5555

`ws` is not a valid scheme. Use `http`.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your future questions there, and thanks for understanding!

**Comment by francislavoie** [comment]
See the docs: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#upstream-addresses WebSocket support is enabled by default by the proxy.
