### ISSUE TITLE
Vulnerable golang installed

### ISSUE THREAD

**Issue by hackerfactor** [caddyserver/caddy#5953]
I just downloaded caddy for amd64:
```
$ ./caddy version
v2.7.5 h1:HoysvZkLcN2xJExEepaFHK92Qgs7xAiCFydN5x5Hs6Q=
$ ./caddy build-info | grep google
dep	github.com/google/cel-go	v0.15.1	h1:iTgVZor2x9okXtmTrqO8cg4uvqIeaBcWhXtruaWFMYQ=
dep	github.com/google/certificate-transparency-go	v1.1.6	h1:SW5K3sr7ptST/pIvNkSVWMiJqemRmkjJPPT0jzXdOOY=
dep	github.com/google/go-tpm	v0.9.0	h1:sQF6YqWMi+SCXpsmS3fd21oPy/vSddwZry4JnmltHVk=
dep	github.com/google/go-tspi	v0.3.0	h1:ADtq8RKfP+jrTyIWIZDIYcKOMecRqNJFOew2IT0Inus=
dep	github.com/google/uuid	v1.3.1	h1:KjJaJ9iWZ3jOFZIf1Lqf4laDRCasjl0BCmnEGxkdLb4=
dep	google.golang.org/genproto	v0.0.0-20230913181813-007df8e322eb	h1:XFBgcDwm7irdHTbz4Zk2h7Mh+eis4nfJEFQFYzJzuIA=
dep	google.golang.org/genproto/googleapis/api	v0.0.0-20230803162519-f966b187b2e5	h1:nIgk/EEq3/YlnmVVXVnm14rC2oxgs1o0ong4sD/rd44=
dep	google.golang.org/genproto/googleapis/rpc	v0.0.0-20230920204549-e6e6cdab5c13	h1:N3bU/SQDCDyD6R528GJ/PwW9KjYcJA3dgyH+MovAkIM=
dep	google.golang.org/grpc	v1.58.2	h1:SXUpjxeVF3FKrTYQI4f4KvbGD5u2xccdYdurwowix5I=
dep	google.golang.org/protobuf	v1.31.0	h1:g0LDEJHgrBl9N9r17Ru3sqWhkIx2NB67okBHPwC7hs8=
```
A vulnerability scan using grype finds:
```
NAME                                                           INSTALLED  FIXED-IN  TYPE       VULNERABILITY        SEVERITY 
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp  v0.42.0    0.44.0    go-module  GHSA-rcjv-mgp8-qvmr  High      
google.golang.org/grpc                                         v1.58.2    1.58.3    go-module  GHSA-m425-mq94-257g  High      
google.golang.org/grpc                                         v1.58.2    1.58.3    go-module  GHSA-qppj-fm5r-hxr3  Medium
```
The git repo says that it uses 1.58.3, but the downloaded caddy executable still has 1.58.2.

**Comment by francislavoie** [comment]
Those vulnerabilities don't apply to Caddy.

Security scanners don't understand actual usage, and they make assumptions.

If you absolutely need a build with updated libraries, you can build from `master`.

**Comment by hackerfactor** [comment]
I totally understand that those vulnerabilities don't apply. (Or even if they do apply, I'm not using that functionality.)

HOWEVER, most companies just look at the vulnerability scan results. If there's a "HIGH" that has been patched, then why are you not distributing the patched code?

This isn't a false match like "the CVE is only for Mac and this is the Linux version". In this case, it's code that has a known vulnerability, even though it is never used. If you update the pre-compiled code, then even the "never used" code is no longer identified as having a vulnerability.

Please consider re-opening this issue and deploying the known-patched code.

**Comment by francislavoie** [comment]
> If there's a "HIGH" that has been patched, then why are you not distributing the patched code?

Because it's a waste of our time to go through the release process (takes a few man hours total across multiple people and distributions) when there's absolutely nothing of value added in the release other than ticking a checkbox to make scanners happy.

Our stance is that we ship releases when they're ready, and security releases only when they're critical and actually have an impact on the user base.

> HOWEVER, most companies just look at the vulnerability scan results.

If you or your company absolutely need a release, then please consider [sponsoring](https://github.com/sponsors/mholt) to cover the time cost. Otherwise, please be patient, we'll release when we're ready.

**Comment by mholt** [comment]
> In this case, it's code that has a known vulnerability, even though it is never used

That sounds like a bug in the static analyzer.

We're not going to bend over backwards for a bug in an unrelated project that we didn't even ask for.

Decades of security research has shown that repetitive, false alarms destroy confidence in them and that people will begin to ignore them (look up publications by Stark or Porter-Felt). There's an entire sector of the security industry that's been capitalizing on a gold rush that utilizes the same psychology as major news media manipulations. Unfortunately these kinds of scanners mean nothing to us because of that. I hope they're happy.

Francis is right, too: we are able to accommodate requests like these for business [sponsors](https://github.com/sponsors/mholt).
