### ISSUE TITLE
Unable to run Caddy with Magento 2 because of buffer sizes 

### ISSUE THREAD

**Issue by rofthedeep** [caddyserver/caddy#5966]
Hi,

with Magento 2 an caddy I'm getting "502 Bad Gateway" in my local development environment.

To solve it I think I need to configure buffer sizes in Caddy.

Before I used Caddy, I had a nginx setup. There I could solve the problem with setting the different buffer sizes like described here:
https://magento.stackexchange.com/a/320939/86367

I tried a lot of different approaches but didn't get the setup running :( Is there a possibility to set buffer sizes with caddy?

This is my current caddy file (tried a lot of other settings, too):

```
test.test {
    tls internal
    root * /Volumens/test
    php_fastcgi unix//usr/local/etc/php/php8.1.sock
    file_server
}
```

Thx!

**Comment by mohammed90** [comment]
Thanks for your question, and we're thrilled that you're using Caddy! Per the [`php_fastcgi` docs ](https://caddyserver.com/docs/caddyfile/directives/php_fastcgi#syntax), you can use any of the subdirective of the [`reverse_proxy` directive](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#syntax), which includes `{request,response}_buffers`.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

**Comment by rofthedeep** [comment]
Thx @mohammed90!
If someone has the same Problem - created a question in the community forum: https://caddy.community/t/unable-to-run-caddy-with-magento-2-because-of-buffer-sizes/21883
