### ISSUE TITLE
php_fastcgi should include handle_response for 500/503 errors?

### ISSUE THREAD

**Issue by fliespl** [caddyserver/caddy#6005]
With current implementation, when you use php_fastcgi + handle_errors, you will get broken page (i.e. without filled placeholders) and with improper status code.

I think that something like that should be done or at least mentioned in docs, because proxy servers like CF can cache such "500" page.

Handle errors part:

```
    handle_errors {
        handle {
            header Content-Type text/html
    		respond "<html><head><title>{err.status_code} {err.status_text}</title></head><body><center><h1>{err.status_code} {err.status_text}</h1></center></body></html>"
        }
    }
```

Different results for fastcgi part:

proper err.rstatus_code + err.status_text (page returns with status code = 500)
```
    php_fastcgi unix//run/php/php{{ php_version }}-fpm.sock {
        capture_stderr
        dial_timeout 10s
        read_timeout 300s
        write_timeout 300s

        @error500 status 500
        handle_response @error500 {
            error 500
        }
        @error503 status 503
        handle_response @error503 {
            error 503
        }
    }
```

Incorrect:

{err.status_code} {err.status_text} - not replaced at all  (page returns with status code = 200! - cacheable)

```
    php_fastcgi unix//run/php/php{{ php_version }}-fpm.sock {
        capture_stderr
        dial_timeout 10s
        read_timeout 300s
        write_timeout 300s
    }
```

Simple php file to test on:

```
<?php

throw new \Exception;
```

**Comment by francislavoie** [comment]
Yes, that's working as expected. All proxy responses regardless of the status code is a "successful response". Errors in the context of Caddy mean "an error emitted by a handler". The proxy only emits errors for things like failing to connect to an upstream or not having an available upstream (due to health checks).

This is explained in the docs https://caddyserver.com/docs/caddyfile/directives/handle_errors:

> Note that certain directives, for example [reverse_proxy](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy) which may write a response with an HTTP status which is classified as an error, will not trigger the error routes.

**Comment by fliespl** [comment]
@francislavoie I understand your point re reverse_proxy and it totally makes. 

Yet, I have doubt about php_fastcgi (special directive targeted for PHP apps). Those apps can return 50X errors in random situations (even when handled with set_error_handler).

**Comment by francislavoie** [comment]
`php_fastcgi` is a shortcut for `reverse_proxy` with the `transport fastcgi` and some extra rewrites. The docs explain this as well.

Your fix is the correct thing to do by using `handle_response`. You can shorten it though by matching more than one status code at once instead of only one at a time, and using the status code placeholder with the `error` directive.
