### ISSUE TITLE
caddy binds to all interfaces to port not only to specific IP like instructed

### ISSUE THREAD

**Issue by koh-osug** [caddyserver/caddy#6009]
The listener although instructed to bind to `127.0.0.200:7777` but binds to `enabling HTTP/3 listener        {"addr": ":7777"}`. No other IP address on the loopback interface can now use this port.

> sudo caddy reverse-proxy --from 127.0.0.200:7777 --to 127.0.0.201:7777
2023/12/30 10:33:04.001 WARN    admin   admin endpoint disabled
2023/12/30 10:33:04.001 INFO    http.auto_https enabling automatic HTTP->HTTPS redirects        {"server_name": "proxy"}
2023/12/30 10:33:04.001 INFO    tls.cache.maintenance   started background certificate maintenance      {"cache": "0xc0000af880"}
2023/12/30 10:33:04.005 WARN    tls     storage cleaning happened too recently; skipping for now        {"storage": "FileStorage:/root/.local/share/caddy", "instance": "c87c389d-a044-4f98-abef-c8b75e656f5e", "try_again": "2023/12/31 10:33:04.005", "try_again_in": 86399.999999345}
2023/12/30 10:33:04.005 INFO    tls     finished cleaning storage units
2023/12/30 10:33:04.016 INFO    pki.ca.local    root certificate is already trusted by system   {"path": "storage:pki/authorities/local/root.crt"}
2023/12/30 10:33:04.016 INFO    http    enabling HTTP/3 listener        {"addr": ":7777"}

**Comment by mholt** [comment]
I think this is working as expected. `--from` is not a listener address per-se (though it does imply a listener address), it is a host:port combo so that Caddy can serve TLS with a certificate for the domain or IP there. It is not a "bind" or "listen" address, strictly speaking. It's like a site name in your Caddyfile.

The default bind address is wildcard (all interfaces) on the specified port. This can be customized in the Caddyfile if needed; we don't currently have a way to do that on the CLI for reverse-proxy because it's meant only for simple and quick proxy use cases.

That said, I do wonder if we should automatically bind servers that are serving only localhost to the loopback interface, since you'd never reach `localhost` on a remote machine, right?

Sorry it took me so long to get to this.

**Comment by koh-osug** [comment]
> This can be customized in the Caddyfile if needed
What is the instruction for setting this to something else than the wildcard address?

**Comment by mholt** [comment]
The `bind` directive: https://caddyserver.com/docs/caddyfile/directives/bind

**Comment by koh-osug** [comment]
Thanks
