### ISSUE TITLE
single servers directive can not work with multiple sites

### ISSUE THREAD

**Issue by J0rmo** [caddyserver/caddy#6044]
When I configure the global option like below, 
```
{
    servers :81, :82 {
        protocols h1 h2c
        listener_wrappers {
            proxy_protocol
        }
    }
}
```

I get an error:
_Error: adapting config using caddyfile: parsing caddyfile tokens for 'servers': wrong argument count or unexpected line ending after ':82', at /etc/caddy/Caddyfile:2_

Doesn't the servers directive above support multiple sites?

**Comment by mholt** [comment]
Would it be complex to make it support multiple addresses?

**Comment by francislavoie** [comment]
It might not be, but I think it would be so niche that it's not worth complicating our logic to do it.

**Comment by Kangaroux** [comment]
> It might not be, but I think it would be so niche that it's not worth complicating our logic to do it.

I'm not sure this should be considered this niche; I have caddy configured to handle `domain.com` and `www.domain.com`. It complicates things for me since I want to use the same Caddyfile for local and prod, and in order to do that I inject the host(s) using an env var. 

The simplest solution I can think of is to have two near identical Caddyfiles, except one has two server blocks, which sucks. It also means two separate Dockerfiles and different env var naming schemes. I don't think impl complexity is justifiable when it complicates the config this much

**Comment by francislavoie** [comment]
@Kangaroux what you're saying has absolutely nothing to do with this issue. This is about the `servers` global option, not about domains.

That said, it's very normal to have `Caddyfile.prod` and `Caddyfile.dev` files and use either file depending on your environment. That's what we recommend. You don't need two Dockerfiles for this. Just mount the configs as a volume into your Caddy container, and override the run command to use the correct file (you could also use env vars for this part for the filename)

Let's keep this on topic. Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by Kangaroux** [comment]
> This is about the servers global option, not about domains.

Sorry if it wasn't clear, I was referring to the OP about having to dupe your server block for each domain in the site block:

```caddyfile
{
    servers domain.com {
        # ...
    }

    servers www.domain.com {
        # duplicated
    }
}

domain.com www.domain.com {
    # site block
}
```

I can split up the Caddyfile but the server block still gets duplicated. It just increases the likelihood that I change something in one and forget it in the other.

**Comment by francislavoie** [comment]
The `servers` global option does not take domains, it takes listener addresses. Please review the docs. Your config doesn't work.

**Comment by Kangaroux** [comment]
> The `servers` global option does not take domains, it takes listener addresses. Please review the docs. Your config doesn't work.

This is getting off-topic but -- unless the docs are incorrect -- the [listener address](https://caddyserver.com/docs/json/apps/http/servers/#listen) can be a [domain name](https://caddyserver.com/docs/conventions#network-addresses).

```
The host may be any hostname, resolvable domain name, or IP address.
```

**Comment by francislavoie** [comment]
Yes, but in the Caddyfile it's not. Please read https://caddyserver.com/docs/caddyfile/options#server-options. The listener address will be `:443`, unless you used the `bind` directive. Which makes no sense for your usecase. Adapt your Caddyfile to JSON and see what it produces, you'll see that it does not fill in server settings at all with your current config, it gets completely ignored because it doesn't match the actual listener address in the config.
