### ISSUE TITLE
PROXY protocol replacing `remote_host`?

### ISSUE THREAD

**Issue by polarathene** [caddyserver/caddy#6107]
Not sure if this is considered a bug.

When trying out PROXY protocol (_Caddy 2.7 and unreleased 2.8 master branch build_), I noticed that `remote_host` is also rewritten with the Client IP provided from the PROXY protocol header.

From what I've seen, with HTTP traffic without PROXY protocol connection, the `remote_host` is left alone when a `client_ip_headers` like `X-Forwarded-For` updates `client_ip`. I was wondering if it makes sense for that same expectation when PROXY protocol is in use?

**Comment by francislavoie** [comment]
That's by design. PROXY protocol is updating the `RemoteAddr` field on the `net.Conn` struct. That's what it has to do, because it's all it has access to at the time that it runs (before HTTP/TLS).

The `client_ip` is just an extra variable attached to the `http.Request` which gets filled as per `trusted_proxies` and whatnot.
