### ISSUE TITLE
upgrade deprecated go-jose package v2.6.0

### ISSUE THREAD

**Issue by ayg-qliktech** [caddyserver/caddy#6197]
- Upgrade deprecated go-jose package v2.6.0 (https://github.com/caddyserver/caddy/blob/0dd0487eba1592b19cb2260fe247b7d375301fe5/go.mod#L153). See https://github.com/square/go-jose/tree/v2.6.0 has now moved to https://github.com/go-jose/go-jose.
- As an added recommendation. It might be worth enabling Dependabot for Go package monitoring to help improve automated updates and avoid issues like this one in the future.

**Comment by mohammed90** [comment]
The package is not a direct dependency of Caddy. It's a transitive dependency through [go.step.sm/crypto/jose](https://pkg.go.dev/go.step.sm/crypto/jose). Since this is not actionable by us, I'll close this issue.

**Comment by ayg-qliktech** [comment]
Why close it and not address the top level package that includes the transitive dependency. Because Caddy will still be using the deprecated package otherwise. Which is also flagged with https://nvd.nist.gov/vuln/detail/CVE-2024-28180 when running security scans against Caddy itself. If we have to create another issue as a Security submission that's fine.

**Comment by mohammed90** [comment]
> Why close it and not address the top level package that includes the transitive dependency.

I'm not sure I understand. Caddy is not using `gopkg.in/square/go-jose.v2` directly. Caddy uses `go.step.sm/crypto/jose`, which in turn depends on `gopkg.in/square/go-jose.v2`. We can't, as Caddy, can't just replace `gopkg.in/square/go-jose.v2` with any other JOSE package just because they both do JOSE. The package `go.step.sm/crypto/jose v0.35.1` expects `gopkg.in/square/go-jose.v2` and can only work with that package. The solution in these scenarios is to ask the upstream package to change/upgrade the dependency they're using. We're not _avoiding_ the upgrade. We're saying we, typically, don't have control on an upstream package.

That said...

I see they already did what you're asking for in the commit https://github.com/smallstep/crypto/commit/d9198ca4bdcca8f72c46ec7d6344c558ee7bc075. I'll see if I can manage upgrading this dependency.

**Comment by ayg-qliktech** [comment]
Thank you for the explanation. However, when we run our internal TwistLock scans against the docker flavor of Caddy, it flags the previous mentioned dependency for CVE and points at the Caddy binary under the hood. Which is directly tied to your code base as part of its composition. Therefore, at this time Caddy isn't secure regardless of who does the fix. I will create the issue against the repo you mentioned, since there are newer and patched versions of go-jose out there. Thanks.

**Comment by mohammed90** [comment]
> I will create the issue against the repo you mentioned, since there are newer and patched versions of go-jose out there.

They already tagged a release with the "fix". The upgrade in Caddy is entangled with another dependency, i.e. github.com/smallstep/certificates.
