### ISSUE TITLE
HTTP/2 continuation flood (FYI)

### ISSUE THREAD

**Issue by systemcrash** [caddyserver/caddy#6219]
https://nowotarski.info/http2-continuation-flood-technical-details/

**Comment by francislavoie** [comment]
My understanding is this is already fixed in Go, you just need to build Caddy with the latest Go version. Nothing for us to do here.

**Comment by makew0rld** [comment]
Is making a new release with prebuilt binaries that don't contain this bug an option? Currently I've installed Caddy through Caddy's Debian repos and I was hoping for there to be a solution that would just be `apt upgrade caddy` instead of building from source.

**Comment by bartekn** [comment]
> My understanding is this is already fixed in Go, you just need to build Caddy with the latest Go version. Nothing for us to do here.

The issue is also in `golang.org/x/net` (actually it's only there, Golang just bundles it's `http2` package to standard `net/http` as `h2_bundle.go` file) and Caddy imports it here: 

https://github.com/caddyserver/caddy/blob/45132c5b24b411afbf90e8f897a1598d4eca790f/modules/caddyhttp/http2listener.go#L12

The version imported is 0.22:

https://github.com/caddyserver/caddy/blob/45132c5b24b411afbf90e8f897a1598d4eca790f/go.mod#L41

and the [security advisory](https://pkg.go.dev/vuln/GO-2024-2687) includes this version as vulnerable.

**Comment by francislavoie** [comment]
You should be able to build from master now to have the fix.

**Comment by makew0rld** [comment]
Will there be a new release for this? Thanks for the quick response.

**Comment by mvarendorff** [comment]
@francislavoie As an outsider I have no insight into how much effort it takes to make a new release but building from source is not a great option for a lot of people because they don't just have Caddy installed on one but many systems. Carrying the binary around dozens or more servers is a pain. An official build with the fix easily installed through apt or the like would make this important fix much more accessible to a lot of servers and it would be appreciated by a lot of people!

+ an additional question: Will 2.8 have this fixed in build? I am not familiar enough in Go to know where to look for to know whether it is or not.

**Comment by francislavoie** [comment]
@mvarendorff you can use `v2.8.0-beta.2`, right now.

**Comment by systemcrash** [comment]
When I reported this, I figured that this would warrant its own release. Dangling a beta for production usage to fix a specific vulnerability doesn't seem... right.

Anyway, thanks for the great product. <3
