### ISSUE TITLE
IP is set but cannot be accessed

### ISSUE THREAD

**Issue by 107295472** [caddyserver/caddy#6230]
{
	admin :2020 {
		origins 192.168.10.65
		enforce_origin
	}
}

![Q}{7H SX``{OCZJV$ZVQC}T](https://github.com/caddyserver/caddy/assets/6436116/82d615fd-3ff6-4889-a644-e0d42e15b119)

**Comment by mohammed90** [comment]
Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
