### ISSUE TITLE
Download crawl or stall

### ISSUE THREAD

**Issue by ertankucukoglu** [caddyserver/caddy#6239]
Hello,

I am using caddy v2.7.6 on Windows Server 2022 running in a VPS for http downloads with basic http authentication. It was working just fine until recently. There is no change on my setup and caddy especially and I started to have problems.

I am also using No-IP for possible change of VPS system aka IP number in the future. I have the same problem using an IP address or domain in my case. My Caddyfile for config is below. Some information in it is masked as <removed>.

```
{
  auto_https off
}

http://<removed>:2000 {
  basicauth * {
    Secret <removed>
  }
  root * /RepositoriesBackups
  file_server browse
}

```
Whole purpose is to download a single 7Zip file about 500MB using caddy. Manually using wget2 on my computer from command line and I see it starts downloading and stalls at about 2% to 4% (2 to 20MB). It does not complete or reports days to finish (very slow progress) after that.

If I do a remote desktop connection (RDP), I can download the same file just fine over that RDP connection without any observation of slowness or momentary pause it takes about 4min to complete on my slow internet connection. 

I tried to use a completely different network and computer. That system has about 10 times the speed compared to mine. This time I see download speed is way too slow like 15kb/sec. I also tried to copy the same file over RDP connection while that second system is downloading and it completed in 4min again. While second system continued download.

Speed on caddy download fluctuated when there are two downloads parallel. It did speed up and went to 35% instantly and then slowed down to 15kb/sec.

I do not know if the problem is caddy here. But, I also don't know how to search for the source of the problem.

Any help is appreciated.

Thanks & Regards,
Ertan

**Comment by mohammed90** [comment]
It's possible that the ISP has changed something which affects you (the client) or Caddy (the server side). Please share the following:

- Enable logs (access logs by using the [`log` directive](https://caddyserver.com/docs/caddyfile/directives/log), and debug logs by using the [`debug` global option](https://caddyserver.com/docs/caddyfile/options#debug)) and share the resulting logs while experiencing the issue

- Run Wireshark/tcpdump on the server and/or the client side and check the subject data stream/connection. Do you see any **TCP Retransmission**?

- If both server and client are in-premise, are the physical connections (cables) proper and not damaged?

For validation/testing purposes only, check the MTU on both networks. Like you, I once had an issue where the client struggled to view a page served by Caddy (only received HTTP headers, but nothing more -- stalls, as you'd say) despite working fine for a year or more before. The fix was to manually set the MTU on the server to match the client. Give it a shot, if you can, just to confirm.

**Comment by ertankucukoglu** [comment]
Turned out to be an IP ban from government. I am explained that it is earlier users might have been use the IP for fraud or something illegal. Otherwise, VPS company would have received a letter for explanation.
I am provided a new IP number and now everything is back to normal.
Sorry for the noise.
