### ISSUE TITLE
How can Caddy Server automatically switch over the next upstream server when it encounters an unhealthy HTTP status code during load balancing?

### ISSUE THREAD

**Issue by masx200** [caddyserver/caddy#6256]
How can Caddy Server automatically switch over the next upstream server when it encounters an unhealthy HTTP status code during load balancing?

```
*.xxxxxxx.xxxxxxx{
	encode gzip
	tls internal
	rewrite * /xxxxxxx/xxxxxxx/xxxxxxx/{host}{uri}
	reverse_proxy * https://xxxxxxxxxxxxxxxxxxxxx https://xxxxxxxxxxxxxxxxxxxxx https://xxxxxxxxxxxxxxxxxxxxx  {
		fail_duration 20s
		max_fails 3
		unhealthy_status 5xx
		health_uri /
		health_status 2xx
		health_interval 30s
		header_up Host {upstream_hostport}
	}
}

```

**Comment by mohammed90** [comment]
Use `lb_policy first`, per the [`reverse_proxy`documentation](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#load-balancing).

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. For the next time, please ask in the forum.
