### ISSUE TITLE
Unable to configure to Host: agnostic and port agnostic.

### ISSUE THREAD

**Issue by rishta** [caddyserver/caddy#6277]
The case is  most easily explained with docker config.

Assume I have a docker container tunning Caddy, that maps `0.0.0.0:8580 => 0.0.0.0:80` and a following Caddyfile entry:

```
{$SERVER_NAME:-0.0.0.0}:80 {
    some-configuration
}
```

With `nginx` the server "any" (`_`) listening on :80 exposed in the container in the manner shown above would catch and handle the requests without problems (`Host:` - agnostic and port agnostic), whereas Caddy, unless I specify explicitly:

```
localhost:8580 {
    configuration
} 
```

shows only white blank page. No errors either in logs or in the browser.

Unless I am missing something from the docs, this makes Caddy problematic for use with containers, because it enforces passing ports to the configuration. I would expect a `*:80` mapped by the container to be handled transparently and the headers and port passed to whatever service under caddy (php fcgi for example). Caddy SHOULD be able to ignore those headers.

**Comment by mohammed90** [comment]
You actually want

```
:80 {
    # config
}
```
What you're defining in the first line is the host; so when you put `0.0.0.0`, you're telling Caddy the host name _is_ `0.0.0.0`.

This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your questions there, and thanks for understanding!

**Comment by francislavoie** [comment]
This site address in the Caddyfile is not the server bind address. It's a higher level config which maps to the bind address (port, usually) and a `Host` matcher. See https://caddyserver.com/docs/caddyfile/concepts#addresses
