### ISSUE TITLE
Multiple header values on the same field

### ISSUE THREAD

**Issue by soyuka** [caddyserver/caddy#6317]
Hi, according to the documentation I thought that the following would work: 

```
handle /books {
  header "Link" "<https://localhost/books>; rel=\"self\""
  header +"Link" "<https://localhost/.well-known/mercure>; rel=\"mercure\""
  try_files books.jsonld {path}
}
```

But only the first one is set. The only way I could make this work is by setting `header` once and separating values with a comma. Note that I also tried: 

```
header {
  "Link" "a"
  +"Link" "b"
}
```

Is this a bug?

**Comment by mholt** [comment]
No, you've just got something funky with your Caddyfile syntax:

`+"Link"` is a strange use of quotes. It's trying to set a header called `Link` and add one called `"Link"` -- I'm guessing the Go std lib rejects the one with the quotes because it's invalid? Not 100% sure what's happening there without diving in more, but basically, remove the quotes around the field name and it will work.

Remember that the Caddyfile is not bash, so quotes in the middle of a string like `+"Link"` aren't parsed like bash. Either surround the token with quotes `"+Link"` or don't use them at all when not needed: `+Link`
