### ISSUE TITLE
Any possibility/Hope for GUI like Nginx proxy manager ?

### ISSUE THREAD

**Issue by HakaishinShwet** [caddyserver/caddy#6359]
Web ui makes thing much easier to see and find and manage things, I like cli it makes thing fast and i am already linux  user with tiling manager so its not like i hate files or cli stuff at all BUT it doesnt change the fact that gui makes thing easier to manage. I know in the past some not many did conversate regarding this  and some third party gui tool were created but they are not maintained plus not great at ui is what i can see, I didnt do thorough research on gui so i might be missing some great project so please tell if i did miss any. But official support will still be much better in my opinion,

**Comment by francislavoie** [comment]
We're not planning on it anytime soon, no official one anyway. Building a GUI is a huge time investment that we don't really have the time for on top of the rest of our maintenance tasks.

**Comment by mholt** [comment]
Several members of the community have shared GUIs they have created:

- [OPNSense plugin](https://docs.opnsense.org/manual/how-tos/caddy.html) ([forum post](https://caddy.community/t/caddy-v2-as-reverse-proxy-with-gui-in-opnsense/22047))
- [Caddy Proxy Manager](https://caddy.community/t/so-ive-created-a-web-ui-for-caddy/17278)
- [A simple admin UI](https://caddy.community/t/announcing-a-simple-admin-ui/16557)

I know I've seen a couple of others, including a neat JSON config builder UI, but I can't find the links anymore... :(

Going to close this, since it's outside the scope of this repository, but feel free to continue discussion and share links if you find more!
