### ISSUE TITLE
TLSv1.3 (IN), TLS alert, internal error (592) - When use TLS for IP address with Caddy

### ISSUE THREAD

**Issue by kocoten1992** [caddyserver/caddy#6364]
Hi Caddy, today I've a peculiar task, and doing that task reveal a bug in in caddy tls module:

TLSv1.3 (IN), TLS alert, internal error (592)

OpenSSL/3.0.11: error:0A000438:SSL routines::tlsv1 alert internal error

https://github.com/openssl/openssl/issues/19518

--------------------------------------------------------------------------------------------------------------------------

I was in need of tls for an IP address (NOT a domain or subdomain), I research about the possibility and turn out, it is entirely possible to do so - just not with letsencrypt (I need to buy an external ssl https://www.geocerts.com/support/ip-address-in-ssl-certificate).

I'm not promote any service here, but for the sake of this bug - PositiveSSL on ssls dot com (you need a domain to active the plan first then contact support and ask reissue ssl plan it to become an ip address later).

I enter information correctly:

```
tls cert key {
  ca
}
```

That's when I encounter a bug like above, but if I use the same config for nginx - it work out of the box..

**Comment by bt90** [comment]
Might be related with #6344

**Comment by mholt** [comment]
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_ **using the latest version of Caddy.** This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

This should be the latest version of Caddy:

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Instructions -- please heed otherwise we cannot help you (help us help you!)

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222) Please enable debug and access logs.
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by kocoten1992** [comment]
Thanks for the follow up!

## 1. Environment

### 1a. Operating system and version

Caddy on Debian inside a docker container

```
Debian 12.5
Docker version 20.10.24+dfsg1, build 297e128 (debian build)
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

This should be the latest version of Caddy: I try both caddy (debian build) and latest version download from github, same issue

```
~ apt-cache policy caddy
caddy:
  Installed: (none)
  Candidate: 2.6.2-5
  Version table:
     2.6.2-5 500
        500 http://debian.xtdv.net/debian bookworm/main amd64 Packages
```

(I also try latest release version from github `caddy_2.8.4_linux_amd64.deb` - same issue)

## 2. Description

### 2a. What happens (briefly explain what is wrong)

Chrome browser don't return much, it just a grey background with with some error complain about TLS/SSL being error

`curl -vvv` also don't tell much, it say this:

```
...
TLSv1.3 (IN), TLS alert, internal error (592)

OpenSSL/3.0.11: error:0A000438:SSL routines::tlsv1 alert internal error
...
```


### 2b. Why it's a bug (if it's not obvious)
It should display a site instead of http client complain about tls/ssl.



### 2c. Log output

No log, none.


### 2d. Workaround(s)

No work around.


### 2e. Relevant links

https://www.geocerts.com/support/ip-address-in-ssl-certificate


## 3. Tutorial (minimal steps to reproduce the bug)

Let follow the very first post, but I think maybe if you solve https://github.com/caddyserver/caddy/issues/6344, high chance you also solve this too.

**Comment by kocoten1992** [comment]
> What do you mean "no log output"?

I distinctly remember it didn't split out any log, the only log is the redirection from http -> https. If I access directly via https, no http log at all (it make sense since it bug at the very first tls exchange).

> Where did you look? Caddy definitely emits logs. Make sure you enabled the debug global option.

I didn't enable debug global option - this could be the reason, was looking at my own config `/var/log/caddy/<mysitelog>`.

At that moment, my hand is tied - I can't replace nginx with caddy and risk bring down company site, I'll try `debug global option` when have the chance.

**Comment by ledlamp** [comment]
Browser does not tell server name in client hello when connecting to a IP address (even though it does tell it in http Host header) so it can only assume it is the destination ip of the connection, but if NAT is used this will not match.

You have to set `default_sni <site ip address>` in global options.

**Comment by idontusenumbers** [comment]
I ran into this same issue. Documenting here to help other folks searching for this in the future.

The lack of logging, or reliance on debug logging, makes this very difficult to diagnose. Took me many hours diving into network debug consoles in Chrome, Firefox, network internals in chrome, wget, curl, and even using Wireshark, none helped. Thankfully, the last thing I tried, `curl -v` revealed the same error message as the original post here.
 
## Problem

Using a caddyfile:
```
https://{$site_host}:{$web_portSecure} {
	# ...
}
```


Connecting to a Caddy server with an IP address when no matching host block exists as an exact match, this is what I see.

Connecting from Chrome: `ERR_SSL_PROTOCOL_ERROR`
Connecting from Firefox: `SSL_ERROR_INTERNAL_ERROR_ALERT`
Connecting from `wget`: `OpenSSL: error:0A000438:SSL routines::tlsv1 alert internal error`
Connecting from `curl`: `TLS connect error: error:0A000438:SSL routines::tlsv1 alert internal error`

Chrome's `chrome://net-export/` produces the following information:
```
t=134389 [st=30]      SSL_HANDSHAKE_ERROR
                      --> error_lib = 16
                      --> error_reason = 1080
                      --> file = "../../third_party/boringssl/src/ssl/tls_record.cc"
                      --> line = 489
                      --> net_error = -107 (ERR_SSL_PROTOCOL_ERROR)
                      --> ssl_error = 1
```
Wireshark was of little help.

All of these produce the same output on the server. 

Without `debug` enabled in `global` section of caddyfile:
```
[nothing]
```

With `debug` enabled:
```
{"level":"debug","logger":"events","msg":"event","name":"tls_get_certificate","id":"/*...*/","origin":"tls","data":{"client_hello":{"CipherSuites":[/*...*/],"ServerName":"","SupportedCurves":[/*...*/],"SupportedPoints":"AA==","SignatureSchemes":[/*...*/],"SupportedProtos":["h2","http/1.1"],"SupportedVersions":[2570,772,771],"RemoteAddr":{"IP":"192.168.65.1","Port":34701,"Zone":""},"LocalAddr":{"IP":"172.18.0.3","Port":8443,"Zone":""}}}}
{"level":"debug","logger":"tls.handshake","msg":"no matching certificates and no custom selection logic","identifier":"172.18.0.3"}
{"level":"debug","logger":"tls.handshake","msg":"no certificate matching TLS ClientHello","remote_ip":"192.168.65.1","remote_port":"34701","server_name":"","remote":"192.168.65.1:34701","identifier":"172.18.0.3","cipher_suites":[/*...*/],"cert_cache_fill":0.0003,"load_or_obtain_if_necessary":true,"on_demand":false}
{"level":"debug","logger":"http.stdlib","msg":"http: TLS handshake error from 192.168.65.1:34701: no certificate available for '172.18.0.3'"}
```

## Solution:

Adding `default_sni {$site_host}` to `global` section of caddyfile gets past the SSL handshake error but results in a blank page:
```
{"level":"info",,"logger":"http.log.access","msg":"NOP","request" /*...*/}
```

Adding a catch all for the port, I finally see what I'm looking for (note the missing host):
```
https://{$site_host}:{$web_portSecure}, https://:{$web_portSecure}  {
	# ...
}
```

**Comment by jmhmd** [comment]
I am seeing this same error when trying to use `tls internal` (as well as with a custom cert). I think it must have something to do with the server being on a private hospital network, not accessible to public internet? 

@idontusenumbers with your solution, what is "web_portSecure"? Is that 443? 

I for example have an application running on the local linux VM at port 3006 alongside caddy, and the host `site.hospital.edu` points to the VM. So for your solution, I would add:

```
{
    default_sni site.hospital.edu
}

https://site.hospital.edu:443, https://:443 {
    reverse_proxy localhost:3006
    tls internal
}
```

Is that correct?

**Comment by idontusenumbers** [comment]
> [@idontusenumbers](https://github.com/idontusenumbers) with your solution, what is "web_portSecure"? Is that 443?

It's what ever you want it to be. I use a non-default port because I have any number of web servers running on my dev box.

**Comment by jmhmd** [comment]
I see - but you would then have to specify the port when accessing via a browser, correct?

I'm getting this same `error:0A000438:SSL routines::tlsv1 alert internal error` using a pretty simple config:
```
site.sub1.sub2.exampleorg.edu {
  reverse_proxy localhost:3006
  tls internal
}
```
I'm not sure if the issue is because it's a private hospital network (no inbound web traffic) or what.

**Comment by mholt** [comment]
@jmhmd What command are you using / what request are you sending to get that error?

(Although, if I am going to be of any help, I'll need real, unredacted domains and IP addresses, since crucial details are lost when obfuscating them.)

**Comment by jmhmd** [comment]
I get that error when sending `curl -I https://localhost` from the box running caddy (and the target application)

The IP I don't know (internal to a hospital network, I have the distinct pleasure of trying to debug this via zoom and asking a local admin to type commands via putty...). The domain is also not publicly accessible, something close to `radpacsbin.win.ad.[hospital].edu` (not sure if they want me posting an internal domain).

Also get unreachable error in chrome, but site loads when accessing via `http://radpacsbin.win.ad.[hospital].edu:3006`

I now realize the curl command probably fails because it's using `localhost` instead of the host defined in the Caddyfile, but still confused why it won't load in Chrome.

**Comment by mholt** [comment]
> I get that error when sending curl -I https://localhost from the box running caddy (and the target application)

I think that makes sense, since there is no cert for `localhost` with the above config.

**Comment by PandorasFox** [comment]
I have an inactionable, but interesting, single-device repro case of this. The root cause for this showing up, in my case, has ended up being something Haunted with the dns resolution on my roommate's decade-old thinkpad that I now have root on. Here's some fun tidbits:

```
root@shitbox:~# ping cerberus.local -qc4
PING cerberus.local (192.168.0.5) 56(84) bytes of data.

--- cerberus.local ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 2.579/3.027/3.240/0.261 ms
root@shitbox:~# curl -kvs https://cerberus.local 2>&1 >/dev/null | head -n10
* Host cerberus.local:443 was resolved.
* IPv6: (none)
* IPv4: 192.168.0.5
*   Trying 192.168.0.5:443...
* Connected to cerberus.local (192.168.0.5) port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
root@shitbox:~# curl -kvs https://files.cerberus.local 2>&1 >/dev/null | head -n10
* Host files.cerberus.local:443 was resolved.
* IPv6: redacted public ip :)
* IPv4: redacted public ip :)
*   Trying [redacted public ip :)]:443...
* Connected to files.cerberus.local (redacted public ip :)) port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS alert, internal error (592):
```

(my roommate had named the laptop that before I got my hands on it, to be clear)

What's happening here is that, for some reason I have yet to delve fully into because it's just Haunted, it resolves all subdomains of my nas to my router's public IP address. No other device on the network does this - the mechanism here is avahi + [this](https://github.com/grishy/go-avahi-cname) for publishing cnames of *.[host].local. I can't really think of any sane reason for why that laptop is able to do the zeroconf resolution of the base .local domain, but then *just* it breaks on the subdomains in a spectacular way. In either case, this is more of a tale for anyone else finding themselves here: the failure case that I see here, generates zero debug logs whatsoever (yes, there's other debug logs visible), because this device... isn't even routing the request correctly in the first place, presumably due to some dhcp/search domains buggery or the like that is wholly unrelated.
