### ISSUE TITLE
After renaming basicauth to basic_auth directive Caddyfile fails to load if custom salt argument was used

### ISSUE THREAD

**Issue by 13xforever** [caddyserver/caddy#6379]
Basically, this was an undocumented change that removed support for custom salt. Old configuraitons using this feature can not be updated to use the new `basic_auth` directive without regenerating all the hashes (in some cases this is not even possible).

Please at the very least update the documentation, adding the migration guide/breaking changes section, but ideally restore the compatibility with old config format.

**Comment by francislavoie** [comment]
Scrypt support was deprecated a long time ago. We removed scrypt support. It doesn't have to do with renaming the directive.

**Comment by 13xforever** [comment]
well it's hard to retrace the changes without links to older documentation version, my config is using default parameters, and it's not apparent that other algorithms didn't support salt parameter etc

I have a very simple issue: after upgrade and following the release note changes, my config doesn't work anymore and I have no easy way to migrate

**Comment by 13xforever** [comment]
realistically no one would bother to look at the logs until everything is broken, unless you're a big corpo and actually care about proactive infra monitoring

anyway, I don't see any warnings in the systemd journal before the upgrade, and if what you're saying is true and salt was silently ignored all this time, I'll try simply removing it from config file and see if the old credentials still work

**Comment by 13xforever** [comment]
Well you may disagree all you want, but the fact is it's hard to retrace what's broken after upgrade and why. As I said, at the very least there should be a note in the documentation that explains the configuration format change and migration notes, including the change of the default hashing algorithm, the removal of extra parameters, and how people can tell they're affected.

**Comment by francislavoie** [comment]
The note existed in the docs for two years that scrypt was deprecated. When we remove it, we also clean up the docs to remove references to it to get rid of irrelevant information.

If you tried to use salts with bcrypt, that was a user-error, because that doesn't make any sense (because bcrypt manages its own salt in the hash). Trying to use a custom salt doesn't make sense anyway, salts should _always_ be randomly generated at the time of generating the password, and should always be different for all passwords, otherwise it's possible to produce a rainbow table using that salt if it's reused.

**Comment by 13xforever** [comment]
That's a strange decision, to remove actually helpful note for people who will be struggling the most trying to figure out what needs to be fixed.

As for primer on salts, thanks, I have sufficient background in crypto, but it doesn't mean I can look at the legacy caddyfile and immediately understand what all the random parameters are meant to be especially when everything is using defaults without explicitly stating the configured algorithm anywhere.

**Comment by francislavoie** [comment]
Scrypt was never the default. You would have had to explicitly choose to use it. And Caddy will have warned every time you load with the algorithm configured to scrypt that it was deprecated. You can revert to 2.7.6 if you need to keep using those for the time being, giving you time to migrate.

**Comment by mholt** [comment]
The default has been bcrypt ever since there was a default before Caddy v2 was even released, all the way back in early 2020: https://github.com/caddyserver/caddy/blame/dd103a67876bd19afd000bda4410fbf83ee5b57d/modules/caddyhttp/caddyauth/basicauth.go

Maybe if you show us your config we can help you understand more about the changes in 2.8.

**Comment by 13xforever** [comment]
my config file literally looks like this, so I have zero clue:
```
basicauth /path {
  user Base64Hash hexsalt
}
```

**Comment by francislavoie** [comment]
How do you know that it doesn't work if you remove the salt? How did you actually try that?

Scrypt was dropped in this PR https://github.com/caddyserver/caddy/pull/6091. If you were using `scrypt` you would have had to specify the algorithm like this:

```
basicauth /path scrypt {

}
```

But since you aren't doing that, you must be using `bcrypt`, in which case the salts never did anything and should be dropped from your config. And like I said, you should try base64-decoding the hashes to see if they contain `$2a$` and if they do use the decoded version in your config.

**Comment by 13xforever** [comment]
yeah, I've regenerated the password for one user that I know for sure is used in my ddns script, everything else I'll only know when something will break somewhere, (I can't find the old password hash values to see if it was double-b64 encoded or not; I had to remove the auth part of the config to make caddy work again for other parts of the server).

**Comment by francislavoie** [comment]
> I can't find the old password hash values to see if it was double-b64 encoded or not

Wait, you've already lost your basicauth config? I'm not sure I follow.

**Comment by francislavoie** [comment]
It is in the release notes:

![image](https://github.com/caddyserver/caddy/assets/2111701/6d0c8023-b8ca-49a0-bfd2-7e7bd060896b)

https://github.com/caddyserver/caddy/releases/tag/v2.8.0

If you were specifying salts when using `bcrypt`, that has never done anything useful as I've explained, and therefore was user error. We didn't warn about that in the past, you're right, but it doesn't make sense anyway so we didn't think to warn in that case.

I'll close this, there's nothing actionable for us to do here. If you were using `scrypt`, you've had warnings for a very long time. If you used invalid config, then... fix it. That's all.
