### ISSUE TITLE
Issue with Unrecognized DynamoDB Storage Module in Caddyfile

### ISSUE THREAD

**Issue by pra-cloud** [caddyserver/caddy#6433]
We are encountering an issue while trying to store SSL certificates in a DynamoDB table using Caddy. Despite following the official Caddy documentation, we are facing a problem with the DynamoDB storage module not being recognized. Below are the details and steps we have taken:

Error:  

![image](https://github.com/caddyserver/caddy/assets/64471391/dfb05c68-8ba4-4564-9273-47f96537dd04)

Steps Followed

Source: [Caddy Documentation](https://caddyserver.com/docs/json/storage/dynamodb/)

Step 1
I made a custom build for the DynamoDB storage module, and it ran successfully:

>> xcaddy build --with github.com/silinternational/certmagic-storage-dynamodb/v3

output
![custom-build](https://github.com/caddyserver/caddy/assets/64471391/5fcbde52-002a-48c9-9480-0c939af70517)

Step 2
I specified the DynamoDB storage module in my Caddyfile:

Caddyfile :

{

    storage dynamodb {
        "table": "",
            "aws_region": "us-east-1",
            "aws_disable_ssl": false,
            "lock_timeout": 7,
            "lock_polling_interval": 7
    }

    on_demand_tls {
        ask http://127.0.0.1:5555
        burst 5
        interval 2m
    }

}

https:// {
        tls {
                on_demand
        }

        root * /var/www/html/public
        encode gzip
        file_server

     
    }

We are not sure if we are missing something or if this is an issue with the module itself. Any help in resolving this problem would be greatly appreciated.

**Comment by mohammed90** [comment]
Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
