### ISSUE TITLE
Caddy's self-signed certificates require daily validation

### ISSUE THREAD

**Issue by miltuss** [caddyserver/caddy#6467]
Hello, I am having a big problem with Caddy's self-signed certificates locally with LAN IP addresses.  The certificates install correctly with the following instructions, but every time I restart the computer I have to re-validate all the self-signed service certificates on each browser!

```
 192.168.0.100:9000 {
   reverse_proxy 192.168.0.100:7004
 }
```

 It looks like Caddy is constantly changing self-signed certificates, requiring new manual validations every time the client computer restarts.  While other applications (syncthing, cockpit, etc.) which have a self-signed SSL certificate by default require a single validation of the certificate on browsers.

 How to solve this problem ?

**Comment by mholt** [comment]
You do not have to validate every day. Caddy automatically manages its own PKI including a signing authority, which root cert is valid for 10 years. Caddy installs the root cert locally into most trust stores automatically if it is given privileges. (For trust outside of localhost, you'll have to install the root cert yourself of course.)

The leaf certs are only valid for about 12 hours I think, but that doesn't matter since they're signed by an intermediate that's valid for 7 days, which is signed by a root that's valid for 10 years -- so you only need to update trust stores once every 10 years.

Will close this, but we can reopen it if there's a bug in Caddy.

**Comment by miltuss** [comment]
@mholt You explained the theory to me, but in practice the browser asks me to validate Caddy's self-signed certificates every day for each service, this is valid for Firefox, Chrome and all other browsers.  These same browsers only ask me for one validation of self-signed certificates for services that are not managed by caddy.

 So the problem comes specifically from the management of Caddy's self-signed Certificates.  Why do all browsers require daily validation of Caddy's self-signed certificates?

**Comment by mholt** [comment]
If the browser is really asking every time, then it's probably just not installed for that trust store. Caddy doesn't recognize all trust stores (for example, I think Chrome just started shipping their own instead of using the OS trust store), so sometimes you will have to manually install the root cert yourself. (We use mkcert's trust store package, so contributions there would be welcomed.)

**Comment by miltuss** [comment]
I use Librewolf as my main browser, how do I manually register self-signed certificates in Librewolf which is a fork of Firefox?

 I should point out that once I validate Caddy's self-signed certificate in a browser, the service remains perfectly available with SSL encryption in HTTPS for 12 hours, so the certificate is stored somewhere during this period of time?

**Comment by mholt** [comment]
No idea, never heard of it. If it's the same as Firefox, and it doesn't have documentation on how to manage the trust store, you can try looking up Firefox's instructions and see if that works.

> I should point out that once I validate Caddy's self-signed certificate in a browser, the service remains perfectly available with SSL encryption in HTTPS for 12 hours, so the certificate is stored somewhere during this period of time?

The browser remembers your choice to trust a specific certificate. Once the cert changes, it will ask you again. That is why the root needs to be installed.

**Comment by miltuss** [comment]
> No idea, never heard of it. If it's the same as Firefox, and it doesn't have documentation on how to manage the trust store, you can try looking up Firefox's instructions and see if that works.

Yes, librewolf is the same as Firefox

> The browser remembers your choice to trust a specific certificate. Once the cert changes, it will ask you again. 

Exactly, Caddy's self-signed certificate is not supposed to be changed.  So if he asks for validation again, it means that he has changed!  Do you agree that Caddy changes self-signed certificates?

> That is why the root needs to be installed.

I didn't understand this sentence, which root should I install?

**Comment by miltuss** [comment]
I'm going to do a test, I'm going to save the current SSL certificate.  When the browser asks me to validate the certificate again, then I will compare it with the old certificates to find out if it has changed or was not saved by the browser.

**Comment by mholt** [comment]
> Exactly, Caddy's self-signed certificate is not supposed to be changed. So if he asks for validation again, it means that he has changed! Do you agree that Caddy changes self-signed certificates?

Like I said, there are 3 certificates at play. The root, the intermediate, and the leaf. If anything changes, the browser will invalidate your security bypass. That's why you need to install the root certificate, which does not change (for 10 years).

**Comment by francislavoie** [comment]
Where Caddy's root cert is located depends on how you installed and run Caddy. You didn't specify in your post so I can't give an accurate answer. How are you running Caddy?

**Comment by miltuss** [comment]
> Where Caddy's root cert is located depends on how you installed and run Caddy. You didn't specify in your post so I can't give an accurate answer. How are you running Caddy?

I run Deploy Caddy with Docker Compose like this:

```
version: "3.7"
services:
  caddy:
    image: docker.io/library/caddy:latest
    container_name: caddy
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    #    ports:
    #      - "80:80"
    #      - "443:443"
    #      - "443:443/udp"
    volumes:
      - /data/Caddyfile:/etc/caddy/Caddyfile
      - /data/site:/srv
      - /data/caddy_data:/data
      - /data/caddy_config:/config
```

**Comment by miltuss** [comment]
> > Exactly, Caddy's self-signed certificate is not supposed to be changed. So if he asks for validation again, it means that he has changed! Do you agree that Caddy changes self-signed certificates?
> 
> Like I said, there are 3 certificates at play. The root, the intermediate, and the leaf. If anything changes, the browser will invalidate your security bypass. That's why you need to install the root certificate, which does not change (for 10 years).

I found only two SSL certificates in the Caddy tree, the intermediate and the root, I did not find the leaf in `/data/caddy/pki/authorities/local`

![Sélection_422](https://github.com/user-attachments/assets/14f94483-5c95-443e-ab7b-4e532b94ec01)

What are all these certificates for?  Why does Caddy need to transition between middleman, leaf and root?  Why doesn't Caddy just use a single certificate?

**Comment by francislavoie** [comment]
Web PKI uses a chain of trust. The root cert signs the intermediate, the intermediate signs leaf certs. This is how all websites are set up. The root cert has long lifetime but is kept super-protected, and intermediates has a shorter lifetime and produces leaf certs. The leaf certs contain the actual public key matching the private key used to encrypt traffic for connections to that domain.

So what you need to do is install the _root CA cert_ on your system's trust store. Doing that, clients will trust any connection to Caddy, since Caddy will send along both the intermediate and leaf in the handshake, and the client can verify that the root cert in its trust store did indeed sign the intermediate, and by proxy the leaf was signed by that intermediate, so trusting the root means leaf certs are trusted.

Since you're in Docker, yes your certs are stored in `/data`. The `.key` files _must never leave that location_, that's the important part. The `.crt` files contain public information and can be pulled out. The `root.crt` is what you want to install.

We have instructions here for setting up trust when using Docker: https://caddyserver.com/docs/running#local-https-with-docker

**Comment by miltuss** [comment]
@francislavoie  THANKS.  Installing the certificate in Linux operating system didn't work, but installing root.crt certificate in browsers worked.  This is the answer I was waiting for :)
