### ISSUE TITLE
Caddy Web GUI HTTPs invalid

### ISSUE THREAD

**Issue by BcgA59SLMw** [caddyserver/caddy#6476]
I am attempting to get caddy to use a cert I generated for the webgui. I have copied the certs to /opt/postal/config/ and my domain folder in /opt/postal/caddy-data/caddy/certificates/local/domain/

I edited the Caddy file and added the tls directive: 
tls internal /config/fullchain.pem /config key.pem

However, my webgui always uses the caddy generated cert and not the one I made. I am sure I'm missing something obvious - anything I'm missing or other places to look?

**Comment by mohammed90** [comment]
Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
