### ISSUE TITLE
[windows] cannot run executable found relative to current directory

### ISSUE THREAD

**Issue by TeKett** [caddyserver/caddy#6508]
Im trying to start caddy, and not run it. Since i still want access to the cmd window and not have it locked so that i can make more commands.

It was working fine when i installed it a couple weeks back. Fast forward a couple weeks, now when i try to "start" it i get `Error: starting caddy process: exec: "caddy": cannot run executable found relative to current directory`. I can still "run" caddy without issue, but then i cant do more commands.

**Comment by francislavoie** [comment]
You should run Caddy as a Windows service to keep it running. https://caddyserver.com/docs/running#windows-service

**Comment by mholt** [comment]
I think it should also be in your PATH.

Closing, but feel free to continue discussion if this is a bug in Caddy.

**Comment by WeidiDeng** [comment]
There is `PATH` on windows, but unlike unix, it's quite cumbersome to set up. Python and Java installer can be configured to configure this variable at install time on windows for a reason. `PATH` is vital in this case, because those executables depend on lots of other executables that will be searched in `PATH` and some of those related, util executables and put in the same directory.

For simple use case and the binary itself not needing external executables such as caddy I think it's reasonable to put it anywhere user likes and expect it to run.

**Comment by WeidiDeng** [comment]
@TeKett Can you try `xcaddy build relative-path-fix` to see if it's fixed?

**Comment by TeKett** [comment]
> xcaddy build relative-path-fix

xcaddy is an unknown command, tried with "caddy" instead and it does not know what "build" is. I tried to add caddy to the path, did not work either. I'm still learning and i don't actually remember what i did 2 weeks ago. All i want is to have the cmd window open and accessible, since i need to keep restarting the server and other stuff whenever i make config changes. And for whatever reason caddy is not automatically reading the caddyfile (its located right next to the caddy.exe) so i have to include it as an argument, which i cant do if i run it as a service.

**Comment by francislavoie** [comment]
@TeKett https://caddyserver.com/docs/build#xcaddy
