### ISSUE TITLE
file transactions on .lock files 

### ISSUE THREAD

**Issue by joomker** [caddyserver/caddy#6516]
We have a setup involving two Caddy servers hosted on Azure, with an SMB store mounted from Azure Storage using fstab. These Caddy servers are behind an Azure Load Balancer (LB) and primarily handle web redirection.

Problem: When we configure redirection and the DNS record does not point to the Load Balancer (Caddy), we observe that Caddy creates a lock file. This behavior leads to an unexpected surge in transactions, with approximately 900 transactions occurring within just 5 minutes.

![image](https://github.com/user-attachments/assets/9c2c7b29-4f93-4939-890b-4a84dde5c912)

**Comment by mholt** [comment]
That's Caddy (CertMagic) trying to get certificates for domains that don't have DNS records set yet. Caddy's file system locker uses active locking, which means that it polls to determine if the lock is still active. These are `open` (read-only) or `read` calls, so they're very lightweight, and can happen every second or two. If getting a cert fails, there will be more of them since Caddy will backoff and retry until it can succeed. It's waiting for that DNS record.

Is this causing a problem with your environment?

Btw, I highly recommend [sponsoring](https://caddyserver.com/sponsor) the project if your company isn't already, as we can provide support and publicity or whatever is needed, especially important for larger deployments.

**Comment by joomker** [comment]
It's about the costs of storage, as Azure charges per transaction.

To be honest, we thought that this lock check applies only when the HTTP challenge is applicable.

So, when CertMagic gave up trying to issue a certificate because it cannot do the HTTP challenge, it is supposed to try again the next day, as per the documentation:

"After all enabled challenge types have been tried, [it tries the next configured issuer](https://caddyserver.com/docs/automatic-https#issuer-fallback) Let's Encrypt ZeroSSL After all issuers have been tried, it backs off exponentially Maximum of 1 day between attempts For up to 30 days"


In the current scenario, even after 30 days, CertMagic will continue to check the lock, which generates filesystem activity

**Comment by mholt** [comment]
Locking is used regardless of challenge type -- to avoid stepping on other instances' toes.

Yep, so if the DNS record isn't pointing to the machine, don't try to get a certificate for it. I mean, you _can_ try, but it will fail, and result in lots of lock ops like that.

If storage is expensive, you can tune certificate management to do maintenance less often, or use a different storage backend altogether.

**Comment by joomker** [comment]
Thank you for explanation. Looks like all is as it should, thanks

**Comment by mholt** [comment]
No problem! Please do consider a sponsorship though and I can help in more dedicated ways, like via email or chats/calls.
