### ISSUE TITLE
Matcher inside reverse_proxy header_up directive parses successfully but does nothing

### ISSUE THREAD

**Issue by Rexios80** [caddyserver/caddy#6528]
```caddy
handle /keycloak* {
	@oauth path /keycloak/realms/asdf/protocol/openid-connect/*
	rewrite @oauth ?{query}&client_id={env.KEYCLOAK_CLIENT_ID}

	@token {
		path /keycloak/realms/asdf/protocol/openid-connect/token
		path /keycloak/realms/asdf/protocol/openid-connect/revoke
	}

	reverse_proxy http://keycloak:8080 {
		header_up @token Authorization "Basic {env.KEYCLOAK_CLIENT_CREDENTIALS}"
	}
}
```

The authorization header is not added for the `/token` or `/revoke` endpoints. The following config does work:

```caddy
handle /keycloak* {
	@oauth path /keycloak/realms/asdf/protocol/openid-connect/*
	rewrite @oauth ?{query}&client_id={env.KEYCLOAK_CLIENT_ID}

	@token {
		path /keycloak/realms/asdf/protocol/openid-connect/token
		path /keycloak/realms/asdf/protocol/openid-connect/revoke
	}

	reverse_proxy @token http://keycloak:8080 {
		header_up Authorization "Basic {env.KEYCLOAK_CLIENT_CREDENTIALS}"
	}

	reverse_proxy http://keycloak:8080
}
```

Is it expected that the first code sample does not work? If so it should fail to parse instead of causing me hours of pain.

**Comment by francislavoie** [comment]
Technically, what `header_up @token Authorization "Basic {env.KEYCLOAK_CLIENT_CREDENTIALS}"` does is use the 3-param syntax of `header_up`, which is "replace a value in the `@token` header field, searching for the value `Authorization` and replacing it with `"Basic {env.KEYCLOAK_CLIENT_CREDENTIALS}"`. It's valid syntax, but obviously it's nonsense in your case.

What you should actually be doing is use the [`request_header` directive](https://caddyserver.com/docs/caddyfile/directives/request_header) instead to manipulate the header _before_ passing it to `reverse_proxy` so that you only need one `reverse_proxy`.

```
	@token path /keycloak/realms/asdf/protocol/openid-connect/token /keycloak/realms/asdf/protocol/openid-connect/revoke
	request_header @token Authorization "Basic {env.KEYCLOAK_CLIENT_CREDENTIALS}"

	reverse_proxy keycloak:8080
```

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
