### ISSUE TITLE
Invalid character \x00 in logs, crashing Docker

### ISSUE THREAD

**Issue by antoineleclair** [caddyserver/caddy#6556]
I had high CPU usage on my home server. It's a Rapsberry Pi 5, running Ubuntu 24.04 server. 
When I ran `htop`, I saw Docker was using ~25% of all 4 cores of the CPU.
After some debugging, I saw that if I stopped Caddy (running in a Docker container, using the image `caddy:2.7.6`), the CPU went back to normal.
Running `docker logs -f name-of-caddy-container`, showed regular logs, but the last line was
```
error from daemon stream: error grabbing logs: invalid character '\x00' looking for beginning of value
```
and the command returned, instead of watching for new logs.

I cleared the logs of container with this command
```
sudo sh -c 'echo "" > $(docker inspect --format="{{.LogPath}}" name-of-caddy-container)'
```

and all went back to normal.

Looking at log lines just above the last one that crashed, I see requests for files like `/bypass403.php`, `f0x.php` and a bunch of other files that I do no host, trying to find vulnerabilities. I suspect that someone sent an invalid request containing `\x00` in the URL in some way and Caddy logged it, making Docker unhappy.

**Comment by mohammed90** [comment]
At first glance, if that's the case, I'd fault Docker for crashing or falling apart when encountering this in logs. I have to experiment with how Caddy, shells, and Docker would result in faulty situation.

I've attached a template below that will help make this easier and faster. **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.** Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by antoineleclair** [comment]
## 1. Environment

### 1a. Operating system and version

Ubuntu 24.04 LTS on a Raspberry Pi 5.

`uname -a` gives this:

```
Linux pi-green 6.8.0-1010-raspi #11-Ubuntu SMP PREEMPT_DYNAMIC Thu Aug  8 23:22:41 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

### 1b. Caddy version (run `caddy version` or paste commit SHA)

I'm using the Docker image `caddy:2.7.6`

Running `docker run caddy:2.7.6 caddy version` gives:
```
v2.7.6 h1:w0NymbG2m9PcvKWsrXO6EEkY9Ru4FJK8uQbYcev1p3A=
```

### 1c. Go version (if building Caddy from source; run `go version`)

N/A

## 2. Description

### 2a. What happens (briefly explain what is wrong)

Docker had high CPU usage (~25% of all 4 cores of the CPU on my Raspberry Pi 5) on idle.
I discovered that if I ran `docker logs -f caddy-container-name`, it showed the regular logs, and ended with this line:
```error from daemon stream: error grabbing logs: invalid character '\x00' looking for beginning of value```
and the command would return instead of waiting for new logs.

I cleared the logs of the container with
```
sudo sh -c 'echo "" > $(docker inspect --format="{{.LogPath}}" caddy-container-name)'
```

and it fixed the CPU usage, and `docker logs -f caddy-container-name`.

### 2b. Why it's a bug (if it's not obvious)

Leaving Caddy unsupervised results in high CPU usage.

### 2c. Log output

```
error from daemon stream: error grabbing logs: invalid character '\x00' looking for beginning of value
```

### 2d. Workaround(s)

```
sudo sh -c 'echo "" > $(docker inspect --format="{{.LogPath}}" caddy-container-name)'
```

### 2e. Relevant links

N/A


## 3. Tutorial (minimal steps to reproduce the bug)

I don't know the exact way to reproduce. I suspect that someone sent invalid requests, trying to find vulnerabilities, and one of them contained `\x00` in the URL, and Caddy logged it, crashing Docker.

**Comment by antoineleclair** [comment]
There you go :point_up:, I hope that helps.

Thanks for taking the time :pray:.

Regarding the issue being a problem with Docker vs a problem with Caddy, I feel like it's probably a problem with both? Logging `\x00` probably doesn't make sense (for Caddy) and crashing on an invalid character probably doesn't make sense (for Docker).

**Comment by antoineleclair** [comment]
I'm linking this issue that seems related.
https://github.com/moby/moby/issues/29511

>There are other reports of the exact behavior with the "local" log driver on rpi's after abrupt power loss.

I had a power loss this week. It could explain.

**Comment by mholt** [comment]
I doubt Caddy is actually logging a null byte; a power loss would certainly be capable of corrupting a byte between leaving Caddy and appearing in the logs. I think this is a pretty normal aspect of computer I/O and Docker shouldn't crash showing the logs :wink:

Sorry if that's not much help. But we appreciate the thoroughness to report. We can reopen this if there's anything actionable for us to do.
