### ISSUE TITLE
ipv6 proxy lan service

### ISSUE THREAD

**Issue by baozi510** [caddyserver/caddy#6588]
I only have IPV6 public, ipv4 is private. I use ipv6 to proxy IPV4 LAN services. The LAN service ports must be allowed through the firewall.
When I use public IPV4, only the proxy ports need to be passed through the firewall.

caddyfile
```
https://xxxx.com {
	reverse_proxy http://192.168.123.123:8012

}
```
https://xxxx.com ipv6 only

must `ufw allow 443 
 ufw allow 8012`
i want just `ufw allow 443`

I know this may not be a problem with Caddy

i use docker-compose

**Comment by mohammed90** [comment]
Have you and found it not working? Give it a shot. You don't need to do `ufw allow 8012` anyways.

This looks more like a question about networking than how to use Caddy, a bug report, or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your questions on Caddy usage. I hope you'll ask your Caddy questions there, and thanks for understanding!
