### ISSUE TITLE
Let Caddy stop by itself when there are no active connections so that Caddy can work on demand with the help of socket activation

### ISSUE THREAD

**Issue by eriksjolund** [caddyserver/caddy#6642]
Instruct Caddy to stop when there are no active connections. Caddy would then be able to do work on demand.

The starting functionality is already available as Caddy supports _socket activation_:
systemd starts Caddy when a new client connects to the listening socket systemd has created.

I haven't tried it out myself. Is there a risk of missing some connections by letting Caddy stop by itself?

**Comment by eriksjolund** [comment]
Maybe it's interesting if you run a web page with very few visitors (e.g. one visit per week)?
Most of the time there would be no Caddy process running because it has terminated by itself.

An example of a self-stopping service is _podman.service_ which is configured to use a Unix socket.

My Fedora CoreOS 41.20241006.1.1  has these files:

 _/usr/lib/systemd/system/podman.service_
```
[Unit]
Description=Podman API Service
Requires=podman.socket
After=podman.socket
Documentation=man:podman-system-service(1)
StartLimitIntervalSec=0

[Service]
Delegate=true
Type=exec
KillMode=process
Environment=LOGGING="--log-level=info"
ExecStart=/usr/bin/podman $LOGGING system service

[Install]
WantedBy=default.target
```


 _/usr/lib/systemd/system/podman.socket_
```
[Unit]
Description=Podman API Socket
Documentation=man:podman-system-service(1)

[Socket]
ListenStream=%t/podman/podman.sock
SocketMode=0660

[Install]
WantedBy=sockets.target
```

According to the`podman system service` man page,  the service is stopped after a timeout of 5 seconds by default.

https://docs.podman.io/en/latest/markdown/podman-system-service.1.html#time-t

**Comment by mholt** [comment]
To clarify, I'm open to this idea, but I am just struggling to understand the motivation. What's the benefit of stopping a process on a server even if it's mostly idle? Like why not just leave it running? That way it can keep certificates renewed in the background, etc. Otherwise you have to wait. Visitors will likely get certificate errors unless on-demand TLS is being used, but even then they'll experience a delay while the handshake takes longer to complete when first starting up.

**Comment by eriksjolund** [comment]
> That way it can keep certificates renewed in the background

Oops, I didn't think about the renewal of certificates. 
Maybe Caddy could create a [_systemd timer_](https://www.freedesktop.org/software/systemd/man/latest/systemd.timer.html) that could start Caddy later.

**Comment by mholt** [comment]
Timers just don't scale very well or respond to dynamic environments like ACME. For example, if a certificate is being revoked and the ARI window moves earlier, we won't know it because we're only on a timer.

i.e. we basically are re-implementing certbot, etc, and lose all the benefits of a live, running system.

**Comment by francislavoie** [comment]
I agree this is probably not a good fit for Caddy, since we have a variety of modules that want to run long term (e.g. proxy active health checking, storage cleanup, cert issuance & renewal, things other plugins might do).

Unless an actual solid usecase for this is discovered, I don't think we need to explore it further.

**Comment by chetan-reddy** [comment]
@eriksjolund I needed this feature (on a local http only caddy), so I implemented it as a plugin. Please see https://gist.github.com/chetan-reddy/fe23b1ec53e7086173836d0b17be5e55

I don't know how caddy expects modules to handle a global option when its removed from a Caddyfile on a reload, but other than that it works for me as expected. It's my first bit of golang code, and I haven't yet finished going through "A Tour of Go", so please excuse any flaws. Happy to fix if you point them out.

PS: Someone else asked for this feature on this locked thread -> https://caddy.community/t/exit-caddy-after-inactivity-idle-time-automatically/31155

**Comment by francislavoie** [comment]
The problem with your setup is your duration config is not actually in the JSON config so it's only read if the main process receives a Caddyfile and not otherwise. The "correct" way to do it would be to have an App module which carries that config, then use a UsagePool in the app module which tracks overlapping start/stop calls, if stopping with count of 1 (instead of 2) then you know the config was removed from the new config so you should do cleanup. That way you can also have your goroutine in the app module instead of global, and the http handler can fetch the app instance via the ctx (your handler is given ctx in Provision) and report the activity through the app module if it's configured and do nothing otherwise.
Can simplify even more when using an app, if you count a config reload as "activity", you cancel the goroutine in the old config in Stop then start a new one in Start and it starts a new timer from there. So you can remove all global state vars and isolate it to the app module instance.

**Comment by chetan-reddy** [comment]
Thanks for the feedback @francislavoie . I've updated the [gist](https://gist.github.com/chetan-reddy/fe23b1ec53e7086173836d0b17be5e55) to have separate App and Handler modules, and got rid of the globals. It now works correctly when the config is changed/removed and reloaded. It would be nice if I didn't have to add `exit_on_idle` to every site block, but I couldn't figure out a way to achieve that. Any other feedback is welcome. Thanks again.

**Comment by francislavoie** [comment]
You could maybe implement it as a listener wrapper instead which would run on the entire HTTP server instead of needing middleware/handler per site.
