### ISSUE TITLE
panic: certificate worker: runtime error invalid memory address or nil pointer dereference from certmagic

### ISSUE THREAD

**Issue by pimlie** [caddyserver/caddy#6672]
This is not the same error as #6609 as I built caddy manually with `certmagic@0.21.4`.

I tracked the panic down to a network issue, it occurs when the api of the dns provider isn't reachable. So it seems that network issues might not be nicely handled yet? To be clear, the api hostname could be resolved through DNS, but actually connecting to the api failed due to a network routing issue.

Unfortunately I don't have a stack trace anymore as docker only kept 100 lines of the log, but let me know if you really need one as I can break the network routing again if needed. The panic occured on [this line](https://github.com/libdns/leaseweb/blob/7d389d1f05f654715f96127dc5d23c8900c7f9e8/client.go#L119) though (Im also using that dev branch as my PR hasnt been merged yet)  :)

**Comment by francislavoie** [comment]
How did you build Caddy exactly? Show `caddy build-info`

**Comment by mholt** [comment]
That actually looks like a bug in the leaseweb plugin.

**Comment by francislavoie** [comment]
```
xcaddy build \
    --with github.com/caddyserver/certmagic@v0.21.4
```

That's the wrong way to build. You can't just upgrade certmagic without upgrading Caddy as well.

**Comment by mholt** [comment]
Ah okay, thanks for the issue anyway!

**Comment by mholt** [comment]
Yeah, I don't think there's anything actionable here for us.

**Comment by bhavin-qryptal** [comment]
After recent upgrade to caddy.Version=v2.9.1 (from caddy.Version=v2.8.4) , I have encountered following errors twice in 2 days post upgrade. As a result, have rolled back caddy version to v2.8.4. 

**Error stack trace:**
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3d8 pc=0x92ae79]
goroutine 79449 [running]:
github.com/caddyserver/certmagic.(*Config).certNeedsRenewal(0xc0005448c0, 0x0, {{{0x0, 0xedf986771, 0x0}, {0x0, 0xedf9b0a71, 0x0}}, {0x0,>
        github.com/caddyserver/certmagic@v0.21.6/certificates.go:95 +0x99
github.com/caddyserver/certmagic.(*Config).handshakeMaintenance.func1({_, _}, _, {{{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, ...}, ...}, ..>
        github.com/caddyserver/certmagic@v0.21.6/handshake.go:564 +0xa9
github.com/caddyserver/certmagic.(*Config).handshakeMaintenance.func2(_, {{{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, ...}, ...}>
        github.com/caddyserver/certmagic@v0.21.6/handshake.go:625 +0x34e
created by github.com/caddyserver/certmagic.(*Config).handshakeMaintenance in goroutine 79438
        github.com/caddyserver/certmagic@v0.21.6/handshake.go:609 +0xd9d
caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
caddy.service: Failed with result 'exit-code'.
caddy.service: Consumed 50.236s CPU time.
` 
**Environment Info:**
`caddy.Version=v2.9.1 h1:OEYiZ7DbCzAWVb6TNEkjRcSCRGHVoZsJinoDR/n9oaY=
runtime.GOOS=linux
runtime.GOARCH=amd64
runtime.Compiler=gc
runtime.NumCPU=2
runtime.GOMAXPROCS=2
runtime.Version=go1.23.4
`
We are using AWS EFS to store SSL certificates in order to run Caddy servers in High Availability mode. Please let me know any additional information is needed. 

I am sorry, if I am not supposed to post this here (Please guide if I have misunderstood the outcome of the discussion so far). Please guide. 

Thank you very much for your attention and assistance.

**Comment by mholt** [comment]
@bhavin-qryptal That's very much a different issue, and it has already been patched in CertMagic, just not released quite yet. I'm close to a new release. Or you can build with the latest commits using [`xcaddy`](https://github.com/caddyserver/xcaddy) in the meantime.

**Comment by bhavin-qryptal** [comment]
Thank you very much @mholt for your prompt response and guidance. I would wait for fixed release to be available in APT repository to deploy in our environments. Would you please point me to a link where this issue is reported / tracked (if available)?

**Comment by mholt** [comment]
IIRC it was privately reported by a sponsor, the commit history on the CertMagic repo will show a few relevant commits. (I'm mobile so sorry for no link)
