### ISSUE TITLE
Is it possible to export websocket-related metrics from caddy to prometheus?

### ISSUE THREAD

**Issue by maxamel** [caddyserver/caddy#6686]
Hi, I was looking at the caddy docs regarding prometheus integration and I see there are metrics for http calls, but didn't see anything related to websockets.
I have a socketio app for which I'd like to monitor basic metrics such as throughput, total calls, etc.
Is there any way to do this at the moment?

**Comment by hairyhenderson** [comment]
Hi @maxamel, generally with a use-case like yours, you'll want to instrument your socketio app directly to monitor those things.

In order to gather metrics about the messages passed across your socket, Caddy would need to be capturing traffic at a higher level. This seems like something that might be possible with a plugin, but certainly doesn't sound like something Caddy should be doing itself.

**Comment by mholt** [comment]
Yeah, and to expand on that, we technically do read and write all the bytes so we have that information, but right now it's just read from the read buffer and written directly to the writer, in other words, the bytes get copied directly between client and backend. It's more efficient that way, so we don't inspect the bytes, although we could. (They do get counted though.)
