### ISSUE TITLE
There is a bug in the automatic certificate replacement, and the certificate is not replaced when it expires.

### ISSUE THREAD

**Issue by 107295472** [caddyserver/caddy#6744]
msy.xxxx.cc {
	handle {
		root D:\\server\\sites\\msy
		try_files {path} /index.html
		file_server
	}
	handle /api/* {
		reverse_proxy /api/* localhost:1888
	}
	log {
		output file logs/msy.log {
			roll_size 10mib
			roll_local_time
		}
		format transform `[{ts}] - {request>headers>X-Forwarded-For>[0]:request>remote_ip} "{request>method} {request>uri} {request>proto}" {status} {size} "{request>headers>Referer>[0]}" "{request>headers>User-Agent>[0]}"` {
			time_format "wall_milli"
			time_local
		}
	}
	header {
		Strict-Transport-Security max-age=31536000;
		X-Content-Type-Options nosniff
		X-Frame-Options SAMEORIGIN
		Referrer-Policy origin
		X-Download-Options noopen
		X-Permitted-Cross-Domain-Policies master-only
		X-XSS-Protection "1; mode=block"
	}
}

Last version,golang 1.22

**Comment by mohammed90** [comment]
That cannot be true by the virtue of numerous users running Caddy for years and never having an expired certificate. I personally have a server running since 2017 and never had expired certificates. Please provide evidence.


Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by 107295472** [comment]
It should be a network problem. The certificate cannot be pulled.

**Comment by mohammed90** [comment]
> Can I manually renew it one year in advance? It is now expired today and I have not changed it.

The certificates validity is 90 days, nothing more. Caddy can manage renewing them just fine when used properly, e.g. allow the traffic through the firewall.

> How to use other certificates? No free ones.

You can use the [`tls` directive](https://caddyserver.com/docs/caddyfile/directives/tls).

Please use [the forum](https://caddy.community) for usage questions. The issue tracker is reserved for actionable bugs or feature request.
